- app/assets/v2/css/profile.css
- app/dashboard/templates/profiles/header_details.html
- app/dashboard/templates/profiles/profile.html
- app/dashboard/templates/profiles/status_box.html
- app/dashboard/templates/profiles/tab_active.html
- app/dashboard/templates/profiles/tab_grant_contribs.html
- app/dashboard/templates/profiles/tab_portfolio.html
- app/dashboard/templates/profiles/tab_viewers.html
- app/dashboard/templates/profiles/tabs.html
Reported at: https://gitcoincore.slack.com/archives/CDML7FS7M/p1578507443003400
After Fix: 
[Profile Header](https://user-images.githubusercontent.com/5358146/72044410-affb5e80-32d9-11ea-8c63-d6f03fa5a6bb.png)
[Active Issues Tab](https://user-images.githubusercontent.com/5358146/72046334-374ad100-32de-11ea-9ad7-e68e472f6eb7.png)
[Portfolio Tab](https://user-images.githubusercontent.com/5358146/72046335-374ad100-32de-11ea-83e8-9cef31fe35a3.png)
[Viewers Tab](https://user-images.githubusercontent.com/5358146/72046336-37e36780-32de-11ea-8669-442dfe45493d.png)
[Grants Tab](https://user-images.githubusercontent.com/5358146/72050166-8432a580-32e6-11ea-871e-d815501d8008.png)
> bug: profile fix

- app/grants/templates/grants/activity.html
Fixes the broken PR around hiding ethereum address in grants activity
tested locally
> Fix hide address

- requirements/base.txt
Bump celery version
Issue with python 3.7 and the async keyword
https://github.com/celery/celery/issues/4849
> update celery to 4.4.0 to fix python 3.7 issue

- app/app/context.py
- app/assets/v2/js/pages/chat.js
- app/chat/management/commands/sync_users_to_chat.py
- app/chat/tasks.py
- app/chat/templates/chat.html
- app/chat/views.py
- app/dashboard/views.py
- scripts/debug/grants_round_stats.py
adds linux and mac desktop apps; alerts users when apps not ready yet
slack convo
tested locally
> adds linux and mac desktop apps; alerts users when apps not ready yet

- app/retail/templates/vision.html
- app/retail/views.py
Add youtube embed videos to /vision page
Fixes #5742 
Go to `/vision` to view it.
> Issue 5742 add youtube preview to vision page

- app/app/utils.py
- docker-compose.yml
Fix orgs not being fetched when someone without the 'orgs' scope login. This was something we changed for "permission management" but we didn't changed back when rolled back the scopes.
Also this fix an error on login happening sometimes on localhost as how is docker setup:
"werkzeug/filesystem.py:60: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ascii'"
"UnicodeEncodeError: 'ascii' codec can't encode character '\xe1' in position 988"
> Fix the fetch org on login

- app/dashboard/templates/ftux/job.html
- app/dashboard/templates/profiles/tab_hackathons.html
- app/dashboard/templates/profiles/tabs.html
- app/dashboard/views.py
Adds hackathon tab to profiles showing the projects I created.
fix: #5787
> add hackathon projects to profile

- app/dashboard/models.py
- app/dashboard/views.py
Use the new `bounty_state` defined in models.py as opposed to `idx_status`
closes https://github.com/gitcoinco/web/issues/3782
> chore: update active bounties logic

- app/assets/v2/js/pages/bounty_details.js
> var -> let/const

- app/assets/v2/js/grants/shared.js
Fixes an issue that only a few users are happening, but it throws a lot of errors in sentry
untested
> fix sentry error when no account available in grants

- app/app/settings.py
- requirements/base.txt
This PR adds the datadog django integration (ddtrace)
n/a
untested but env flagged
> add datadog django integration (ddtrace)

- pydocmd.yml
This PR fixes pydoc in travis
broken travis on master
tested on travis
> remove command that doesnt exist that causes travis error in pydoc

- app/app/urls.py
- app/assets/v2/js/status.js
- app/dashboard/templates/profiles/status_box.html
- app/marketing/mails.py
- app/retail/emails.py
- app/retail/templates/emails/mention.html
- app/retail/templates/emails/mention.txt
- app/retail/views.py
- app/townsquare/views.py
Show dropdown of a list of users when a @ is detected in the textarea.
Fixes #5823.
> Show dropdown when user is about to tag a person using @

- app/grants/models.py
- app/grants/templates/grants/activity.html
- app/grants/templates/grants/transaction.html
- app/grants/utils.py
grant fee deductions are now broken out + shown in the contribution history
and the total amount funded for a grant now is represented as the amount the user actually received .. the example grant above had 991 DAI before and how has 964 DAI..
> grants fee deductions are now transparent

- app/assets/v2/css/gitcoin.css
- app/assets/v2/js/pages/profile.js
- app/dashboard/templates/profiles/tabs.html
- app/quests/templates/quests/index.html
Fix UI inconsistency on tabs.
Fixes #5718 
Checkout profile page tabs and quests tabs to view it.
> Ui element fixes

- app/assets/onepager/js/receive.js
- app/assets/v2/js/pages/kudos_receive.js
- app/assets/v2/js/pages/onboard.js
- app/dashboard/tip_views.py
- app/dashboard/utils.py
- app/dashboard/views.py
- app/kudos/views.py
- app/marketing/views.py
This PR fixes some POST/GET and potential XSS issues
https://github.com/gitcoinco/web/issues/5183
tested by OG bounty hunter
> Xss fixes majortomsec

- app/assets/v2/js/pages/carousel.js
- app/kudos/templates/kudos_about.html
- app/kudos/templates/kudos_details.html
- app/kudos/templates/kudos_marketplace.html
- app/kudos/templates/shared/kudos_card.html
Replaces jquery jquery-unveil making fail the logo animation and some page images using the new native lazy loading for images (https://caniuse.com/#feat=loading-lazy-attr)  with a fallback using the browser observer api to detect scroll in more performatic way. 
- Native lazy loading image with fallback to observer on marketplace 
- Lazy load with observer in carousel
- Fix bootstrap being loaded 2 times
- Fix kudos rarity popover description broken 
https://share.vidyard.com/watch/kLb95naDbthVJQr7uYuSUW?
yep see video w
> Kudos native lazy load, fixes

- app/assets/v2/css/search.css
- app/assets/v2/js/search.js
- app/dashboard/templates/dashboard/users.html
Fix some bugs:
nav across the site with diff styles 
select2 classes 
Add gc-search class to search module to avoid collisions. 
Add responsive css 
Css changes to avoid flicking spaces.  
Add scroll to handle many results on box.
Tested diff pages and nav sizes.
> fix search css and js bugs

- scripts/deploy.bash
This PR creates a directory to store the profile wallpaper if it doesn't exist - this will happen on a newly deployed server so now one less thing to keep track of when putting up a new box
https://github.com/gitcoinco/web/issues/5921
untested but non-destructive
> create wallpaper dir if doesnt exist

- app/dashboard/templates/dashboard/sidebar_search_hackathon.html
- app/dashboard/views.py
`orgs = list({v['org_name']:v for v in orgs}.values())`
That list code is to remove duplicates from the org sidebar list
as both org_name (sablier and gitcoinco)  were actually "gitcoinco"  then only one is surviving
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1580912469043700
> fix hackathon override org listing 

- app/grants/templates/grants/detail/matching.html
- app/retail/templates/about.html
- app/retail/templates/bounties/funder/benefits.html
- app/retail/templates/emails/campaigns/email_campaign_day_3.html
- app/retail/templates/not_a_token.html
- app/retail/templates/results.html
- app/retail/templates/shared/what_is_gitcoin.html
- app/retail/views.py
- docs/README.md
Changed medium links to redirect to the gitcoin blog. As a user, I don't link being redirected to medium which in turn tells you to read the full story in the gitcon blog. I removed one 
unnecessary step.
Doesn't need testing
> Change medium links to redirect to the Gitcoin blog

- app/dashboard/templates/onepager/send2.html
- app/dashboard/tip_views.py
- app/dashboard/views.py
This use the same avatar as profiles when tipping a user by searching or linking from profiles 
Also fix the logic to pick the active avatar of the user to match the profile instead of the first one on the query results.
Example:
Is very confusing when you search some user to tip and the picture doesn't match with the one on profile, that make you feel insecure. 
locally testes with users and non users with base avatar and with just the GitHub image.
> Fix tip avatar not matching

- app/dashboard/templates/profiles/header_sync_profile.html
Small wording fix. See commits.
> [Small Fix] Wording on Back up Profile

- app/assets/v2/js/grants/fund.js
- app/assets/v2/js/grants/new.js
Adds a warning for users about using Brave Wallet and MetaMask while visiting `https://gitcoin.co/grants`
Fixes: https://github.com/gitcoinco/web/issues/5865
No issues on eslint and stylelint.
> Add warning for users visiting Grants page

- app/assets/v2/js/activity.js
When commenting/replying on activities/status posts, comments can be duplicated by hitting the return key more than once Disabling the textarea for every call of post_comment would solve the duplication problem.
closes https://github.com/gitcoinco/web/issues/6007
> fix: duplicate activity comments

- app/app/urls.py
- app/assets/v2/js/activity.js
- app/townsquare/views.py
- introduces new endpoint for comment (can be used for edit later)
- allows comment owner to delete comment
- updated the UI without refresh if delete is successful 
https://share.vidyard.com/watch/37ioTWS2PeK5Gvj2MdWAkU?
> feat: ability to delete comments

- app/avatar/utils.py
- app/dashboard/models.py
Ensure that organizations have proper avatars pulled from GitHub
Fixes #5992.
Manually tested by removing my own avatar and allowing the backend to automatically resync
> Fix org avatars

- scripts/deploy.bash
restarts celery on deploy
deploy channel
still working out kinks.  see deploy channel
> restarts celery on deploy

- app/assets/v2/js/pages/bounty_details.js
- app/marketing/mails.py
- app/townsquare/models.py
> bug: fix activity section in bounty

- app/app/utils.py
- app/assets/v2/js/notifications.js
- app/inbox/models.py
- app/inbox/signals.py
- app/inbox/utils.py
- app/marketing/mails.py
- app/retail/views.py
- app/townsquare/models.py
- app/townsquare/tasks.py
Get notifications from someone pinging me in the town square or for responses to my post
- I receive a notification when someone pings me on a post
- I receive a notification when someone comments on my posts
- I receive a notification when someone pings me on some comments
#5943
> As a gitcoin user, I would like to see the responses to my post in the Notifications.

- app/assets/v2/js/pages/townsquare.js
- app/dashboard/models.py
- app/retail/views.py
- app/townsquare/templates/townsquare/index.html
- app/townsquare/views.py
Added the filter for getting only those activities which are related to the user.
Fixes: https://github.com/gitcoinco/web/issues/6012
N/A
> Add personal only filter for activity feed

- app/app/urls.py
- app/dashboard/management/commands/sync_etc_payouts.py
- app/dashboard/models.py
- app/dashboard/utils.py
- app/dashboard/views.py
- remove sync/etc
- create new endpoint for bounty_fulfilment
- added fields to BountyFulfillment [ token_name, payout_tx_id, payout_status,
payout_amount ]
- replaced etc sync checks to use BountyFulfillment as opposed to Bounty
> api: refactor + new endpoint for ETC payout

- app/dashboard/templates/ens/base.html
Missing moment.js error on ENS page
#6053
> Add missing moment that prevents register ens subdoamin

- app/townsquare/templates/townsquare/index.html
> remove: negative bonuses  

- app/assets/v2/js/activity.js
Shows a confirmation before deleting a comment and enables canceling.
Demo video: https://youtu.be/LfLDCPo3IjM
Closes https://github.com/gitcoinco/web/issues/6084
> feat: show confirmation before deleting comment

- app/assets/v2/css/gitcoin.css
- app/dashboard/templates/dashboard/index.html
- app/townsquare/templates/townsquare/index.html
Sticky nav in townsquare and bounties explorer so people can access diff areas an notifications without need to scroll to the top
> sticky nav in some places

- app/dashboard/views.py
This PR fixes a bug in the tribes explorer where it would try to load too much data at once and possibly time out
tested locally
> fix tribes explorer loading and user explorer

- app/perftools/management/commands/vacuum.py
- scripts/crontab
as you guys know, i have OCD about site speed.  so today when the postgres auto vacuum er locked up the site, i had a conniption.
i wrote this quick script to turn off the auto vacuumer https://bits.owocki.com/bLum0Ene 
and then i wrote this PR so we could vacuuum the site on our own schedule.. when load is lowest (sundays)
sample output:
```
root@f48599102c8a:/code/app# ./manage.py vacuum
dashboard_profilestathistory took 0.66s
quests_questfeedback took 0.05s
economy_conversionrate took 0.18s
feeswapper_currencyconversion took 0.07s
dashboard_blockedurlfilter took 0.02s
townsquare_like took 0.02s
faucet_faucetrequest took 0.03s
grants_update took 0.02s
marketing_accountdeletionrequest took 0.02s
dashboard_bounty took 1.97s
economy_token took 0.03s
auth_group took 0.02s
dashboard_coupon …
```
> vacuum tables on our own schedule

- app/assets/v2/css/grants/detail.css
- app/assets/v2/css/grants/new.css
- app/assets/v2/js/grants/detail.js
- app/assets/v2/js/grants/new.js
- app/assets/v2/js/grants/shared.js
- app/grants/templates/grants/card/front.html
- app/grants/templates/grants/detail/info.html
- app/grants/templates/grants/new.html
- app/grants/tests/test_views.py
- app/grants/views.py
`/grants/new`
`/grants/`
`/grants/<:grant-id>`
https://share.vidyard.com/watch/3WXLB5bzS9Dc4NGFyWLKwc
Refs: https://github.com/gitcoinco/web/pull/5615
> bug: fix up grant category

- app/app/local.env
- app/app/utils.py
- app/assets/v2/js/base.js
- app/chat/tasks.py
- app/dashboard/tasks.py
- app/dashboard/views.py
Couple of quick fixes to address some post deploy issues.
- moving chat_id and gitcoin_chat_access_token reconciliation into the `sync_profile` method
- ensure that the hackathon project creator gets added to the channel
- check for new notifications on page load and then interval the checks at 15 seconds
> Hotfix/chat 1.2.2

- app/app/context.py
- app/app/utils.py
- app/avatar/views_3d.py
- app/dashboard/notifications.py
- app/dashboard/views.py
Uses a [solution found here](https://stackoverflow.com/questions/492519/timeout-on-a-function-call) to prevent production timeout errors.
adds a re-usable decorator for managing those timeouts
Production timeout errors on approving users
```
from app.utils import timeout
import time
@timeout(2)
def foo():
time.sleep(10)
foo()
```
will yield
```
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
<ipython-input-1-f4b9f2b0c14b> in <module>
6     time.sleep(10)
7
----> 8 foo()
/code/app/app/utils.py in func_wrapper(*args, **kwargs)
508             async_result = pool.apply_async(item, args, kwargs)
509             # raises a TimeoutError if execution exceeds max_timeout
--> 510 …
```
> Handle Prod Timeout Worker Approve Timeout Errors

- app/assets/v2/js/pages/bounty_details2.js
- app/dashboard/templates/bounty/details2.html
- app/dashboard/utils.py
- app/dashboard/views.py
change pending by default after payout
close modal
refetch bounty data.
> fix etc payout flow

- .gitattributes
add .gitattributes and ensure LF for shell files - fixes exit code 2 of Worker in local Docker builds on Windows
closes https://github.com/gitcoinco/web/issues/6136
> add .gitattributes and ensure LF for shell files - fixes exit code 2 of Worker in local docker builds on Windows

- app/grants/clr.py
- app/grants/management/commands/estimate_clr.py
- app/grants/views.py
- remove random data as the algorithm has changed
- filter contribution as +ve and -ve contributions
- update code to ensure -ve voting is taken into account
- update check to ensure algorithm runs when a grant has no `-ve` voting
> chore: final BE wiring for grants

- app/grants/clr.py
Last minute Vitalik changes to the negative voting in the case of 1 negative vote with no pair.
creates a more linear positive/negative voting curve
confirmed on Aditya's / Frank development branch: https://github.com/thelostone-mc/clr/blob/frank-dev/contrib_calculator_r5.py
> Negative Voting Single Calculation Change

- docs/CONTRIBUTING.md
Specify that there's a `make fix` command and makes our lives easier while ensuring that PR code follow Gitcoin styling & lining standards
Refs: https://github.com/gitcoinco/web/issues/4943
> Fix contribute docs

- app/inbox/signals.py
When `activity.kudos_transfer.receive_url_for_recipient` doesn't exist (doesn't require the user to redeem the kudos), the user is redirected to `gitcoin.co/{gh_handle}/kudos`
Take User to Profile After Clicking See Kudos Notification #6212
> Take User to Profile After Clicking See Kudos Notification

- app/assets/v2/css/town_square.css
- app/townsquare/templates/townsquare/index.html
> remove position-relative on clr_container 

- app/dashboard/helpers.py
- app/dashboard/models.py
This PR is a simple, but inelegant fix for issues where cross chain bounties have the wrong projects attached
Tested locally w/ prod data
> Naive std bounties cross chain

- docs/RUNNING_LOCALLY_DOCKER.md
There was an additional backtick breaking instructions on #### Docker for-mac troubleshooting section, and it has been corrected.
https://github.com/gitcoinco/web/issues/6310
This is a documentation change.
> Typo correction that was breaking instructions.

- app/assets/onepager/js/send.js
- app/assets/v2/js/activity.js
- app/assets/v2/js/grants/shared.js
- app/assets/v2/js/pages/bounty_details.js
- app/assets/v2/js/pages/bulk_payout.js
- app/assets/v2/js/pages/cancel_bounty/ETH.js
- app/assets/v2/js/pages/faucet_form.js
- app/assets/v2/js/pages/fulfill_bounty/ETH.js
- app/assets/v2/js/pages/increase_bounty.js
- app/assets/v2/js/pages/process_bounty.js
- app/assets/v2/js/pages/refund_request.js
- app/assets/v2/js/shared.js
- app/dashboard/templates/onepager/base.html
- app/retail/templates/pricing/subscribe.html
This moved the `listen_for_web3_changes` to the files where it's needed as opposed to having it shared.js
Flows tested
✔️  Bounties
✔️ [Tips](https://user-images.githubusercontent.com/5358146/78261919-7d9a7f80-751d-11ea-9271-79153ee3be53.png)
✔️ Townsquare [PART 1](https://user-images.githubusercontent.com/5358146/78261985-9014b900-751d-11ea-80aa-a5f03ad31de8.png) & [PART 2](https://user-images.githubusercontent.com/5358146/78262028-9f940200-751d-11ea-8010-b1a8367d118f.png)
✔️ [Kudos](https://user-images.githubusercontent.com/5358146/78261861-68255580-751d-11ea-9e56-03ba79321f63.png)
✔️ Activities page [PART 1](https://user-images.githubusercontent.com/5358146/78262141-c94d2900-751d-11ea-9f7f-5b35509527e9.png) & [PART 2](https://user-images.githubusercontent.com/5358146/78262246-ec77d880-7 …
> refactor: fixup listen_for_web3_changes

- app/assets/v2/css/dashboard.css
- app/assets/v2/css/search_bar.css
- app/assets/v2/css/sidebar_search.css
- app/dashboard/templates/dashboard/hackathon/projects.html
- app/dashboard/templates/dashboard/index.html
- app/dashboard/templates/dashboard/sidebar_search_hackathon.html
- app/dashboard/templates/shared/search_bar.html
Reverts gitcoinco/web#6347
This code was already used in #6359
> Revert "Add hackathon prizes view and projects"

- app/assets/v2/css/search.css
- app/assets/v2/js/search.js
- app/assets/v2/js/vue-filters.js
- app/dashboard/templates/shared/nav_auth.html
- app/dashboard/templates/shared/search.html
- redo search UI based on sketch  
- built out search in vue
- add new vue filters
- split results into categories
- description is trimmed
- design is responsive 
- layout is built as per the sketch 
- hides the categories until 3 chars are entered 
- if a category has no results -> no matches found message is shown
https://github.com/gitcoinco/web/pull/5835
https://share.vidyard.com/watch/gjPeWcUnystHYCXSGJTRBN?
> feat: redo search UI

- app/retail/templates/shared/activity.html
> "Got a distribution of"

- app/assets/v2/js/activity.js
The existing regex to identify @mentions was also identifying the same that could occur in URLs like from medium: https://medium.com/@shevski/how-decentralised-are-you-a6539eeb27ff
The regex has been modified to correctly identify intended @mentions and not those in URLs.
Fixes #6298 
Original input to status update:
```
@shevski @shevski @shevski
Although the article is published over one year ago. It’s a must read for anyone involved in tech related businesses. https://medium.com/@shevski/how-decentralised-are-you-a6539eeb27ff
```
**Before:**
Also see: https://github.com/gitcoinco/web/issues/6298#issuecomment-612713914
**After:**
> Fix @mention recognition in Townsquare

- app/dashboard/views.py
- app/grants/views.py
- app/kudos/views.py
- app/quests/views.py
- app/retail/templates/tribes/landing.html
- app/retail/views.py
https://github.com/gitcoinco/web/pull/6451
> Fix card  image display on twitter cards

- app/assets/onepager/css/main.css
- app/assets/v2/css/bounty.css
- app/assets/v2/css/gitcoin.css
- app/assets/v2/js/pages/bounty_details2.js
- app/dashboard/templates/bounty/details2.html
- app/dashboard/templates/shared/organization_tooltip.html
- app/dashboard/templates/shared/permissions_type_tooltip.html
- app/dashboard/templates/shared/project_type_tooltip.html
- app/dashboard/templates/shared/status_tooltip.html
- app/dashboard/views.py
- remove unused admin methods
- add activity on close bounty
- fixed broken fa icons
- updated tooltip design
- added icon for expired fulfillment to inform user
- set txn/address link based on token
- made qr code generate based on token
> chore: cross-chain improvs

- app/assets/v2/js/pages/bounty_details2.js
This PR adds testnet URI schema for Celo and the expected schema for ZIL
n/a
untested
> add uri schema for celo, zil

- app/app/urls.py
This PR fixes an issue where a username starting with the prefix "web3" would get handled by the wrong view if trying to view their profile.
reported on slack
tested locally
> match strictly to prevent profiles starting with web3 from redirecting

- app/dashboard/templates/profiles/tribes-vue.html
> Add projects responsive fixes

- app/assets/v2/js/vue-components.js
Fixed suggested profile key issue.
> remove bad :key

- app/grants/clr.py
this PR fixes a divide by zero error where the normalization factor could not be calculated during CLR
n/a
not tested
> No contrib grants clr fix

- requirements/base.txt
This PR bumps the version of django-autotranslate to its latest release. It solves the error being raised when building the web docker container using a version of pip>=20.1
```
Collecting django-autotranslate==1.1.0
Downloading django-autotranslate-1.1.0.tar.gz (8.7 kB)
ERROR: Command errored out with exit status 1:
command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-05q5rnle/django-autotranslate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-05q5rnle/django-autotranslate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-jfqeewod
cwd: …
```
> Bump version of django-autotranslate

- app/assets/v2/js/pages/bounty_details.js
- app/assets/v2/js/shared.js
- app/assets/v2/js/user_card.js
> chore: lint fixes

- app/assets/v2/js/activity.js
limit maximum input in the comments otherwise, you will get something like this
https://gitcoin.co/townsquare?tab=activity:273525
so better allow maximum 500 chararacters
> limit maximum input in the comments 500 chars

- app/app/urls.py
- app/dashboard/views.py
Fixes the issue where if you put an uppercase char in the URL the system will not be able to find u rprofile
self
tested locally
http://gitcoin.co/Virtual-Face
http://gitcoin.co/Owocki
> profile casing fixes

- app/townsquare/utils.py
- app/townsquare/views.py
townsquare/utils has a helper can_pin to check for permission to create/update/delete a pin, the grant import was missing.
Bug found by @owocki
> Add missing Grant import to townsquare/utils

- app/dashboard/views.py
- app/retail/templates/shared/activity.html
- app/townsquare/templates/townsquare/shared/shareactivity.html
Pinned post introduced a regression due to a variable name re-use.
shared/activity.html was including a hidden input that gets passed along, it is failing for hackathons/tribes/anything that uses the shared/activity with the exception of plain townsquare.
No ticket, was found by @connoroday reported via slack
Please test with Prod data before deploying.
> Fix issue with posting to integrated townsquare views.

- app/assets/v2/js/pages/dashboard.js
Fixes broken search when search term has `.`
closes https://github.com/gitcoinco/web/issues/6740
> bug: fix explorer search

- app/retail/emails.py
from https://gitcoincore.slack.com/archives/CDML7FS7M/p1590761159004600
> revert breaking premailer fix

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/discussion.md
- .github/ISSUE_TEMPLATE/feature_request.md
- app/dashboard/notifications.py
- app/retail/templates/emails/funder_payout_reminder.html
- docs/CONTRIBUTING.md
- docs/GRANTS.md
Changed links to redirect to chat instead of slack
PR so small, are tests needed?
> Change slack links to chat ones

- app/avatar/migrations/0007_auto_20200229_2343.py
- app/grants/templates/grants/fund.html
- app/grants/templates/grants/shared/landing_hero.html
- app/retail/templates/shared/footer.html
- app/townsquare/templates/townsquare/offer.html
- app/townsquare/templates/townsquare/shared/matchround.html
Using `target="blank"` opens links each time in the same window with name "blank". The intended behavior seems to be to create a new window for each link, so this PR fixes all wrong targets "blank" to "_blank".
N.A.
This fixes only static HTML, no changes in test.
> Fixed all wrong target "blank" to "_blank"

- app/app/urls.py
http://localhost:8000/gas -> directs you to GAS
http://localhost:8000/gas/ -> directs you to GAS
http://localhost:8000/gasrwerworme -> tries to find profile page
closes https://github.com/gitcoinco/web/issues/6707
> bug: fix incorrect url

- app/dashboard/models.py
- app/grants/views.py
- app/kudos/templates/transaction/receive_bulk.html
- app/kudos/views.py
- app/quests/helpers.py
- app/revenue/management/commands/submit_pending_kudos.py
- scripts/crontab
A few weeks ago, i noticed that with high gas prices on the eth network, the kudos minter was burning $200 per day in gas fees.
so i introduced a change to require people to pay their own gas, which would cut down the costs.
but following up on that today, it looks like this has really hurt the number of quest players, see below:
so i'm introducing this PR, which introduces a "not submitted" state to the kudos transfer object, wherein the kudos will be submitted to one's profile immediately, but not to their web3 wallet until the ethereum network isnt super expensive anymore.
hopefully this approach reaches the twin goal of keeping gitcoin's costs down AND also keeping quest usage up
from testing:
> re-enable free kudos for Gitcoin Quests/Grants

- app/grants/templates/grants/new-whitelabel.html
- app/grants/views.py
This PR allows the matic dapp registration page to be loaded w/o logging in, enabling the Twitter card to work properly
n/a
Tested locally
> show twitter card w/o login, alert w/o login

- app/assets/v2/js/grants/funding.js
- app/grants/templates/grants/cart-vue.html
Closes https://github.com/gitcoinco/web/issues/6867
Changes:
- Replaces `select2` component `:options` parameter with `<option>` elements
- Replaces underscores with emdashes for token divider (this centers the divider in its row instead of having it at the bottom)
To test:
1. Add multiple grants to cart
2. Remove one
3. Make sure token selections do not change
4. Change token selections of remaining grant check local storage > `grants_cart` 
and make sure the `grant_donation_currency` field is updated and matches what is in the token selection box
cc @owocki @apbendi
> Fix token selection dropdown

- app/assets/v2/js/pages/new_bounty.js
This PR fixes the showing of `undefined` in 'Invite to Bounty' contributors list when creating a new bounty
**Note:** This PR is pointed to `stable` branch because the fund.html is removed in the `master` branch. Please LMK if this needs to be changed.
Fixes #6861 
**Before:** https://github.com/gitcoinco/web/issues/6861#issue-638823508
**After:**
> Fix: undefined in Invite to Bounty contributor list

- app/dashboard/templates/dashboard/index-vue.html
noticed the hackathon nav on 13inch laptop while @vs77bb  was sharing screen
The hackathon sponsor takes too much real estate
This PR cleans it up 
- by shrinking the sponsor section
- fixing the wonky css where the sponsor logo overflows the white bg
LIVE: https://gitcoin.co/hackathon/clarity/?tab=hackathon:20
In 13inch screen:
**This PR:** 
In 13inch screen:
In 15inch screen:
> chore: cleanup sponsor sidebar

- app/grants/templates/grants/new.html
> chore: change Grant Categories 

- app/retail/templates/cookielaw/banner.html
In the cookie banner, the `Gitcoin's Terms & Conditions` is redirecting to `legal/policy` instead it should point to `legal/terms`, I've jsut changed that.
PR so small, no need to test
> Change Gitcoin's Terms & Conditions to point to legal/terms instead of legal/policy

- app/assets/v2/js/cart-data.js
- app/assets/v2/js/cart.js
- app/economy/models.py
- app/grants/templates/grants/bulk_add_to_cart.html
- app/grants/templates/grants/cart-vue.html
- app/grants/templates/grants/shared/hidden_inputs.html
- app/grants/views.py
- Share cart with amount and token included
- Persist comments when the user refresh
https://www.loom.com/share/092a487867f44753a6e56c43c80a00d2
> Share amount and tokens

- app/grants/router.py
It seems the current output from the `/grants/report/` endpoint contains duplicate entries, which is supposedly causing a performance issue at the endpoint, ultimately leading to a 502: https://github.com/gitcoinco/web/pull/6633#issuecomment-641137758
https://gitcoin.co/api/v0.1/grants/report/?eth_address=0xC0eBeFadCbF1d2A85fBfDDC226a95860F5152b5f&from_timestamp=2019-05-01T01:24:15Z&to_timestamp=2020-06-09T01:24:15Z
This PR prevents the duplicate entries to appear in the API response.
Refers/Fixes/Follow-up to: #6633 
Refers/Fixes/Follow-up to: https://github.com/gitcoinco/web/pull/6633#issuecomment-641137758
**Before:**
**After:**
> Fix: duplicate entries in /grants/report API

- app/grants/templates/grants/cart-vue.html
Closes #6950 and #6897
Adds an explicit `step="any"` to inputs on the Cart page to prevent Firefox from incorrectly showing a red border when a user enters a decimal value
@owocki
> Fix Firefox issue that showed red border for decimal inputs in cart

- app/app/urls.py
- app/dashboard/management/commands/grant_txn_failed_email.py
- app/marketing/mails.py
- app/retail/emails.py
- app/retail/templates/emails/grant_txn_failed.html
- app/retail/templates/emails/grant_txn_failed.txt
- app/retail/templates/emails/template.html
This PR builds a new email to notify Grants contributors if their contribution txns have failed
Fixes #6556
**Gmail Web:**
**Gmail Mobile:**
**Web Preview:**
> New Grants txn Failed Email

- app/assets/v2/js/cart.js
- app/retail/templates/about.html
This PR has two changes in regards to gas estimates
The current default estimate for token donations is 100k per donation, but this is insufficient for some tokens:
- A standard ANT transfer costs up to 131k gas, so for ANT donations we add some margin and now use a value of 170k gas
- An aDAI transfer can vary in gas cost depending on your address status in the platform (e.g. if you are borrowing it might be more costly than if you're not borrowing). The Aave team suggested a gas limit of 500k per transfer which they say should be more than enough
- If transferring cDAI in MetaMask, the gas limit is automatically set to 400k. So we add a bit of margin here and use 450k gas per transfer
If a cart is all Dai (which is about 75% of checkouts), we use a linear regression to estimate the gas …
> Improve cart gas estimates for DAI, aDAI, cDAI, and ANT

- app/assets/v2/js/cart.js
- app/assets/v2/js/grants/funding.js
Fix bug introduced when `get_amount` endpoint was updated to accept multiple currencies as an input
cc @thelostone-mc
> Fix parsing of fallback amount

- app/grants/clr.py
Based of  https://github.com/thelostone-mc/clr/commit/0b7e57dd23d077999bc6a9f17467c0f334970793
> chore: update normalization logic

- app/assets/v2/js/pages/bounty_details2.js
- app/assets/v2/js/pages/new_bounty.js
- app/dashboard/sync/celo.py
- app/dashboard/templates/dashboard/hackathon/new_bounty.html
- app/dashboard/utils.py
- replace cGLD-> CELO
- replace testnet with mainnet
- test out flow
https://share.vidyard.com/watch/RAHFbh3jrXtkhvFqhGiJzQ?
> celo: move to mainnet

- app/assets/v2/css/activity_stream.css
- app/assets/v2/css/gitcoin.css
- app/assets/v2/css/town_square.css
- app/assets/v2/js/activity.js
- app/assets/v2/js/base.js
- app/assets/v2/js/pages/townsquare.js
- app/townsquare/templates/townsquare/index.html
- app/townsquare/templates/townsquare/shared/feednav.html
- app/townsquare/templates/townsquare/shared/hackathons.html
- app/townsquare/templates/townsquare/shared/matchround.html
- app/townsquare/templates/townsquare/shared/reflink.html
- fix up alignment on tooltip
- fix up clunky UI + made stuff more breathable 
- added in some dark mode fixes
- removed weird accordion and reused existing code
- reindent TS files
Built on top of https://github.com/gitcoinco/web/commit/7f2311fb90bde4eaf1a5a6d9865b65552b4a8811 
(pushed this into master as it had small fixes)
https://share.vidyard.com/watch/TPCDPvfToxBH45eJYaBZfd?
> chore: clean up TS

- app/grants/clr.py
- set CLR_END_DATE if not default to current.timezone 
- removed defaults and added null checks in place
- updated code to use CLR_END_DATE
> chore: set CLR_END_DATE

- scripts/crontab
Disable syncing to slack since its broken now as the underlying API has changed - not sure if this feature is even used anymore (likely not since nobody has reported this)
https://sentry.io/organizations/gitcoin/issues/1547301462/?project=1398424&query=is%3Aunresolved
not tested but probably not needed
> disable sync slack as slack api has changed

- app/assets/v2/js/pages/bounty_details2.js
- app/assets/v2/js/pages/hackathon_new_bounty.js
- app/dashboard/models.py
- app/dashboard/templates/bounty/details2.html
- app/dashboard/views.py
- Add new payout_type/web_3_type manual
- Add new tenant CUSTOM
- Add validation to ensure manual bounties are allowed only for hack bounties
- Update hackathon form logic to set web3_type -> manual for other chains
- Add Bounty Details Payout Modal for manual payout flow 
creation -> https://share.vidyard.com/watch/Uakjjvo3tahiCvHfkdqMG8?
submission + payout -> https://share.vidyard.com/watch/vZXjB1eeDGjKzS1Rp3E666?
> feat: add support for new type manual

- app/dashboard/templates/onepager/base.html
- app/grants/templates/grants/new-whitelabel.html
- app/kudos/templates/transaction/base.html
- app/retail/templates/bounties/contributor.html
- app/retail/templates/bounties/funder.html
- app/retail/templates/how_it_works/index.html
This PR adds in missing cookielaw script imports to stop sentry errors
https://sentry.io/organizations/gitcoin/issues/903799097/?project=1398424&query=is%3Aunresolved
tested locally
> add cookielaw script ever ywhere

- app/dashboard/views.py
`HackathonRegistration` instances are prone to have duplicates as described here https://github.com/gitcoinco/web/issues/7070. This pull requests ensures that `hacker_count` counts only distinct `registrants` for a hackathon event.  Tested locally.
fixes https://github.com/gitcoinco/web/issues/7051
related https://github.com/gitcoinco/web/issues/7070
> fix: count distinct registrants to avoid duplicates

- app/assets/v2/js/cart.js
- app/grants/urls.py
- app/grants/views.py
Closes https://github.com/gitcoinco/web/issues/7002
Changes/notes:
1. New endpoint of `/grants/bulk-fund`
2. Similar API to the original `/grant_id/grant_slug/fund` endpoint. The difference is that now the payload expects arrays of data for the object fields that differ for each donation.
3. Like before, when the `postToDatabase()` function of `cart.js` sends the POST request, it *does not* wait for the response before proceeding
4. `perftools.models.JSONStore` is used to save the POST payload before any processing happens
cc @owocki @apbendi
> Reduce carts post requests

- app/assets/v2/js/cart.js
Closes https://github.com/gitcoinco/web/issues/7056
During checkout, if the user selects DAI for each grant contribution in their cart, a special heuristic is used to estimate gas. Before this PR, this heuristic would be accidentally applied any time a cart used the same token for each grant in their cart, regardless of whether or not that token was DAI. 
This PR resolves that so the gas estimation heuristic is now only used for carts with DAI
cc @owocki
> Fix check to see if cart uses only DAI

- app/assets/v2/css/town_square.css
The current z-index overlaps with the top navigation bar when you're scrolling. Setting the z-index to 0 would make the activity card go under the navbar as expected.
> Set the z-index for .activity.hackathon_new_hacker to 0

- app/dashboard/tip_views.py
> removes per tip txn limit

- app/assets/v2/js/grants/new.js
- app/grants/templates/grants/new-whitelabel.html
Allow matic grant creation without web3 
https://github.com/gitcoinco/web/issues/7106
tested locally (matic, regular grants)
> allow matic grant creation w/o web3

- app/assets/v2/js/pages/bounty_detail/web3_modal.js
Flows tested
- Rinkeby ETH flow
- Mainnet ETH flow
- Rinkeby ERC20 token (LOLA)
- Mainnet ANT token
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1596709635067100?thread_ts=1596666404.051500&cid=CAXQ7PT60
cc @octavioamu could you validate it
> bug: fix ERC-20 payment flow

- app/kudos/tasks.py
This PR stops exceptions that are thrown when minting or redeeming airdropped kudos, either due to network congestion or some other reason that causes the celery task to be retried. After the max retries are hit, we stop attempting to retry to the task.
n/a
untested
> proactively stop retrying tasks before max retries exception

- app/assets/v2/js/pages/kudos_details.js
https://sentry.io/organizations/gitcoin/issues/1724229795/?project=1398424&query=is%3Aunresolved
This variable is not used anywhere on our site ! Guess it was added but either was removed / never wired it
> bug: remove unused var kudosNumClonesAvailable

- app/assets/v2/js/pages/profile-tribes.js
- app/assets/v2/js/users.js
- app/assets/v2/js/vue-components.js
- app/dashboard/templates/profiles/tribes-vue.html
1. Add gitcoin staff to the tribe's admin view.
- user story: Help sponsors troubleshoot
If I’m an admin of gitcoin, I should also see admin view of tribes (so core team can help)
2. Fixes All view sorting by contributor rank
- before: All people view section under tribe sorted based on the user id.
- change: Sort all people view on the basis of users contributor rank.
3. Fixes tribe bounty tab for the default view (!minor)
- Current bounties tab was only viewable if the user follows the tribe.
- Change the bounties tab is the default for the tribe.
4. Fixes tribe Townsquare sidebar shows follow the suggestion for the top member-based on contributor rank.
- Once the user is followed it will disappear from the list
- Top 10 profiles will be shown based on the contributor rank.
- Don't show …
> Tribes light housekeeping #7143

- app/dashboard/templates/dashboard/index-vue.html
- app/retail/templates/shared/head.html
- app/townsquare/templates/townsquare/index.html
The bootstrap-vue styles are globally required now that chat is available in a fly out.
> move the bootstrap vue global styles into the shared head template

- app/dashboard/templates/dashboard/hackathon/hackathons.html
- app/dashboard/templatetags/date_fromisoformat.py
- app/dashboard/templatetags/timesince_fromisoformat.py
- app/dashboard/utils.py
- app/dashboard/views.py
- app/perftools/management/commands/create_page_cache.py
Have context loaded from `perftools.models.JSONStore`. Updates whenever `create_page_cache` management command runs. 
refers https://github.com/gitcoinco/web/pull/6297#discussion_r465957162
> Fix hackathon list page loadtime

- app/assets/v2/js/pages/dashboard-sponsors.js
- app/assets/v2/js/vue-components.js
- app/dashboard/templates/dashboard/index-vue.html
- app/dashboard/templates/dashboard/sponsors.html
- app/dashboard/views.py
Cleanup for the Integrated Hackathon view, move the ManageSponsor Component to ManageMentors and migrated it to the sponsor dashboard.
https://a.cl.ly/o0u8ZO9r
> fix for regression around bounty mentor payloads

- app/dashboard/views.py
related to recent PR https://github.com/gitcoinco/web/pull/7254
prevent error in local docker builds due to non-existing JSONStore object by automatically calling `create_hackathon_list_page_cache` from the `get_hackathons` view if `debug` is on.
> fix: missing JSONStore object

- app/assets/v2/js/pages/dashboard.js
- app/grants/management/commands/subminer.py
- app/marketing/management/commands/hypercharge_mode.py
- app/townsquare/management/commands/create_rankings.py
https://sentry.io/share/issue/9d3f30b8f1484072880914e614c5b43c/
Cannot resolve keyword 'grant_type' into field.
https://sentry.io/share/issue/00327463caf54c65a96232aff5e65909/
NoneType' object has no attribute 'process'
https://sentry.io/share/issue/927b7f72944546e8bfaeb3805224a536/
'NoneType' object has no attribute 'title'
https://sentry.io/share/issue/8d134aedb4034e6aaa030d2952a9b427/
Cannot read property 'toString' of undefined
> sentry fixes:

- app/dashboard/templates/dashboard/hackathon/onboard.html
- app/dashboard/views.py
To prevent duplicate hackathon registrations under an event:
- return error on POST to /register_hackathon/ if user already registerd
- if no poll on hackathon onboard page, disable 'Join Now' button on click
- if poll on hackathon onboard page, disable poll submit button on click
fixes https://github.com/gitcoinco/web/issues/7070
> fix: duplicate registration on hackathon onboarding

- app/dashboard/templates/dashboard/index-vue.html
- Integration of circle to apollo hackathon only.
- Replaces the old town square with gitcoin circle community.
Demo Video
https://www.loom.com/share/7574a829191e47b8b1c428e3f122caf2
> Integrate Circle

- .gitattributes
Useful for when `git log -L` is used on class methods -things work without the diff driver for functions and classes- and diffcore-pickaxe options.
> add python diff driver to gitattributes

- app/assets/v2/js/cart.js
- app/assets/v2/js/grants/detail.js
- app/grants/templates/grants/cart-vue.html
Second round of zkSync changes is ready for review. There are a lot of code paths and I've only tested against Rinkeby, so there are almost guaranteed to be some bugs and issues so please report any issues you find while testing this PR.
Changes in this PR are explained below.
There are two zkSync accounts to consider: 
1. gitcoinSyncWallet — A zkSync wallet generated by having the user sign a Gitcoin-specific message. This gives us the private key used to create this deterministic wallet. Since we have the private key, we can send transfers without prompting the user
2. nominalSyncWallet — The default zkSync wallet generated through the zkSync SDK, using the user's web3 account. We do not have the private key, so the user receives a signature prompt on each transfer
Upon clicking …
> zkSync updates part 2

- app/assets/v2/js/grants/index.js
- app/grants/templates/grants/detail/info.html
- app/grants/templates/grants/index.html
- app/grants/templates/grants/shared/landing_subnav.html
- app/grants/templates/grants/shared/sidebar_search.html
- app/grants/views.py
- responsive design is messed up on the list view https://bits.owocki.com/7KuLwDrr
- count is correct but not all grants are being fetched (due to some weird additional filter being applied)
SEE HERE
It might be cause of the default filters you add here ?
- #7319
- can u pls reverse the coloring of these filters? https://bits.owocki.com/E0unNxNL
- My Grants doesn't work
- http://localhost:8000/grants/tech?network=rinkeby
The network param doesn't get applied when entered via URL
#7319
https://github.com/gitcoinco/web/issues/7352
> Batch 1 - fix for vue view list and add team members

- app/assets/v2/js/cart.js
- app/assets/v2/js/pages/profile-trust.js
- app/assets/v2/js/vue-components.js
- app/dashboard/templates/profiles/tab_trust.html
- app/dashboard/views.py
- app/grants/templates/grants/cart-vue.html
- app/grants/views.py
This PR represents the minimum needed improvements to the Trust Bonus system to launch Grants Round 7.
**Note**: one thing that *is* missing is the conditional information about the Trust Bonus in the email after a grant contribution. This should be completed as part of https://github.com/gitcoinco/web/issues/7131
* Add SMS verification to Trust Bonus tab (Note: it currently pushes the user to the cart to verify their SMS. This is a hack until we can refactor that code)
* Add Twitter verification placeholder to the Trust Bonus tab (Functionality "Coming Soon")
* Conditionally show a banner on the cart with information about the Trust Bonus, only if the user is not already BrightID verified.
* Increase the size of the BrightID QR Code by 75%
> Grants Round 7 Trust Bonus Improvements

- app/assets/v2/js/abi.js
- app/assets/v2/js/cart.js
> zkSync bug fixes

- docs/RUNNING_LOCALLY_DOCKER.md
Container ships in bin <code> python3</code> env by default <code> python </code> shall throw enviroment issue
> [docs] make sure it uses python3

- app/assets/v2/js/cart.js
- app/assets/v2/js/grants/index.js
For zkSync Flow A:
- We were sending too much as amount for first transfer, so zkSync transfers could fail if the total amount held in zkSync was close to the total donation amount
- Previously we were incorrectly estimating max required signatures for zkSync
Also ran the linter which is the only reason `index.js` is modified
> Fix small zkSync bugs, run linter

- app/assets/v2/js/cart.js
- app/assets/v2/js/pages/results.js
Current changes
Fixes item 2 of https://github.com/gitcoinco/web/issues/7421, which says:
> POST request to save data is not sent until after all transactions, so if the donation tx fails this does not get logged and we don't have the contribution data for matching. Move this POST request to be sent after L1 tx (if applicable) and before the L2 txs are sent
For Flow A (pure zkSync) the POST request is now sent after the initial transfer from the nominal zkSync wallet to the Gitcoin zkSync wallet. This means if transfers fail we'll still have all the contribution data in a JSON Store and saved as contributions/subscriptions
For Flow B (L1 deposit) nothing is changed. The POST request is still sent after the deposit tx is sent, but before it is mined (and therefore before any L2 txs occur) …
> More zkSync fixes

- app/assets/v2/js/pages/new_bounty.js
- app/dashboard/templates/bounty/new_bounty.html
Prevents having a decimal value, entered into the estimated hours' field. This is accomplished by using the Math.ceil function to round to the next hour. Since typically, 20minutes work should be billed on an hourly basis.
https://github.com/gitcoinco/web/issues/7261
1. Attempted inputing a whole number value, nothing changes
2. Input Decimal value that can be rounded up (e.g 3.7), it should round up to 4
3. Input decimal value that can be rounded down (e.g 2.2), it should round up to 3
4. Attempt pastiing decimal value (e.g 5.19), it should round up to 6.
> Prevent decimal on estimated hour field

- app/grants/models.py
- app/grants/views.py
In 044f877931eca4cc70971ed533710c6546a1e13f @owocki changed one of the contribution fields to use 18 decimals. The previous value of 4 decimals was causing the tx validator to incorrectly report some txs as failed.
This PR builds on that to just tweak the validator comments so that when they do fail we can get a little bit more info as to why
cc @octavioamu @thelostone-mc
> Tweak validator comments

- app/assets/v2/js/cart.js
- app/assets/v2/js/pages/profile-trust.js
- app/dashboard/templates/profiles/profile.html
- app/dashboard/templates/profiles/tab_trust.html
- app/grants/templates/grants/cart-vue.html
- docs/RUNNING_LOCALLY_DOCKER.md
Instead of kicking users over to the cart to verify their SMS, they can now do it directly from the Trust Bonus tab.
Note: This PR extracts and modifies code from the cart to create a vue component used on the Trust Bonus tab. The component is NOT currently shared with the cart, but should be, to DRY things up. This needed refactoring is noted in TODO comments, and should be tackled post Round 7.
> Enable SMS Verification directly from Trust Bonus tab

- app/assets/v2/js/cart.js
The list of supported zkSync tokens is stored as a computed property called `zkSyncSupportedTokens`. It's dependent on `document.web3network`. Vue cannot react to changes in `document`, so when the network changed this was not updated.
This means if a user visits the cart, then connects their wallet, the network change would not be detected, and `zkSyncSupportedTokens` would return an empty list. As a result, they would not be able to checkout with zkSync.
We fix this by adding a new property to the component. Vue can watch and react to changes in this new property, and we update this new property when the `dataWalletReady` event is detected. We also make the mainnet token list the default when nothing is detected
cc @octavioamu @thelostone-mc
> Make computed properties reactive to document.web3network changes

- docs/GRANTS.md
I changed 2000 -> 2k, to use the same notation on one sentence.
At first look, it could read as "2000k gas", since you use the notation of 'k' in the rest numbers.
> Bring to one order gas costs notations.

- app/assets/v2/js/cart.js
This is required for cart checkout with zkSync to work on wallets like Status that don't support `eth_sign`
> Fallback to personal_sign if eth_sign fails

- app/assets/v2/js/grants/new.js
Blunt force fix to a bug where the user's address is not validated or the ENS name is not resolved before the user submits a new grant, as documented in #7445.
> Prevent ENS name or other string from being submitted as address

- app/assets/v2/js/cart.js
- app/grants/templates/grants/cart-vue.html
- docs/GRANTS.md
Resolves #7397, #7469
1. To fix https://github.com/gitcoinco/web/issues/7397: When the cart loads we check the DB for a deposit tx hash from the user to see if their checkout was interrupted. If it was, we now have a check to see if the transaction failed. If it did fail, we mark the user as "not interrupted" so they can try checking out again
2. To fix https://github.com/gitcoinco/web/issues/7469: During zkSync checkout Flow B (user makes L1 deposit), the zkSync fees were not shown to the user anywhere, so we now show them at the bottom of the modal along with a link to the docs/GRANTS.md file to learn more about fees and how the checkout flow works. The modal is shown in the screenshot below. (Note that we don't need to show these fees in Flow A since the user signs a message containing …
> zkSync UX Improvements

- .travis.yml
Supress debug toolbar in travis configuration. Django debug_toolbar isn't required while running tests.
`/grants/categories/` and `/quests/new` return `Internal Server Error` which causes travis checks to fail
debug_toolbar produces this error `FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/gitcoinco/web/assets'`
> supress debug toolbar in .travis.yml

- app/assets/v2/js/cart.js
- app/grants/templates/grants/cart-vue.html
1. `cart.js` now has an `isZkSyncDown` flag. This PR sets it to true. When true the modal looks like the screenshot below when loading. **We must remember to set this back to false when things are ok!**
2. Fixes a bug in https://github.com/gitcoinco/web/pull/7489 where the full fee string was not always displayed at checkout
@owocki
> More zkSync UX updates

- app/app/settings.py
- app/taskapp/celery.py
Adds the ability to route tasks to different queues, so that marketing tasks (like sending emails) dont get in the way of high priority task queues.
#circle-engineering
https://docs.celeryproject.org/en/stable/userguide/routing.html
run with
```
celery worker --app=taskapp --queues=<QUEUE_NAME>
```
> MVP of celery task routing

- app/economy/tx.py
Updates the validator for L1 transactions to identify when a contribution is an automatic donation to Gitcoin. Without this, the `expected_amount` field is incorrect
> Add check to distinguish gitcoin donations when checking amount

- app/assets/v2/js/cart.js
- app/grants/templates/grants/cart-vue.html
Closes https://github.com/gitcoinco/web/issues/7458
> Fix bugs in #7458 that happen when items are removed from cart

- app/retail/templates/bounties/funder.html
- app/retail/templates/shared/what_is_gitcoin.html
Fixes illegible text by closing unclosed anchor tag.
Fix #7577
> Fix Illegible Text on Bouties Page

- app/dashboard/models.py
- app/townsquare/views.py
Rinkeby bounty activity was being displayed in production
This PR ensures only mainnet bounty activities are shown in production.
> (townsquare) fix/show only mainnet bounty activities in prod

- app/grants/management/commands/analytics_clr.py
Just use the Grant's object number of contributors and amount contributed source instead of recalculating it.
None, just ensuring that our analytic final scripts are ready.
Tested to ensure results from script match frontend localhost:8000 using 10/02 production backup data.
> Fixed Analytics Script: Source Issue

- app/assets/v2/js/grants/funding.js
When side cart is open, the UI breaks as demonstrated below. To fix required changing the toggled style from block to inline-flex
https://share.vidyard.com/watch/m4wAqzs3kGBosMGrXmbh63
> Fix Grants UI break on sidecart opened

- app/retail/templates/shared/activity.html
- app/townsquare/templates/townsquare/index.html
On the townsquare page, on medium screen device, there's a ribbon overflow as shown in the Screenshot below
Desktop
Tablet
> Add custom css to prevent ribbon from overflowing in each activity

- app/assets/v2/js/cart.js
- app/grants/templates/grants/zksync-recovery.html
- app/grants/urls.py
- app/grants/views.py
1. Checkout using zkSync + L1 transaction
2. Close the page immediately after confirming your deposit tx
3. Wait for it to be mined, then wait ~1-2 minutes for zkSync to recognize it (1 confirmation on Rinkeby, 10 on mainnet)
4. Run `docker-compose exec -e DJANGO_SETTINGS_MODULE="app.settings" web python3 app/manage.py update_tx_status`. The validator comment for your contributions should now have either `Transaction not found, unknown reason` OR `Found deposit but no transfer`. This depends on the status of your zkSync account. Either one is ok
5. Go to the `/grants/zksync-recovery` page
6. Read the copy, use the button to send the rest of your transactions
7. Page should redirect when complete and show a modal like the screenshot below (the `undefined` text is expected because we aren't …
> Finish zkSync recovery page

- app/app/pipeline.py
- app/app/utils.py
- app/dashboard/models.py
- app/dashboard/tasks.py
- app/grants/views.py
- app/marketing/mails.py
- app/townsquare/views.py
- docs/user_directory.md
decreaseses the login from from 7s to 2.3s by making the sync tasks happen on a delay
self evident
tested locally
> decreaseses the login from from 7s to 2.3s by making the sync_profile tasks happen on a delay

- app/assets/v2/js/cart.js
- app/grants/templates/grants/cart-vue.html
The first time an account uses zkSync, you must submit a signature to register your account. This has a mainnet gas cost, which zkSync used to subsidize. That is no longer the case, so we must account for that now. 
To test, complete a checkout using a new account that has never interacted with zkSync before
> Update zksync to accomodate fee on setSigningKey

- app/assets/v2/js/grants/detail.js
- app/grants/templates/grants/detail/info.html
The grant page used to look a bit clumsy given that the display fonts don't fully reflect what content is being displayed, esp. for grant owner.
I fxed this by making grants display regular p tags by default and then switch them out for input fields when someone clicks to edit.
https://www.loom.com/share/65fd4bc275f940eeae4fdb99f4d8c7d7
> Fix grant view/edit page

- app/assets/v2/js/hackathon-projects.js
- app/assets/v2/js/pages/fulfill_bounty/index.js
- app/dashboard/templates/bounty/fulfill.html
- app/dashboard/views.py
if start work project post failed the user will not able to submit work
Gives the user the ability to create a project on submission if there is not projects.
working hours not decimals 
fix #7695
> Add project submission

- app/grants/models.py
- app/grants/sync/helpers.py
- app/grants/sync/zcash.py
- app/grants/urls.py
- app/grants/views.py
- add check to ensure txn is not older than 5 min
- ensure contirbution mail is sent only after txn is validated
- removed address as a mandatory param on the backend
- set deploy_tx_id default to 0x0
> chore: backend fixes

- app/dashboard/templates/profiles/rank_tooltip.html
Add "more" to the following phrase, in the contributor rank explanation:
If you are funded by a connector in the network, then that Rank is worth {more} than if you are funded by a solitary user.
> Fix missing word in rank_tooltip.html

- app/assets/v2/css/results.css
- app/retail/templates/results.html
- app/retail/utils.py
migrates results page to consolidate the story
tips + bounties => hackathons
ads, ecosystem => other products
convo with mike kriak asking why our stats dont show our current major projects
tested locally
> migrates results page to consolidate the story

- app/retail/templates/shared/activity.html
distortion in html if there's no project name, app/retail/templates/shared/activity.html - line 82
```
title="Go to {{ row.project.name }}">via {{ row.project.name }}</a>
```
will be
```
via
```
instead, display `via project <project id>`
#7773
> fix: properly display project info in activity

- app/assets/v2/js/pages/bounty_details2.js
I'm pretty sure this was unintentionally done 
There is a quote <code> ' </code> at the begin of the text
> extra quote on "you've stopped work" text

- app/dashboard/models.py
factors trust bonus into a parameter on profile
we should port this into the grants/clr code to manage the trust bonus additions there in a DRY way :)
convos with aditya/frank
tested locally
> factors trust bonus into a parameter on profile

- app/assets/v2/js/pages/bounty_details2.js
Updating the QR string based on https://github.com/celo-org/celo-monorepo/pull/5515
This will be available in version 1.4 of Valora
> fix: update QR code for CELO + cUSD

- app/assets/v2/css/grants/detail.css
- app/assets/v2/js/grants/detail.js
- app/grants/templates/grants/detail/info.html
- app/grants/views.py
- scripts/debug/run_perftools.py
Users are not able to edit github repo URL of a grant after creation.
This PR makes the github repo URL editable when "Edit Info" is clicked
#7788 
https://www.loom.com/share/dfb001c16bb44aac92bcf2914c71b672
> feat(grants): allow update of github project url

- app/grants/management/commands/ingest_grant_txns.py
Update contribution ingestion script:
- Only use checksum addresses
- Add comments to clarify input arguments
> Contribution ingest script updates

- app/dashboard/templates/dashboard/hackathon/onboard.html
change hackathon chat link in onboarding from gitcoin chat to discord.
close #7856
> fix(onboard): link hackathon chat to discord

- app/grants/sync/helpers.py
- app/grants/tasks.py
- app/grants/views.py
- app/marketing/mails.py
- app/retail/emails.py
- app/retail/templates/emails/grants/thank_you_for_supporting.html
- app/retail/templates/emails/grants/thank_you_for_supporting.txt
This allows it so that a single email is sent when a user funds a list of grants
Still working on improvements: 
Closes #7755 
No tests currently, still investigating where to add since haven't seen any integrations with SendGrid. 
I also had trouble viewing the email (it won't show it up in my inbox including spam) on my end but I think it has to do with protonmail policy and my SendGrid accounts trust level so would appreciate if someone could test this branch with their creds and post the screenshot here. There definitely is some work to be done for the styling because right now it's reusing existing HTML.
> Send a single email for all grant  items in cart

- app/assets/v2/js/cart.js
Fix for this bug in https://github.com/gitcoinco/web/issues/7947#issuecomment-734890033:
>  total on my cart is wrong. 4x1 DAI = 4 DAI, not 1 DAI https://bits.owocki.com/12uK5KbX
> Fix incorrect donation summary values

- app/grants/templates/grants/cart-vue.html
Some browsers may block Gitcoin from opening other windows. This happened with Firefox, and the solution is for the user to update the browser settings to allow popups from Gitcoin. I added a message explaining this as shown below:
> Add zkSync popup message

- app/dashboard/idena_utils.py
- app/dashboard/models.py
- app/dashboard/templates/profiles/trust-vue.html
- app/grants/templates/grants/cart-vue.html
- app/grants/views.py
* Ensure Idena service on Trust Bonus doesn't break during active validation rounds
* Moves Idena to a new section on the Trust Bonus page for "Active Beta" services
* Alphabetize services on the Trust Bonus tab that have the same Bonus amount
* Remove Idena from the Trust Bonus calculation
* Add Google & POAP to the Trust Bonus calculation
> Trust Bonus Cleanup and Improvments

- app/assets/v2/js/cart.js
Helps resolve https://github.com/gitcoinco/web/issues/7744
Last round there were contributions user's made that did not show up in the database and we weren't sure why. Previously I assumed this meant the POST request silently failed somehow. However, contributions/subscriptions are created from a celery task, so this assumption was wrong. As a result, there's no easy way for us to ensure contributions were created successfully when the POST request succeeds. 
Therefore I think we should always keep the JSON store that backs up a user's cart data. Previously we save this at the beginning, and delete it when the POST request succeeded. By always keeping it, we can, if needed, later write a script that pulls from the JSON store to ingest missing contributions/subscriptions without …
> Always keep JSON store cart backup

- app/assets/v2/js/cart.js
- app/grants/templates/grants/cart-vue.html
Changes:
- Change message from "Not eligible for CLR" to "Cannot match own grant" when a grant you are a team member of is in the cart
- Change copy when clearing cart from "are you sure" to "Are you sure you want to clear your cart?"
@ceresstation @vs77bb Open to suggestions on for the cart match amount copy. Trying to keep it short so it doesn't impact the UI. Also want to make it clear that you can fund your own grant if you want to, but it just won't get matched
> Copy tweaks

- app/grants/templates/grants/shared/active_clr_round.html
- app/grants/templates/grants/shared/sidebar_search.html
standardize clr rounds display to uppercase
https://github.com/gitcoinco/web/issues/7947#issuecomment-737356221
> standardize clr rounds display to uppercase

- app/assets/v2/js/cart-ethereum-zksync.js
- app/assets/v2/js/cart.js
Once we receive transaction hashes, we update the JSON store to include these transaction hashes, and rename it with a timestamp to avoid overwriting it in subsequent checkouts. This is a stopgap until a celery task verifies that the contributions/subscriptions were successfully created and deletes the JSON store
> JSON stores are now backed up with transaction hashes

- app/grants/views.py
This PR improves the performance of the get_grants view by lowering the number of database calls used to get information regarding the grant admin and team_members via prefetching in the `build_grants_by_type` method.
n/a
tested locally
> prefetch profile data, grant type (foreign keys) for grants loading via get_grants

- app/economy/tx.py
Adds two checks to the validator:
1. If transaction failed, and `gasUsed = gasLimit`, set validator comment to indicate transaction ran out of gas
2. If transaction failed, and the gas used is with 1% of the gas limit, set validator comment to indicate that "out of gas" is the likely failure reason. Sample transaction where that happens [here](0xac37f5bc0e9b75dd0f296b8569f72181a066458b9bee1bbed088ec2298fb4344)
cc @owocki
> Update validator to check for out of gas condition

- app/assets/v2/js/cart.js
For all DAI carts we use `25000 * numContributions + 125000` to get the gas limit. This was based on actual transaction gas costs from previous rounds. However, there's been a few out of gas errors, so we've made these more conservative:
- There was all DAI bulk donation [here](https://etherscan.io/tx/0xac37f5bc0e9b75dd0f296b8569f72181a066458b9bee1bbed088ec2298fb4344) that ran out of gas, and failed on the very last transfer.  As a result, I made the heuristic more conservative so the new amount would have been sufficient for that transaction to succeed
- There was a single DAI donation [here](https://etherscan.io/tx/0x41f0a3150d534e843f68026f684f6edde7b72bd73e09d0de8957eef660e74af9) that failed, so we bumped up the single-DAI cart estimate also
- There was also a single ETH checkout that …
> Make gas limit estimates more conservative

- app/grants/templates/grants/cart-vue.html
Only change is that zkSync checkout URL is updated from `https://checkout.zksync.dev` to `https://checkout.zksync.io`. The `*.dev` URL they use for testnets, and wanted to make it more clear that checkout is production code, not dev code
> Bump zksync version

- app/dashboard/tip_views.py
Follow-up for #7830 
Fixes showing this error for non-logged-in user:
> 'AnonymousUser' object has no attribute 'profile'
https://github.com/gitcoinco/web/pull/7830#issuecomment-733157241
This user is not logged in:
> Fix error in /tip for non-logged in user

- app/economy/tx.py
We previously had a check in the validator to make sure the transaction was sent to the bulk checkout contract before verifying it. This check should be removed since it fails for wallets like Argent that use meta-transactions and relayers
> Remove validator check that wrongly fails for certain wallets

- app/grants/templates/grants/cart-vue.html
Resolves checkout typos and content adjustments from @ceresstation
> fix(checkout): typo

- app/assets/v2/js/cart.js
- app/grants/templates/grants/cart-vue.html
Adds a flag to `cart.js` that can be toggled to indicate when zkSync is down. When toggled, the checkout page will look like this:
> Add toggle to hide zksync checkout when zksync is down

- app/assets/v2/js/cart-ethereum-zksync.js
- app/assets/v2/js/cart.js
- app/grants/templates/grants/cart-vue.html
Closes #8114 and #8143
To test:
1. Either add 45 items to your cart, OR change `maxItems` in `cart-ethereum-zksync.js` to a number like 2. The number set there is the max allowed
2. If you change it to 2, add 2 items to your cart and things should look normal. Add a third and the zkSync button should be disabled with a message
The actual zkSync limit is 50, but we use 45 cart items to leave room for automatic tip contributions which are added as separate transfers
> Limit zkSync checkout to 45 items in cart

- app/grants/views.py
- app/perftools/management/commands/create_page_cache.py
When you toggle the dropdown for ZCash grants (or any grant category), the counts on the subcategories are showing total count for that subcategory not just the count of Zcash grant in that subcategory, The solution was to fix the query that inerts the count to Redis and JSONStore.
closes #7795
> Fix Subcategories count

- app/app/context.py
- app/app/settings.py
- app/dashboard/templates/board/ptokens.html
- app/dashboard/templates/profiles/scorecard_ptoken.html
- app/retail/helpers.py
Hides fields and forms for pToken interaction if the user's IP is in NY. Works as follows
- Adds `is_location_blocked_for_ptokens` flag to context
- On the dashboard page, we show the ptokens tab but show a message indicating it's not available for NY users
- On the profile page, the pToken scorecard disables the buy and redeem buttons if you are in NY
To test:
- The debug IP address has a location of Ohio, United States. Therefore everything should be enabled by default
- Open settings.py and make the change below. This will make Ohio the blocked region to simulate being a NY user
```diff
- PTOKEN_BLOCKED_REGION = { 'country_code': 'US', 'region': 'NY' }
+ PTOKEN_BLOCKED_REGION = { 'country_code': 'US', 'region': 'OH' }
```
> Add NY geofence for pTokens

- app/app/settings.py
The final pToken factory contract has been deployed on mainnet and Rinkeby at [0x358bcf43fe7ec2659aD829F3604c72781fc93a9E](https://etherscan.io/address/0x358bcf43fe7ec2659aD829F3604c72781fc93a9E), so this PR updates the pToken factory address
Related PR: https://github.com/raid-guild/gitcoinco-ptoken-contracts/pull/4
> Update pToken factory address

- app/dashboard/templates/board/index.html
- app/dashboard/templates/board/ptokens.html
- app/dashboard/views.py
- app/ptokens/management/commands/setup_ptoken_launch.py
- app/ptokens/views.py
Returns a 403 on the create ptoken endpoint if a user does not have the necessary permissions and hides the model the dashboard page. 
Run the `ptoken` migration to add a user to the group and create the necessary permissions. Then, login and navigate to the dashboard page. If a user has permission should see the modal, else it will not appear
> Create groups for ptokens

- app/grants/admin.py
this pr does two things
- makes the grant team member / admin emails easily accessible in the admin, so one can reach out to them easily
- makes it so the grant admin takes 0.2s to load instead of 5-10s, by adding an optional 'show data' link to the contribution,subscription links in the admin.  this is a nice way of offloading prod performance to only use the CPU/DB cycles when needed, and also makes viewing the admins a little nicer UX wise
self
tested locally
> a few grant admin fixes

- app/assets/v2/js/pages/hackathon_new_bounty.js
- app/assets/v2/js/pages/new_bounty.js
- app/dashboard/templates/bounty/new_bounty.html
- app/dashboard/templates/dashboard/hackathon/new_bounty.html
Allow manual filling of binance address as a fallback to autofilling when user doesn't have Binance Wallet Extension installed.
#8249
> manual fallback to binance address autofill for new bounty

- app/dashboard/templates/board/ptokens.html
Fix: A token creator was able to click 'Complete' on a request, but this should not be possible. Only requestors should mark it as complete
This fix is copied from https://github.com/gitcoinco/web/pull/7896, but that PR is pretty old so it was easier to replace that as opposed to rebasing
> pToken fix for who can Complete a request

- requirements/base.txt
The Github auth process we currently use has been deprecated and would be removed completely in May 2021. So as to prevent our system from any any downtime or user's being unable to sign in, we're updating the social auth app to the latest version which still supports github authentication and doesn't break our current integration.
closes #8072
> Fix Github Authentication Deprecation

- app/grants/templates/grants/components/card.html
Make verified twitter address tooltip work on grant cards
Fixes #7387
No Python code was changed/added.  Just updated a tooltip component to work correctly.
> Make verified twitter tooltip work on grants card

- app/assets/v2/js/grants/_detail-component.js
- app/grants/views.py
https://gitcoin.co/grants/1924/gitcoin-grants-round-9-dev-fund
https://gitcoin.co/grants/1927/gitcoin-grants-official-matching-pool-fund-round-
Users are able to modify a Grants twitter handle after the verification process. 
Replicated here: https://gitcoin.co/grants/1930/test-2
This pull will clear the verification if the twitter_handle_1 field is modified.
clsoes https://github.com/gitcoinco/web/issues/8303
Untested - I don't have my local instance set-up with a twitter_access_token yet, I can't see anything going wrong, but let me know if you want me to test it 👍
> Drops a Grants Twitter verification if the user modifies the twitter_handle_1 field

- app/grants/templates/grants/detail/template-grant-details.html
This will fix the .grant-data elements sizing issue on Firefox, without a width it was defaulting to auto which was filling the whole container.
https://github.com/gitcoinco/web/issues/8310
Before:
After:
> Fix overflowing grant-data element

- app/grants/urls.py
- app/marketing/views.py
user has been unable to payout bounty https://gitcoin.co/issue/status-im/status-react/11488/100024619
this PR prevents the update of email subscription email if user profile email already has an entry.
#8328 
refer to ticket
> handle email subscription duplicate entry

- app/assets/v2/js/pages/bounty_details2.js
- app/assets/v2/js/vue-filters.js
- app/dashboard/models.py
- app/dashboard/templates/bounty/details2.html
- app/dashboard/views.py
Currently, when the bounty owner tries to stop a worker who has been approved to work on a bounty, it doesn't happen and he simply gets an error. This happens because the endpoint for removing an interest from a bounty (stop worker) only does a worker check and not bounty owner check. This PR allows a worker to remove himself from a bounty and a bounty owner to stop a worker as well. It doesn't introduce a new functionality, only fixes a functionality that is broken.
closes #8331
https://www.loom.com/share/8f269920f1f94ad09c980da5f6f05fed
> Allow bounty onwer to stop worker.

- app/app/settings.py
- requirements/base.txt
Adds CSP header (frame-ancestors 'self') to protect against clickjacking.
Fixes: https://github.com/gitcoinco/web/issues/8324
Tested locally:
> Adds CSP header (frame-ancestors 'self') to django settings (#8324)

- app/app/settings.py
- requirements/base.txt
Updates the sentry-sdk version and introduces traces_sample_rate (set to sample 35% of requests).
Refers: https://github.com/gitcoinco/web/issues/8309
@octavioamu provided figures on reqs/min to get us to the 0.35 figure. If the load changes, we might need to readdress how much sampling we do.
> Updates sentry-sdk (0.7.7->0.19.5) and introduces traces_sample_rate

- app/assets/landingpage/app.css
- app/retail/templates/home/index2020.html
landing page fixes
#8277 
https://www.loom.com/share/c3462421f6c547ebb5e61908272466ee
> fix(landing): caps + btn alignment

- app/dashboard/management/commands/sync_pending_fulfillments.py
QR bounties have an expiry period of 20 minutes from created time. This is wrong as it should be from modified time.
slack bug report
> fix expiry duration for qr bounties

- app/assets/landingpage/app.css
- app/assets/landingpage/logo.scss
- app/assets/landingpage/section_footerconsensys.scss
- app/assets/landingpage/section_footersocial.scss
- app/assets/landingpage/section_grid.scss
- app/assets/landingpage/section_intro.scss
- app/assets/landingpage/section_newsletter.scss
- app/assets/landingpage/section_twitter.scss
- app/assets/landingpage/typography.scss
- app/retail/templates/home/index2020.html
- Fixes responsiveness for larger displays
- Fixes alignment on the newsletter subscribe section
- Replaces Ethereum with ETH when talking about the token (in the intro)
Partial fix for: #8382
Before - @25% zoom
After - @25% zoom
Before - subscribe alignment:
After - subscribe alignment:
> Improves responsiveness of landing page for larger displays

- app/grants/views.py
fixes an issue where grants API output was unperformant, and also where zksync addresses were not showing up in the dataset 
https://gitcoincore.slack.com/archives/CBDTKB59A/p1611241494001400
texted locally
http://localhost:8000/grants/v1/api/export_addresses/round7.json
http://localhost:8000/grants/v1/api/export_addresses/all.json
http://localhost:8000/grants/v1/api/export_addresses/grant238.json
http://localhost:8000/grants/v1/api/export_addresses/grant238_round7.json
> grants api fixes - shows addresses from zksync AND from L1

- app/app/settings.py
- app/app/urls.py
- app/assets/v2/scss/test1.scss
- app/assets/v2/scss/test2.scss
- app/retail/templates/home/sass_experiment.html
- app/retail/views.py
- requirements/base.txt
- scripts/deploy.bash
- Adds a simple page to include both types of compression in order to test the deploy script prior to merging master into stable
Refers: #8368
Tested locally (in dev environment)
> Adds test case to ensure safe deploy of compressed assets (js/scss)

- app/app/settings.py
- app/app/static_storage.py
- Saves a local copy of .scss and .js assets (with and without hash) during collectstatic so that compressor can instrument cache over STATIC_ROOT
Refers: #8368
Tested in dev with production ENV's
> Adds local static cache for .scss and .js files

- app/app/settings.py
- app/assets/v2/scss/gitcoin.scss
- app/assets/v2/scss/town_square.scss
- app/retail/templates/emails/shared_template_head.html
- app/retail/templates/shared/head.html
This will fix the email's shared template head: 
1. We changed the Compress tags from `inline` to `file` so that we could get the `compress` command to complete, this reverses that
2. Replaces `url('...')` with `url(static('...'))` so that static paths are more clearly defined in the scss sheets
3. There are also several `OfflineGenerationError` errors flowing into sentry that this will fix (we should merge asap because emails will be failing until this is deployed)
3. Depends on: https://github.com/gdixon/django-compressor/commit/c98be36a49471efb004f6aced50c6d9c3916b002
Commit: 845a5d43708bc8d1a7a658d8435d0a30ca402b6d
Tested locally with development and production .envs
> hotfix: Fixes scss imported into emails/shared_template_head (will also fix the build and system emails sent from gitcoin)

- app/dashboard/models.py
this pr properly handles grant_obj field in `to_json` method for a hackathon project
which prevent lots of users from visiting binance sponsor dashboard.
hackathon sponsor dashboard couldn't load because `/api/v1/hackathon/{hackathon}/prizes` was returning a 500 (`Object of type Grant is not JSON serializable`) caused by when `grant_obj` is linked for a hackathon project that was converted to a grant
https://www.loom.com/share/fbaea19094fe4b779ce371377dd97281
https://www.loom.com/share/c289762393314dc5b92632d813691046
> hotfix: grant_obj serialization in hackathon project

- app/assets/v2/js/board.js
- app/dashboard/views.py
- app/ptokens/views.py
This updates the Vue context with the correct variable to toggle the create pToken modal as well as fixes the permissions check as the string used was incorrect.
Give a user staff role to view the pToken tab, then run the management command: `docker-compose exec web python3 app/manage.py setup_ptoken_launch`
Navigate to the users menu in the Django admin and add the user to the newly create pToken group along with the `add_pToken_auth` permission.
> Fix pToken dashboard permissions

- app/assets/v2/js/grants/funding.js
- app/retail/templates/shared/grant_thanks_modal.html
Implements the redesigned "Thank You" modal after grants checkout, with one major limitation:
Currently the image on the modal is an old-school Gitcoin robot, left as a placeholder. The updated design calls for a collections-like image with four quandrants for grant images, plus the user's photo in the middle. However, since the user's cart is not yet a collection at this screen, I don't believe the endpoint for generating these images is set up for this use case. I was wondering if the GPG folks would have some thoughts on how to address this. Alternatively, we could use an updated static image for a version 1.
> Implement post-checkout Grants Modal Redesign and Refactor

- app/app/settings.py
Adds the HEAD commit hash to the manifest filename so that for each deployment we generate a new manifest.*.json file, allowing the old version to carry on serving files whilst the deployment finishes (avoiding OfflineGenerationError's).
Depends on updates to -> https://github.com/gdixon/django-compressor/commit/97cf285af96110da88810f5e19b3809ef748a322
Refers: #8368
Tested locally (with production .env variables)
> Adds commit hash to the 'manifest.json' making manifest generation deploy specific

- app/assets/v2/js/cart.js
- app/assets/v2/scss/grants/cart.scss
- app/grants/templates/grants/cart-vue.html
- app/grants/templates/grants/cart/eth.html
- This PR completes the work carried out by @mds1 (thank you!! :D)
- Cherry-picks Matts commits to a new branch on master
- Builds out the mobile view
- Fixes alignments, breakpoints and font-weight's
- Alters the behaviour of the comment open/close (can now be closed, but not if a message is present)
- Fixes the Grant name to a max of 2 lines (truncating the remaining text with an ellipsis)
Refers: #8445
Refers: #8451
https://www.loom.com/share/e7474c2baa754388934319062ed100ae
> Cart mobile setup

- app/grants/templates/grants/detail/_index.html
adds a dynamic loading indicator to grants loading page, so user gets a sense that a grant is loading
> adds loading indicator to grants

- app/grants/models.py
- app/retail/emails.py
- app/retail/templates/emails/grants/new_supporter.html
- app/retail/templates/emails/grants/new_supporter.txt
show blockexplorer url of transaction in email, retires old "x times" language in emails
common sense, self
tested locally https://share.getcloudapp.com/2NuED8wR
> show blockexplorer url of transaction in email, retires old "x times" language in emails

- app/dashboard/models.py
https://gitcoin.co/nance2uiuc
that user paid out a $60k bounty, to 20 diff users.  and instead of giving credit to the user for one $60k bounty the system did it 20 times.
this PR fixes that by taking the bounty fulfillment amount + creating the earning from that.
but this PR is blocked from being truly useful by the fact that bountyfulfillment.payout_amount is null for most objects in production ( https://github.com/gitcoinco/web/issues/8486 )
see above
tested locally
> record proper usd value of a bounty fulfillment

- app/assets/v2/js/grants/ingest-missing-contributions.js
- app/grants/templates/grants/ingest-contributions.html
- app/grants/views.py
- Frontend verifies that connected wallet address matches form inputs
- Frontend asks for a signature and passes that data to backend
- Backend verifies address recovered from signature matches user address
I *think* this should work, but before merging needs more testing first against a mainnet token list. The reason is because web3py does not let you recover addresses from PoA networks like Rinkeby and it throws with:
`web3.exceptions.ValidationError: The field extraData is 97 bytes, but should be 32. It is quite likely that you are connected to a POA chain. Refer http://web3py.readthedocs.io/en/stable/middleware.html#geth-style-proof-of-authority for more details. The full extraData is: HexBytes('0xd883010918846765746888676f312e31352e35856c696e757800000000000000c4f6ccfbbfd37487321a523ac …
> Start improving missing contribution page

- app/retail/templates/emails/shared_template_head.html
This PR reverts .scss changes made in commit 4763718c325b31390f4d4e21d770597c7e42120b.
We made these changes because the css being used in `shared_template_head.html` is duplicated from the core app's css - in order to DRY up the codebase, we wanted to use a single source of truth, unfortunately django-compressor is failing to inline the .scss block in production. 
We will readdress this in the future, the path forward will likely be:
- assess what css is being used by the emails
- refactor and bring just that css into a single new css document and inline that instead of the 3 .css documents we are currently inlining
- rename that new document `email_head.css` so that there is no ambiguity as to what the file is. 
Fixes: 4763718c325b31390f4d4e21d770597c7e42120b
Tested locally
> Reverts inline .scss block to inline .css block

- app/dashboard/models.py
- app/dashboard/tests/test_users_list.py
- app/dashboard/tokens.py
- app/marketing/tests/management/commands/test_assemble_leaderboards.py
This will fix test_user_list.py and test_assemble_leaderboards.py (Bounty/BountyFulfillment details) allowing tests to complete and adds the `network` as a param to `token_by_name()` so that the correct token is chosen.
Refers: #8488 
Tested locally
> Fixes tests and adds network as a param to token_by_name()

- app/passport/views.py
I have found [defunct_hash_message](https://ethaccount.readthedocs.io/en/stable/eth_account.html#eth_account.messages.defunct_hash_message) from web3py that should use to hash a msg before signHash method.
I did not change any requirement version as discussed in #8571.
https://github.com/gitcoinco/web/issues/8571
Check this tx from my contract:
https://rinkeby.etherscan.io/tx/0xce4c7763b9d5aae69ccd9f0038fd6bf561c8021a9fedc1babb68425ddcd3158a
and here is my Gitcoin Passport
https://rinkeby.etherscan.io/token/0x7b02739251d06dc0669465db00c7986badae50b0?a=0x18ae9fc06bed0637b1d46063d6b7af1a4f97b02c
> Fixed This Web3py Signed Message That Will Not Validate In Solidity

- app/grants/templates/grants/ingest-contributions.html
Verbiage changes to make this more clear.
> Making this form more clear

- app/assets/v2/js/activity.js
- app/assets/v2/scss/activity_stream.scss
- app/assets/v2/scss/base.scss
- app/retail/templates/shared/activity-vue.html
- app/retail/templates/shared/activity.html
This PR fixes the activity stream's content cards (New bounty/New Kudos etc...), clicking a card will open the respective page in a new tab.
Fixes: https://github.com/gitcoinco/web/issues/8483#issuecomment-793939602
Tested locally
> Fixes content cards so that they link to respective pages

- app/assets/v2/js/grants/contribution-trust-bonus.js
- app/assets/v2/js/grants/grant-thanks-modal.js
- app/retail/templates/shared/contribution_trust_bonus.html
- app/retail/templates/shared/grant_thanks_modal.html
This PR fixes the Twitter Share button in the post-checkout thank you modal so that it opens in a new tab, and ensures the trust-bonus modal will always open when the thank you modal closes.
Fixes: https://github.com/gitcoinco/web/issues/8483#issuecomment-796760402
Tested locally
> Opens twitter share in a new tab and ensures trust-bonus always opens

- app/assets/v2/js/pages/new_bounty.js
- app/dashboard/templates/quickstart.html
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1615596513109800
> prevent quickstart from redirecting to /new page

- app/assets/v2/js/cart.js
- app/assets/v2/js/grants/cart/polkadot_extension.js
- app/grants/templates/grants/cart-vue.html
This pr move the chains js dependencies to an object and add a computed prop to with the tenants presents on the cart. For each tenant present on the cartData (grants)  this will inject the proper chain js lib needed avoiding load unused big js libs if not going to be used.
For future chains additions we will need to just add the tenant name and the object with all the js endpoints (external or internal) following the same pattern we do for the tabs.
There is a special rule for kuzama as this one have diff chain id / name but is actually part of polkadot and use the same files.
With this approach cart seems to be loading normally again and even if you pick a polkadot grant then the load time doesn't fill tedious as the other js are not loaded (unless you pick one grant of each of our …
> only load chains lib scripts when needed

- app/assets/v2/scss/about.scss
- app/retail/views.py
fixes stretching of team images in about page
closes #8556 
same locally as in issue
> fix(about): team img stretch

- app/assets/v2/js/grants/_detail-component.js
- app/grants/templates/grants/detail/template-grant-details.html
- app/grants/views.py
This is duplicate of https://github.com/gitcoinco/web/pulls and uses `is_clr_elgible` instead of adding a new field cause we had a few support requests asking us to remove their grant from CLR
> allow admin to opt out of CLR

- app/assets/v2/js/pages/bounty_details2.js
- app/dashboard/sync/rsk.py
- app/grants/sync/rsk.py
- RIF: 0x2aCc95758f8b5F583470bA265Eb685a8f45fC9D5
- SOV: 0xefc78fc7d48b64958315949279ba181c2114abbd
ChainID: 30
Decimals: 18
Converstion Rates : available on coingecko 
note: Tokens are added in live but have not been approved
- need tokens on mainnet to test but this has no codechange , so it should work without any issues cause we already have DOC / RDOC which relies on this piece of code
> add RSK tokens

- app/app/urls.py
- app/assets/v2/js/lib/collage.js
- app/assets/v2/js/search.js
- app/grants/templates/grants/collage.html
- app/grants/urls.py
- app/grants/views.py
- app/marketing/tasks.py
create a collage from the top grants in matching pool
marketing idea i had
tested locally
> create a collage from the top grants in matching pool

- app/grants/management/commands/update_contributor_address.py
To run the script, use network of `rinkeby` or `mainnet` in the command below.
```
docker-compose exec -e DJANGO_SETTINGS_MODULE="app.settings" web python3 app/manage.py update_contributor_address "rinkeby" 
```
This script will search for all subscriptions that have a `contributor_address` of `N/A`, then find the address of the user who sent the transaction and set that as the `contributor_address`. This requires one network request per subscription, so it may take some time to run if there's a lot of subscriptions.
Note: This approach does not guarantee the correct contributor address. Because we are using the sender of the transaction as the contributor, we get the wrong address for users with wallet's that use a relayer or meta-transactions, such as Argent. In those cases, the relayer …
> Add management command to update contributor addresses of N/A

- app/assets/v2/js/grants/ingest-missing-contributions.js
When testing on Rinkeby, the transaction hashes and address I used for testing were my own. As a result, this bug slipped in, and our new "let staff bypass" feature fails because the frontend will currently error, but this PR fixes that
> Fix: bypass address verification checks if user is staff

- app/assets/v2/js/pages/bounty_details2.js
- app/dashboard/templates/bounty/details2.html
Show PR link to 
- admin
- funder
- person who made the submission
By @connoroday 
>Problem: Some bounties (especially for bug bounties) should not have submissions be public
Request: “Private” submissions for bug bounties or similar
> show submission only to needed folks

- app/dashboard/templates/dashboard/sponsors.html
- app/dashboard/views.py
- app/grants/urls.py
- app/grants/views.py
- rename participants -> registrants
- fix count on dashboard (which was previously turning up as 0)
- changes makes one less query
Issue: 
Problem: Sponsor dashboard still says 0 participants, should say the registrants #
Request: Sponsor dashboard should say number of participants, bugged right now
^ reported by @connoroday
> fix buggy number on participants

- app/dashboard/templates/bounty/details2.html
From connor
>Problem: “Override status” button no longer works for admins after moving from standard bounties, admins have to “view in admin” and then type in “done” in override status field to close
Request: Fix “Override status” button on bounty frontend
The fix instead :
- to expose close bounty button to admin
- remove override status  (this is done cause we don't want bounty jumping the states)
> remove override and allow close button clickable by admin

- app/assets/v2/js/pages/fulfill_bounty/index.js
- app/assets/v2/js/pages/fulfill_bounty/token.js
- app/dashboard/templates/bounty/fulfill.html
- update placeholder to let folks know to enter chain address
- added client side validation for chains when user submits work
> add client side validation

- app/app/db.py
- app/dashboard/admin.py
- app/grants/management/commands/update_contributor_address.py
- app/grants/tasks.py
- app/grants/urls.py
- app/grants/views.py
- app/retail/templates/admin/change_form.html
@connoroday 
> Problem: When extending hackathon end date, bounties expiration doesn’t change
Request: Bounty deadlines get updated when hackathon is extended
- Head over to a hackathon event in admin
- Update the end date and click on SAVE
- Once the hackathon end date has been updated, scroll to the bottom and hit the `Update Related Bounties Expiry Date` button and all the bounties for the hackathon event should have the same expiry date. 
Check the video for more info
> update bounty expiry date to hackthon end date

- app/retail/templates/shared/head.html
Reference to non-existent assets, `/v2/scss/forms/button.scss`, deleted in PR https://github.com/gitcoinco/web/pull/8622, is causing django-compressor to throw `UncompressableFileError`.
Resolved by deleting the line.
> fix: UncompressableFileError due to non-existent file

- app/dashboard/views.py
This PR allows width and height to be set against an image in the hackathon onboarding description editor - these tags were not part of the whitelist and were being "cleaned" on save. 
Refers: https://gitcoincore.slack.com/archives/CAXQ7PT60/p1617818978085500
Tested locally
> Allows width/height to be set against an img in the hackathon onboarding description editor

- app/marketing/management/commands/assemble_leaderboards.py
Refactors the leaderboard job to be performant by leveraging the database to compute the data (instead of doing it in memory).  
for now, this refactor supports earners, payers, orgs, and token_names, in the future this could be extended to support
- cities
- countries
- continents
- kudos
- programming languages
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1617764681082700
tested locally
> Refactors the leaderboard job to be performant

- app/assets/v2/js/pages/bounty_details2.js
- app/dashboard/templates/bounty/details2.html
This PR corrects the following problem:
If there is no wallet connected when a bounty owner goes to payout a submission, then the active modal is closed and the wallet selection modal is opened, when the wallet selection is closed the original modal should be reopened, instead a different modal is being opened - and this is causing the wrong submission to be paid out for the bounty.
Fixes: https://gitcoincore.slack.com/archives/CAXQ7PT60/p1617915148092600?thread_ts=1617910888.089500&cid=CAXQ7PT60
https://www.loom.com/share/021f94b4991149fdb84c2967b3f22ce0
> Fixes bounty payout modal so that the correct instance reopens after web3 onConnect

- app/retail/views.py
- Issue: 
- https://sentry.io/share/issue/323917544b4d4d2ea38a6464b774c506/
- https://sentry.io/share/issue/60236e3fcaca4d74b78b5380114ba938/
- report: 4.1k + 6.4k
- flow affected: /activity
> bug: invalid literal for int() with base 10: 'test ORDER BY 1#'

- app/git/utils.py
- Issue: https://sentry.io/share/issue/efca7d7914d046458d75eb4f4e3b7edc/
- report: 280
- flow affected: bounty detail page
> bug: bounty flow - invalid literal for int() for base 10

- app/grants/views.py
https://sentry.io/organizations/gitcoin/issues/2114815291/?project=1398424&referrer=slack
Claim button is being used for non-eth grants which causes the failure !
Current Report: 128
> fix: https://sentry.io/organizations/gitcoin/issues/2114815291/

- app/grants/models.py
Ran into this issue on my local where without any historic Grant CLR and I tried running it for the first time,
it errors out cause round_nums ends up being an empty list with `None` AKA `round_nums = [None]`
This just adds an extra safety to check
> bugfix: add error checking for new users when round_num is [None]

- app/grants/admin.py
- app/grants/clr.py
- app/marketing/management/commands/assemble_leaderboards.py
- app/retail/templates/admin/change_form.html
Introduce 2 new actions on Grant CLR admin
- `Reset CLR calculations for this round` -> set the `GrantCLRCalculations` for that round to `latest` = `False` 
- `Reset all CLR calculations for all rounds` -> -> set ALL `GrantCLRCalulations` to `latest` = `False`  
-  Any time the estimate_clr runs for a round -> the earlier records for that CLR`GrantCLRCalculations`  has the `latest` column set to `False` and the once all the CLR are calculated , the effective CLR for each grant is nothing but the same of the latest `GrantCLRCalculations` with `latest=True` and the that grant.pk
- When the round runs
- the older ones are invalidated (aka latest is set to False) 
- new records are created
- When a round ends, the records with latest=True are created. Let's call these `Record X`.
- When a new …
> feat: have ability to set latest flag to 0 in GrantCLRCalculation

- app/assets/v2/scss/quests.scss
This PR will prevent the footer from displaying on Quests Battle (regression).
Refers: #8500
> Prevents the footer from displaying on Quests Battle

- app/dashboard/router.py
This PR:
- Closes a sentry issue (reported events: **5.7k**)
- Ensures the bounty slim api's `limit` get param is always an int
Fixes: https://sentry.io/share/issue/ee152a3b616b401cb8b948297c5ded2d/
Tested locally
> bugfix: bounty slim - invalid literal for int() with base 10

- app/marketing/mails.py
limit bounties in daily digest to 24 hours ago;
nothing new, just a piece that was left out in fallback from tag matching
> fix(email): add timeago to bounties tag matching fallback

- .babelrc
- .gitignore
- app/app/urls.py
- app/assets/v2/js/bundle_experiment.js
- app/dashboard/management/commands/bundle.py
- app/dashboard/templatetags/bundle.py
- app/retail/templates/home/bundle_experiment.html
- app/retail/views.py
- package.json
- requirements/base.txt
- scripts/deploy.bash
- webpack.config.js
- yarn.lock
This PR will expose a test run for `{% bundle ... %}` template tags:
Before pulling to prod
- install yarn on the cron box:
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
apt-get update
apt-get install -y yarn
yarn global add n
n stable
yarn install
```
- and the new requirements:
```
pip3 install -r requirements/prod.txt
```
Refers: #8860
Tested locally
> Adds POC for bundle template tags

- app/retail/views.py
redirect slack to discord, since community slack is now defunct
ref https://gitcoincore.slack.com/archives/CAWFUGVHQ/p1621008722081500
> redirect community slack to discord

- app/quadraticlands/helpers.py
Users with 0 tokens for the drop are still able to get to the claims page and attempt claim for 0 tokens.  This fix will remove the unnecessary error log from the backend and is the first part of this fix only.  @scco and are working on a client side fix that will make this more clear to the user as well. We aim to have that ready soon. This can be merged now (to stop the flood of error logs) or when we complete the UI fix. 
https://github.com/gitcoinco/web/issues/8948
> removing error log for claim breakdown not found

- app/assets/v2/js/quadraticlands/mission/use/vote.js
- app/quadraticlands/helpers.py
In QL delegate mode OFF workflow there is an issue with signing the vote message from some (mostly hardware) wallets. This PR will fix that issue by moving the user ahead even in the event that the signed message fails. 
No bug filed yet for this that I'm aware of.
> Zac signed message fix

- app/app/utils.py
Sentry link: [URL](https://sentry.io/organizations/gitcoin/issues/1957083533/?project=1398424&query=is%3Aunresolved&sort=freq&statsPeriod=14d)
Report: 13k 
This seems to happen when user doesn't exist in github (aka user changed username )
and we kick of a retry to try and find the info 
Eg: https://api.github.com/users/alexmedkex/orgs?per_page=100 (see sentry log )
> fix: https://sentry.io/organizations/gitcoin/issues/1957083533/

- app/assets/v2/js/quadraticlands/components/nav.js
This PR fixes `selectedAccount is not defined` - (_EVENTS_: **11k** - _USERS_: **258**)
Refers: https://sentry.io/organizations/gitcoin/issues/2418268702/?project=1398424
Tested locally
> Fixes selectedAccount is not defined

- app/assets/v2/scss/notifications.scss
- app/assets/v2/scss/search.scss
This PR prevents the notification box and search box from having a double scrollbar at any viewport size, and sets `height: auto;` for mobile.
Fixes: #8982
Tested locally
> fix: Ensures notification box and search box remain scrollable for short viewports

- app/dashboard/templates/shared/menu.html
changes company in the header to organization
https://gitcoincore.slack.com/archives/CCZFZDT9V/p1622645614051600?thread_ts=1622224102.049600&cid=CCZFZDT9V
> changes company in the header to organization

- app/dashboard/utils.py
- app/townsquare/views.py
This PR corrects the logic for POAP verifications. 
The old logic made the assumption that the token with the lowest ID was transferred earliest, according to [this](https://gitcoincore.slack.com/archives/CAXQ7PT60/p1622708407113000) report - the earliest transfer might not always have the lowest ID. This could be because the tokens were minted earlier and then transferred to the user, or it could be down to the order that the tokens were transferred from xDai to mainnet. Either way, this PR alters the logic so that:
- each token's most recent transfer is recorded into a list
- that list is sorted
- the earliest transfer is selected from all tokens held
fixes: #8979
Tested locally against the address provided in slack
> fix: POAP - Ensures that all tokens are considered and not just the token with the lowest ID

- app/marketing/views.py
- app/retail/emails.py
This PR sets DNC in to mautic for account deletions and adds an option to the account settings for the user to toggle DNC state.
Fixes: #8346
Tested locally
> Adds mautic-dnc to settings and for account deletion

- app/assets/v2/js/ql-banner.js
- app/assets/v2/scss/ql-banner.scss
This PR ensures that after closing the ql-banner, the `top` position on the sticky-nav is `0px`
fixes: #9006
Tested locally
> fix: Fixes position of sticky-nav after closing ql-banner

- app/assets/v2/js/vue-components.js
Chat button is removed on hackathon projects
closes https://github.com/gitcoinco/web/issues/9021
> bug: remove reference to gitcoin chat on hack project

- app/assets/v2/js/cart.js
- app/grants/templates/grants/cart/eth.html
- inc zksync limit to 90 (max is now 100 )
- Re-purposes the cartMaxItems to allow users to use standard checkout for any number of grants 
- Updates the text when cart exceeds 40 telling the user 
- the reason zksync has been disabled
- they should reduce how many items from the cart to enable it 
- they can use standard checkout instead
Closes https://github.com/gitcoinco/web/issues/8916
> chore : remove cap limit on std checkout

- app/retail/emails.py
This PR replaces `modified_on` with `created_on` so that only new contributions will be included in the rollup
Fixes: #9104
Untested (but is logically sound)
> fix: Use created_on date rather than modified_on to source recent contributions

- app/economy/management/commands/get_prices.py
This ensures get_prices doesn't crash when user adds a token and doesn't set the conversion_rate_id param (which is mandatory) 
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1624028091237400
> chore: ensure get_prices doesn't break with missing data

- app/kudos/admin.py
- app/kudos/tasks.py
- app/retail/templates/admin/change_form.html
Adds some sanity to the kudos minter by decoupling the 'sync' actions from the mint action.  The reason its worth doing this is that the site 504s sometimes bc syncing takes so long.  This allows us to mint them 1 by 1 then alllows a sync job thereafter.
my own empirical experience.
tested locally
> Adds some sanity to the kudos minter

- app/kudos/templates/kudos_marketplace.html
fixes: broken kudos page
GITC-81
> GITC-81: broken kudos 404 page

- app/assets/cookielaw/js/cl.js
- app/kudos/templates/transaction/base.html
- app/quadraticlands/templates/quadraticlands/components/nav.html
- app/retail/templates/bounties/contributor.html
- app/retail/templates/bounties/contributor/explorer.html
- app/retail/templates/bounties/funder.html
- app/retail/templates/bounties/funder/howworks.html
- app/retail/templates/cookielaw/banner.html
This PR:
- moves the dismissal event binding to `cl.js` to avoid Cookielaw being `undefined`
- tidies up bad/duplicate inclusions
fixes: GITC-82
Tested locally
> GITC-82: fixes "ReferenceError: Cookielaw is not defined"

- app/dashboard/views.py
https://sentry.io/organizations/gitcoin/issues/1098741849/?project=1398424&query=is%3Aunresolved
Ensures POST call fails gracefully when values are not valid
Tested locally
https://gitcoin.atlassian.net/browse/GITC-84
> GTC-84: could not convert string to float: '1\xa0000'

- app/assets/v2/js/pages/project-page.js
- app/assets/v2/js/vue-components.js
- app/dashboard/models.py
- app/dashboard/router.py
- app/dashboard/templates/bounty/details.html
- app/dashboard/templates/bounty/details2.html
- app/dashboard/templates/dashboard/hackathon/project_page.html
- app/dashboard/templates/dashboard/hackathon/projects.html
- app/dashboard/templates/profiles/tab_hackathons.html
- app/dashboard/templates/project/detail/info.html
- app/dashboard/templatetags/slug.py
- app/dashboard/views.py
- app/grants/tasks.py
- app/kudos/models.py
- app/quests/models.py
- app/retail/templates/results.html
- app/retail/templates/shared/activity.html
- app/townsquare/models.py
- requirements/base.txt
This PR fixes the project_page by ensuring any `project.name` containing unicode is decoded prior to slugifying (this same fix is applied to every use of slugify across the codebase), also DRYs up the process by declaring URLs in the model avoiding the need to recreate them on the frontend and corrects some minor styling issues.
* Note: this PR adds `unidecode` as a dependency
Fixes: GITC-108
Tested locally
> GITC-108: Fixes 500 errors when bounty.name contains unicode chars

- app/assets/v2/js/navbar.js
- app/assets/v2/js/pages/profile-trust.js
- app/dashboard/views.py
- app/tdi/views.py
some butthead is going in and ddosing our twilio account with twilio verify requests, which cost like 1c each... and in aggregate costing us hundreds of $$$$ per round.  
this PR adds a rate limit to the twilio endpoint call so that it cant be done anymore.
ideally we'd extend this even further and block ppl who abuse the system as such.. but i dont have cycles to code that today
https://app.datadoghq.com/logs?query=request_user_sms&index=
https://www.twilio.com/console/verify/services
did not test, but its a simple addition of a rate limit so hope its ok
> hotfix - twilio ddos fix

- app/kudos/templates/transaction/receive_bulk.html
https://gitcoin.atlassian.net/browse/GITC-123
> GITC-123: fix js error calling the function before defined

- app/dashboard/templates/bounty/fulfill.html
Let users know ETH addresses are also accepted while submitting work
> GITC-87: update placeholder nervos bounty fulfill

- app/perftools/management/commands/create_page_cache.py
This PR adds a defensive check to make sure the profile is set before summing contributions in create_top_grant_spenders_cache.
Fixes: GITC-129
> GITC-129: Ignores any contributions which do not have a profile associated from create_top_grant_spenders_cache

- app/townsquare/views.py
Looking at the [datadog trace](https://app.datadoghq.com/apm/traces?query=env%3Aprod%20service%3Adjango%20resource_name%3A%2Atownsquare%2A%20%40duration%3A%3E%3D12.5s&index=apm-search&spanID=1926285002054291218&streamTraces=true&traceID=15069572059855755779&start=1625234553487&end=1625235453487&paused=false) its clear to me that the lookup for activity counts (to show on the badges) is the slow part in a production like env
this pr removes those, under the judgement call that the badges arent worth a 30s load time (and the subsequent load on the db that comes from that).
in the future, refactoring on the activity table (maybe just a db index, but it probably is getting big enough it doesnt belong in postgres too) may be necessary if we want to query this table deeply in the future …
> Straw man fix for gitcoin.co/townsquare?dressing=1 being hella flow

- app/grants/router.py
- app/grants/serializers.py
Introduces a new endpoint for `/clr_round_metadata` to get information on rounds 
**URL:**  `api/v0.1/grants/get_clr_round_metadata`
**Parameters:**
_Note: All parameters are optional_
- `id=<number>` -> returns specific CLR round 
- `active=true` -> returns only active rounds
- `from_timestamp` -> returns CLR rounds which started after given date. Format: `YYYY-MM-DD`
- `to_timestamp` -> returns CLR rounds which ended before given date. Format: `YYYY-MM-DD`
- https://github.com/gitcoinco/web/issues/9255
- https://github.com/gitcoinco/web/issues/9256
- GITC-182
- GITC-190
> GITC-182 chore: add endpoint for GrantCLR metadata

- app/quests/helpers.py
This PR optimises `generate_leaderboard` to use a `GROUP BY... SUM` query to find the quest leaders up to the `max_entries`
Fixes: GITC-192
Tested with production data
> GITC-192: Optimises generate_leaderboard to use a GROUP BY... SUM query

- app/marketing/tasks.py
- app/taskapp/celery.py
This PR will double the time given to a celery task before it will fail (if we still get errors we will need to profile the longest running tasks on production/staging and set these values accordingly)
Fixes: GITC-165
Tested configuration locally
> GITC-165: Increases celery task_time_limit to account for longer running tasks

- app/dataviz/d3_views.py
- app/dataviz/templates/dataviz/mesh.html
https://gitcoin.co/_administration/mesh wasnt loading the most recent grants rounds data anymore, because its just TOO much data (400k rows).  so i wrote a trimmer that thins out the data so the network can still be representatively viewed without the system suffering in-browser-memory issues or 504 gateway timeouts on the server side.
this PR trims nodes from the mesh network for browser perf reasons, so we can view GR10 mesh data and update this thread https://twitter.com/owocki/status/1375278049420144645
https://gitcoin.co/_administration/mesh if you try to view most recent grants round
tested locally
> /administration/mesh performance fix, so i can ship GR10 data viz

- app/quadraticlands/templates/quadraticlands/mission/index.html
This PR puts the Quadratic Diplomacy mission behind a staff flag on the mission homepage
Fixes: GITC-198
Tested locally
> GITC-198: Puts QD mission behind staff flag on mission page

- app/grants/utils.py
This PR Imports NOTION_API_KEY and NOTION_SYBIL_DB directly allowing the continued use of `save_grant_to_notion()`
Fixes: GITC-201
Tested locally
> GITC-201: Imports NOTION_API_KEY and NOTION_SYBIL_DB directly

- app/dashboard/router.py
Removes metadata from the bounty model
GITC-40
Flows tested
- Creation
- Start / Approve Work
- Submit Work
- Payout 
- the bounty showing up on the Explorer
> GITC-40: remove metadata from bounty api

- app/assets/v2/js/quadraticlands/mission/diplomacy/room.js
Looks like when you try to vouch on https://gitcoin.co/quadraticlands/mission/diplomacy/fe7d112e-4b90-454d-a716-3f074809a1b0/gitcoin-frens
It fails due to incorrect balance being passed from the frontend
Tested Locally
> GITC-208: fix QD signature failing when saved

- app/app/context.py
- app/assets/v2/js/base.js
- app/dashboard/tasks.py
This PR moves `record_join` and `record_visit` logic into celery tasks to avoid saving data on page load
Fixes: #9282 
Fixes: GITC-210
Tested locally
> GITC-210: Record visit/join actions inside a celery task instead of context.py

- app/app/utils.py
This PR fixes `sync_profile` by storing the `NamedUser.raw_data` instead of the `NamedUser` instance
See here for details: https://github.com/PyGithub/PyGithub/blob/4faff23ce9eab00c451ffdd842686781e8a1b4eb/github/GithubObject.py
Fixes: GITC-214
Tested locally
> GITC-214: Fixes sync_profile by storing the NamedUser.raw_data vs NamedUser instance

- requirements/base.txt
This outdated version is causing a series of evens that results in errors being sent to AWS every few seconds. Increasing the version of watchtower should resolve the issue and stop the logs coming in over and over for the same issue.
Need to test on staging or prod as the logging is not set up locally to be pushed to AWS.
> GITC-207: Updating watchtower version

- app/grants/templates/grants/cart-vue.html
Check GITC-211 for complete story.
TLDR: zksync rinkeby was broken due to few issues. Team advised on upgrading and this PR does that and tests to ensure the following flow works
- Contributing to a Grant via L2 with no deposit
- Making the deposit
- Doing the actual transfer
- Saving the right txn ID
The same flow was also tested with the account not having to do a deposit as funds were already present. 
It worked as expected
GITC-211
> GITC-211: upgrade zksync to 0.0.13

- app/grants/utils.py
- app/perftools/management/commands/create_page_cache.py
- scripts/debug/add_grants_team_members.py
`grants.utils.generate_grants_leaderboard` returns a dict which is saved to a JSONStore in `create_page_cache`.
This method is performing a conversion for every subscription and is causing `create_page_cache` to be killed before completing and the resultant JSONStore (if it was to be written) is unused.
This PR will purge all references.
Fixes: GITC-213
Tested locally
> GITC-213: Purges generate_grants_leaderboard as the resultant JSONStore is unused

- app/dashboard/admin.py
- app/retail/templates/admin/change_form.html
This PR adds a button to the Hackathon Events admin page to refresh the hackathons-list cache
Fixes: GITC-212
Tested locally
> GITC-212: Adds button to admin to refresh hackathon events cache

- app/assets/v2/js/pages/bounty_details2.js
> Report from Algorand:
Hi all, we found a potential bug of Gitcoin in one of our bounty: https://gitcoin.co/issue/algorandfoundation/grow-algorand/79/100026111
A user named “igarrestu” somehow managed to apply to this bounty multiple times and you can see the record in the bounty page. 
Would you consider this is bug in Gitcoin’s anti-spam feature?
We already have backend checks for this. 
The only time this issue occurs is when users fire click the interest button in quick sucessions -> leading the check to fail as 
the first request is yet to have been saved.
This PR fixes ensure the frontend disables the button preventing the user from clicking it multiple times
GITC-234
Tested locally.
> GITC-234 bug: user being able to fire multiple start work events

- app/app/bundle_context.py
- app/dashboard/admin.py
- app/dashboard/management/commands/bundle.py
- app/grants/clr.py
We realized in Gr10 that the team was using shadow ban users to ignore contributions to be considered for matching.
Upon digging into it -> it came to light that our CLR calculations doesn't really ignore banned contributions. We would need to fix this
This PR tweaks that to ensure squelch profiles are taken into account while fetching the data
GITC-223
> GITC-223: ignore squelched profiles in clr

- app/retail/emails.py
> update some email copy

- app/dashboard/management/commands/bundle.py
- app/dashboard/templatetags/bundle.py
Now that the block is being rendered as a template (by the bundle command) prior to being passed through the bundle templatetag, we must ensure that the `static_url` and  appended file hash is properly removed from the requested filenames.
To be sure that we're removing the correct 12 chars (the file hash), this PR rewrites the regex to include the static_url in the match.
This PR also ensure that timestamps are being properly read from files loaded with a `base_dir` attr to avoid unnecessarily regenerating unchanged assets. 
Fixes: GITC-233
Tested locally under production like setting
> GITC-233: Cleans up static_url removal from bundled assets and ensures that ts checks are functional

- app/grants/clr.py
Running CLR calculations on cron takes too long and during payout we'd want to be able get the results quicker.
This does exactly that and populates the clr match table with just the current match and set the other values to 0.0
> chore: ability to ignore prediction values

- app/dashboard/templates/project/detail/info.html
- app/dashboard/views.py
- app/grants/management/commands/payout_round_noncustodial.py
This PR fixes a XSS vulnerability on the projects `work_url` (both retroactively and prevents future malformed urls being placed)
Fixes: GITC-277
Tested locally
> GITC-277: Fixes xss vuln on projects work_url

- app/dashboard/router.py
- app/retail/templates/emails/bounty.html
Removes fulfiller email form Bounty API
It which is used as fallback field to show the fulfiller info when we don't have their handle.
Does not impact on the actual flow 
GITC-249
Locally tested
> GITC-249: remove fulfiller email from API

- app/dashboard/views.py
- app/git/utils.py
- app/grants/views.py
- app/kudos/views.py
- app/marketing/views.py
- app/retail/views.py
- app/townsquare/views.py
- https://sentry.io/organizations/gitcoin/issues/1727368446/ (2.6k)
- [bug: 'AssertionError' object has no attribute 'data (4.4k)](https://sentry.io/organizations/gitcoin/issues/2522450092/)
- User.profile.RelatedObjectDoesNotExist
- https://sentry.io/organizations/gitcoin/issues/1902956247/? (1.1k)
- https://sentry.io/organizations/gitcoin/issues/1246636419/ 1.3k
- https://sentry.io/organizations/gitcoin/issues/2170202852 1.1k 
- https://sentry.io/organizations/gitcoin/issues/2074050238/?project=1398424 (28k)
- https://sentry.io/organizations/gitcoin/issues/1664409267/?project=1398424 (6.3k)
- https://sentry.io/organizations/gitcoin/issues/2199790129/ (854)
- https://sentry.io/organizations/gitcoin/issues/2545687412 (619)
- https://sentry.io/organizations/gitcoin/issues/1747280089 (535) …
> bug: sentry fixes

- app/app/settings.py
- app/quadraticlands/router.py
- app/quadraticlands/serializer.py
- app/quadraticlands/urls.py
- requirements/base.txt
This PR uses drf-flex-fields to introduct endpoint for stewards information
**URL:** 
- `http://localhost:8000/quadraticlands/api/v1/stewards`
- `http://localhost:8000/quadraticlands/api/v1/stewards/?expand=profile`
https://gitcoin.atlassian.net/browse/GITC-333
> feat: introduce steward endpoint

- app/dashboard/models.py
i recently discovered that the usd amounts for the earnings table for all bountyfulfilments data.
upon further investigation, this was because the usd conversion function on bountyfulfillment assumes that `self.payment_amount` was an integer which needed to be divided by `10**decimals` , when in fact it is not.  it is a floating point number that represents the amount of tokens transfered
https://gitcoincore.slack.com/archives/CBWA6A75M/p1629222791016400
this test data
tested locally
we will need to run save() on all bountyfulfillments when this is done
```
from dashboard.models import *
for bf in BountyFulfillment.objects.all():
bf.save()
```
> fixes bounty fulfillment data (usd amounts)

- app/dashboard/management/commands/update_trust_bonus.py
- app/dashboard/models.py
- app/dashboard/tasks.py
- app/grants/admin.py
- app/grants/clr.py
- app/grants/clr2.py
- app/grants/clr3.py
- app/grants/management/commands/analytics_clr2.py
- app/grants/management/commands/analytics_clr3.py
- app/grants/management/commands/estimate_clr.py
- app/grants/management/commands/estimate_clr2.py
- app/grants/management/commands/estimate_clr3.py
This PR implements the CLR calc in SQL in an attempt to improve performance.
To test:
```
docker exec -it web_web_1 ./app/manage.py update_trust_bonus --call-now 1
docker exec -it web_web_1 ./app/manage.py estimate_clr mainnet 1 full true
docker exec -it web_web_1 ./app/manage.py estimate_clr2 mainnet 1 full true
docker exec -it web_web_1 ./app/manage.py estimate_clr3 mainnet 1 full true
```
*please note, once each of the variations have been tested on production - a follow up PR will be raised to remove print statements and move the most effective variation to `clr.py`*
Fixes: GITC-245
Tested locally
**clr.py**
**clr2.py**
**clr3.py**
*note: I've deferred contributions from 1095 -> 993 - your results will be different to what you see in these screenshots*
> GITC-245: Implements the CLR calc in SQL

- app/grants/urls.py
- app/grants/views.py
Introduces endpoint to fetch trust bonus of given address.
Will be consumed by dGrants
- method: `POST`
- endpoint: `/grants/v1/api/trust-bonus`
- body format: `json`
- request body: 
```json
{   
"addresses": [
"0x5cdb35fADB8262A3f88863254c870c2e6A848CcA",
"0x997D35b300bA1775fdB175dF045252e57D6EA5B0"
]
}
```
- response object: 
```json
[
{
"address": "0x5cdb35fADB8262A3f88863254c870c2e6A848CcA",
"score": 0.5
},
{
"address": "0x997D35b300bA1775fdB175dF045252e57D6EA5B0",
"score": 0.5
}
]
```
> feat: trust-bonus api

- app/dashboard/templates/profiles/profile.html
- package.json
- yarn.lock
This PR corrects the version number of `vue-tel-input` used to verify sms on the trust-bonus page.
Fixes: GITC-315
Tested locally and the modal now loads correctly - @zacheryschiller to test more on his local with twilio keys
> GITC-315: Fixes sms verify

- app/retail/templates/emails/new_bounty_expire_warning.html
- app/retail/templates/emails/render_bounty_startwork_expired.html
When I get an email from gitcoin, then I click to link slack it will be redirect to discord
Just fix small text and link, so do not need testing
> Fix small bug when click to slack link

- app/dashboard/helpers.py
- app/grants/urls.py
- app/grants/views.py
Introduces and endoint to allow bsci toggle users as sybil/not
Endpoint: `/grants/v1/api/toggle_user_sybil`
Headers: `token: <PROVIDED-BY-GITCOIN>`
**Body:**
```
{
"sybil_users" :[
{
"id": 94849,
"comment": "reason for marking user as sybil"
}
],
"non_sybil_users" :[
{
"id": 94841
}
]
}
```
comment is mandatory when user is marked as sybil
> feat: toggle sybil/non sybil users

- scripts/crontab2
- scripts/crontab3
- scripts/crontab4
This PR updates the crontabs to run the clr calc more frequently (every 15 minutes)
Tested locally
> Runs clr calcs more frequently (every 15 mins)

- .travis.yml
- Dockerfile
- app/app/travis.env
- bin/ci/cypress-run
- bin/docker-command.bash
- cypress/integration/test_visit.js
- docker-compose.yml
- package.json
- yarn.lock
Pulling in pieces of other open PRs to attempt to run cypress tests in CI. The first goal is to run what tests are available (the visit tests)
This adds a script that:
* sets up ganche to start with a specific mnemonic
* runs database migrations
* starts the web application
* and runs the cypress tests
Adds the Xvfb service to travis along with the chrome addon
> Travis running cypress

- app/grants/templates/grants/cart/eth.html
Updating some of the Polygon copy to read better.
Tested locally, but needed to bump the ipdb version [as in this PR](https://github.com/gitcoinco/web/pull/9443) to run Docker locally.
> Polygon copy updates

- app/app/db.py
- app/app/settings.py
Adding the newly deployed read replica 3
Must test with deployment
Once merged we need to update the DBs in the django admin as well.
> Add db read replica 3

- app/assets/v2/js/grants/_new.js
When updating grant creation tests to work with tags I noticed a failure with the eth address validation. This PR updates the call `web3.utils.isAddress` to `Web3.utils.isAddress`. This failure was preventing the form from being submitted and disabled the submission button.
Manual test to verify on staging (until cypress tests are merged). Create a grant with an ETH payout address.
> Validation Fix

- app/retail/emails.py
- app/retail/templates/emails/grants/new_contributions.html
- app/retail/templates/emails/grants/new_contributions.txt
This PR includes L2/Sidechain earnings for zkSync and Polygon (behind staff flag) in grants contributions email
> GITC-408: Update contributions email with L2 info

- app/marketing/views.py
- scripts/crontab2
- scripts/crontab4
https://gitcoin.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=GITC&modal=detail&selectedIssue=GITC-434
https://sentry.io/share/issue/ef42b4c169b649bd9578a1665a6d5b86/
4.7k
tested locally
> GITC-434: handle invalid user access tokens

- app/assets/v2/js/grants/index.js
- app/grants/templates/grants/components/collection.html
- app/grants/templates/grants/explorer.html
- when using the search if "enter" is pressed execute the query.
- If Im seeing a collection I can add all the collection to my cart with one click 
Based on discord users feedback 
unblock #9460
https://gitcoin.atlassian.net/browse/GITC-402
> add bulk add for collections

- app/dashboard/templates/shared/cart_nav.html
This PR will fix a bug in ios where the carts images were being stretched.
Fixes: GITC-430
Tested on ios device
> GITC-430: Forces nav-cart images to use auto height on ios

- app/dashboard/templates/shared/nav_auth.html
log out link was broken before
The redirect link is now going to / instead of the current path
https://github.com/gitcoinco/web/issues/9493
Go to https://gitcoin.co/settings/account
Press the user drop-down. Then try to log out.
> Changed log out link

- app/grants/management/commands/sent_cart_reminder.py
- app/grants/views.py
- app/marketing/management/commands/post_data.py
- app/perftools/management/commands/create_page_cache.py
- app/retail/utils.py
- scripts/debug/add_squelched_profiles.py
- scripts/debug/address_usage_finder.py
- scripts/debug/grants_collusion_stats.py
- scripts/debug/grants_export.py
grants explorer broke due get_clr_rounds_metadata update
https://gitcoincore.slack.com/archives/CDML7FS7M/p1633365131046300
> fix grants explorer

- app/dashboard/templates/bounty/details2.html
This PR resolves a bug in which users were unable to extend the deadline of existing bounties. The issue was that the daterangepicker was broken because the script importing it was not present in the HTML.
> bug fix/users cannot extend deadline of existing bounties

- scripts/deploy.bash
This PR will ensure we restart `gunicorn` (which is being managed by `supervisord`) following a deploy.
> fix: adds restart for supervisor gunicorn after deploy

- app/grants/templates/grants/detail/_index.html
- app/grants/views.py
massivlye speeds up grants.views.grant_details_contributions
note there is a tradeoff here where we have to remove some of the params from the result
my sad view on on https://app.datadoghq.com/apm/traces?query=env%3Aprod%20service%3Adjango%20%40duration%3A%3E%3D4.5s&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&historicalData=true&messageDisplay=inline&sort=desc&streamTraces=true&start=1635521435028&end=1635525035028&paused=false
tested locally, brings the call on http://localhost:8000/grants/v1/api/grant/12/contributions?limit=100 down from 30s to 0.2s
> massively speeds up the grants contribution api call

- app/grants/templates/grants/explorer.html
- app/grants/views.py
GIVEN I am a Gitcoin user on the Grants Explorer and have opened a filter menu
WHEN I select a filter element(s)
THEN the filter menu remains open.
GIVEN I am a Gitcoin user on the Grants Explorer and have opened a filter menu
WHEN I click outside of the filter menu
THEN the filter menu closes.
https://gitcoin.atlassian.net/browse/GITC-521
> GITC-521 : search on applying filter

- app/retail/tests/factories/bounty_factory.py
- app/retail/tests/factories/interest_factory.py
- app/retail/tests/factories/profile_factory.py
- app/retail/tests/test_emails.py
Adds unit testing to ensure that the `reject_worker_url` is present in `render_start_work_new_applicant`
This is related to this issue on Jira: https://gitcoin.atlassian.net/jira/software/c/projects/GITC/boards/2?modal=detail&selectedIssue=GITC-379
The fix for that issue has been deployed
> add test for render_start_work_new_applicant method

- pytest.ini
This PR adds the `reuse-db` flag to `pytest.ini` to speed up any tests after the first run (this flag ensures we don't have to run migrations again once they have been ran once in the pytest context).
Tested locally, see discussion here: https://gitcoincore.slack.com/archives/C01H9H320CV/p1635885499096200
> fix: adds reuse-db flag to pytest runs

- app/assets/v2/js/cart-ethereum-zksync.js
- app/assets/v2/js/cart.js
https://share.vidyard.com/watch/TRjFhuhRfqt25ddH8dH292?
> GITC-600: enforce ethereum chain for zksync checkout

- app/grants/management/commands/grant_collections_shuffle.py
- app/grants/models/grant_collection.py
- app/grants/router.py
- app/grants/tests/management/commands/test_grant_collections_shuffle.py
Sort collections based on updated shuffle_rank that randomizes sort while giving collections with meaningful metadata more of a chance of being shown closer to the top
Refs: https://github.com/gitcoinco/web/issues/9614
These changes sort collections randomly by giving each collection a shuffle_rank. This shuffle_rank is then increased if the collection and related grants contain meaningful data. When the shuffle ranks is increased it gives the collection a higher chance of appearing close to the top of the page.
Refs: https://github.com/gitcoinco/web/issues/9614
Unit tests were added to functions that collections
> Randomized but meaningful collections displayed on collections tab

- app/dashboard/sync/tezos.py
This PR will ensure the sync command will continue even when presented with a malformed/missing (from chain) txhash
Refers to: L2 issue (https://discord.com/channels/562828676480237578/910066042284429332/910686876329988147)
Tested locally
> fix: ensure that an invalid tezos txhash will not halt the sync command

- app/assets/v2/js/cart.js
- app/assets/v2/js/tokens.js
- app/grants/templates/grants/cart/eth.html
> GITC-599: remove duplicates in token selection input (cart + tips)

- Dockerfile
- app/app/local.env
- app/app/settings.py
- bin/docker-command.bash
This PR refactors/cleans up the Dockerfile and ensures that we have enough watches available for watchdog to see all changes. Also adds flags to skip parts of the provisioning script so that we can get up and running quicker.
Fixes inotify issues when using nerdctl
Tested locally
> fix: ensures that were using watchdog and have enough watches available

- app/dashboard/views.py
> GITC-612: prevent users for access bounty owner UI page

- app/assets/v2/js/grants/index.js
In grants explorer not all pages are loaded when scrolling.
This change fixes the issue by removing an erroneous setting of the flag `vm.grantsHasNext = false`
Before fix: in the grants explorer only a limited subset of the grants are shown in total (normally the first 2 pages, 12 items). Scrolling down doesn't load all items.
After fix: all the grants are loaded as the user scroll down.
> Fixing bug in grants explorer scrolling.

- app/assets/v2/js/grants/index.js
This is a quick fix for resolving the bug in GITC-389. When in append mode (the mode triggered from scrolling), before adding new grants received from the server, it will check to see if it already exists. A more robust fix can be included in the server, that will be added as a new ticket.
GITC-389
Tested locally
> GITC-389 Remove duplicates from explore page

- app/assets/v2/js/cart-ethereum-polygon.js
- app/assets/v2/js/cart-ethereum-zksync.js
- app/grants/templates/grants/cart/eth.html
GIVEN I am on the Grants checkout page
WHEN I trigger an error that appears below the checkout button
THEN the error should not appear under the checkout button and instead be mapped to a standard error that appears as a banner on the top of the page.
https://share.vidyard.com/watch/zPsfRpVM23vKw7pTc4x4DQ?
> GITC-622: move under button errors to top

- app/assets/v2/js/grants/index.js
- app/grants/views.py
- cypress/integration/grants/test_grant_explorer.js
This PR fixes a bug present in the A-Z/Z-A sort on the grants explorer that breaks the sort if some grant titles are capitalized and others are not capitalized.
Also removes a deprecated sort option that was left in by mistake.
Tested locally
> Jeremy/bug fix/grants explorer A-Z/Z-A sort does not take capitalization into account

- app/assets/v2/js/grants/index.js
This PR fixes a bug where infinite scroll would break after applying filters to the results in the grants explorer.
The issue was that before the next page of results would be fetched from the API, the app would check to make sure that it had not been fetched already. Before the initial `fetch`, `!pageIsFetched` returns true, and so the `fetch` will proceed. After the initial `fetch`, `!pageIsFetched` returns `false`, preventing subsequent pages from being fetched.
Removing the `pageIsFetched` check resolves this issue.
https://user-images.githubusercontent.com/36638840/143063709-15d10d6c-7f1b-4069-9cb7-b308531dd8ec.mov
> GITC-502: infinite-scroll-stops-working-after-applying-filter

- app/grants/tests/factories/grant_clr_factory.py
- requirements/test.txt
This PR will fix `GrantCLR` -> `banner_text` to 50 chars with `factory.Faker` to prevent insert transaction from failing (intermittently).
Failing tests
Tested locally
> fix: ensures `banner_text` never exceeds 50 chars

- app/dashboard/views.py
This PR fix a CSS injection in profile banner filename filter. 
The old filter can be bypassed with the payload below:
```
Content-Disposition: form-data; name="banner"
/static"); background-image: url(**Image Link Here**); display: (/wallpapers/2021_795.png
``` 
Any CSS without double quote could be injected by using the payload.
An injected example: https://gitcoin.co/tkzcm
The new filter should be fine while the banners are only from the wallpapers folder.
> fix: prevent CSS injection in profile banner filename filter

- app/assets/v2/js/pages/quests.quest.quiz_style.js
Have changed the way how dynamic content is assembled by leveraging query functions instead of string concatenation.
GITC-609
This PR fixes 
1. the issue mentioned specifically in the Jira ticket - this has been tested as indicated in the ticket
2. several other potential XSS vulnerabilities - this was not tested yet. I was unable to reproduce scenarios where this code would be used. This might contain bugs / side effects and should be properly tested in staging.
> Gitc 609 xss on quest page

- app/assets/v2/js/grants/index.js
- app/grants/views.py
This PR addresses @frankchen07 feedback in this comment: https://github.com/gitcoinco/web/pull/9725#issuecomment-982130159 - and ensures the following behaviour:
```
GIVEN I am looking to filter by a primary matching category
WHEN I click on my primary-level selection
THEN the primary item is highlighted
AND the page returns all grants eligible in rounds under the primary matching category selection
AND the pillbox reads "Grant Round: [primary]".
```
Fixes: GITC-580
Tested locally
> GITC-580: allows for multiple clr_rounds to be selected at once

- app/dashboard/models.py
- app/dashboard/views.py
- app/marketing/views.py
- app/perftools/management/commands/create_activity_cache.py
- app/perftools/management/commands/create_page_cache.py
- app/retail/views.py
- app/townsquare/views.py
This PR will clean up the `Activity` queries so that we're not passing every `ActivityIndex` as a `pk` into `Activity.objects.filter(...)` 
Refs: DB load on RR1 and RR2
Tested locally (needs more testing once we have it pulled on to the cronbox to verify this fixes the problem)
> fix: cleanups activity commands and queries

- app/grants/clr.py
This PR will zero out the predicted matching once a grant hits the `match_cap_per_grant` - this should only be merged once we've added the complementary messaging to support this change. cc. @frankchen07 @lthrift 
Refs: #match-estimate-at-cap thread
Tested locally
> fix: 0 out predicted matching once a grant hits the `match_cap_per_grant`

- app/grants/models/contribution.py
- app/grants/models/subscription.py
This PR fixes regressions introduced by #9511 which reverts changes made to the models in #9444.
The `gas_price` should no-longer be included in the amounts, this PR will make sure they're not.
Fixes: regressions
Tested locally
> fix: amount_per_period_minus_gas_price model regressions

- app/assets/v2/js/cart-ethereum-polygon.js
This PR ensures that the user holds a balance without throwing a `bn` error when they don't. 
Refs: underflow - polygon checkout thread in l2
Tested locally
> fix: ensures polygon balance checks don't error out before they're meant to

- Dockerfile
- app/grants/models/contribution.py
- app/grants/models/subscription.py
- app/retail/emails.py
- app/retail/templates/emails/grants/thank_you_for_supporting.html
match estimate in grant checkout emails
common sense
tested locally
> match estimate in grant checkout emails

- app/grants/clr.py
- app/grants/management/commands/estimate_clr.py
This PR will apply the matching_cap post normalisation (recursively)
Refs: match-cap thread
Tested locally
> fix: apply the cap after normalising the distribution

- app/assets/v2/js/cart-ethereum-polygon.js
This PR will ensure that wallets which contain a large number of tokens will not throw a bigNumber overflow error
Fixes: #9854
Tested locally
> fix: prevents bigNumber overflow

- cypress/integration/grants/test_grant_explorer.js
Refactors fragile Cypress tests to avoid unintentional test failures in future
> Fix fragility in Cypress tests

- app/assets/v2/js/cart-ethereum-polygon.js
- app/grants/admin.py
- app/grants/clr.py
- app/grants/management/commands/estimate_clr.py
- app/quests/models.py
Getting master ahead of stable
> stable -> master

- app/grants/clr.py
Currently if during a round if a grant is removed from a CLR round, the CLRCalculation is still taked into account as the latest field is marked True and hasn't been toggled back.
This PR ensures that when the clr cals are run the next time -> it toggle the `latest` flag to False for all grant's clr cals which are no longer part of the round.
https://discord.com/channels/562828676480237578/907740735602851840/919793535702691890
> bug: ignore grant removed from round in clr calculation

- app/assets/v2/js/cart.js
Ensure that the same token is used in calculations for the items in the checkout cart for ETH network
GITC-665
GIVEN I have one ore more items in my cart with 0 matching and another token except DAI selected for checkout
WHEN I add another grant to the cart in the Grants Explorer
THEN I expect to see a single token in the summary (namely the one chosen in the cart)
> GITC-665: mismatch grants token and cart

- app/assets/v2/js/cart-ethereum-polygon.js
- app/assets/v2/js/cart.js
- app/grants/admin.py
- app/grants/clr.py
- app/grants/management/commands/estimate_clr.py
- app/grants/templates/grants/cart-vue.html
- app/grants/views.py
- app/quests/models.py
This PR allows admin to toggle checkout options using Static JSON store as opposed to relying on a deploy every single time. The Static JSON has already been created in admin
This takes away the need for engineering to be involved and have operations toggle switches 
**==================
Message from zksync team :
==================**
Tomorrow (most likely in 8-12 hours) we need to update the server. Unfortunately I can not yet tell the exact time when we will be able to start, it may cause the downtime for a few minutes. Most likely users won't feel any effect, but I think you should know in case there will be support requests on that matter. We are sorry for the short notice 😦 
Thank you for understanding!
> allow disabling checkout via admin

- app/dashboard/notifications.py
- app/dashboard/views.py
- app/git/models.py
- app/git/tests/models/test_git_cache.py
- app/git/tests/test_utils.py
- app/git/utils.py
This extends caching of github objects to repos, issues, comment.
GITC-327 GITC-569
GIVEN I have successfully logged in to Gitcoin
WHEN I create a new Bounty
THEN All the information is correctly pulled from Github when I provide the github issue url (Issue Title and Details) and a comment with the issue status is posted in the github issue "Issue Status: 1. Open 2. Started 3. Submitted 4. Done ..." 
GIVEN I have a bounty linked to a github issue
WHEN I cancel the bounty
THEN A comment about the cancelation is posted in the github issue
GIVEN I create a contest bounty (multiple contributors)
WHEN each contributor submits his work
THEN each submission of work is reflected in a github comment on the bounty issue (a single comment, aggregating the information of all submissions)
> GITC-327: GitHub caching extension

- app/assets/v2/js/pages/new_bounty.js
Introduces helper function that allows bounty and hackthon to show only mainnet tokens on eth and not polygon
GITC-696
> GITC-696: ensure only mainnet tokens loads in bounty

- app/assets/v2/js/grants/_new.js
https://gitcoin.atlassian.net/browse/GITC-690 - This will allow input of special twitter handles that have greater than 2 characters when creating grants. The current limit is set to 4 characters which I believe is the current limit based on https://help.twitter.com/en/managing-your-account/twitter-username-rules
Just a regex change
> GITC-690 allow special short twitter handles

- app/git/tests/models/test_git_cache.py
- app/git/tests/test_utils.py
- app/retail/emails.py
The grant contribution summary email takes into account all contributions sent in 12 hours and sends it to the grant owner.
Currently we take into account all grants contributions (ignoring the txn status) 
It makes sense to use only successful contributions and not include contributions where the : 
- txn ID cannot be found on the chain (user does something funny / uses wrong network)
- txn ID is in a pending state
> fix: ensure only successfull contributions are sent

- app/assets/v2/js/pages/profile-trust.js
- docs/README.md
Removing the link to verify sms offline. The modal now looks like the attached image.
GITC-708
> GITC-708 - Remove link to verify offline

- scripts/crontab
This PR will ensure we always run `sync_pending_fulfillments` and `sync_pending_contributions` even if the previous call is still running.
Fixes: GITC-697
> GITC-697: ensure pending commands are always called even after failures

- app/assets/v2/js/grants/matching_funds.js
- app/grants/templates/grants/matching_funds.html
https://discord.com/channels/562828676480237578/932141631778467881/932161852841033748
**Note:** 
- ~hardcoded data has to be removed~
- this currently doesn't work as expected cause the UI is updated after a delay. (THIS NEEDS A FOLLOW UP STORY)
The situation is applicable for users who have claimed funds on etherscan and we don't have a record of it on our UI.
The fix here is to until we have a solution in place , we check the contract to check if balance is 0 and if so , we show the txn in the history and not ready to claim
As we don't have the claim tx in our DB. -> we just redirect them to the events log on etherscan
> hide claims which have 0 amount for grant owner

- app/grants/templates/grants/components/collection.html
This should remove the nan value and show the remainder count
before
after
> accessing cached count for collections card

- app/dashboard/tests/views/test_profile_projects.py
- app/dashboard/views.py
This PR will ensure that PortfolioItems can only be deleted by their owner/staff
Fixes: #9747 / GITC-610
Cases have been added to test both paths (success/failure on unauth'd)
> GITC-610: fixes auth on portfolioItem deletion

- app/taskapp/celery.py
if we can get sentry working on celery tasks, then when theres a long running query we could just go in and pg_terminate_backend(pid) the long queries and watch in the senry logs which job fails.
https://docs.sentry.io/platforms/python/guides/celery/configuration/integrations/django/
When testing locally with debug=True I received output saying sentry was successfully installed.
> initiate sentry logging within celery taskapp

- app/gitcoinbot/management/commands/get_notifications.py
This PR:
1. ensures the notification subject `url` is defined before attempting to `.replace()` on it
2. ensures non-numeric comments are ignored (as they throw when passing through `get_issue_comments()` util)
3. adds a missing positional to the `post_issue_comment_reaction()` call
Refs: #10031 
Tested locally
> fix: `get_notifications()` fixes

- app/grants/clr.py
- app/grants/models/grant.py
This PR:
1. caches the `sqrts` for each contributor to reduce the need to perform the same (expensive) calc multiple times
2. changes how we pair so that our time complexity comes in at something like `O((n^2)/2)`:
```
obj = {1: 2, 2: 3, 3: 4}
contributors = []
pairs = {}
for k1, v1 in obj.items():
for k2 in contributors:
u_k1 = k1 if k2 > k1 else k2
u_k2 = k2 if k2 > k1 else k1
if u_k1 != u_k2:
if u_k1 not in pairs:
pairs[u_k1] = {}
if u_k2 not in pairs[u_k1]:
pairs[u_k1][u_k2] = 0
pairs[u_k1][u_k2] = obj[u_k1] * obj[u_k2]
contributors.append(k1)
```
We expect `pairs = {1: {2: 6, 3: 8}, 2: {3: 12}}`, which consists of every pair multiplied together just once, this reduces the number of calcs we need to perform by 50%. We also apply this same behaviour to the `calculate_clr` function, to …
> chore: optimise CLR performance away from O(n^2)

- app/grants/models/contribution.py
This PR will correct failed zksync reports if the `split_tx_id` is missing the `sync-tx:` prefix
Fixes: #10053
Tested locally and in prod
> fix: zksync contrib false failure reports

- docs/RUNNING_LOCALLY_DOCKER.md
The `RUNNING_LOCALLY_DOCKER.md` file describes a way to deploy a custom `ERC20` token using a tokenfactory. 
Recently that factory doesn't work, so I added a simple `ERC20` snippet that can be use to deploy a token to a testnet using remix.
> DOCS: add a simple ERC20 code example for remix in case tokenfactory doesn't work

- app/dashboard/templates/profiles/header_details.html
Link to the GitHub profile's main page instead of to the repositories tab.
> Link to a GitHub profile's main page

- app/dashboard/views.py
This PR ensures we don't incorrectly drop the BrightID service from the data fed to the trust-bonus tab (this is a regression following the removal of Quadratic Diplomacy from the trust-bonus options).
Fixes: #10173
> fix: ensures we don't drop brightID from trust-bonus tab for non-staff users

- app/assets/v2/js/cart-ethereum-polygon.js
- app/assets/v2/js/cart-ethereum-zksync.js
- app/assets/v2/js/cart.js
When the cart is initialized and when a tab is selected, the `tabChange` method is called.
This method was opening the web3 dialog by default, or waiting to connect to web3 in case it was already opened.
I removed that part so that the dialog is opened only at the final checkout action if needed. 
The final checkout action is already doing the same check, opening the dialog in case the wallet is not connected.
Fixes: #9991
> don't show web3 modal on cart page init and tab change

- app/assets/v2/js/grants/matching_funds.js
One user had some old QF matches, from rounds 7 and lower, which were causing previously paid out matches to show that they could be claimed. e.g. 
`{amount: 6.74208445222599
claim_tx: null
grant_payout: null
pk: 1148
ready_for_payout: true
round_number: 7}`
(https://discord.com/channels/562828676480237578/947861866644901928/947861868993732619)
Another user had a rogue clr_match associated with a non existent round: 121. Unsure how this was created.
https://discord.com/channels/562828676480237578/947992211528749086
`{claim_tx: null
grant_payout: null
pk: 2001
ready_for_payout: true
round_number: 121}`
Both of these weird matches have in common that they do not have a grant_payout. I believe a clr_match should have a grant_payout regardless of whether or not they have claimed their funds. …
> filter out old rounds for available matches since payout does not exist

- app/dashboard/tests/test_dashboard_utils.py
`test_get_bounty()` is testing that a standardBounty entry can be picked up from IPFS - because we don't control the version of the infura ipfs node and `ipfshttpclient` is unable to communicate with that node (version mismatch), we are going to drop this test to restore our passing CI.
Refs: failing CI
> fix: deletes test_get_bounty() to keep a passing CI

- app/assets/v2/js/cart.js
- app/assets/v2/js/grants/cart/algorand_extension.js
The original PR for Algorand checkout (#9953) hardcodes one wallet, although the code does have the option for us to select which one of AlgoSigner, MyAlgoConnect, or WalletConnect we want to set as the default. We want to change the logic so that the app will run through that list of wallets, see which one the user has, and then move forward with that extension.
The priority list of wallets is:
- WalletConnect
- MyAlgo Connect
- AlgoSigner
closes #10240
> algorand: multiple wallet fallback

- app/grants/views.py
Just a little fix to avoid backend errors in case the `ingest_merkle_claim_to_clr_match` API receives a request without a token set in the headers.
> fix: use `request.headers.get` to avoid backend errors

- app/search/management/commands/update_search_index.py
- app/search/models.py
Currently we concat the title and description, but elasticsearch's `match` method is using a keyword index. 
eg this works:
https://gitcoin.co/api/v0.1/search/?term=otterscanotterscan
but this doesn't
https://gitcoin.co/api/v0.1/search/?term=otterscan
This PR alters the elasticsearch `full_search` field so that each keyword definitely has a space between it, once merged we will need to recreate the index.
Fixes: #9785
Tested against the prod es instance
> fix: ensure elasticsearch full_search field contains spaces between keywords

- app/assets/v2/js/grants/ingest-missing-contributions.js
While attempting to log polygon claims, I kept getting prompted to switch to mumbai testnet instead of polygon mainnet. This always prompts user to switch to polygon mainnet
fixes: #10330
> default to switching to mainnet

- app/assets/v2/js/carousel-extensions.js
- app/assets/v2/scss/jtbd.scss
- app/retail/templates/home/index2021.html
- app/retail/templates/shared/footer_scripts.html
As describe in #10302 we want any click in the GR13 banner to redirect to `/grants` unless the user clicks on the `Explore Grants` button, which sends the user to `/grants/explorer`.
Since [nested links are illegal](https://www.w3.org/TR/html401/struct/links.html#h-12.2.2), we cannot have an `a` tag that wraps the full carousel item which contains another link button. 
A solution could be having an absolute `a` with `width` and `height` 100% and the carousel inner element again with absolute position placed on top of it. This solution can already have problems depending on the inner content, and in this specific case it can break some other parts given that the carousel `js` and `css` are implemented in the external bootstrap lib.
For this reason I added a simple extension to the carousel …
> add carousel extension to make gr13 banner clickable

- app/grants/views.py
If a grant has multiple eligibility tags and the user filters by all ecosystem rounds by clicking `ecosystem` grants that have multiple ecosystems tags will be returned from the api multiple times
This makes sure only unique grants are returned
fixes: #10333 
Before changes
https://user-images.githubusercontent.com/6887938/158625564-a254be26-2384-40f9-a629-6bc02ef3ed1c.mov
After
https://user-images.githubusercontent.com/6887938/158625644-1b3b436f-9776-42eb-8c32-eb372ff8a61f.mov
> only return distinct grants when filtering for all ecosystem rounds

- app/dashboard/router.py
- `interested_count` is a property of the model, it cannot simply be listed in the fields, hence I have created a MethodField for this
#10353 
Have tested the following URLs and they do not throw any 500 error any more:
- http://127.0.0.1:8000/api/v0.1/bounties/slim/?network=mainnet&idx_status=open&applicants=1&order_by=-featuring_date&offset=0&limit=10&is_featured=True
- http://127.0.0.1:8000/api/v0.1/bounties/slim/?network=mainnet&idx_status=open&applicants=0&order_by=-featuring_date&offset=0&limit=10&is_featured=True
- http://127.0.0.1:8000/api/v0.1/bounties/slim/?network=mainnet&idx_status=open&applicants=1-5&order_by=-featuring_date&offset=0&limit=10&is_featured=True
> Fix definition of BountySerializerSlim

- app/assets/v2/js/grants/_detail.js
- app/grants/templates/grants/detail/template-grant-details.html
Multiple users (on desktop and mobile) are reporting seeing extra decimals for the contribution amounts when on the grant details page. Screenshots below
This formats values when data is received instead of in the template
fixes: #10367
> additional filter updates

- app/assets/v2/js/grants/_new.js
This fixes back navigation in the grant creation flow, when the user is in the last step.
2 cases need to be handled separately:
1. the user clicks the right button (for next) -> need to check if we submit form 
3. the user clicks the left button (go back) -> need to check if we are on the first page
No ticket open for this. I have noticed this as I was implementing the same flow for bounties, and did not want to walk by it.
Has been tested locally.
https://www.loom.com/share/dd5388b2126d4513a03cdc0e50c2b854
> Fix back navigation in grant creation flow

- app/assets/v2/js/search.js
- app/assets/v2/scss/gc-utilities.scss
- app/dashboard/templates/shared/search.html
- app/search/models.py
This PR prevents race-conditions from appearing on `search()` by preventing resubmissions and adds `boosts` to the elasticsearch query to help order the results. 
We're currently boosting on the `title` (by 10) and if the `source_type="grant"` (by 2), this promotes results with the wildcard search term in the `title` to the top and then pushes those which relate to `grants` slightly higher so that the first results we get back should point to `grants` whose titles best fit the given search term.
Refs: https://github.com/gitcoinco/web/pull/10298
Tested locally and against the prod elasticsearch instance.
> fix: prevents race-condition on search() and improves elasticsearch result ordering

- app/assets/v2/js/cart-ethereum-polygon.js
- app/grants/templates/grants/cart/eth_checkout_button.html
It looks like after splitting multisig and non multisig grants for polygon checkout the split modal was continuing to display. This should only show polygon multisig modal if it is called from the ethereum checkout page
fixes: #10380
https://user-images.githubusercontent.com/6887938/159502620-78a53173-2ed3-4396-b524-24bcfae98c78.mov
> updated disable and polygon modal display logic

- app/dashboard/views.py
dug into the twitter one and it looks like the api returns the tweet
> @notionport I know the founder well if you'd like an intro 🙂
Looking at the code. == > 
What we do is look at last tweet of user to see if that have the I have verified myself on gitcoin 
The issue was that the  verify tweet was posted and before our backend could verify -> annika | gitcoin replied / tweeted the above message and our backend ended up picking that up.
This PR changes to ensure we look at last 10 tweets
closes https://github.com/gitcoinco/web/issues/10406
> chore: check last 10 tweet activities instead on last tweet activity

- app/assets/v2/js/pages/bounty_details2.js
To match the e-mail address used for support in `board.js`:  https://github.com/gitcoinco/web/blob/58262661125d44db4a7b9f26bbc65ca9d782ac10/app/assets/v2/js/board.js#L48
---
Relates to #10501
> Change e-mail address to support@gitcoin.co

- app/grants/templates/grants/components/historical_claim.html
> I would add a bug here. 
e.g my grant https://gitcoin.co/grants/2922/gitcoin-governance-chinese-ecosystem-development
I have claimed GR12, but the status showed Returned to matching pool (tx is https://etherscan.io/tx/0x808152f5e0be029a351c3d03387f5075ef1b2e6b57ae2a6bdf19838901e67453)
Looks like for the older contracts (non merkle), the status is set to NA despite have a claim tx id.
The reason is the older contracts rely on a diff abi to check balance. To account for that , we need to tweak our conditions to ensure to check claim_tx_id is set before checking if status is contract is funding_withdrawn
https://discord.com/channels/562828676480237578/963768450445082645/965417369801457704
> bug: ensure older claims show up after contract is drained

- requirements/test.txt
Pinning django debug toolbar to a version that works with our environment.
No specific issue, this fixes workflow errors.
GHA workflow is expected to pass and not fail due to django debug toolbar version.
> Pinning django debug toolbar to version that works with our environment

- app/grants/tasks.py
- app/search/management/commands/create_search_index_with_active_grants.py
- app/search/models.py
Deleted and inactive grants were being returned from search results. This adds a new command to create a new index that only includes active grants. It also should check for grants being active and/or hidden before it saves them and indexes them into the search model as well as the elastic index. A new index had to be created since grants were being deleted from the django admin and it was impossible to detect which grants had been deleted.
This is the command to create the new index: docker-compose exec web python3 app/manage.py create_search_index_with_active_grants {index-name}. 
Once this is merged the command should be ran to create the new index. Once the index is created we should be able to merge https://github.com/gitcoinco/web/pull/10557
Fixes: #10478
> Reindex elastic to only inlcude active grant 

- app/assets/v2/js/cart-ethereum-polygon.js
- app/assets/v2/js/cart.js
- app/assets/v2/js/grants/ingest-missing-contributions.js
- app/assets/v2/js/wallet.js
This PR removes MetaMask lock-in by using the provider instance from Web3Modal for polygon interactions. This will enable users access to other Web3Modal supported wallets.
closes #10530 
successful polygon checkout -> https://mumbai.polygonscan.com/tx/0xcca1441412f14520cfc388ed102087c5685a948724029869d58d362f148d22de
> use web3modal for polygon interactions

- app/dashboard/models.py
- app/dashboard/views.py
As a funder
I want to be prevented from creating bounties on expired hackathons
So that i dont give fale realities to contributors
Acceptance Criteria
Redirect user to Onboarding Page
GIVEN I have created a hackathon with a specific end date
AND it is past that specified end date... aka hackathon has ended
WHEN I navigate to [www.gitcoin.co/hackathon/slug-here/new](http://www.gitcoin.co/hackathon/slug-here/new)
THEN i should be redirected to the in focus hackathons onboarding page
AND i should be prevented to create any new bounties on that hackathon
fixes: #10577 
Active Hackathon:
https://user-images.githubusercontent.com/6887938/167189236-166dea51-c8de-46af-b982-b5b0d11bce26.mov
Expired Hackathon:
https://user-images.githubusercontent.com/6887938/167189297-8b7fe1e3-8e3a-4aec-9d87-6162e9 …
> check if hackathon is expired and redirect to onboarding if true

- app/app/settings.py
- app/assets/v2/js/search.js
- app/assets/v2/scss/search.scss
- app/dashboard/templates/shared/search.html
- app/search/management/commands/create_search_index_with_active_grants.py
- app/search/models.py
- app/search/views.py
These updates bring back totals for all of the different models that are being searched so that pagination is accurate for each tab. It adds another query to bring back results for each tab individually. 
Pagination was updated on the fe to request results based on the active tab. 
There is also a new environment variable that sets the elastic index once it is created. It corresponds to {index-name} passed to the above command and is named `ACTIVE_ELASTIC_INDEX`
fixes: #10478 and #10480
https://user-images.githubusercontent.com/6887938/166337104-0d3f8029-950b-482a-bdcb-866a41a55f06.mov
> 10480 change result amount logic

- app/assets/v2/scss/quests.scss
There are media queries on buttons for screens less than 991px in `quests.scss` that are causing this issue. 
```css
.btn {
width: -webkit-fill-available;
top: 0.4rem;
border: none;
}
```
This PR adds higher specificity styles for the back-to-top button.
> Fix quests UI bug on mobile devices

- app/assets/v2/js/pages/profile-trust.js
- app/dashboard/poh_utils.py
- app/dashboard/views.py
- app/grants/abi/eip_1271_abi.py
- app/grants/utils.py
Fixes an issue where smart contract wallets can't properly sign the trust bonus verification for proof of humanity. The solution is to attempt to call IsValidSignature() on the wallet address if the usual recoverHash() method fails. I tested specifically on an Argent wallet, but in theory, as long as the wallet supports eip-1271, this should work.
Note: I'm very new to interacting with these tech stacks (python, smart contracts), so the more guidance anyone can provide, the better! Thanks!
- Also includes minor typo fix
EIP-1271 https://eips.ethereum.org/EIPS/eip-1271
Argent wallet support for EIP-1271 https://docs.argent.xyz/wallet-connect-and-argent#message-signature
Wasn't able to locate existing tests around similar code, but would be happy to add them if provided some guidance
> Allow smart contract wallets to obtain Proof of Humanity trust bonus

- app/assets/v2/scss/jtbd.scss
- app/marketing/admin.py
- app/retail/templates/home/index2021.html
- app/retail/views.py
- Upload images in Image Dropzone
- Head over to StaticJsonEnv 
- Select row with key `landingBanner`. If it doesn't exist -> create one 
- To show default landing banner ->  set the value to `{}`
- To enable slider -> ensure the value is updated in the following format  
```
{
"slides": [
{
"title": " text which appears above image",
"subtitle": "text which appears below image",
"img": "pk on ImageDropzone"
"buttonLink": "Where the button links to",
"buttonCTA" : "Text on the button",
"backgroundImage": "pk on ImageDropzone"
},
{...}
]
}
```
- To change order on slider -> simply change the order in slider array 
Here is an example: 
```
{
"slides": [
{
"title": "March 9-24, 2022",
"subtitle": "Web3's Biggest Funding &amp; Building Event",
"img": 4,
"buttonLink": "/grants/explorer", …
```
> feat: toggle landing page slider

- app/grants/templates/grants/cart/extension/binance.html
- app/grants/templates/grants/cart/extension/harmony.html
- app/grants/templates/grants/cart/extension/kusama.html
- app/grants/templates/grants/cart/extension/polkadot.html
- app/grants/templates/grants/cart/extension/rsk.html
- app/grants/templates/grants/cart/qr/celo.html
- app/grants/templates/grants/cart/qr/zcash.html
- app/grants/templates/grants/cart/qr/zil.html
Celo Cart doesn't load.
This is cause we attempt to reference data before the API returns a value.
Adding a if check to ensure we render the dropdown only after data is available fixes this 
https://discord.com/channels/562828676480237578/976547054925021205/976547056564961301
Locally tested
> bug: fix cart loading

- app/assets/v2/js/cart.js
issue: #10633 reported a global function being undefined. It seems like an edge case, but its possible that the functions within`app/assets/v2/js/shared.js` were not globally available at the time that the component had mounted. This should reload the component and pick up the global functions that are outside of Vue's scope
fixes: #10633
> force reload component if global wallet functions are undefined

- app/assets/v2/js/search.js
- app/search/models.py
This updates relevance when searching globally across the site. It also resets the current tab to 'All' when running a second search to clean up the ui 
This also changes the logic to only search title.
fixes: [#10560](https://github.com/gitcoinco/web/issues/10560)
https://user-images.githubusercontent.com/6887938/169910319-1567ddad-bf49-4c6e-a7fd-789e04a3e3b9.mov
> updated relevance priority for global search

- app/app/settings.py
- app/dashboard/passport_reader.py
- app/dashboard/tasks.py
- bin/docker-install.bash
- docker-compose-celery.yml
- requirements/base.txt
- requirements/test.txt
This PR adds a bash script to install docker in `Ubuntu 16.04` environments - we intend to also add a Dockerfile and move our celery nodes into this docker environment.
This is to get around a sub-dependency issue - `DIDKit` requires `glibc_2.27` and `Ubuntu 16.04` can only be safely upgraded to `2.23`, we plan to temporarily move our celery nodes into docker containers hosted in situ running `Ubuntu 20.04` which will later be replaced as we roll out our new infra-as-code solution.
Refs: #10618 
Tested locally
> fix: adds bash script to install docker for celery servers

- app/assets/v2/js/pages/profile-trust.js
- app/dashboard/tasks.py
- app/dashboard/views.py
- app/grants/management/commands/grants_cv.py
This fixes:
- some loge messages (one of which was causing Sentry to track events) 
- some linter issues
No issue exists for this
> Adjusting log messages + linter fixes

- app/assets/v2/js/pages/change_bounty.js
- app/assets/v2/js/pages/profile-trust.js
- app/dashboard/tasks.py
- app/dashboard/templates/bounty/details2.html
- app/dashboard/templates/bounty/new_bounty_step_5.html
- app/dashboard/views.py
- app/grants/management/commands/grants_cv.py
- app/grants/utils.py
Merging fixes from master to stable
> Merging fixes from master to stable

- app/dashboard/tasks.py
allows these common tasks to be flushed from the queue
record join
record  visti
profile dict
and a few others
2 years ago, id care more about the data integrity / analytics repercussions of doing something like this - and would do more serious refactoring of how this data is stored.  but since were ditching the monolith in a few months, i dont think it really matters anymore if visits arent recorded or if the profile dicts are recomputed with the same urgency.
what matters more now is freeing up the resources to the site to stay online so that the GPC can focus more on maintenance mode stuff like building grants 2.
https://discord.com/channels/562828676480237578/990199901633789962/990439454583967764
tested locally
> allows these common tasks to be flushed from the queue

- app/assets/v2/js/pages/profile-trust.js
This PR sets a maximum health-check timeout of 60s (a maximum of 60s between pings) when checking if ceramic is online.
Refers: https://github.com/gitcoinco/passport/issues/312
Tested locally
> fix: sets a maximum healthCheck timeout of 60s on trust-bonus tab

- app/retail/templates/bounties/contributor/feature.html
The text underneath "Get Paid for Contributing to Freelance Issues" was duplicated underneath "Sharpen Your Coding Skills". I updated with some relevant descriptive content.
N/A
N/A
> Fix:  duplicate subtext

- docs/README.md
Hey all, this PR adds a [GitPOAP Badge](https://docs.gitpoap.io/api#get-v1repoownernamebadge) to the README that displays the number of minted GitPOAPs for this repository by contributors to this repo.
You can see an example of this in [our Documentation repository](https://github.com/gitpoap/gitpoap-docs#gitpoap-docs).
This should help would-be contributors as well as existing contributors find out that they will/have received GitPOAPs for their contributions.
CC: @colfax23 @kayla-henrie
No testing since this is only a change to the README displayed on GitHub. However, here's a screenshot of the updated README:
> [README] Add GitPOAP Badge to Display Number of Minted GitPOAPs for Contributors

- app/grants/views_api_vc.py
Replacing field `is_gr14_contributor` to `num_gr14_contributions` for sake of consistency.
> Change in API for gitcoin stamps: replacing field is_gr14_contributor to num_gr14_contributions for sake of consistency.

- app/grants/templates/grants/landing/landing_qf_active.html
- app/grants/views.py
Shows banner if there is an active round and they don't have full trust bonus
fixes: https://github.com/gitcoinco/passport/issues/535
> verification cta

- Dockerfile
- requirements/base.txt
This should resolve issues around building the docker containers for the repo. 
From my understanding `RUN dpkg -i google-chrome-stable_current_amd64.deb` was added for cypress integration testing, and it is not necessary
I'm lacking context on `psycopg2` but it seems as though everything is working as expected with the version bump.
Tested on build
> Build issue

- app/grants/views.py
Given a grantee has submitted a new grant
When the grant record is saved 
Then the main round tag is selected in the requested tags field.
On creation of a new ethereum grant -> the *** Main Round** is applied to both tags requested and tags column
Refer: https://discord.com/channels/562828676480237578/1017467074882326538/1017467076891394048
Please ensure the tag *** Main Round** is created while testing locally / staging
> feat: auto-add main round to all grants

- app/assets/v2/js/cart-ethereum-polygon.js
the version of web3js that gitcoin uses was updated recently to https://github.com/ChainSafe/web3.js/releases/tag/v1.7.5. In v1.7.5 if you do not add a `gasPrice` parameter the priority fee defaults to `2.5` 
pull that is referenced in v1.7.5 release: https://github.com/ChainSafe/web3.js/pull/5121/files#diff-365a22cb44473b7399e704d0bf30aefe872162914bf9af3ed3525d87beacc1aaR160
These are the gas prices when these screenshots were taken:
This was happening before these changes:
The priority fee is defaulting to 2.5 ↘️ which is too low
This is what happens after these changes:
The fee is being set to the fast value, which is why it is saying that the priority fee may be too high. Imo this is ok since it amounts to a fraction of penny and should ensure it is successful
> remove gas param

- requirements/base.txt
Build was failing and throwing an error originating from `django-oauth-toolkit`
Error:
`Traceback (most recent call last):
File "./manage.py", line 59, in <module>
execute_from_command_line(sys.argv)
File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
utility.execute()
File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
django.setup()
File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate …
> peg django-oauth-toolkit version

- app/grants/views_api_vc.py
After the last modification `round_num` might be null in `GrantsContributionIndex`
This relates to https://github.com/gitcoinco/passport/issues/593
Has been tested on local
> Exclude round_num==null when counting number of rounds contributed to

- app/app/settings.py
Fixes zksync queue ingestion delay, which causes users to not be able to see their grants donations until the place in the queue has been processed
> fix: moved zksync ingestion task to high priority queue

- app/assets/onepager/js/receive.js
When tips are paid in low value tokens the amount in wei is returned from python/django in scientific notation. Throwing an error when trying to convert it to a BN
This use `BigInt` to parse number because it works for numbers that are in scientific notation as well as ints
fixes: #41
> use BigInt to parse scientific notation

- app/dashboard/utils.py
This is a hotfix for https://github.com/gitcoinco/web/pull/10938 the `INFURA_V3_PROJECT_ID` needed to be switched out with `ALCHEMY_KEY`
> switch infura key with alchemy

- infra/production/index.ts
There are currently two buckets on S3, the new one, [bucket-fc46b51](https://s3.console.aws.amazon.com/s3/buckets/bucket-fc46b51?region=us-west-2), deployed Nov 11. The app is currently mis-configured to upload assets to the new bucket, but the CloudFront CDN still points to the old bucket
[bucket-0427bb4](https://s3.console.aws.amazon.com/s3/buckets/bucket-0427bb4?region=us-west-2). This hardcodes the app to point to the old bucket, which has had assets synced from the new one.
> Hardcode website static assets bucket name in Pulumi
