gitcoinco/web

- README.md
:wave: This PR documents all the fields coming back from the API and adds docs on how to use the URL parameters to limit the results returned from the API.
> Documents API Fields & Filter/Sort URL Parameters

- app/dashboard/templates/yge/receive.html
- app/dashboard/templates/yge/send1.html
- app/dashboard/templates/yge/send2.html
> Update link on image

- app/marketing/management/commands/post_quote.py
- app/marketing/quotify/run.py
class random.SystemRandom([seed])
Class that uses the os.urandom() function for generating random numbers from sources provided by the operating system.
#38
> Standard pseudo-random generators are not suitable for security/cryptographic purposes.

- app/retail/templates/about.html
- Change "**Want to build `to` future of open source?**" to "**Want to build `the` future of open source?**"
> Minor Typo Error

- README.md
Hi, I added the field of the _bountydetails function.  Please review and revise as needed :)
> WEB3 API documentation

- .gitignore
- app/app/local_settings.py.dist
- app/app/utils.py
- app/dashboard/management/commands/post_to_craigslist.py
- app/dashboard/notifications.py
- requirements.txt
resolves #42 
You will need to add the email credentials in the settings file/ local settings file to test this out.
Please let me know if any further changes are required
> Craigslist

- app/assets/v2/css/timeline.css
Fix roadmap items move when hover over them.
https://github.com/gitcoinco/web/issues/64
> Fix roadmap items move when hover over them.

- app/assets/v2/css/base.css
- app/retail/templates/shared/mailchimp.html
Files change: 
- mailchimp.html
- base.css
Module(s) affected: 
- template
Fixes: https://github.com/gitcoinco/web/issues/66
> css: prettify the subscribe button

- app/assets/yge/youvegoteth/send.js
* Modified alert to display proper grammer when user enters a value below the minimum on tip page
* `send.js`
> Fix grammer in alert on tip page

- .gitignore
- .travis.yml
- Dockerfile
- README.md
- app/app/settings.py
- app/economy/utils.py
- app/marketing/utils.py
- app/marketing/views.py
- app/tdi/views.py
- docker-compose.yml
- requirements-test.txt
- requirements.txt
- setup.cfg
The goal of this PR is to implement automated testing and coverage to the repository. 
Reference: #89 
Repository owner should:
- Visit https://codecov.io/gh/gitcoinco/web/ and add the github webhook  
- Visit https://github.com/apps/codecov and configure codecov integration for `gitcoinco/web`
- Visit https://travis-ci.org/ and add the `gitcoinco/web` repository to Travis.
> Add Travis and Codecov integrations

- app/assets/v2/js/amounts.js
- app/assets/v2/js/pages/new_bounty.js
- app/assets/yge/youvegoteth/index.js
- app/assets/yge/youvegoteth/send.js
- app/dashboard/helpers.py
- app/dashboard/templates/submit_bounty.html
- app/dashboard/templates/yge/base.html
- app/dashboard/templates/yge/send2.html
> Tips now show USD estimates

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Set up a base template to provide some clarity to encourage fresh
faces to contribute.
Refs: https://github.com/gitcoinco/web/issues/65
Modules(s) changed:
-  doc
> doc: added contributing.md

- app/assets/v2/css/base.css
Fixes unexpected consequence on the accept/reject page.
> css: Quick style fix for buttons using the btn-info class

- app/dashboard/templates/bounty_details.html
- app/dashboard/templates/claim_bounty.html
- app/dashboard/templates/clawback_expired_bounty.html
- app/dashboard/templates/dashboard.html
- app/dashboard/templates/process_bounty.html
- app/dashboard/templates/profile_details.html
- app/dashboard/templates/submit_bounty.html
- app/retail/templates/leaderboard.html
aka "do not scream at me"...
This is a quick untested PR to suggest to remove the text-uppercase classes and not write all the content in all-caps. 
I personally think that non-all-caps text is easier to read and generally more polite (uppercase looks like screaming?) :) I don't know what's the reason behind it, I am not a designer at all and generally have no idea, but still wanted to raise this topic.  ;)  
(feel free to close the PR if you disagree/don't care - I know there are more important topics todo :) ❤️ ❤️  :high5:
> Remove all-caps (text-uppercase) classes

- app/assets/v2/js/shared.js
Fixes https://github.com/gitcoinco/web/issues/150
> shared.js: Escape single quotes with &#39;

- README.md
> add "setup database" section to documentation

- README.md
- app/app/local_settings.py.dist
- app/app/utils.py
- app/dashboard/management/commands/activity_report.py
- app/dashboard/models.py
- app/dashboard/tokens.py
- app/marketing/mails.py
- requirements/base.txt
add a management command to generate a CSV of tips and bounties in a date range, then email them
fixes #157
> add activity_report management command

- app/assets/v2/js/pages/dashboard.js
Fixes #188.  Feel free to add to close this PR and open a new one if this doesn't sufficiently fix the problem. I'm not able to run this locally with the resources at my disposal, so this is a shot in the dark that's sort of been tested in Chrome dev tools.
ui
Fixes #188
> Add sane fallback for localStorage usage

- app/assets/v2/css/base.css
- app/assets/v2/js/shared.js
- app/dashboard/templates/bounty_details.html
- app/dashboard/templates/claim_bounty.html
- app/dashboard/templates/clawback_expired_bounty.html
- app/dashboard/templates/dashboard.html
- app/dashboard/templates/process_bounty.html
- app/dashboard/templates/profile_details.html
- app/dashboard/templates/submit_bounty.html
- app/dashboard/templates/toolbox.html
- app/retail/templates/leaderboard.html
- shrunk vertical nav from col-3 to col-2
- refactored base.css
- ui
Refs: https://github.com/gitcoinco/web/issues/133
> css: shrunk vertical navbar +  refactoring

- app/dashboard/templates/yge/base.html
The viewport meta is duplicated for iOS support
UI
> remove duplicate viewport meta

- app/dashboard/views.py
- app/gas/utils.py
- app/marketing/admin.py
- app/marketing/google_analytics.py
- app/marketing/management/commands/ingest_slack_users.py
- app/marketing/management/commands/pull_stats.py
- app/marketing/models.py
- docker-compose.yml
The goal of this PR is to address issues and difficulty with accessing the gitcoin postgresql data.
Additionally, I sorted the python project to fix travis builds.
Ref: https://gitcoincommunity.slack.com/archives/C8E45J5D0/p1515104528000353
Docker compose stack
Fixes #216
> Expose psql port in docker stack

- app/dashboard/notifications.py
- app/dashboard/views.py
- app/linkshortener/management/commands/create_shortlinks.py
- app/linkshortener/views.py
- app/marketing/admin.py
- app/marketing/models.py
- app/retail/views.py
Fixes isort failures in the current master build.  This simply rearranges certain module import orders to satisfy isort.
Refs: #241
> Fix the test suite isort failures

- README.md
- app/app/local_settings.py.dist
doc: changed port to 8000 in github integration ( same port as what the server is running )
- doc
> doc: changed port to 8000 in github integration steps

- app/assets/v2/css/base.css
- ui
- Fixes: https://github.com/gitcoinco/web/issues/347
> css: set max-width to 100% to fix display

- app/assets/v2/js/shared.js
Fixed `SyntaxError: expected expression, got '*'` by replacing `**` with `Math.pow()`
- resolve rollbar error
- https://github.com/gitcoinco/web/issues/338
> js: replaced ** with Math.pow()

- app/dashboard/helpers.py
- app/dashboard/models.py
- app/dashboard/tests/test_dashboard_helpers.py
- app/dashboard/tests/test_dashboard_models.py
- app/economy/tests/test_economy_utils.py
- app/gas/tests/test_gas_utils.py
- requirements/test.txt
Increases code coverage.
Fixes: #353
> Increase code coverage

- app/assets/v2/js/abi.js
Ref : https://github.com/gitcoinco/web/pull/374
- js
- https://github.com/gitcoinco/web/issues/391
> rollbar: replaces ** with Math.pow

- app/assets/v2/js/pages/leaderboard.js
There were a few problems according to ESLint,
and Docker would not allow me to continue work on Issue #239,
until they were corrected. Here is a list of those errors:
node_1     |
node_1     | /node/app/assets/v2/js/pages/leaderboard.js
node_1     |    4:57  error  Unexpected space before function parentheses     space-before-function-paren
node_1     |    4:60  error  Missing space before opening brace               space-before-blocks
node_1     |    7:5   error  Expected blank line after variable declarations  newline-after-var
node_1     |   11:40  error  There must be a space inside this paren          space-in-parens
node_1     |   11:42  error  There must be a space inside this paren          space-in-parens
node_1     |   11:43  error  Missing space before opening brace …
> Fix ES Linting issues for leaderboard.js

- app/retail/templates/whitepaper_new.html
Fixing typo as pointed out by @vs77bb [here](https://gitcoincommunity.slack.com/files/U88M8173P/F9CKWGYE7/pasted_image_at_2018_02_21_02_39_pm.png)
- language :P
> text: fixed typo

- app/assets/legacy/v2/js/shared.js
- app/assets/v2/js/shared.js
Show a different message to local env users about which networks they can use. 
- [] linter status: 100% pass (not sure how to run it through the linter)
ui
Changes the text in the box. Locally it doesn't overflow the box and looks fine. 
Refers to https://github.com/gitcoinco/web/issues/465
> alert user to local env networks #465

- app/assets/v2/css/base.css
- app/assets/v2/css/leaderboard.css
- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/templates/bounty_details.html
- app/dashboard/templates/fulfill_bounty.html
- app/dashboard/templates/kill_bounty.html
- app/dashboard/templates/process_bounty.html
- app/dashboard/templates/profile_details.html
- app/dashboard/templates/submit_bounty.html
- app/dashboard/templates/toolbox.html
- app/dashboard/views.py
- app/retail/templates/leaderboard.html
- removed left panel in /profile, /toolbox, /new/funding
- replaces newletter and pushed it to the bottom
Fixes: https://github.com/gitcoinco/web/issues/411
> html: removed left rails

- app/assets/v2/js/tokens.js
- app/assets/yge/youvegoteth/tokens.js
- app/dashboard/tokens.py
Add Project Wyvern token (WYV) as a payment option for funding issues.
[Etherscan page](https://etherscan.io/address/wyverntoken.eth), [project website](https://projectwyvern.com), [token overview](https://token.projectwyvern.com).
This will enable the [Wyvern DAO](https://dao.projectwyvern.com) to fund bounties directly.
- dashboard
- crypto
Changes the same files as previous PRs, e.g. https://github.com/gitcoinco/web/pull/210.
Not applicable.
> Add Wyvern (WYV) token

- app/assets/v2/css/forms/select.css
- app/assets/v2/js/pages/new_bounty.js
- app/dashboard/templates/submit_bounty.html
We want to ensure selects have same dropdown elements. This also updates dropdown arrow to avoid jumpiness
UI
Pull down and test
Comment made my @PixelantDesign
> FIX: Replace selects with select2 and update arrow

- app/assets/v2/css/base.css
- app/assets/v2/css/current_balance.css
- app/assets/v2/css/dashboard.css
- app/assets/v2/css/external_bounties/checkboxes.css
- app/assets/v2/css/gitcoin.css
- app/assets/v2/css/search_bar.css
- app/assets/v2/css/sidebar_search.css
- app/assets/v2/css/tag.css
- app/assets/v2/js/base.js
- app/assets/v2/js/pages/dashboard.js
- app/assets/v2/js/shared.js
- app/dashboard/templates/bounty_details.html
- app/dashboard/templates/dashboard.html
- app/dashboard/templates/shared/current_balance.html
- app/dashboard/templates/shared/search_bar.html
- app/dashboard/templates/shared/sidebar_search.html
- Redo the explorer page
- Refactor html + CSS + JS
- Break down CSS + remove inline
- Enable filter by multiple options under the same category
- Update as per design 
- css
- html
- js
- https://github.com/gitcoinco/web/issues/503
- https://github.com/gitcoinco/web/issues/412
- https://github.com/gitcoinco/web/issues/494
> core:  Rebirth of the explorer

- app/assets/v2/css/dashboard.css
- app/assets/v2/css/search_bar.css
- app/assets/v2/images/comment.svg
- app/dashboard/templates/dashboard.html
- changed background to red if metmask is locked
- reduced border-radius for the search button
- added github comments icon
> review: added feedback for the explorer page

- app/assets/v2/js/pages/dashboard.js
Fixes clearing filters below the search bar -- #555
> Added remove filter functionality for Search Tags

- app/assets/v2/css/base.css
- app/dashboard/models.py
- app/dashboard/templates/profile_details.html
- app/dashboard/views.py
> show tips on leaderboard / profiles

- app/assets/v2/css/dashboard.css
- app/dashboard/templates/dashboard.html
Fixed up the CSS media queries to make sure nothing breaks and removed redundant code
This PR is to ensure that gitcoins most valuable user @mkosowsk has a pleasant experience in a device of any size :)
> css: refactored media queries

- app/gitcoinbot/views.py
The goal of this PR is to resolve https://rollbar.com/mbeacom/gitcoin/items/478/
gitcoin bot
Fixes #598
> Check dict existence in gitcoin bot payload view

- app/dashboard/models.py
slack notifications upon start / stop work
notifications
> slack notifications upon start / stop work

- app/assets/v2/css/base.css
- app/dashboard/templates/shared/status_tooltip.html
Updated tooltip as per review comments from @PixelantDesign  as given in https://github.com/gitcoinco/web/pull/585#issuecomment-372419795
- ui 
Refs: #585
> tooltip: updated as per review comments

- app/assets/v2/css/gitcoin.css
- app/dashboard/templates/shared/nav_auth.html
- refactored nav_auth.html
- replaced images with font-awesome
- redesigned css
- css 
- html
> nav: redesigned the dropdown

- app/assets/v2/css/gitcoin.css
@mbeacom Last fix for this! Sorry about this  😅
> css: dropdown fix

- app/assets/v2/css/dashboard.css
- app/assets/v2/css/search_bar.css
- app/assets/v2/js/pages/dashboard.js
- app/assets/v2/js/shared.js
- app/dashboard/templates/dashboard.html
- app/dashboard/templates/shared/search_bar.html
- app/dashboard/templates/shared/sidebar_search.html
- updated the #stats secition
- trimmed down the bounty summary text
https://github.com/gitcoinco/web/issues/601
> explorer: updated view

- package.json
As Readme said this project is adopting AGPLv3 license, which should reflect to `package.json` file
> use AGPLv3 license

- readme_runninglocally.md
Updated local setup path. Fixed the path 
- doc
> doc: corrected setup path

- app/assets/yge/youvegoteth/send.js
Fixes undefined message described in https://github.com/gitcoinco/web/issues/687
frontend
Sent a tip to see if message is displayed correctly.
Fixes #687
> Fixes: https://github.com/gitcoinco/web/issues/687

- app/assets/v2/css/base.css
- app/assets/v2/css/search_bar.css
• fixed broken save search UI
• fixed missing save search text on mobile
Fixes: #8
> fixed broken save search UI & missing save search text on mobile

- app/dashboard/templates/bounty_details.html
> html: reordered css links

- app/app/tests/test_app_urls.py
- app/app/urls.py
- app/assets/v2/css/bounty.css
- app/assets/v2/js/pages/bounty_details.js
- app/assets/v2/js/shared.js
- app/dashboard/models.py
- app/dashboard/templates/bounty_details.html
- app/dashboard/views.py
- app/marketing/mails.py
- app/marketing/management/commands/test_email.py
- app/retail/emails.py
- app/retail/templates/emails/bounty_uninterested.html
- app/retail/templates/emails/bounty_uninterested.txt
issue funder should be able to stop work
- Email
- UI
- Backend
Email notification send not tested.
Fixes: #463
> Issue funder can remove users from issue

- app/assets/v2/css/bounty.css
- app/assets/v2/js/pages/bounty_details.js
- app/assets/v2/js/shared.js
- app/dashboard/templates/bounty_details.html
- bounty
@mbeacom This is a better approach that we discussed yesterday :P 
@PixelantDesign
> bounty: display submit only on starting work

- docs/CONTRIBUTING.md
To keep new contributors aware of stylelint:fix.
> stylelint:fix info in CONTRIBUTING.md

- docs/RUNNING_LOCALLY_DOCKER.md
Guess who docker-ized his dev env?  this guy! 
this PR adds instructions on how to enable github login via docker
> docker / github login instructions

- app/assets/v2/css/bounty.css
- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/templates/bounty_details.html
I had all expired bounties which were state done -> so the progress bar never appeared on those 😅 
Fixed
---
Fixes: 
- #824
- #823
> bounty: hide progress bar on work done status

- app/assets/v2/css/base.css
- app/dashboard/templates/profile_details.html
profile view resuscitation
front-end
locally
Fixes: #817
> responsive profile

- app/assets/v2/css/bounty.css
- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/templates/bounty_details.html
Fixes: https://github.com/gitcoinco/web/issues/839
[screenshot](http://bits.owocki.com/2H09343B110o/Screen%20Shot%202018-04-09%20at%202.41.28%20PM.png)
> fix for Expired bounty invalid days ago counter

- app/marketing/tests/management/commands/test_expiration.py
> fix expiration tests

- app/marketing/tests/management/commands/test_expiration_start_work.py
Fix broken tests
backend tests
pytests
> expiration tests fix

- app/app/settings.py
https://github.com/gitcoinco/web/issues/876
> fixes https://github.com/gitcoinco/web/issues/876

- app/assets/v2/css/about.css
- app/assets/v2/css/base.css
- app/retail/templates/about.html
Fixed up the origin story section
-html
-css
> about: Fix Origin Story

- app/marketing/mails.py
- app/marketing/management/commands/bounty_feedback_email.py
- app/retail/emails.py
This PR sends an email asking for feedback to anyone who cancelled a bounty
email
tested
self
> more feedback emails

- app/assets/v2/js/pages/fulfill_bounty.js
- app/assets/v2/js/pages/increase_bounty.js
- app/assets/v2/js/pages/kill_bounty.js
- app/assets/v2/js/pages/new_bounty.js
- app/assets/v2/js/pages/process_bounty.js
- app/dashboard/models.py
unsupported network warnings when trying to do an aciton on a network we dont support
ui
tested it
self
> unsupported network warnings when trying to do an aciton on a network we dont support

- app/assets/v2/css/forms/input.css
- app/assets/v2/js/amounts.js
- app/assets/v2/js/pages/new_bounty.js
- app/dashboard/models.py
- app/dashboard/templates/increase_bounty.html
- app/dashboard/templates/submit_bounty.html
pricing brackets on the new bounty flow 
demo - http://bits.owocki.com/0U2C0M2h0G3j/Screen%20Recording%202018-04-25%20at%2010.52%20AM.mov
ui
i tested it 
https://github.com/gitcoinco/web/issues/21
> pricing brackets

- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/templates/bounty_details.html
[screenshot](http://bits.owocki.com/3E312o0V3a1a/Screen%20Shot%202018-04-26%20at%205.05.27%20PM.png)
> adds rates estimate on bounty details page

- app/app/settings.py
- app/marketing/management/commands/slackbot_welcome.py
- scripts/crontab
```
Welcome to Gitcoin! :gitcoin:
Gitcoin's mission is to *Grow Open Source*.
A few quick facts:
- We aren't an ICO.  There is no Gitcoin token.
- We are a community of blockchain developers.
- We are mission driven.  Check out our mission: https://gitcoin.co/mission
Here's how to get started in the community
- Say hey :wave: in #community-intros
- Join the community livestream every Friday at 5pm EST: https://gitcoin.co/livestream
We believe that a great way to build new skills is to learn by doing, and Gitcoin's core product (Bounties) supports that.
Here's how to get started with bounties:
- Check out the open bounties at https://gitcoin.co/explorer
- Post a bounty of your own at https://gitcoin.co/new
- Send a tip to any github username at https://gitcoin.co/tip
If you have any …
```
> slack welcome messages

- .gitignore
- app/assets/v2/css/bounty.css
- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/notifications.py
- app/dashboard/signals.py
- app/dashboard/templates/addinterest.html
- app/dashboard/utils.py
- app/retail/views.py
What
* fixes for https://gitcoincommunity.slack.com/archives/C8E45J5D0/p1525097521000711
* here is the issue that got screwed up in the first place
https://github.com/ethereum/solidity/issues/3965
How
* updates gitcoinbot comment to identify who has 'precedence' over an issue
* fixes some css issues with the 'start work' modal
* [Adds two checkboxes to the 'start work' modal](http://bits.owocki.com/31360K2N3u2C/Screen%20Shot%202018-04-30%20at%209.08.42%20AM.png)
> fixes for https://gitcoincommunity.slack.com/archives/C8E45J5D0/p1525097521000711

- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/templates/bounty_details.html
- app/dashboard/views.py
gives staff the ability to remove users from a bounty, so taht @vs77bb can remove ppl during his weekly issue explorer check ins
start / stop work
self
> gives staff the ability to remove users from a bounty

- app/dashboard/notifications.py
- app/marketing/management/commands/expiration_start_work.py
implements https://github.com/gitcoinco/web/issues/1040
github integration
easy copy changes
https://github.com/gitcoinco/web/issues/1040
> fixes https://github.com/gitcoinco/web/issues/1040

- app/dashboard/models.py
- app/dashboard/views.py
- app/marketing/management/commands/expiration_start_work.py
logs abandoned work and prevents users from starting new work bc of it
db, start work
tested it
https://github.com/gitcoinco/web/issues/1003
> logs abandoned work and prevents users from starting new work bc of it

- app/assets/v2/css/base.css
- app/assets/v2/css/forms/form.css
- app/assets/v2/css/forms/input.css
- app/dashboard/templates/shared/github_username.html
- app/dashboard/templates/submit_bounty.html
This PR addresses a few issues which me and @mbeacom came upon while fixing: 1056
---
---
- css 
- html
- https://github.com/gitcoinco/web/issues/1056
> css: funding / killing form update 

- app/assets/v2/js/pages/dashboard.js
Allow search by freeform text in the Issue Explorer
None
Fixes: #1046
> Fixed #1046

- app/assets/v2/js/pages/dashboard.js
Tech Stack filter failing due to special character.
Enclosing them in quotes fixes it
- js
- https://github.com/gitcoinco/web/issues/1078
> bugfix: tech stack filter fix

- app/assets/v2/css/help.css
Motivation - It is not visually obvious the questions listed on the [help page](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit) are clickable. 
Even though it is intuitive the user has to click on the question text to find the answer, changing the cursor to a pointer makes it visually clear.
> Change cursor of questions in help page to pointer

- app/dashboard/templates/shared/notification_email.html
makes email address optional in new bounties
new bounmty submit 
tested
https://github.com/gitcoinco/web/issues/1088
> makes email address optional in new bounties

- app/assets/v2/js/tokens.js
- app/assets/yge/youvegoteth/tokens.js
- app/dashboard/tokens.py
Adds Avocado token with symbol AVO.
https://etherscan.io/address/0xfa6f7881e52fdf912c4a285d78a3141b089ce859
**About Avocado Token**
On March 1st, 2018, 9000 CryptoKitties players were chosen at random to receive an airdrop of 100m AVO tokens each. The reasoning for this was because CK players were recognized as creative, innovative, and positive users of crypto. This action has been dubbed the world's first reverse-ICO, bringing people together for the purpose of community and collaboration. 
The community are now working together to build and create uses for AVO and we would like to use gitcoin to offer AVO token incentives for various projects. 
- dashboard
- crypto
> Add Avocado (AVO) token

- app/assets/v2/js/pages/bounty_details.js
- app/assets/v2/js/pages/dashboard.js
- app/assets/v2/js/pages/fulfill_bounty.js
- app/assets/v2/js/pages/increase_bounty.js
- app/assets/v2/js/pages/new_bounty.js
- app/assets/v2/js/pages/process_bounty.js
- app/assets/v2/js/shared.js
- app/assets/v2/js/toolbox.js
- app/assets/yge/redeem_coin.js
- app/assets/yge/youvegoteth/new.js
- app/assets/yge/youvegoteth/receive.js
- app/assets/yge/youvegoteth/send.js
- app/assets/yge/youvegoteth/web3alert.js
@mbeacom figured I'd fix this up, would make review a bit easier as folks who refer the existing code base would use it the way we want it to be used
- js
> js : added gettext across all alerts

- app/assets/yge/youvegoteth/receive.js
> bug: added button--primary to back to gitcoin button

- Makefile
- app/dataviz/d3_views.py
- app/dataviz/views.py
- requirements/test.txt
- setup.cfg
The goal of this PR is to introduce `yapf` for automatic python styling.  Additionally, the `dataviz` app has been automatically formatted with `yapf` to get us started.  We'll want to slowly migrate each django app over to yapf formatting to allow us to add the check to precommit/CI.
backend
Tested locally.
> Add yapf linting base and lint dataviz app

- app/assets/v2/js/tokens.js
- app/assets/yge/youvegoteth/tokens.js
- app/dashboard/tokens.py
Adds Unblocked Ledger Token with symbol ULT.
Etherscan Link: https://etherscan.io/token/0x09617f6fd6cf8a71278ec86e23bbab29c04353a7
Website: https://ulcproject.com/
The Unblocked Ledger project is building a peer-to-peer payment network that incorporates sharding and auto-scaling to provide high throughput, low latency, and immediate finality while maintaining the highest level of decentralization and security.
The supporting technology that allows for these features is our original Unblocked Consensus Algorithm, which is based on Proof-of-Quorum, in combination with our Unblocked Sharded Ledger system, which is a distributed ledger that addresses the problems of linear scaling and state sharding as the network grows.
For the development of this network, we will be issuing an ERC-20 token …
> add Unblocked Ledger Token (ULT)

- app/assets/v2/js/tokens.js
- app/assets/yge/youvegoteth/tokens.js
- app/dashboard/tokens.py
Add Livepeer Token (LPT) to the list of ERC20 tokens available for tipping.
- dashboard
- crypto
> Add Livepeer Token (LPT) for tipping

- app/assets/v2/css/bounty.css
- app/assets/v2/js/pages/bounty_details.js
Ugh i didn't check for images that were too large in height :|
thanks for pointing that out @mbeacom
> bug: set width to 100% on magnify

- app/app/settings.py
- app/dashboard/apps.py
- app/dashboard/signals.py
- requirements/base.txt
Adds cors headers, and conditionally allow all for GET requests of bounties.
https://github.com/gitcoinco/web/pull/1076
> Adds cors headers, and conditionally allow all for GET requests of bounties.

- app/retail/emails.py
> roundup! vivek's first PR

- app/dashboard/templates/shared/newsletter.html
- app/retail/templates/shared/mailchimp.html
GDPR -- Add info to our contact forms 
emails
tested it
fixes: https://github.com/gitcoinco/web/issues/1231
> GDPR -- Add info to our contact forms 

- app/enssubdomain/views.py
Implements UTS46 on the ENS module.  Otherwise someone with a unicode-containing Github username will get the wrong name on ENS
ENS
tested it
Self
> UTS46 ENS domain names

- app/assets/cookielaw/css/cookielaw.css
Cause I promised @mbeacom I'd work on this ^_^
- css
- https://github.com/gitcoinco/web/issues/1236
> css: update cookie styling

- app/assets/v2/css/base.css
- app/retail/templates/settings/account.html
- refactored code
- added modal + updated text
- unified modal css
- css
- html
- js
> settings: redid page

- app/assets/v2/css/dashboard.css
- app/assets/v2/css/onboard.css
- app/assets/v2/js/pages/dashboard.js
- app/assets/v2/js/pages/onboard.js
- app/dashboard/templates/_dashboard/ftux.html
- app/dashboard/templates/dashboard.html
- app/dashboard/templates/ftux/github.html
- app/dashboard/templates/ftux/metamask.html
- app/dashboard/templates/ftux/skills.html
- app/dashboard/templates/onboard.html
- Updated green banner
- Split code into small templates
- fixed a few minor bugs 
- js
- html
- css
Refs: #957
> onboard : autopopulate keywords for users

- app/retail/templates/settings/account.html
Updates text in deletion modal
Refs: #1243
> Updates text in deletion modal

- app/assets/v2/css/base.css
- app/assets/v2/css/forms/button.css
- app/retail/templates/settings/account.html
Improves the colors of the buttons
Refs: #1243
> Improves deletion confirmation modal button styling

- app/assets/v2/js/pages/dashboard.js
- app/dashboard/templates/dashboard.html
> css: fixed dashboard filter row

- app/assets/v2/css/current_balance.css
Fixes Upper right of the dashboard
> Fix: specify height of upper left only for submit bounty form

- app/dashboard/templates/yge/send2.html
send tip from github username, not just 'full name'
this will make life easier from a tracking perspective because everything is tied to github handles
screenshot -> http://bits.owocki.com/2S2N1D2b0O1i/Screen%20Shot%202018-05-28%20at%2011.29.56%20AM.png
tested it
self
> send tip from github username, not just 'full name'

- app/assets/v2/css/profile.css
- app/dashboard/models.py
- app/dashboard/router.py
- app/dashboard/templates/profile_details.html
org profiles
* Remove 'tips' section
* add all bounties that have been posted on that organization
* remove contributor/funder section up top, and instead add org_stats 
[screenshot](http://bits.owocki.com/1i3J3K2F3W2V/Screen%20Shot%202018-05-29%20at%204.52.42%20PM.png)
profiles
tested it
https://github.com/gitcoinco/web/issues/1292
> org profiles

- app/dashboard/templates/shared/newsletter.html
- app/retail/templates/shared/mailchimp.html
Fixes the email links in newsletter and mailchimp templates
Tested it.
Fixes #1320
> Fix email link in newsletter and mailchimp templates

- app/assets/v2/js/amounts.js
[screenshot](http://bits.owocki.com/0L0q0j0H2I3A/Screen%20Shot%202018-05-30%20at%201.48.48%20PM.png)
> show pricing guide on new bounty form

- app/marketing/webhookviews.py
disable sendgrid events until we figure out root cause of sendgrid db size issues
https://github.com/gitcoinco/web/issues/1278
> disable sendgrid events until we figure out root cause of db size issues

- docs/ENVIRONMENT_VARIABLES.md
Recognoized -> Recognized
Documentation
> Fix minor typo

- app/assets/v2/js/pages/new_bounty.js
- app/dashboard/helpers.py
- app/dashboard/models.py
- app/dashboard/tests/test_dashboard_models.py
- app/dashboard/tests/test_dashboard_utils.py
- app/dashboard/utils.py
- app/dashboard/views.py
- package-lock.json
The goal of this PR is to introduce extremely basic cleaning of the bounty vc/github URL on bounty save and in a few other places we are performing general checks on the associated URL.
For example, the bounty associated with: https://github.com/balance-io/balance-manager/issues/187 was created with a `#issuecomment` portion included and ultimately breaks our url lookup.
bounties
Local
> Clean hashbang from gh urls

- app/assets/v2/css/base.css
- app/assets/v2/css/dashboard.css
- app/assets/v2/css/gitcoin.css
- app/assets/v2/css/profile.css
- app/dashboard/templates/profile_details.html
- app/dashboard/templates/shared/profile_activities_bounty.html
- app/retail/templates/shared/result.html
So the new profile has a few bugs which needed a fix and along with that cam an update to the UI
**Issues:** 
- Bounties list weren't clickable 
- text overflows on smaller devices 
- random weird CSS classes 
- The bounties list shows one difficulty level and not other info 
- not using our default tooltips and stuff
- cs + html + js
Self tested but need to verify on staging once with more profiles
> profile : revamp

- app/assets/v2/js/pages/bounty_details.js
- app/assets/v2/js/shared.js
- removed filter code as the filter options are no longer
shown on bounty_detail page
- removed attach_close_button in shared as it's not being
used anywhere
- removed sidebar_redirect_triggers in shared as the sidebar
filter are using only in the explorer
- moved custom input type function before document entirely
loads to ensure fields appear on devices with slow internet
connection
- js 
Tested it myself but would like to be tested once more
@SaptakS @mbeacom 
@vs77bb this ensure that the input fields appear along with the other firlds
> shared: refactored + removed dead code

- app/dashboard/templates/shared/no_issue_error.html
> Corrects lightbulb image name

- app/retail/templates/shared/nav.html
Adds new funding link in the navbar of the landing page
> Adds funding link in the navbar for landing page

- app/retail/templates/about.html
Profile link to open in same tab. 😓
> Open gitcoin profile links on the same tab

- app/assets/v2/css/landing_page.css
- app/retail/templates/index.html
- app/retail/templates/shared/nav.html
> Fix: return of login

- app/assets/v2/css/gitcoin.css
- app/assets/v2/css/landing_page.css
- app/assets/v2/css/newsletter.css
- app/dashboard/templates/shared/nav_auth.html
- app/retail/templates/base.html
- app/retail/templates/index.html
- app/retail/templates/shared/nav.html
- app/retail/templates/slack.html
- updated green banner
- updated font on mobile
- fixed padding & margin stuff breaking on mobile
- removed weird planet from navbar 
- css
> landing : updated mobile design

- app/retail/templates/index.html
> Add space between not and have

- app/retail/templates/shared/hero.html
Updates 'Join Gitcoin Slack' CTA link from `/tools` to `/slack`
> Update slack CTA link

- app/assets/v2/js/tokens.js
Replace arrow functions with traditional functions as older browsers don't understand ES6.
Fixes #1423
> Replace arrow functions with traditional functions

- app/assets/v2/js/landing_page.js
- app/assets/yge/youvegoteth/pre.js
- app/dashboard/templates/quickstart.html
Cause we serve the dark lord and he asked us to checkout rollbar issues :P 
Reason for bug : 
Fixes: https://github.com/gitcoinco/web/issues/1398
Not sure but this might fix https://github.com/gitcoinco/web/issues/1395
Not sure how to test it out 🤔
> rollbar : quickstart

- app/assets/v2/css/card.css
- app/assets/v2/css/ios.css
- app/dashboard/templates/ios.html
- Fixed up the ios page
- mobile +  tablet responsive
- enabled stylelint & fixed up the errors
- html + css
- https://github.com/gitcoinco/web/issues/1430
> ios: updated css + refactored

- app/dashboard/templates/shared/yge_auth.html
Loads font awesome css file in the ENS page, thereby fixing the black circle issue.
UI
Manually tested
Fixes #1353 
/cc @owocki
> Fix font awesome loading in ENS page

- app/faucet/views.py
Please recommend if there is a better way to convert gwei to ETH.
Fixes: https://github.com/gitcoinco/web/issues/1341
> Added the gas amount to the right place

- app/assets/yge/css/main.css
- app/dashboard/templates/ens/base.html
Update pull request link hover color on ENS page
UI
> Change pull request link hover color

- app/gitcoinbot/management/commands/get_notifications.py
The gitcoinbot currently reacts with a heart emoji and a comment asking the maintainer to install gitcoinbot on the repo. The PR retains the heart emoji reaction and removes the comment.
Fixes #1498
> Remove bot's response to repos missing @gitcoinbot

- app/retail/templates/about.html
Product Developer role on the [about](https://gitcoin.co/about) page links to a careers page for a front end developer position. The PR updates the position on the about page.
/cc @owocki
> Update open gitcoin role on about page 

- app/dashboard/templates/profile_details.html
- app/dashboard/templatetags/add_url_schema.py
- app/dashboard/templatetags/clean_url.py
Adds URL scheme to user's personal URL from github if not present. Also opens the github link and personal URL in a new tab.
Tested, _manually_
Fixes #1505
> Clean up user's personal URL from github

- app/assets/v2/css/onboard.css
- app/assets/v2/js/pages/onboard.js
Show the buttons properly in the standalone avatar page. Also fixed their working
> Fix buttons in standalone avatar page

- app/retail/templates/results.html
> Fix malformed HTML

- app/assets/v2/js/pages/wallet_estimate.js
Fixes check for fast gas to include gas price and slow time
> Check for slow instead of fast

- app/assets/v2/js/pages/wallet_estimate.js
Gas price on changing and clicking on recommendation is fixed.
> Fix gasPrice on changing recommendation

- app/assets/v2/css/base.css
- app/assets/v2/css/profile.css
- app/dashboard/templates/profile_details.html
- Make issues on the issue explorer and gitcoin profile circular.
- Add bottom border to profile sections.
UI
I did, _manually_
Fixes #1478
> WIP: Make funder icons circular

- app/assets/ens/pending.js
- app/assets/v2/js/shared.js
- app/assets/yge/youvegoteth/index.js
Refactor `switch` statements with an object in finding the network.
> Refactor getNetwork code

- app/assets/v2/css/avatar_builder.css
- app/assets/v2/css/onboard.css
- app/assets/v2/js/pages/onboard.js
- app/dashboard/templates/_dashboard/ftux.html
- app/dashboard/templates/ftux/avatar.html
- app/dashboard/templates/ftux/onboard.html
- app/dashboard/templates/ftux/skills.html
- Change range of years to <3, 4-7, 7+
- show avatar on nav for logged in user
- remove previous button on first screen
- move prev button to the right
- move skip button to the top right
- https://github.com/gitcoinco/web/issues/1516
- https://github.com/gitcoinco/web/issues/1527
> ftux : further changes

- app/assets/v2/js/pages/dashboard.js
Fixes `Error: cannot call methods on selectmenu prior to initialization; attempted to call method 'refresh' ` issue.
For more info, check [Rollbar](https://rollbar.com/gitcoin/gitcoin/items/1382/)
> Fix selectmenu initialization issue

- app/assets/v2/css/base.css
- app/dashboard/templates/bounty_details.html
- app/retail/templates/shared/nav.html
- admin button: udpated color
- show how it works on explorer only
- fixed html template for admin button with no id
- css + html
> minor changes: added 

- app/assets/v2/js/avatar_builder.js
Fixes issue in firefox for avatar builder.
> Fix localstorage issue  in firefox

- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/templates/bounty_details.html
- css
-  https://github.com/gitcoinco/web/issues/1511
@mbeacom got a better way to do this ? 🤔
> all admin actions are in a new line

- app/retail/templates/settings/feedback.html
- app/retail/templates/settings/matching.html
- app/retail/templates/settings/slack.html
- app/retail/templates/settings/tokens.html
Fixes: https://github.com/gitcoinco/web/issues/1561
> text: Go -> Save

- app/assets/v2/css/landing_page.css
- app/assets/v2/js/landing_page.js
- app/retail/templates/index.html
- app/retail/templates/shared/tree.html
Replaced tree with svg animation
@mbeacom @SaptakS ENJOY :P
- html + css + js
-  #1462
> landing : added growing tree svg

- app/retail/templates/shared/nav.html
The goal of this PR is to display the "How It Works" nav items everywhere the standard nav is displayed with the exception of the index page.
ui, nav
Locally
> Display how it works everywhere except index page

- app/dashboard/templates/shared/nav_auth.html
Update icon to `ethereum `
Refs: https://github.com/gitcoinco/web/issues/1568
> refs: https://github.com/gitcoinco/web/issues/1568

- app/assets/v2/js/pages/bounty_details.js
Add link to the issue URL in the confirmation page
> Add link to the issue URL in the confirmation page

- app/assets/v2/js/shared.js
- Removed weird `;` in the alert box
- Fixed up positions when multiple alert boxes are present
> fixed alerts

- app/retail/templates/shared/footer.html
Add results to the footer
footer (html)
> Adds results link to the footer

- app/assets/yge/youvegoteth/send.js
- app/retail/templates/shared/nav.html
since i dont think ppl can find it in the current nav https://gitcoincommunity.slack.com/archives/C8E45J5D0/p1530502668000111
> adds help link to how it works dropdown

- app/assets/v2/css/base.css
- app/assets/v2/js/pages/wallet_estimate.js
- app/dashboard/templates/shared/wallet_estimate.html
Fixes following:
- there is bleed on the left side of the 'gas amount' module into the right amount
- the rounding issue .. it says $0 but should be rounded to the cent (0.00) amount
html + css + js
gas settings
Fixes #1580
> Fix gas price settings css

- app/retail/templates/emails/bounty.html
- app/retail/templates/emails/bounty_roundup.html
- app/retail/templates/emails/template.html
> email: reindent + update css

- app/dashboard/notifications.py
Updates the notification messages posted to `#notif-gitcoin` channel in the slack team.
Notifications
I am unsure how to test it. I tried to create a test bounty on rinkeby locally and print the message but couldn't find the desired output. I did comment out lines 172-173 to make sure the message is built. Not sure what I am missing. Would really appreciate if anyone could help me test this out.
Fixes #1507
> Update slack notification format

- app/dashboard/templates/bounty_details.html
- app/dashboard/templates/dashboard.html
- app/dashboard/templates/fulfill_bounty.html
- app/dashboard/templates/kill_bounty.html
- app/dashboard/templates/process_bounty.html
Removes references to `shared.js` as it is already being included in `footer_scripts.html`
/cc @thelostone-mc
> Remove duplicate script tags

- app/assets/v2/js/base.js
> Fix - #1593

- app/dashboard/notifications.py
Bounty worth -> Bounty value
/cc @PixelantDesign
> Replace 'worth' with 'value'

- app/assets/v2/js/pages/wallet_estimate.js
Fixed gas settings
Fixed gas price.
> Fix gas settings

- app/app/context.py
- app/app/settings.py
- app/retail/templates/shared/head.html
The goal of this PR is to introduce [Hotjar](https://www.hotjar.com/) for heat maps, click tracking, feedback loops, surveys, session tracking, etc.
ui
Locally
> Add Hotjar

- app/retail/templates/whitepaper_new.html
Fix one misplaced 'endblock'.
Fixes #1641
> Fix: White paper page isn't responsive and rendering is off

- app/assets/v2/js/shared.js
- app/retail/templates/settings/tokens.html
> Change 'not enabled this token'-banner color to orange.

- app/assets/v2/js/base.js
- app/assets/v2/js/pages/gas.js
- app/assets/v2/js/pages/shared_bounty_mutation_estimate_gas.js
- app/assets/yge/youvegoteth/receive.js
- app/dashboard/views.py
- app/retail/templates/gas.html
This is a gas estimation calculator for the /gas page, so one can see the estimates of how much it costs to do certain actions on gitcoin at today's gas prices.
here is a demo:
gas / eth
tested it
self
> gas estimation calculator on gas page

- app/retail/templates/shared/analytics.html
bc we already have your email if ur logged in
> no sumo popup if logged in

- app/assets/v2/js/pages/increase_bounty.js
- app/assets/v2/js/pages/new_bounty.js
Passes the alert type `error` to error alerts.
UI
Fixes #1692
> Fix alerts without types

- app/assets/onepager/css/main.css
onepages: updated to Muli & letter-spacing
> onepages: updated to Muli & letter-spacing

- app/dashboard/templates/shared/wallet_estimate.html
Fixes: https://github.com/gitcoinco/web/issues/1665
I wasn't able to reproduce the bug locally, but cross-working with devtools and local files it seems to be alright. Please review.
> Bug - Misaligned Css On The Acceptance Page #1665

- app/assets/v2/css/quickstart.css
> Fix image alignment on /bounty/quickstart

- app/assets/v2/js/pages/bulk_payout.js
Fix linter errors that sprung up after running `eslint`. Besides simple syntax fixes, I renamed the local variable in the for loop to use `j` as opposed to the global `var i` which was already declared. 
Fixes all the other PRs that had this broken in Travis. like #1756
> fixed linter errors. assigned new variable in for loop.

- app/retail/templates/contributor_landing.html
- app/retail/templates/shared/analytics.html
Add google optimize to the analytics module
Analytics
> Adds google optimize to contributor landing page

- app/dashboard/templates/submit_bounty.html
Since issue title and issue description are fetched from github, we are disabling editing of the title and description to maintain consistency.
Funder form
#1588
> Disables editing of the issue title and description

- app/dashboard/tip_views.py
The goal of this PR is to remove unused imports and variables, remove duplicate card dict key, 257 the docstrings, and resolve bare exceptions.
tips
Locally
> General lint/cleanup of tip views

- app/dashboard/templates/submit_bounty.html
Replace disabled with readonly.
Refs: #1588
> Replace disabled attribute with readonly for title and desc

- app/assets/v2/js/pages/shared_bounty_mutation_estimate_gas.js
Fixes the error in the bulk payout page where gasLimit came to be 0.
Gas Settings for bulk payout page fixed
> Adds gasLimitEstimate for bulk payout

- app/assets/v2/js/pages/bounty_details.js
- app/assets/v2/js/pages/dashboard.js
> Remove soft-expired logic from user interface.

- app/assets/onepager/css/main.css
Fix missing ckeck icon 
Interface
> Fix checkbox icon

- app/dashboard/templates/bulk_payout_bounty.html
- app/dashboard/templates/fulfill_bounty.html
- app/dashboard/templates/increase_bounty.html
- app/dashboard/templates/kill_bounty.html
- app/dashboard/templates/process_bounty.html
- app/dashboard/templates/submit_bounty.html
> dashboard/templates: Add 'required' attribute to all 'terms' checkboxes

- app/assets/v2/css/landing_page.css
- app/retail/templates/landing/contributor/hero.html
http://bits.owocki.com/073R1X1Z2e3P/Screen%20Recording%202018-07-25%20at%2011.11%20AM.gif
on the prod landing page the laptop on the right is stretched in wide screens..  this fixes that.
tested responsive
> fix for stretched laptop on contributor landing page

- app/assets/v2/css/bounty.css
- app/assets/v2/js/pages/bounty_details.js
- app/assets/v2/js/shared.js
>  Fix markdown of html tags in issue description

- app/retail/templates/index.html
- app/retail/templates/landing/contributor/activity.html
- app/retail/views.py
adds recent activity on funder landing page so ppl can see how active the site is
also a little cleanup from last PR
ui
tested it 
https://github.com/gitcoinco/web/pull/1828
> adds recent activity on funder landing page  so ppl can see how active the site is

- app/assets/v2/css/landing_page.css
- app/retail/templates/contributor_landing.html
- app/retail/templates/landing/contributor/activity.html
- app/retail/templates/shared/activity.html
- css is now responsive
- code refactor
- removed weird green banner
- UI
- https://github.com/gitcoinco/web/pull/1831
> contributor page: css updates

- app/dashboard/templates/onepager/receive_legacy.html
This PR solves the missing gif :
> change name of missing image

- app/retail/templates/presskit.html
The goal of this PR is to update the presskit copy to the copy requested by @PixelantDesign 
presskit, frontend
Locally
> Update the presskit copy

- app/assets/v2/js/pages/dashboard.js
- app/dashboard/templates/shared/sidebar_search.html
Removing tech-stack filter as this is not being used 
- https://github.com/gitcoinco/web/issues/1868
> dashboard: remove tech stack filter

- app/dashboard/management/commands/sync_geth.py
- scripts/crontab
sync geth stopgap fix, syncs the latest 10 bounties every 3 minutes.  
this is because users keep complaining that their changes dont sync fast enough, and we haven't yet figured out whats' wrong with sync_listener
sync_geth
tested it
slack help requests
> sync geth stopgap fix

- app/locale/hi/LC_MESSAGES/django.po
- app/locale/hi/LC_MESSAGES/djangojs.po
Made changes to improve auto-translation of gitcoin to hindi.
Fixes #1844
> Confirming Auto-translation

- app/app/urls.py
Refs: https://github.com/gitcoinco/web/issues/1273#issuecomment-410134814
> allow trailing slsah for profile

- app/assets/v2/css/landing_page.css
- app/retail/templates/shared/what_is_gitcoin.html
As discussed in https://github.com/gitcoinco/web/pull/1927#issuecomment-411029469
> what_is_gitcoin : revert to old design

- app/dashboard/models.py
The goal of this PR is to resolve #1934 by filtering `Bounty` results to only bounties that have active funding or funding has been dispersed.
profile, quarterly stats emails
Locally
Fixes #1934
> Fix #1934 - Resolve cancelled funds appearing in profile total

- CHANGELOG.md
- app/assets/v2/css/base.css
- app/assets/v2/js/pages/increase_bounty.js
- app/assets/v2/js/pages/new_bounty.js
- app/assets/v2/js/pages/tokens_settings.js
- app/assets/v2/js/shared.js
- app/assets/v2/js/tokens.js
- app/dashboard/templates/bounty/increase.html
- app/dashboard/templates/shared/pricing.html
- app/retail/templates/settings/tokens.html
Remove the distraction and slight embarrassment of having a misspelled finance-related word appear 18 times in the project.
n/a 
It's a superficial change.
n/a
> replaced misspelled 'deonomination' with 'denomination' 

- app/assets/v2/js/pages/dashboard.js
Cleans up extra `&` and removed `filter keys` when no value is selected
Before
After
> uri : cleanup

- app/retail/emails.py
- app/retail/templates/emails/bounty_roundup.html
adds leaderboard to weekly roundup
tested it
> leaderboard on weekly roundup

- app/assets/v2/js/pages/bounty_details.js
- Clears example action plan when the textarea is focused
- Fixes a minor typo (Netflify -> Netlify)
Fixes #1852
> Minor tweaks to action plan textarea

- app/assets/v2/css/bounty.css
- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/templates/addinterest.html
Bounty start work - replace text placeholder
> start work : update placeholder

- app/dashboard/router.py
- https://github.com/gitcoinco/web/pull/1925
> api: fixed offset param in explorer

- app/retail/emails.py
> newsletter 8/17

- app/assets/v2/css/gitcoin.css
- app/retail/templates/landing/contributor/hero.html
- app/retail/templates/shared/hero.html
Remove un-needed tags and fix up html
- html
- #1868
> refactor: remove unneeded html tag

- app/dashboard/templates/shared/search_bar.html
Removing dead html code which I forgot to take off from the dashboard
> dashboard: remove save search link

- app/assets/v2/js/pages/dashboard.js
- app/dashboard/templates/shared/sidebar_search.html
This PR does the following  - 
- Enables applied filters to be reflected on the URL
- Refactor code ( rename  + remove dead code)
- remove the extra `Any` filters 
How it works: 
- /explorer defaults to mainnet + localStorage applied filters
- adding filters updates the URL with filters
- visting URL with filters attached -> resets localStorage 
and stores updates the filters from the URL onto the localStorage
Note: @mbeacom I haven't removed the network filter cause hotjar did show a few folks using it on live
we could wait for a month and see -> and then remove it if needed 
- js
- https://github.com/gitcoinco/web/issues/1791
> dashboard: enable deep link of search 

- app/assets/v2/css/gitcoin.css
Fixes navbar in pages like dashboard, new funder etc with a narrower navbar to allow overflow, unlike the ones with the rain
dropdowns, navbar
> Fixes navbars with dash class, the narrow navbars

- app/assets/v2/css/base.css
- app/assets/v2/js/shared.js
Full-page loading animation to let the user know something is happening.
Fixes/Related #2032
> shared.js: Add {show,hide}BusyOverlay

- app/assets/v2/js/pages/wallet_estimate.js
> eslint : lint fixes

- app/dashboard/templates/ens/base.html
- app/dataviz/templates/dataviz/circles.html
- app/dataviz/templates/dataviz/draggable.html
- app/dataviz/templates/dataviz/heatmap.html
- app/dataviz/templates/dataviz/scatterplot_stripped.html
- app/dataviz/templates/dataviz/spiral.html
- app/dataviz/templates/dataviz/sunburst.html
- app/gas/management/commands/output_gas_viz.py
- app/retail/templates/gas.html
The goal of this PR is to replace hardcoded `/static/` references throughout the graph and gas html files and formatting the modified HTML to follow formatting/linting.
graphs, gas, static
Locally
Extension of:  https://github.com/gitcoinco/web/commit/ad3bba82967bf64fbb0bbd556e6cebeb699e2e44
> Update static references to replace hardcoded graph and gas static references

- app/retail/emails.py
@owocki pls review. feel free to make any edits inline!
> newsletter 8/24

- app/assets/v2/js/pages/new_bounty.js
screencast: http://bits.owocki.com/81f4e7e8febb/Screen%20Recording%202018-08-23%20at%2003.10%20PM.gif
ref: https://gitcoincore.slack.com/archives/CAXQ7PT60/p1535056555000100
> warns user if they try to bounty something but dont have enough tokens

- app/assets/v2/js/pages/bounty_details.js
https://github.com/gitcoinco/web/commit/32ffd842eca809bd226c5f0f4b8443d93e146847
> eslint: fix

- app/assets/v2/css/bounty.css
- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/templates/bounty/details.html
- app/dashboard/templates/bulk_payout_bounty.html
- app/dashboard/templates/shared/success_container.html
For crowdfunded bounties: 
https://github.com/gitcoinco/web/issues/2072
> bounty: crowdfunded bounties

- app/retail/templates/cookielaw/banner.html
Update the text for cookie law banner
Fixes #2122
> Update text for cookielaw

- app/assets/v2/js/pages/bounty_details.js
- Checks if logged in user has already fulfilled bounty & hides submit button
- remove dead code
- bounty actions 
- https://github.com/gitcoinco/web/issues/2118
> bounty: enable submit only once per user

- .github/PULL_REQUEST_TEMPLATE.md
A description on -> A description _of_
> Fix minor grammatical issue

- app/assets/v2/css/bounty.css
- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/templates/bounty/details.html
- Moves moderator and admin actions out of bounty details info and makes it sticky on scroll
UI
Fixes #2045
> Isolate moderator and admin actions for ease of usability

- app/dashboard/templates/bounty/details.html
As discussed [here](https://github.com/gitcoinco/web/commit/62139a076208113408c642105d994afc476eeff0#r30356134)
> show accept/reject bounty in permissioned bounty

- app/assets/v2/css/base.css
Fixes: https://github.com/gitcoinco/Marketing/issues/1
Fixes: https://github.com/gitcoinco/Marketing/issues/2
> landing: reduce size of title on mobile

- app/app/settings.py
- app/locale/ja/LC_MESSAGES/django.po
- app/locale/ja/LC_MESSAGES/djangojs.po
Fixes #1863 
Enables Auto-translation to Japanese
> Auto-Translation to Japanese #1863

- app/assets/v2/js/pages/bounty_details.js
> crowdfunded: bug fix

- app/retail/emails.py
The goal of this PR is to update the roundup email copy/bounty references for the week of 2-8SEP2018.
Locally
> Roundup email updates for 7SEP2018

- app/assets/v2/css/gitcoin.css
- app/retail/templates/shared/nav.html
Fixes: https://github.com/gitcoinco/web/issues/2177
> navbar: fix tablet friendly

- docs/CONTRIBUTING.md
proposed gitcoin contribution monetary policy
per discussion in #product-gitcoin channel on slack
> proposed gitcoin contribution monetary policy

- app/retail/emails.py
The goal of this PR is to update the weekly roundup email per @vs77bb's provided copy changes.
Locally
> Weekly Roundup - 14SEP2018

- app/manage.py
- bin/docker-command.bash
- docker-compose.yml
- docs/CONTRIBUTING.md
- docs/ENVIRONMENT_VARIABLES.md
The goal of this PR is to add vscode remote debugging support (optional) and necessary setup documentation.
Locally
> Add VSCode remote debugging handling and documentation

- app/retail/emails.py
The goal of this PR is to update the `weekly roundup` email for the week of 21SEP2018.
Copy provided by @vs77bb 
Locally - Currently breaking on local (debugging in process)
> Update roundup email for 21SEP2018

- app/assets/v2/js/user-search.js
Fix wrong box position when select 2 render first time
> Fix box position bug in select2

- docs/ENVIRONMENT_VARIABLES.md
- docs/THIRD_PARTY_SETUP.md
updates documentation 
* removes ETHOS
* adds SendGrid documentation to third party integration guide and environment variables docs
> updates documentation

- app/dashboard/templates/bounty/new.html
The issue title in the funder form is now made as a required field. So in case if there is some time gap between the sync and the creation of bounty, then it will throw an error instead of going on with the creation of bounty.
This prevents blank fields going to the IPFS and maintain the title.
> Makes the issue title a required field in new funding

- app/retail/emails.py
The goal of this PR is to update the `marketing/emails.py@render_new_bounty_roundup` email for the week of 28 September 2018.
Locally
> Update roundup email for 28SEP2018

- app/app/pipeline.py
- app/app/utils.py
- app/dashboard/helpers.py
- app/dashboard/models.py
- app/git/utils.py
The goal of this PR is to resolve github api throttling by offloading user generated requests to the profile access token.
github, new funding, issue details, profile
Locally
Ref #2600
> Adjust issue_details to use profile access token

- app/app/context.py
- app/app/templates/shared/document_user.html
- app/app/urls.py
- app/assets/v2/js/pages/bounty_details.js
- app/assets/v2/js/shared.js
- app/dashboard/helpers.py
- app/dashboard/templates/bounty/details.html
- app/dashboard/templates/bounty/new.html
The goal of this PR is to resolve a context issue with issue_details by passing the token to the endpoint directly.  Additionally, this PR establishes the `document_user.html` django template for defining user specific variables for FE (access_token, username, etc) and moves `isStaff` to `isModerator` to the currentProfile object.
issue_details, funding, profile
Locally
> Adjust issue details token handling and move user specs to currentProfile

- app/assets/v2/js/pages/bounty_details.js
Hides start work button if you are the funder 
Fixes: https://github.com/gitcoinco/web/issues/2308
> bounty: hide start + submit work for funder

- app/assets/v2/css/profile.css
- app/assets/v2/css/tabs.css
- app/assets/v2/js/pages/tabs.js
- app/dashboard/models.py
- app/dashboard/templates/profiles/profile.html
- app/dashboard/templates/shared/profile_activities_bounty.html
- app/retail/templates/ui_inventory.html
Refactor profile page to show all activities in tabular format.
Fixes #2077
> Refactor profile page

- .travis.yml
- app/app/travis.env
The goal of this PR is to pull down and configure the necessary database files and dependencies to ensure location lookup by IP works correctly.
travis, ci
Locally, Travis
> Adjust Travis config to handle GeoIP dbs

- app/dashboard/models.py
- app/dashboard/templates/profiles/profile.html
> re-enables org profiles

- app/retail/emails.py
The goal of this PR is to update the weekly roundup email copy and bounty references for the week of 5 October 2018.
Locally
> Update roundup email for 5OCT2018

- app/assets/v2/js/pages/bulk_payout.js
- app/dashboard/templates/bulk_payout_bounty.html
- Ensure `tr` tag is placed inside `table` element
- code clean up
- ensure that `update_registry` is invoked when autcomplete is updated 
fixes: https://github.com/gitcoinco/web/issues/2380
Need an extra pair of eyes on testing this out
> bug: advanced payout

- app/retail/templates/landing/contributor.html
Fixes: https://github.com/gitcoinco/Marketing/issues/11
> landing: contributor page

- app/dashboard/templates/onepager/send2.html
Fixes #2410 
cc: @PixelantDesign @thelostone-mc
> CSS changes to tooltip hover in tips

- app/assets/v2/css/dashboard.css
- app/dashboard/templates/dashboard/index.html
> Bounty row layout fix(es)

- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/templates/bounty/details.html
See https://github.com/gitcoinco/web/issues/2406.
Not affected.
Fixes https://github.com/gitcoinco/web/issues/2406
> fixed button alignment on bounty page

- app/assets/v2/css/grants/new.css
- app/assets/v2/js/grants/new.js
- app/grants/templates/grants/new.html
- app/grants/views.py
- custom css for search fields
- removed redundant `console.log` 
- ensure that team-members is passed on to backend
> refactor grants/new

- app/grants/templates/grants/grant_card.html
- app/grants/templates/grants/new.html
Minor fixes related to default logo
> Makes minor fixes with logo and copies

- app/grants/templates/grants/index.html
> Makes home page responsive

- app/assets/v2/css/grants/grant.css
- app/assets/v2/css/grants/new.css
- app/assets/v2/js/grants/index.js
- app/grants/templates/grants/detail.html
- app/grants/templates/grants/grant_card.html
- app/grants/templates/grants/index.html
- fixed sort by css to match explorer
- css clean up + responsive design
- fixed up cards css
- re-indent shit
> grants/index: css update

- app/assets/v2/css/base.css
- app/assets/v2/css/bounty.css
- app/assets/v2/js/grants/new.js
- app/assets/v2/js/pages/bounty_details.js
- app/assets/v2/js/shared.js
- app/grants/templates/grants/new.html
Add the waiting screen like the one that we get on bounty creation.
> Waiting screen on grants creation

- app/assets/v2/css/grants/detail.css
- app/assets/v2/css/grants/milestones.css
- app/assets/v2/css/grants/new.css
- app/assets/v2/js/grants/milestones.js
- app/grants/forms.py
- app/grants/migrations/0001_initial.py
- app/grants/models.py
- app/grants/templates/grants/detail.html
- app/grants/templates/grants/milestones.html
- app/grants/templates/grants/new.html
- app/grants/urls.py
- app/grants/views.py
- app/retail/templates/shared/head.html
WIP - Add Milestones to Grants
**Working from this mock up:**
**This branch adds the following:
(before milestones have been added)**
**(the form to add milestones)**
**(adding milestones)**
**(grant with milestones)**
TODO
> Add Milestones to Grants

- app/assets/v2/css/grants/detail.css
- app/assets/v2/css/grants/new.css
- app/assets/v2/js/grants/detail.js
- app/grants/templates/grants/detail.html
- app/retail/templates/shared/head.html
- adds dummy edit to name & description 
- TODO: fire API to save data
> grants/admin: base setup

- app/assets/v2/css/grants/detail.css
- app/assets/v2/css/grants/fund.css
- app/assets/v2/css/grants/grant.css
- app/grants/templates/grants/detail.html
- app/grants/templates/grants/fund.html
- app/retail/templates/shared/head.html
- mobile friendly
- refactor
- remove dead code
> grants/fund : refactor

- app/assets/v2/css/grants/detail.css
- app/assets/v2/css/grants/grant.css
- app/assets/v2/js/grants/detail.js
- app/grants/templates/grants/detail.html
- added team members
- fixed up supported by
>  grant/detail: updated UI

- app/assets/v2/js/grants/detail.js
- app/assets/v2/js/grants/new.js
- app/grants/templates/grants/detail.html
- app/grants/urls.py
- app/grants/views.py
refactored routes to be restful
> refactored routes to be restful

- app/grants/templates/grants/cancel.html
- app/grants/views.py
> Cancel view clean up

- app/assets/v2/css/grants/fund.css
- app/assets/v2/css/grants/new.css
- app/grants/templates/grants/fund.html
- app/grants/templates/grants/new.html
Implemented warning label on 'new' and 'fund' with style given by KO
> Implemented warning label on 'new' and 'fund' with style given by KO

- app/grants/views.py
> Changes for cancel view PR

- app/grants/templates/grants/profile.html
- app/grants/views.py
changed 'supported by me' tab in grants/profile to display grants I support instead of grants 'created by me'
> My Grants - 'Supported by me' tab

- .github/PULL_REQUEST_TEMPLATE.md
Fix the broken URL to contribution document in pull request template.
[X] Template change - no code modification(s)
github
Create PR, see change.
Fixes: #2529 - https://github.com/gitcoinco/web/issues/2529
> #2529 - Fix broken URL in GitHub Pull Request Template

- Dockerfile
- app/app/urls.py
- app/assets/v2/js/grants_index.js
- app/assets/v2/js/pages/process_bounty.js
- app/dashboard/templates/grants_index.html
- app/dashboard/views.py
> Grants dummy

- app/assets/v2/css/quickstart.css
Fixed styles in video modal 
Fixes: #2521
> apply styles just for video modal

- app/dashboard/management/commands/activity_report.py
The goal of this PR is to resolve the python deprecation warning on `GITHUB_REPO_PATTERN`.
backend, activity reports
Locally
> Resolve regex deprecation warning in activity_report

- app/kudos/models.py
- app/retail/templates/emails/new_kudos.html
- fix kudos png sizes and quality
- fix new kudos email
Fixes: #2708
#2726
> [WIP] Fix email new kudos

- Makefile
- app/assets/v2/js/grants/cancel_subscription.js
- app/assets/v2/js/grants/fund_grant.js
- app/assets/v2/js/grants/new.js
- app/grants/models.py
- app/grants/templates/grants/fund.html
- app/grants/templates/grants/new.html
- app/grants/views.py
Fixes token drop downs, period_seconds selectors, and gasPrice issues
> Rinkeby fixes

- app/app/urls.py
- app/dashboard/gas_views.py
- app/dashboard/management/commands/cleanup_db_space.py
- app/dashboard/templates/shared/gas_nav.html
- app/gas/utils.py
- app/retail/management/commands/warm_cache.py
- app/retail/templates/gas_heatmap.html
Added heatmap view for gas prices as per issue #2733 
Fixes #2733
> Gas Heatmap (WIP)

- app/dashboard/notifications.py
make the bot text friendlier 
- https://github.com/gitcoinco/web/issues/2758
> bot: warning -> reminder

- app/app/settings.py
- requirements/base.txt
The goal of this PR is to implement direct CW logging for prod
Logging
Locally
> Adjust django logging to output to CW

- app/faucet/templates/shared/faucet_over_balance_error.html
Donations! Donations! Free donations!
> Donating a missing </div> to unbreak faucet

- app/assets/v2/js/pages/dashboard.js
- app/marketing/tests/management/commands/test_assemble_leaderboards.py
This PR aims to fix the currently-failing test with profile uniqueness 
Marketing
#2736
> Tear down profiles after each test

- app/grants/templates/grants/detail.html
- app/grants/views.py
> Ks details buttons

- app/app/settings.py
- app/kudos/views.py
The goal of this PR is to cache the queryset result of the `Token` query using `SearchVector`.
kudos, marketplace
Locally
> Adjust caching for kudos marketplace

- app/dashboard/templates/profiles/profile.html
> Fix load more kudos card flip

- app/assets/v2/css/forms/form.css
- app/assets/v2/css/forms/input.css
- app/assets/v2/css/forms/label.css
- app/assets/v2/css/grants/detail.css
- app/assets/v2/css/grants/milestones.css
- app/assets/v2/css/grants/new.css
- app/assets/v2/css/tabs.css
- app/assets/v2/js/grants/new.js
- app/grants/forms.py
- app/grants/templates/grants/cancel.html
- app/grants/templates/grants/card.html
- app/grants/templates/grants/detail.html
- app/grants/templates/grants/fund.html
- app/grants/templates/grants/index.html
- app/grants/templates/grants/milestones.html
- app/grants/templates/grants/nav.html
- app/grants/templates/grants/new.html
- app/grants/templates/grants/profile/index.html
- app/grants/templates/grants/quickstart.html
- app/grants/views.py
- refactoring
- added common nav
- added custom nav for grants
- new: removed min + hours + any
- new: increase textarea height + make form neater
- new : increased font-size
- detail: remove duplicate fund text
- milestones: change order + remove description
- milestones: UI cleanup
- milestones: add back button
- details: tab fixes (justify text + ensure post activity appears only on activity tab)
refs: #2798
refs: #2753
refs: #2803
> qa : fixes

- app/assets/v2/js/amounts.js
Fix the convert usd to eth in funding form,
Fixes: #2524
> Fix usd to eth convertion

- app/assets/v2/css/grants/card.css
- app/assets/v2/css/grants/detail.css
- app/assets/v2/css/grants/grant.css
- app/grants/templates/grants/card.html
- app/grants/templates/grants/detail.html
refs: #2798
refs: #2753
refs: #2803
> card: clickable + image

- app/assets/v2/css/grants/detail.css
- app/assets/v2/js/grants/detail.js
- app/grants/templates/grants/detail.html
refs: #2798
refs: #2753
refs: #2803
> inline -> bulk edit

- app/assets/v2/css/grants/card.css
- app/grants/templates/grants/card.html
Currently on stage: https://grants.gitcoin.co/grants/
After this PR:
> grants/card: same size

- app/assets/v2/js/shared.js
> fix tooltip not found

- app/assets/v2/css/dashboard.css
- app/retail/templates/shared/result.html
Fix explorer row breaking when have co-founding amounts
> Fix breaking styles

- app/assets/v2/css/grants/detail.css
- app/grants/templates/grants/detail.html
> detail: css fixes

- app/kudos/templates/kudos_marketplace.html
read the code, it speaks for itself :)
> konami code action update

- app/dashboard/router.py
Accept "true" and "True" in API calls
> API: Case-insensitive comparison for is_open

- app/avatar/utils.py
Wallpapers being not centered and too small -> auto-finding proper wallpaper size
Wallpaper issue as discussed in #2746 
UI
Fixes #2746
> #2746 - Wallpapers being not centered and too small

- app/kudos/templates/kudos_about.html
There was an issue in my last commit where for some reason that last faq-item was not updated (even though it shows as updated on my local copy). I've pushed out a change in this PR. 
UI. 
It's just a one-line change applying pre-existing styles. 
Reference #2854, exapands upon #2844 .
> Updating FAQ styles in Kudos [2]. 

- app/kudos/templates/kudos_details.html
Better alignment and responsive behavior
> Fix related profiles alignment

- app/assets/v2/css/activity_stream.css
- app/retail/templates/activity.html
Fix activity empty tags
Fix top nav 
Fixes:  #2711
> Fix activity empty tags

- app/dashboard/templates/bounty/invoice.html
fix image wasn't showing in the invoice 
Fixes: #2919
> Fix invoice logo

- app/dashboard/views.py
The goal of this PR is to resolve the duplicate worker approvals encountered in #2923 by limiting approval/rejection mutations to cases where `Interest.pending == True`
Additionally, this PR checks whether or not the user passed the worker's handle.  If not, they are prompted with a message (previously, this would have thrown a 500 since we'd be filtering on `profile__handle=None`.
bounty details, interests
Tested both approve/reject cases.  The original copy is now displayed via `messages` whenever no pending interest exists (`This worker does not exist or is not in a pending state. Perhaps they were already approved or rejected? Please check your link and try again.`).
#2923
> Fix #2923 - Adjust handle_worker_approvals to check pending existence

- app/kudos/templates/shared/kudos_card_profile.html
> Fix wrong profile pic

- app/marketing/management/commands/expiration_start_work.py
- app/marketing/tests/management/commands/test_expiration_start_work.py
This PR aims to stop workers who have not been accepted to work on a bounty from being prodded to submit their work. 
marketing _(?)_
Fixes #1982
> Fix prodding for unaccepted workers

- app/assets/v2/css/scroll-carousel.css
- app/assets/v2/js/kudos-search.js
- app/assets/v2/js/kudos_suggestions.js
- app/assets/v2/js/shared.js
- app/dashboard/templates/process_bounty.html
- app/dashboard/templates/shared/add_kudos.html
> Kudos suggestions

- app/assets/v2/js/pages/dashboard.js
- app/dashboard/router.py
- app/dashboard/templates/dashboard/sidebar_search.html
- app/dashboard/templates/shared/organization_tooltip.html
Add a text field to filter bounties by organization name.
Ref: #2836
> Filter bounties by organization 

- app/assets/v2/images/kudos/IconKudos.svg
- app/dashboard/templates/shared/nav_auth.html
> Updated Kudos icon in nav

- app/dashboard/models.py
- app/marketing/tests/management/commands/test_assemble_leaderboards.py
- app/marketing/tests/management/commands/test_expiration_tip.py
The goal of this PR is to resolve failing pytests noted in #2977
tests, leaderboard, tips
Locally
Fix #2977
> Update tip expiration test handling and leaderboard counts

- app/assets/v2/js/grants/cancel_subscription.js
- app/assets/v2/js/grants/shared.js
- app/grants/templates/grants/cancel.html
- app/grants/templates/grants/index.html
- app/grants/templates/grants/new.html
fixes web3 functionality for new, fund, and cancel_subscription. Still getting error on cancel_grant.
> fixes web3 functionality on grantz

- app/dashboard/tip_views.py
- app/kudos/views.py
fixes the primary emails being the wrong type 
see 
https://gitcoin.co/_administrationdashboard/tip/
https://gitcoin.co/_administrationkudos/kudostransfer/457/change/
> primary email was wrong type

- app/assets/v2/js/grants/detail.js
Fixes the JS error on callback from metamask on cancelling grants.
> Fix issuel URL in grants cancel cb

- bin/docker-command.bash
see https://django-extensions.readthedocs.io/en/latest/runserver_plus.html
this will make it so the logs dont infinitely scroll
https://gitcoincore.slack.com/archives/CCW6BQ0KA/p1543534988013400
> runserver verbosity to 0

- app/assets/v2/js/grants/fund.js
- app/assets/v2/js/grants/new.js
- app/grants/templates/grants/cancel.html
fix fund view where a user rejects a tx on metamask but frontend still creates new subscription
> fix fund reject issue

- app/assets/v2/js/shared.js
everything non-grants should work on staging 
Good thing @mbeacom didn't change the staging name to grantz :P
> updated grant check in url to path name

- app/assets/v2/js/grants/fund.js
> Ks fund miner fixes

- app/assets/v2/js/grants/new.js
- app/grants/templates/grants/new.html
> add network to new.js

- app/retail/templates/emails/grants/thank_you_for_supporting.html
Refs: https://github.com/gitcoinco/web/issues/3057
> grant/thank_you : fix image overlap

- app/retail/templates/emails/grants/new_grant.html
- app/retail/templates/emails/grants/subscription_terminated.html
- app/retail/templates/emails/grants/successful_contribution.html
- app/retail/templates/emails/grants/support_cancellation.html
- app/retail/templates/emails/grants/thank_you_for_supporting.html
- app/retail/templates/emails/grants/transaction_summary.html
- app/retail/templates/emails/grants/update_notification.html
Refs: https://github.com/gitcoinco/web/issues/3057
> grants/email: unify button size

- app/assets/v2/js/grants/new.js
Add etherscan link to waiting state page.
> Add transaction url in waiting state

- app/assets/v2/css/grants/new.css
- app/grants/templates/grants/new.html
Making the form similar to the `bounty/new`
Ignore the all blue thing -> gif recorder doesn't pick the color diff 😅
> grants/new: updated look & feel

- app/assets/v2/css/grants/fund.css
- app/grants/templates/grants/fund.html
- app/grants/templates/grants/new.html
Fixes: https://github.com/gitcoinco/web/issues/3074
> grant/form : set token value min to 0.001

- app/assets/v2/css/guide.css
webkit needs prefix
Fixes #3122
> guide.css: Add 'position: -webkit-sticky;' to toc.

- app/assets/v2/js/shared.js
Fix sentry bugs in bounty creation realted to 
- https://sentry.gitcoin.co/gitcoin/gitcoin-prod-frontend/issues/2287/
- https://sentry.gitcoin.co/gitcoin/gitcoin-prod-frontend/issues/2288/
> Fixing sentry bugs in bounty creation

- app/assets/v2/js/grants/shared.js
- app/assets/v2/js/pages/bounty_details.js
- app/assets/v2/js/shared.js
- grants : removed var declaration as it's not being used
- bounty: fixed variable scoping for `interval`
- shared.js
> shared : fixed incorrect var scope

- app/inbox/views.py
> Fix AttributeError in inbox.views

- app/inbox/views.py
> Fix in inbox.views

- app/assets/v2/js/pages/tokens_settings.js
* when metamask request is rejected
then do not perform form submit
* fixes #3147 
ui  
fixes #3147 
locally rejecting token usage
> reject token usage

- app/assets/v2/css/base.css
- app/assets/v2/css/grants/grant.css
- app/assets/v2/css/guide.css
- app/assets/v2/js/grants/shared.js
- app/assets/v2/js/pages/bounty_details.js
- app/assets/v2/js/pages/tokens_settings.js
- app/assets/v2/js/shared.js
- app/kudos/templates/kudos_about.html
- app/retail/templates/shared/nav.html
> Merge master to stable

- app/assets/v2/css/grants/grant.css
- app/assets/v2/js/grants/index.js
- app/assets/v2/js/pages/dashboard.js
- app/assets/v2/js/shared.js
- app/grants/templates/grants/index.html
- app/grants/templates/grants/milestones.html
- app/grants/views.py
- sort options doesn't look like it is wired up yet. 
- searching keyword triggers POST call which refreshes page entirely 
The current_behavior :
- you search keyword for grant -> press search -> trigger POST call and page refeshes 
- you change sort option -> nothing happens
- but if you add it as a GET parameters in the url -> it works
Questions: 
Ideally should all network + sort + keyword all be GET param ?
Also to ensure page doesn't do hard refresh do we use ajax ? 
( if so how cause we'll have to create a new API which throws JSON -> and update the templates)  
----
- adds in shareable url with filters
- persists searched terms
- page refresh on updating filters
- shift all to GET params
- refactored a bit
- cleaned up milestones
- adds default image when no search results are …
> adding network option

- app/assets/v2/css/base.css
- app/assets/v2/css/grants/detail.css
- app/assets/v2/js/grants/detail.js
- app/assets/v2/js/shared.js
- app/grants/templates/grants/detail.html
- app/retail/templates/emails/grants/support_cancellation.html
- app/retail/templates/emails/grants/support_cancellation.txt
The new grant_details page
Demo is on grants channel :P
Fixes: https://github.com/gitcoinco/web/issues/3095
> grant/details: updated activity section

- app/retail/emails.py
> newsletter 12/12

- app/marketing/mails.py
- app/retail/emails.py
> feedback emails come from alisa / frank, not kevin

- app/assets/v2/js/grants/fund.js
- app/assets/v2/js/pages/kudos_send.js
- app/grants/templates/grants/new.html
add checks for signature in fund.js to prevent early submit and double sub
> Add checks for signature in fund.js

- app/kudos/kudos.yaml
Squahser of bugs => Squasher of bugs
Simple typo
ui
pretty sure its just a ui change
> Typo in file name

- app/dashboard/notifications.py
Fix the size of kudos in github comment.
Don't know how to test it "in real life" 
With this change, kudos would look like this: 
Fixes: #3167
> Kudos image size on github comment

- app/grants/templates/grants/card/front.html
- app/grants/templates/grants/detail.html
- Add link to admins in grants details
- Add link to admins in grants card
- Add usernames to supporters in grants details
Refs: #3171
> Make links on profiles and add usernamew

- app/assets/v2/css/profile.css
- app/dashboard/templates/profiles/profile.html
> css: fixed orgs in profile

- app/dashboard/templates/profiles/hidden.html
- app/dashboard/templates/profiles/profile.html
Updated the hidden profile.
If you visit valid profile -> you get the normal page
If it's a hidden profile -> you get the obivan image telling used to check github / slack
> profile: updated hidden profile -> with obiwan

- app/assets/v2/js/pages/process_bounty.js
- fix kudos suggestions in bounty payment
- fix validations when bounty doesn't exist 
- request bounty data onload, needed for validations and suggestions.
> fix suggestions, validations onload

- app/assets/v2/js/grants/cancel_subscription.js
- app/assets/v2/js/grants/detail.js
- app/assets/v2/js/grants/fund.js
Add transaction link and url link in all waiting state pages
> Add transaction link and url link in all waiting state pages

- app/dashboard/templates/labs.html
- fixes weird card rendering on gitcoin/labs cards
> labs: card margin fix

- app/assets/v2/js/grants/new.js
> limit grant image to 250kb

- app/assets/v2/js/grants/detail.js
- app/assets/v2/js/pages/shared_bounty_mutation_estimate_gas.js
- app/grants/templates/grants/detail.html
- app/grants/views.py
Added gas settings on cancel grants
> Grants/details: Add gas settings on cancel grants

- app/retail/emails.py
Pending Permissions changes to grants.
> Newsletter PR 12/21

- app/assets/v2/css/grants/card.css
> Grants card image fit

- app/grants/views.py
> updated create grant message

- app/dashboard/tip_views.py
- app/inbox/admin.py
- app/inbox/apps.py
- app/inbox/models.py
- app/inbox/urls.py
- app/inbox/utils.py
- app/inbox/views.py
cc: @octavioamu @mbeacom 
Todo:
> [WIP] Notif backend

- app/retail/emails.py
> 12/28 Newsletter

- app/assets/v2/css/grants/detail.css
- app/assets/v2/js/grants/detail.js
- app/grants/templates/grants/detail.html
- app/grants/views.py
> grant/detail : edit monthly goal

- app/assets/v2/js/grants/cancel_subscription.js
- app/assets/v2/js/grants/detail.js
- app/assets/v2/js/grants/shared.js
- app/grants/templates/grants/cancel.html
- app/grants/templates/grants/detail.html
> grants: disable cancel action if metamask address doesn't match

- app/retail/emails.py
> Grants Newsletter

- app/retail/templates/emails/new_kudos.html
fixes https://github.com/gitcoinco/web/issues/3337
> kudos alignment fixes https://github.com/gitcoinco/web/issues/3337

- docs/KUBE.md
Kubernetes instructions from Mark onboarding call 2019/01/03
> Kubernetes instructions from Mark onboarding call 2019/01/03

- app/dashboard/templates/shared/issue_details.html
closes https://github.com/gitcoinco/web/issues/3443
cc @pinkiebell
> enable reservedFor

- app/assets/v2/js/grants/cancel_subscription.js
- app/assets/v2/js/grants/fund.js
- app/assets/v2/js/grants/new.js
- app/assets/v2/js/grants/shared.js
warns users not to leave pending page on grants
grants 
https://github.com/gitcoinco/web/issues/3075
tested it
> warns users not to leave pending page on grants

- app/grants/templates/grants/profile/body.html
- app/retail/templates/emails/grants/grant_cancellation.html
- app/retail/templates/emails/grants/new_supporter.html
- app/retail/templates/emails/grants/new_supporter.txt
- app/retail/templates/emails/grants/subscription_terminated.html
- app/retail/templates/emails/grants/successful_contribution.html
- app/retail/templates/emails/grants/support_cancellation.html
- app/retail/templates/emails/grants/support_cancellation.txt
- app/retail/templates/emails/grants/thank_you_for_supporting.html
- app/retail/templates/emails/grants/thank_you_for_supporting.txt
- app/retail/templates/emails/grants/transaction_summary.html
- app/retail/templates/emails/grants/transaction_summary.txt
Fix for issue https://github.com/gitcoinco/web/issues/3462
> Fixes Grants decimal issues

- app/grants/admin.py
remove monthly_amount)subscribed readonly
> remove monthly_amount_subscribed from readonly

- app/grants/migrations/0005_auto_20190109_2042.py
> ks add try/except

- app/assets/v2/js/base.js
> Fixes accordion filter

- app/inbox/signals.py
Adding more notif generations.
> [WIP] Added new notif generation

- app/app/sitemaps.py
> fix sitemaps

- app/assets/v2/css/base.css
- app/assets/v2/css/forms/button.css
- app/assets/v2/css/submit_bounty.css
- app/dashboard/templates/bounty/fulfill.html
- app/dashboard/templates/bounty/new.html
- app/dashboard/templates/shared/github_username.html
- app/dashboard/templates/shared/issue_details.html
- app/dashboard/templates/shared/notification_email.html
- app/dashboard/templates/shared/pricing.html
- app/retail/templates/shared/head.html
`bounty/new`
- Cleaned up form layout 
- Fixed up mobile view
- Renamed Estimated Hour -> Est Hour
----
`bounty/fulfill`
- updated to the new design as in bounty/new
- cleaned up layout + refactored code
- mobile friendly 
Tested out funding flow + payout flow and it worked as expected
> bounty/new + bounty/fulfill revamp

- app/retail/templates/shared/cards_pic.html
> Add missing meta tag on gas/faq

- app/dashboard/views.py
Do not send reservation email more than once.
backend
Fixes: #3618
manually
> [fix] reserved bounty mail

- app/assets/v2/js/shared.js
- app/retail/templates/shared/featured_bounty_cards.html
> fix hardcoded amounts

- app/assets/v2/js/pages/change_bounty.js
- app/retail/templates/emails/bounty.html
> Fix edit bounty

- app/assets/v2/css/base.css
- app/assets/v2/js/grants/shared.js
- app/assets/v2/js/pages/bounty_share.js
> fix metamask bg and share fallback

- app/dashboard/templates/social_contribution_modal.html
> remove search user for not logged users

- app/event_ethdenver2019/templates/ethdenver2019/onepager.html
- app/event_ethdenver2019/views.py
> Ethdenver2019 PR Part 3

- app/dashboard/views.py
- app/grants/templates/grants/detail/index.html
- app/grants/templates/grants/new.html
- app/retail/templates/bounties/funder.html
- limit chars of grant title
- fix onboard (access var before declaring). Find more info over at https://github.com/gitcoinco/web/commit/82f0169d43ae8451797acd1f4d32a7027c3daba1#r32314312
fixes: https://github.com/gitcoinco/web/issues/3684
> onboard + grant/new fixes

- app/retail/templates/shared/nav.html
As requested by @PixelantDesign
> hide why-gitcoin for logged in users

- app/dashboard/templates/dashboard/index.html
- app/dashboard/views.py
- app/retail/templates/shared/head.html
- app/retail/views.py
Adds meta title and description tags for SEO
SEO
Changes to shared HTML templates are enclosed by if statements looking for new "meta_description" and "meta_title" context vars.
> add meta title and description to explorer, homepage

- app/retail/views.py
Add myself to the team section on the about page
Very small change to the about view
> add Dan Lipert to team section

- app/assets/v2/js/pages/new_bounty.js
- app/assets/v2/js/shared.js
> fix busyoverlay

- app/assets/onepager/css/main.css
Fix send-tip input focus color bug
UI
Fixes #3768
> Issue 3768/fix send tip input focus color bug

- app/dashboard/templates/bounty/details.html
> a magic fix

- app/assets/v2/css/base.css
- app/assets/v2/css/gitcoin.css
- app/assets/v2/css/retail/plans.css
- app/assets/v2/js/grants/fund.js
- app/assets/v2/js/shared.js
- app/dashboard/templates/shared/no_metamask_error.html
- app/retail/templates/home/index.html
- app/retail/templates/pricing/subscribe.html
- docs/STYLEGUIDE.md
- pricing: fixed banner css
- added fadein animation code + documented
- used fadein animation on homepage
> homepage + pricing fixes

- docs/RUNNING_LOCALLY.md
- docs/RUNNING_LOCALLY_DOCKER.md
Fixes: https://github.com/gitcoinco/web/issues/3783
> doc: updated sync_geth command

- app/retail/templates/emails/template.html
Removed stylesheet `typography.css` into email template:
- Email clientes can't fetch external stylesheets
- Emails cliente can't use custom fonts
> fix stylesheet used in email

- app/assets/v2/css/bounty.css
- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/templates/bounty/details.html
Got feedback from a few folks that the bounty summary info looked meh on.
This PR does a job of tidying it up a bit.
[ thanks for the report @vsramanujan and pointing out the issues. Appreciate it ]
- removed unwanted code + updated CSS
- responsive + made text + layout uniform 
PR used as an example: https://gitcoin.co/issue/gitcoinco/web/3660/2260
-----
**Screenshot**
> detail: clean up info-section

- app/retail/templates/shared/footer_scripts_lite.html
- app/retail/templates/shared/head.html
fix preload from crossorigin to crossorigin="anonymous"
> fix cors in production

- app/retail/templates/shared/head.html
> Missing change preload cors

- app/assets/v2/css/gitcoin.css
> nav: fixed overlapping background over text

- app/dashboard/templates/bounty/kill.html
Simple PR to change the copy when cancelling a bounty from `Please let us know why you stopped work` to `Please let us know why you cancelled the bounty`.
UI.
Fixes #3800.
Simple typo fix, really no testing needed, but it's been checked across two devices as usual none the less.
> Fixing copy when cancelling bounty.

- app/assets/v2/css/grants/card.css
- app/assets/v2/js/kudos_suggestions.js
- app/grants/templates/grants/detail/matching.html
> css: prettify grant cards

- app/retail/templates/shared/footer_scripts.html
- app/retail/templates/shared/footer_scripts_lite.html
> fix notifications in home

- app/dashboard/models.py
- app/dashboard/tests/test_dashboard_helpers.py
- app/marketing/mails.py
- app/marketing/tests/test_mails.py
Restore code from bad merge for PR https://github.com/gitcoinco/web/pull/3766 and fix email sending on new bounties
> fix new bounty emails, restore email campaign bad merge from https://github.com/gitcoinco/web/pull/3766

- app/app/utils.py
- app/assets/v2/js/avatar_builder.js
- app/avatar/utils.py
- app/dashboard/templates/ftux/avatar.html
- app/dashboard/templatetags/jsonify.py
Implements a method to randomly generate an avatar in the frontend in just a click. Also implements a method in the backend to generate a random avatar when a new user logs in.
Solves issue #3811
> Add process to generate random avatars

- app/retail/templates/emails/funded_featured_bounty.html
> Fix unaligned values in email

- app/dashboard/router.py
Fixes the featured bounty to always return open bounties, irrespective of queryparams.
> Fixes it to always being true

- app/assets/v2/css/base.css
- app/dashboard/templates/profiles/organization.html
- app/dashboard/templates/profiles/profile.html
- app/retail/templates/emails/funded_featured_bounty.html
> fix popover in profiles w many data

- app/dashboard/models.py
- app/dashboard/notifications.py
for https://gitcoincore.slack.com/archives/CAXQ7PT60/p1551990407021500
> hotfix for succesfully funded a bounty email

- app/grants/templates/grants/index.html
Fix this error in sentry 
https://sentry.io/organizations/gitcoin/issues/921918476/?project=1398424&referrer=slack&statsPeriod=14d
> fix error in grants

- app/marketing/tests/management/commands/test_roundup.py
> fix mkt email tests

- app/dashboard/router.py
> fix .lower() get in query

- app/dashboard/templates/profiles/profile.html
Remove reference to `localhost`.
> Remove broken link on profile page

- app/assets/v2/css/home.css
- app/retail/templates/home/index.html
- app/retail/views.py
- Update title + meta as discussed with mark
- cleaned up the homepage why we built gitcoin section
- made the video as a modal as opposed to opening it up in new tab
> homepage fixes

- app/dashboard/admin.py
https://share.vidyard.com/watch/MtX171UY6PAzs6p9pMRB2h
Refs #3963
> add search to verified

- app/dashboard/templates/dashboard/hackathon/ethhack_2019.html
> Copy Edits to Hackathon Landing Page

- app/dashboard/templates/profiles/profile.html
> fix unclosed div

- app/retail/templates/emails/funder_payout_reminder.html
> [#4004] Add padding to button and change button url in email template

- app/app/settings.py
Temporary hotfix to unstick cron jobs
> temporarily disable watchtower logging

- app/app/settings.py
Fixes issue with stuck cronjobs
> remove cloudwatch

- app/dashboard/helpers.py
@danlipert Fixes the unsigned_nda problem
> Retrieve bounty document for new bounty creation on transaction update

- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/templates/addinterest.html
> bounty/detail : refactor NDA section

- app/assets/v2/js/pages/dashboard.js
This PR solves an issue where untrusted content from the URL bar can be rendered unsafely into the DOM
bounties explorer
tested locally against disclosed issue
> scrub keywords during filter rendering

- app/retail/templates/emails/new_bounty_acceptance.txt
> Fixes rating email txt

- app/dashboard/templates/profiles/profile.html
- app/dashboard/templates/shared/rate_bounties.html
> add condition to rating

- app/assets/v2/css/leaderboard.css
- app/grants/templates/grants/new.html
- app/marketing/views.py
- app/retail/templates/bounties/funder.html
- app/retail/templates/leaderboard.html
- code refactor + reuse css classes + weed out unwanted css
- hide bounty plans on bounties/funder
- leaderboard tweaks
closes https://github.com/gitcoinco/web/issues/4101
> leaderboard : final touches

- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/templates/bounty/details.html
> fix #4144 nda condition

- app/dashboard/views.py
> fix rating saved data

- app/assets/v2/js/pages/bounty_share.js
- app/dashboard/templates/social_contribution_modal.html
- app/dashboard/views.py
- app/retail/emails.py
- app/retail/templates/emails/share_bounty_email.html
- app/retail/templates/emails/share_bounty_email.txt
design the invite bounty email
Fixes #4103
> Change invite bounty email

- app/marketing/views.py
> remove context in leaderboard

- app/retail/emails.py
> 041219newsletter

- app/app/urls.py
- app/assets/v2/js/base.js
- app/dashboard/templates/dashboard/hackathon/ethhack_2019.html
- app/dashboard/templates/dashboard/index.html
- app/dashboard/views.py
- app/retail/templates/shared/top_nav.html
1. adds top bar as discussed https://gitcoincore.slack.com/archives/CAW05FUD7/p1555259743000300
2. provides link to FAQ
3. a few other small changes in copy, etc
> hackathon day of updates

- app/dashboard/notifications.py
- app/retail/templates/emails/funded_featured_bounty.html
> remove condition and fix template

- app/dashboard/templates/shared/hackathon_sponsors.html
update `/v2/images/..` -> `v2/images/..`
> hackathon: update static img path

- app/assets/v2/js/shared.js
- app/marketing/tests/management/commands/test_expiration_tip.py
Fix style and test failure in master
> fix test and style

- app/assets/v2/js/pages/dashboard.js
> fix sidebar hackathon

- app/assets/v2/js/pages/dashboard.js
- app/dashboard/templates/dashboard/sidebar_search_hackathon.html
- app/dashboard/views.py
works around the dashboard / api performance issue by just loading the orgs straight from the DB upon pageload.
tested on chrome / on my local
> get orgs on the backend + improve dashboard performance

- app/dashboard/templates/dashboard/index.html
Show network tab only on staging  + local
> fix: hide network tab on live

- app/app/urls.py
> Fix save job data on onboard and settings

- app/retail/emails.py
> Newsletter042619

- app/assets/v2/css/grants/grant.css
- app/grants/templates/grants/index.html
- refactored html+css
- cleaned up page (added gradient transition to make the lansing page more pleasnt)
- fixed up whacky indentation on the landing page
Demo: [HERE](https://embed.vidyard.com/share/P8CKqNXsBedwfMxBrSaJtR?)
> grants/index: clean up landing page

- app/grants/templates/grants/fund.html
Cleaned up the grants/fund form
> cleanup grant/fund

- .github/ISSUE_TEMPLATE/bug_report.md
Updated template to make it less noisy
> cleaned up bug reporting template

- requirements/base.txt
> add websocket python library for slackclient

- docs/THIRD_PARTY_SETUP.md
Fixes minor documentation error incorrectly identifying SendGrid as Github.
N/A
No coding changes.  Content update only.
> Correct reference to SendGrid

- app/assets/v2/css/base.css
- app/retail/templates/shared/nav.html
top nav per https://github.com/gitcoinco/web/issues/4322
https://github.com/gitcoinco/web/issues/4322
desktop screenshot: http://bits.owocki.com/992237958305/Image%202019-05-03%20at%201.06.16%20PM.png
mobile: http://bits.owocki.com/928e229e8aaa/Image%202019-05-03%20at%201.06.36%20PM.png
> Add User Directory to Top Nav 

- app/dashboard/views.py
- requirements/base.txt
Adds active filters in query
Refs: #4353
> Fixes to check active data

- app/dashboard/utils.py
Fixes issues with ipfs and bounties, etc.
> fix infura ipfs url

- app/assets/v2/css/rating.css
- app/dashboard/templates/profiles/profile.html
- app/dashboard/views.py
add stars rating to profile
#4390
> Add stars to profile

- app/app/middleware.py
- app/app/settings.py
- requirements/base.txt
This PR adds middleware to apply the bleach library sanitization method to POST parameters.
https://github.com/gitcoinco/web/issues/4348
This change still passes the test suite, and I've tested it manually by creating bounties that have html in them
> Add bleach middleware to sanitize requests

- app/retail/emails.py
> copy update

- app/retail/emails.py
> newsletter0510

- app/dashboard/templates/shared/issue_details.html
> bounty/new: updated text

- app/dashboard/templates/dashboard/users.html
- app/dashboard/views.py
Add the previously worked label
Fixes #4410
> add previously worked label in user directory

- app/grants/templates/grants/cancel.html
Fix undefined errror on cancel.js
> bug: add missing link

- app/dashboard/views.py
> fix org filters

- app/dashboard/templates/bounty/change.html
- app/dashboard/templates/bounty/fund.html
- app/grants/templates/grants/newv0.html
- app/retail/templates/gas_heatmap.html
> fix bad paths to js lib files

- app/assets/v2/js/pages/new_bounty.js
> Fix call  before initialization

- app/assets/v2/css/submit_bounty.css
Fix Unexpected unknown pseudo-class selector ":window-inactive" for window-inactive selector
> Fix stylelint pseudo class

- Dockerfile
Fix for Vips being moved from testing index to community
> fix vips repo

- app/dashboard/helpers.py
- app/dashboard/management/commands/cleanup_dupe_bounties.py
- scripts/crontab
…omment-496023265
https://github.com/gitcoinco/web/issues/4486#issuecomment-496023265
here is the condition in the codebase https://github.com/gitcoinco/web/blob/master/app/dashboard/views.py#L1484-L1488 that was screwing things up
upon further investigation, noticed this is because there are two ’current_bounty’s
http://bits.owocki.com/1e438fed678e/Image%202019-05-26%20at%205.17.17%20PM.png
to fix this, i just moved the ‘interest’ from the first bounty to the second one, and that solved the problem.  responded to the customer to let them know.
root cause analysis:  there must be something non-deterministic about how this code runs, because https://github.com/gitcoinco/web/blob/master/app/dashboard/helpers.py#L547-L554 is *supposed to handle this case*.  maybe we assumed it would be …
> duct tape interests fix

- app/assets/v2/js/pages/bounty_details.js
- app/assets/v2/js/users.js
- app/dashboard/templates/dashboard/users.html
> Add condition current bounty

- app/retail/emails.py
> newsletter 2019-06-07

- app/dashboard/templates/shared/nav_auth.html
As per @PixelantDesign 's request
> My created Bounties -> My Funded Bounties

- app/retail/templates/how_it_works/funder.html
- app/retail/templates/shared/nav.html
As per @PixelantDesign 's request
Screenshots:
> Adding Funder's Guide

- app/dashboard/tests/test_users_list.py
> set current user for user directory

- app/dashboard/tests/test_users_list.py
- app/grants/migrations/0023_auto_20190604_1552.py
> Bypass clr data

- app/dashboard/templates/bounty/fund.html
- app/dashboard/templates/bounty/increase.html
- app/dashboard/templates/bounty/new.html
- app/dashboard/templates/bulk_payout_bounty.html
- app/grants/templates/grants/fund.html
- Updates the summary text in fund grant for [Recurring Payment](https://user-images.githubusercontent.com/5358146/59433053-534cc980-8e06-11e9-8428-829d099c789a.png) and [One Time Payment](https://user-images.githubusercontent.com/5358146/59433054-534cc980-8e06-11e9-84ca-15a1cc00921c.png)
- Fixed alignment [advanced payout page](https://user-images.githubusercontent.com/5358146/59433978-3dd89f00-8e08-11e9-910e-b61157a07253.png)
it was center aligned before
- Fixed spelling + updated words when a coupon i[s applied on funding bounty](https://user-images.githubusercontent.com/5358146/59435715-d3296280-8e0b-11e9-9735-bf5611374b06.png)
Refs: https://github.com/gitcoinco/web/issues/4634
> updated one time payment summary

- app/grants/templates/grants/fund.html
adds missing trans tag in grants funding description
> add missing trans tag

- app/assets/v2/js/pages/new_bounty.js
fixes https://github.com/gitcoinco/web/issues/4189 by calling the `triggerDenominationUpdate()` method upon pageload
https://github.com/gitcoinco/web/issues/4189
tested locally
> fixes token display not updating when creating a bounty (https://github.com/gitcoinco/web/issues/4189)

- app/bounty_requests/templates/bounty_request_form.html
The current newletter form on the /requests is off. 
Fixes #3632
> Fix newletter position

- app/retail/templates/shared/top_nav.html
update banner text https://gitcoincore.slack.com/archives/CJWQWG6J2/p1561360494001000
> update banner text

- app/dashboard/context/hackathon.py
> fix: banner

- app/assets/v2/css/base.css
- app/dashboard/templates/ftux/onboard.html
- app/retail/templates/about.html
- app/retail/templates/products.html
- app/retail/templates/shared/top_nav.html
Add hackathon banner animation and fix topbar spacing in some pages.
Check out this video: https://embed.vidyard.com/share/jv1xYrgPP5xQcJF3iscbiz?
tested navigating the site
> Add top banner animation

- app/assets/v2/js/user_popover.js
Convert to number the total_earned 
fix string toFixed
Fix #4712
Tested in bounty activity
> Fix profile popover

- app/grants/templates/grants/newv0.html
Fixes a small HTML error on the hidden "legacy grants" creation page
Tested locally
> fix tag typo

- app/marketing/management/commands/sync_mail.py
- scripts/crontab
This change lowers the sync time from every two hours to every twelve hours to reduce load on the database.
This is a temp fix for #4784
> sync mail twice a day

- app/dashboard/templates/dashboard/index.html
desktop
mobile
Fix #4758
Visual changes into the explorer
> add h1 to explorer

- app/assets/v2/js/shared.js
Fix wrong rounded values in issue explorer 
Fixed also in https://github.com/gitcoinco/web/commit/de03a02dea7f50549b1166816535d97bd1f766b2 by @owocki
> fix bad rounded value

- app/assets/v2/css/profile.css
- app/dashboard/templates/profiles/profile.html
- app/dashboard/views.py
- Ensures activity gets loaded based on network 
- Fixed profile banner z-index + css
> pass network argument

- app/dashboard/views.py
fixes https://github.com/gitcoinco/web/issues/4559
https://github.com/gitcoinco/web/issues/4559
tested locally
> fixes https://github.com/gitcoinco/web/issues/4559

- requirements/base.txt
fixes security vulnerabilities
`django` -> `2.2.3`
had to update `django-extensions` to `2.2.1` 
as documented here https://github.com/django-extensions/django-extensions/issues/1295
https://github.com/gitcoinco/web/issues/4740
The following flows have been tested 
- bounty normal payout
- tip send + recieve
- grant create + fund
> update django version -> 2.2.3 django-extensions 2.2.1

- app/grants/models.py
The model definition for grants requires there to be a change ownership entry - we can't save the grant via the admin with this requirement. This PR removes the requirement.
none
tested locally
> allow change ownership to be blank so you can edit via admin

- app/assets/v2/js/base.js
persona modal is missing in production 
REf #4863
> Fix persona image url in modal

- app/app/sitemaps.py
Sitemap was generating url for all full language list but the result view just generate result/LANGUAGE for the short list language not the Full one.
solves just the sitemap problem reported in #4873
tested in my local and sitemap looks ok now
> Sitemap results/ fix, change languages to short list

- app/assets/v2/css/hackathons/explorer.css
- app/dashboard/templates/shared/hackathon_sponsors.html
- updated the height of gold + silver sponsor 
- hardcoded styling to turn font black ( which needs to be removed once #4879 gets in )
> fixed up gold + sliver sponsor size

- app/dashboard/models.py
Fixes typo in calculating profile eth earned
https://github.com/gitcoinco/web/issues/4909
Untested
> fix typo in eth_sum calc

- app/assets/v2/js/pages/bounty_details.js
> fixes breaking bounty detail page

- app/assets/v2/js/grants/detail.js
- app/grants/templates/grants/detail/tabs.html
- app/grants/views.py
> Revert "Fix edit info on grant page"

- app/dashboard/models.py
- app/dashboard/templates/bounty/details.html
change sum eth value function
fix workplan showing in every activity
> Deploy fixes

- app/assets/v2/js/pages/process_bounty.js
- app/assets/v2/js/users.js
Add bounty id to basic payout waiting state 
Add feedback when user is not found using the invite on waiting state.
id 32 comes from a basic payout and was removed for the suggested bounties list
Locally with diff users
> Fix invite to work from waiting state

- app/dashboard/helpers.py
dont re-sync bounty event tags from IPFS if previous bounty event tags had been changed in admin
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1565028834056200
tested locally
> dont re-sync bounty event tags from IPFS if previous bounty event tags had been changed in admin

- app/dashboard/views.py
Fixes: Bug 2 of #4867
This fixes a minor bug in the settings/job page wherein a user needs to upload a resume every time they want to save an update.
Fix Bug 2 of #4867
https://embed.vidyard.com/share/2qPBGoJJfBRka3qxvG8oZD?
> Job status tab bugs

- app/dashboard/templates/dashboard/index.html
- app/dashboard/templates/shared/hackathon_sponsors.html
Fix the class overwriting styles from admin
> Fix hackathon classes styles

- app/marketing/utils.py
Fixes bug with suppression list checking
> fix bug with suppression check

- app/assets/v2/js/grants/detail.js
> re-add tabs click

- app/dashboard/views.py
This PR allows you to remove your resume from the job profile page
> fix for removing resume

- app/assets/v2/js/board.js
- app/dashboard/templates/board.html
- app/dashboard/views.py
Remove duplication , bounties with more than one submission are going to show once 
Filter by pending True removed (that was affection permissionless bounties to shown) 
Add error feedback when query fails.
Fix #4979
> Dashboard fixes

- app/retail/emails.py
> newsletter 2019-08-15

- app/assets/v2/js/base.js
- app/retail/templates/shared/top_nav.html
> updates the hackathon banner

- app/app/urls.py
Fix hackathons url final slash 
https://gitcoin.co/hackathon/grow-ethereum showing ETHEREAL BLOCKS (last hackathon created)
@alexvotofuture 
tested all the hackathon urls on the site with and without /
> Fix hackathons url final slash

- app/assets/v2/js/vue-components.js
> fix multiple select2 component

- pydocmd.yml
Testing the Travis docs deploy fix
> fix grammar in docs and test travis

- docs/SECURITYBOUNTY.md
- pydocmd.yml
This PR adds new security bounty program guidelines to the docs site
n/a
n/a
> add security bounty program

- app/assets/v2/css/base.css
As discussed with @PixelantDesign
> css: change warning from yellow to orange

- js-sdk/package-lock.json
- js-sdk/package.json
- js-sdk/yarn.lock
- package-lock.json
- package.json
- requirements/base.txt
- update django version to 2.2.4[Release notes](https://docs.djangoproject.com/en/2.2/releases/2.2.4/)
- update node packages to fix security vulnerabilities ( + package.lock + yarn.lock )
Both updated are made as separate isolated commits 
https://github.com/gitcoinco/web/network/alerts
Tested main flows and app works as expected
> chore: tech upgrade

- requirements/base.txt
> chore: upgrade Werkzeug to 0.15.5

- app/dashboard/views.py
Fix condition when bounty is permissionless the message was always "reserved for another person"
> fix msg condition

- app/dashboard/models.py
Fixes broken activity page if there is a grant without an image
tested locally
> fix for logoless grant

- app/assets/v2/css/activity_stream.css
- app/retail/templates/bounties/contributor/activity.html
Fix activity css on kudos / tech pages and others places where displayed. 
Locally
> fix acitivity css on kudos

- app/assets/v2/css/profile.css
- app/assets/v2/js/pages/profile.js
- app/dashboard/templates/profiles/header_details.html
- app/dashboard/templates/profiles/profile.html
- app/dashboard/templates/profiles/tab_resume.html
- app/dashboard/templates/profiles/tabs.html
- app/dashboard/views.py
> adds resume tab to profile

- app/assets/v2/css/profile.css
- app/dashboard/templates/profiles/tab_workedwith.html
- app/dashboard/templates/shared/feedback.html
- app/dashboard/views.py
> makes relationship tab on profile a thing

- app/assets/v2/css/profile.css
- app/assets/v2/js/pages/profile.js
- app/dashboard/templates/profiles/header_avatar.html
- app/dashboard/templates/profiles/header_details.html
- app/dashboard/templates/profiles/profile.html
- app/dashboard/templates/profiles/scorecard_funder.html
- app/dashboard/templates/profiles/scorecard_hunter.html
- app/dashboard/templates/profiles/tab_activity.html
- app/dashboard/templates/profiles/tab_details.html
- app/dashboard/templates/profiles/tab_resume.html
- app/dashboard/templates/profiles/tab_workedwith.html
- app/dashboard/templates/profiles/tabs.html
- app/dashboard/templates/profiles/tabs_close.html
- app/dashboard/templates/shared/feedback.html
- app/dashboard/views.py
breaks out profiles into reasonably-sane modules that can be worked on seperately
@danlipert this is one of the first big changes to go into `profile/v2` so PRing it seperately so we can reason about it here.
> breaks out profiles into reasonably-sane modules that can be worked on seperately

- app/assets/v2/js/pages/dashboard.js
Hide arrows if there is nothing more to scroll 
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1567434342017600
tested locally with diff amount of featured bounties and screen sizes
https://embed.vidyard.com/share/iL17UjdyTUwf37fibfGk5Y?
> add checker for arrows

- app/dashboard/views.py
Add new rendering section for views.py to render Currently Working bounties tab.
Fixes #5097 
Will be added.  No current tests for this section of views.py.
> Fixes #5097

- app/assets/v2/css/activity_stream.css
- app/retail/templates/activity.html
- app/retail/templates/results.html
- app/retail/templates/shared/activity_container.html
- app/retail/templates/shared/activity_scripts.html
activity feed on the results page
https://github.com/gitcoinco/web/issues/4944
tested locally
> activity feed on the results page

- app/assets/v2/css/profile.css
- app/dashboard/templates/profiles/activity_level.html
- app/dashboard/templates/profiles/header_avatar.html
- app/dashboard/templates/profiles/header_details.html
- app/dashboard/templates/profiles/profile.html
- app/dashboard/templates/profiles/scorecard_funder.html
- app/dashboard/templates/profiles/scorecard_hunter.html
- app/dashboard/templates/profiles/tab_activity.html
- app/dashboard/templates/profiles/tab_portfolio.html
- app/dashboard/templates/profiles/tab_ratings.html
- app/dashboard/templates/profiles/tab_resume.html
- app/dashboard/templates/profiles/tab_workedwith.html
- app/dashboard/templates/profiles/tabs.html
- app/dashboard/templates/shared/feedback.html
- app/dashboard/views.py
Profile V2 design implementation
Go to your profile page
> Profile css

- app/dashboard/templates/bounty/details.html
Close others popovers when over a new one.
> close any other popover

- app/assets/v2/css/profile.css
- app/assets/v2/js/base.js
- app/dashboard/templates/profiles/organization.html
- app/dashboard/templates/profiles/profile.html
- app/dashboard/templates/shared/profile_rank_link.html
- app/dashboard/views.py
what:
- adds the ability to toggle persona on profile
- if its not your profile, lets you click through to leaderboard
- simplifies profile so you dont have to look at two diff sets of stats (funder + contributor)
https://github.com/gitcoinco/web/issues/4631
external to profile
if it's your profile:
> adds the ability to toggle persona on profile

- app/app/context.py
- app/assets/v2/css/profile.css
- app/dashboard/templates/profiles/profile.html
- app/dashboard/templates/shared/nav_auth.html
- app/dashboard/views.py
proof of concept for how organizational edits could be handled in the app
https://github.com/gitcoinco/web/issues/4832
not tested, do not merge
> proof of concept of org profile editing

- app/assets/v2/css/base.css
- app/assets/v2/css/profile.css
- app/assets/v2/js/base.js
- app/assets/v2/js/pages/profile.js
- app/assets/v2/js/status.js
- app/dashboard/templates/profiles/activity_level.html
- app/dashboard/templates/profiles/activity_stats.html
- app/dashboard/templates/profiles/header_avatar.html
- app/dashboard/templates/profiles/header_details.html
- app/dashboard/templates/profiles/heatmap.html
- app/dashboard/templates/profiles/relationshipgraph.html
- app/dashboard/templates/profiles/scorecard_funder.html
- app/dashboard/templates/profiles/scorecard_hunter.html
- app/dashboard/templates/profiles/skillchart.html
- app/dashboard/templates/profiles/tab_active.html
- app/dashboard/templates/profiles/tab_activity.html
- app/dashboard/templates/profiles/tab_kudos.html
- app/dashboard/templates/profiles/tab_portfolio.html
- app/dashboard/templates/profiles/tab_ratings.html
- app/dashboard/templates/profiles/tab_resume.html
- app/dashboard/templates/profiles/tab_viewers.html
- app/dashboard/templates/profiles/tabs.html
- app/dashboard/templates/profiles/tabs_close.html
- app/dashboard/templates/shared/feedback.html
- app/dashboard/templates/shared/profile_rank_link.html
@owocki sat down and re-indented the file and did some minor cleanup
Could you double check this before merging it in
Also when reindenting I noticed we had a few elements with missing closing / open tags
I noticed you had [tabs_close.html](https://github.com/thelostone-mc/web/blob/cleanup-profile/app/dashboard/templates/profiles/tabs_close.html) but I feel a few are being missed here
- [header_details.js](https://github.com/thelostone-mc/web/blob/cleanup-profile/app/dashboard/templates/profiles/header_details.html#L68) has a missing opening div
- [scorecard_funder.js](https://github.com/thelostone-mc/web/blob/cleanup-profile/app/dashboard/templates/profiles/scorecard_funder.html#L2-L3) has two missing closing divs
- [scorecard_hunter](https://github.com/thelostone-mc/web/blob/cleanup-prof …
> lint fixes + min refactor

- app/retail/templates/about.html
case ahem well you know :P it's a good conversation starter
> minor fixes for mobile

- app/assets/v2/css/grants/grant.css
- app/grants/templates/grants/card/clr_estimate.html
- app/grants/templates/grants/card/clr_estimate_prev.html
- app/grants/templates/grants/card/clr_match.html
- app/grants/templates/grants/card/front.html
- app/grants/templates/grants/clr_estimate.html
- app/grants/templates/grants/detail/info.html
- app/grants/templates/grants/index.html
- app/grants/views.py
- updated CLR design on grant index page
- reident + refactor code
closes https://github.com/gitcoinco/web/issues/5247
https://share.vidyard.com/watch/2cj5rC9hravSaJt9T98X8w?
> clr: update design

- app/retail/templates/shared/result.html
Add 'see prize' when low value
Fix #5238
> Add 'see prize' when lower value

- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/views.py
- sync title when funder does issue sync 
https://share.vidyard.com/watch/nhLNb9P1V7UrDiYqwSyLLG?
> update title on sync

- docs/API.md
- docs/KUBE.md
- docs/KUDOS.md
- docs/STYLEGUIDE.md
- docs/THIRD_PARTY_SETUP.md
- docs/WIDGET.md
I created and highlighted code blocks in documentation
> Create and highlight code blocks

- app/dashboard/templates/board/contributor.html
> fix onboard page

- app/dashboard/templates/board/contributor.html
closes https://github.com/gitcoinco/web/issues/5236
> fix overflowing text

- docs/README.md
> typo fixed

- app/grants/templates/grants/card/front.html
> grant: hide clr info on card once it's ended

- app/retail/templates/emails/template.html
> fix: #logo image wider than email container

- app/app/context.py
- app/app/urls.py
- app/dashboard/models.py
- app/dashboard/templates/profiles/profile.html
- app/dashboard/templates/shared/nav_auth.html
- app/dashboard/tests/test_dashboard_models.py
- app/dashboard/utils.py
> Revert "gitcoin.co/profile/owocki => gitcoin.co/owocki"

- app/grants/models.py
- app/grants/views.py
- app/marketing/mails.py
opens up gitcoin grants to anyone...  reasons:
1. reduce the sense of elitism (and complaints) i get
2. make these projects shill their gitcoin grant; enabling a long tail of virality
instead any new grant will be hidden by default, and us admins will get an email asking us to approve the grant.
when this is merged @ceresstation we should email everyone on the typeform and let them know they can create a grant.
convo that @ceresstation and i had on slack..
tested locally
> opens grants creation to anyone

- app/app/context.py
- app/app/urls.py
- app/app/utils.py
- app/dashboard/models.py
- app/dashboard/templates/profiles/profile.html
- app/dashboard/templates/shared/nav_auth.html
- app/dashboard/tests/test_dashboard_models.py
- app/dashboard/utils.py
fixes https://github.com/gitcoinco/web/pull/5359
> fixes the issues with gitcoin.co/profile

- app/dashboard/views.py
reported here: https://gitcoincore.slack.com/archives/CAXQ7PT60/p1571843524105800
Tested this locally
> ensures user is logged in for payout

- app/assets/v2/css/base.css
- app/assets/v2/js/base.js
- app/retail/templates/cookielaw/banner.html
> removed privacy modal and added it to cookie law text

- app/assets/v2/js/pages/bulk_payout.js
- app/dashboard/templates/bulk_payout_bounty.html
- app/retail/templates/shared/bulk_payout_form.html
- add title
- replace input with label
- move hidden fields to bottom
- reindent + replace var -> const
- updated text of Add user
Refs: https://github.com/gitcoinco/web/issues/5321
> advanced payout fixes

- app/assets/v2/js/pages/new_bounty.js
- app/assets/v2/js/shared.js
Reported over at: https://gitcoincore.slack.com/archives/CAXQ7PT60/p1572251002163200
Fix: https://share.vidyard.com/watch/i3Npqh5otGf2rn3kLiYYvn?
> fix ux issue bounty/new while tabbing to usd_amount

- app/retail/emails.py
Updated Gitcoin Weekly sponsor to Arweave
> Update sponsor to Arweave

- app/assets/v2/js/pages/onboard.js
- app/retail/emails.py
> sentry fixes

- app/retail/templates/emails/grants/successful_contribution.html
closes https://github.com/gitcoinco/web/issues/5448
> bug: change floatformat 2 -> 3

- app/dashboard/views.py
- Adding a check to the `invalid_file_response` helper method to ensure that <script> tags aren't defined inside the content of the uploaded file buffer for uploaded user content.
#5245 
Tested through onboarding, and through /settings/job
> Stored XSS - [ In Review ]

- app/kudos/models.py
Fix kudos on localhost since AWS_STORAGE_BUCKET_NAME is default to '' and that is in self.image
> fix kudos on localhost

- app/dashboard/helpers.py
Fixes potential issue where bounty_value_usdt is None
> check bounty value is not none for lowball alert

- app/assets/v2/css/bounty.css
- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/templates/bounty/details.html
> add missing icon for remarket + prettify

- app/assets/v2/css/bounty.css
- app/assets/v2/css/forms/button.css
> fix btns css

- app/assets/v2/css/bounty.css
- app/assets/v2/images/comment.svg
- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/templates/bounty/details.html
- remove extra img + comment count on github
> bug: fixed wonky button

- app/dashboard/templates/dashboard/sidebar_search.html
remove extra filter on explorer
Demo : https://share.vidyard.com/watch/TAbPbQdoR86VpsewvoNJoM?
> bug: remove duplicate filter

- app/assets/v2/js/grants/new.js
- app/grants/templates/grants/detail/info.html
- app/grants/views.py
- add breathing space for fund your own grant
- ensure grant members get saved during owner creation
closes https://github.com/gitcoinco/web/issues/5492
https://share.vidyard.com/watch/HbnsJNbijAbiBMP8DeB7XQ?
> bug: add teammates during grant creation

- app/app/settings.py
Add SAI to list of stablecoins
> add SAI to stable coins

- app/grants/templates/grants/detail/summary.html
Issue: https://gitcoincore.slack.com/archives/CAXQ7PT60/p1574108783311900
Demo: https://share.vidyard.com/watch/4xHDsDvUjf2JNcazeeqzQj?
> grant_details: resize milestone + activity

- app/assets/v2/css/bulk_payout_bounty.css
- app/dashboard/templates/bulk_payout_bounty.html
Issue: https://gitcoincore.slack.com/archives/CAXQ7PT60/p1574199000318000
Fix: https://share.vidyard.com/watch/oRw9gQjxpKH2G9KpJYaDE7?
> advanced payout: fix star rating overflow

- app/assets/v2/js/user_popover.js
- app/dashboard/templates/bounty/details.html
close others popovers before open a new
Abort ongoing users request when hover a diff user.
Fix #5493
> Users popover on bounty details

- app/assets/v2/css/bounty.css
- app/assets/v2/css/grants/detail.css
- app/dashboard/templates/bounty/details.html
- app/grants/templates/grants/detail/info.html
- app/grants/templates/grants/detail/summary.html
- app/grants/templates/grants/detail/tabs.html
- app/grants/views.py
A team member should be able to 
- edit title + url
- add/remove team members
- fund own grant
- update description + grant photo
- add milestones + activity 
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1573780650271900
close  https://github.com/gitcoinco/web/issues/5523
> feat: allow grant members to edit grant details

- app/dashboard/templates/profiles/tab_resume.html
- app/dashboard/views.py
This PR removes the inline PDF rendering and restores PDF resume uploading temporarily as we work on a more secure solution to check uploaded media for issues.
tested locally
> remove inline resume render, script tag checking

- app/bounty_requests/views.py
Fixes Sentry issue: https://sentry.io/organizations/gitcoin/issues/1255090196/?project=1398424&query=is%3Aunresolved+requests&statsPeriod=14d&utc=true
> fix bounty request email getter when expecting None

- Dockerfile
- requirements/base.txt
> Revert "alpile 3.8 > 3.10"

- Dockerfile
based on 
https://travis-ci.org/gitcoinco/web/jobs/617023755#L389
Our problem seems to be related to https://gitlab.alpinelinux.org/alpine/aports/issues/10962
So I changed vips to vips-dev
fix #5549
> [DONT MERGE] Docker fixchange vips to vips-dev

- docs/API.md
There has been a change to the Gitcoin API. Previously you could access a single bounty like this: `bounties/<bountyId>/` but there has been a change and to access a single bounty you need to access it like this: `/bounties/?pk=<bountyId>`.
I only updated the docs to explain how to access single bounties
#5307
> Gitcoin docs fixes (#5307)

- app/dashboard/templates/bounty/details.html
- app/dashboard/templates/dashboard/sidebar_search_hackathon.html
Fixes
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1575250356374000
> bug: hackathon sidebar fixes

- app/assets/v2/js/pages/new_bounty.js
Sometimes after you setup an ETH value playing with the usd amount didn't update the total value at the end of the page.
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1575324765386700
> trigger change on usd change

- app/assets/v2/css/hackathons/explorer.css
- app/dashboard/templates/dashboard/index.html
- app/dashboard/templates/shared/hackathon_sponsors.html
Based on the discussion over at https://github.com/gitcoinco/web/issues/5484#issuecomment-556081753
> chore: updated hackathon explorer page

- app/assets/v2/css/base.css
- app/assets/v2/css/board.css
- app/assets/v2/css/bounty.css
- app/assets/v2/css/dashboard.css
- app/assets/v2/js/base.js
- app/dashboard/templates/bounty/details.html
- app/dashboard/templates/bounty/fund.html
- app/dashboard/templates/bounty/increase.html
- app/dashboard/templates/dashboard/index.html
- app/dashboard/templates/shared/bounty_categories.html
- mobile: fix up spacing issues in personal modal
- mobile: ensure bounty details have padding in explorer
- mobile + tablet: adding bottom margin for bounty categories
- mobile + tablet: ensure total bounty fee summary doesn't break
- mobile + tablet: ensure bounty detail summary doesn't break
+ a bunch of tiny UI fixes
Fixes
> chore: minor UI fixes across bounty

- docs/CREATING_CELERY_TASKS.md
Adds initial documentation for creating Celery tasks
> Initial Documentation for adding new Celery tasks to the system

- app/dashboard/admin.py
- app/dashboard/helpers.py
- app/dashboard/models.py
- app/dashboard/tests/test_bounty_state.py
- app/dashboard/views.py
This PR provides additional logic to update the `bounty_state` via `BountyEvent` handling.
https://github.com/gitcoinco/web/issues/5329
Tested locally
> Bounty event activity

- app/assets/v2/js/pages/increase_bounty.js
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1575466552394100
> fix crowdfund github_url setting in js

- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/helpers.py
- app/dashboard/templates/bounty/details.html
- app/dashboard/views.py
- updated activity in bounty detail 
- added login mandatory for increase bounty ensuring tips have a sender profile
> chore: crowdfund improvements

- app/dashboard/views.py
> fix tribe tab

- app/dashboard/templates/profiles/header_details.html
- app/dashboard/templates/profiles/tab_tribe.html
> fix chat icon and tribe link

- docs/RUNNING_LOCALLY_DOCKER.md
Currently images are not visible at https://docs.gitcoin.co/mk_setup/. I fixed it by inclusind the correct URL.
https://github.com/gitcoinco/web/issues/4943
This doesn't require any tests as it was a minor fix in the documentation.
> Fix: Image not showing on Installation docs

- app/kudos/templates/share.html
Fix styles overwrite on share kudos modal
> Shared modal styles conflict

- app/retail/templates/bounties/funder.html
Changes to conduct a 5 day test of the glimpse protocol using 3 ConsenSys ads.
Changes limited to `retail/bounties/funder.html`. Our script reuses `<div id=codefund ... />` so no additional modifications needed and we've styled our ad as per codefund's styling.
More info about api calls can be found [here](https://github.com/glimpse-protocol/publisher-js). A recent version of the unminified source can also be found there.
Code changes are minimal so additional testing likely not needed. An live example can be viewed [here](https://staging.glimpseprotocol.io). I've added before and after screenshots to illustrate.
> Glimpse Ad Trial

- app/retail/templates/vision.html
This PR only fix an Small grammar issue on the <code> gitcoin.co/vision </code>
Brave Browser
Chromium
> [Small Fix] Wording issue on Vision

- app/assets/v2/css/grants/new.css
- app/assets/v2/js/grants/new.js
- app/grants/templates/grants/detail/info.html
- app/grants/templates/grants/new.html
- will be shown only to grant team members 
- will be shown until grant is no longer hidden 
GRANT CREATION
GRANT DETAILS PAGE
> show message that grant is being reviewed upon creation

- app/dashboard/templates/bounty/details.html
bug introduced in https://github.com/gitcoinco/web/pull/5688/files
After fix
> bug: fix icon rendering

- .travis.yml
- Dockerfile
- app/assets/v2/js/grants/detail.js
Fix the Geoip download which is causing test failures
https://github.com/gitcoinco/web/issues/5696
Tested via travis
> fix geoip download

- app/grants/views.py
Change phantom funding round to 4
> switch phantom funding round

- app/grants/views.py
Use the new Round 4 Kudos as reward for particupating in CLR round 4
> Set CLR Round 4 kudos

- app/assets/v2/css/base.css
- app/grants/templates/grants/index.html
> chore: prettify load more grants text

- app/marketing/mails.py
This PR improves the quest feedback email so it doesn't look as sketchy.
fixes an issue posted in our community slack channel
not tested
> improve quest feedback email"

- app/grants/clr.py
This PR ensures that only successful contributions are counted towards CLR
untested but simple
> ensure only successful contributions are counted for CLR

- app/grants/templates/grants/detail/index.html
- app/grants/templates/grants/detail/tabs.html
- app/retail/templates/shared/activity.html
- Remove token from showing up in activity which don't need it to be displayed 
[Before](https://user-images.githubusercontent.com/5358146/72160331-2a180a00-33e4-11ea-9317-95a34c297278.png)  | [After PR](https://user-images.githubusercontent.com/5358146/72160520-795e3a80-33e4-11ea-979a-f2e94def9a80.png)
- Fixes weird JSON https://share.vidyard.com/watch/LuaY52XVuR3uzMyr4mNXt8?
closes https://github.com/gitcoinco/web/issues/5748
> chore: fixup activity section + grant description fix

- app/grants/templates/grants/detail/summary.html
- app/grants/templates/grants/detail/tabs.html
Refs https://github.com/gitcoinco/web/issues/5754
> bug: fix milestone+ update text + update tab count

- app/app/context.py
- app/app/settings.py
- app/chat/management/commands/sync_event_bounties_to_chat.py
- app/chat/tasks.py
- app/chat/utils.py
- app/chat/views.py
- app/dashboard/tasks.py
- app/dashboard/views.py
- app/marketing/stats.py
Fixes to the bounty channel creation
Adds a mgmt command so that channels can be created or restored from the command line
> Chat/1.2.1 - bug fixes

- app/assets/v2/js/activity.js
Disable fetching data when tab is not enabled.
> Inactive tab activity

- app/locale/pl/LC_MESSAGES/django.po
- app/locale/zh_Hans/LC_MESSAGES/django.po
- app/locale/zh_Hant/LC_MESSAGES/django.po
- app/retail/templates/newkudos.html
There are a couple of extra s's in a few instances of "license" which I got rid of
> Typo fixes on "liscense"

- app/assets/v2/js/base.js
- app/retail/templates/shared/footer.html
Remove popups on login
Fixes #5771 
clear localstorage and login again. it won't show again.
> Remove product update modal

- bin/docker-command.bash
Tested locally and it works !
removed duplicate fixtures + shfited python -> python3
> python -> python3

- app/assets/v2/js/pages/bounty_details.js
- app/dashboard/router.py
- app/dashboard/templates/bounty/details.html
This PR removes the fulfiller email from the bounty detail activities and fulfiller API
n/a
Tested locally
> remove fulfiller email references

- app/assets/v2/js/pages/bounty_details.js
- app/assets/v2/js/pages/fulfill_bounty/ETH.js
- app/dashboard/templates/bounty/fulfill.html
This PR solves the modal prompting in all event true bounties if the hunter didn't submit a the project when submitting. 
Fix #5860
tested locally
> Fix add new project modal on random bounties

- app/marketing/mails.py
- app/marketing/management/commands/new_bounties_email.py
- app/townsquare/views.py
enables daily email even iff there are no new bounties
bc as we've moved from a bounty site to a general crypto social network.. there is more activity to see than just bounties.
https://gitcoincore.slack.com/archives/CAW05FUD7/p1579216756051800
tested locally
> enables daily email even iff there are no new bounties

- app/retail/templates/shared/top_nav.html
Changes the top banner for the Sustain Web3 Hackathon
Pr so small, doesn't need testing
> Change banner for the next hackathon

- app/dashboard/templates/bounty/invoice.html
- app/dashboard/views.py
This PR adds the platform fee calculation to the bounty invoice
Various issues
Tested locally
> add dynamic bounty fee calculation to invoice

- app/assets/v2/js/pages/cancel_bounty/ETH.js
- app/assets/v2/js/pages/tribe_title.js
- Porting over code from https://github.com/gitcoinco/web/pull/5682 as files have been renamed + split into multiple files (Raised by @zoek1 )
- fix up indentation on tribe title
> duplicate: Fix tip error and kill bounty #5682

- docs/RUNNING_LOCALLY_DOCKER.md
Add special instructions to the documentation for users who want to run docker locally in WSL.
Fixes #4412, fixes #5605.
Refs #4943.
> Document special instructions for running docker locally in WSL

- app/assets/v2/js/users.js
- app/dashboard/templates/dashboard/users.html
https://gitcoin.co/users?persona=Organization
Fix #5735
> add join tribes to directory

- app/dashboard/templates/profiles/tabs.html
> show tribe only on org

- app/grants/models.py
> str -> float

- app/dashboard/templates/profiles/tabs.html
Add the hackathons tab back to the profile removed in https://github.com/gitcoinco/web/commit/a931b65c2f7cdf8f616e30d922342f09bcae232f#diff-90d4e102eac04fa7d8d94977d21e0198L86
@iamonuwa I think that change was yours, please check because all the ID's are the same (ids shouldn't be repeated)
> Add tab hackathons back

- app/assets/v2/css/town_square.css
- app/assets/v2/js/activity.js
- app/retail/templates/shared/activity.html
- app/townsquare/templates/townsquare/index.html
- app/townsquare/views.py
> stable -> master

- app/assets/v2/js/activity.js
Need testing
Delete button on activity instantly remove the activity what about if I somehow unintentionally clicked and remove some valuable stuff
#5837 
Need further testing
> Can't trust the delete button activity on Dashboard

- app/dashboard/models.py
fix error when tribemember user was deleted
https://sentry.io/organizations/gitcoin/issues/1516856914/?project=1398424&referrer=slack
> fix error when tribemember user was deleted

- app/assets/v2/js/activity.js
- app/assets/v2/js/status.js
- app/townsquare/templates/townsquare/index.html
Adds 'shift+enter' as an option to create new lines in Status/Activity comments.
Part of Town Square Imrovmenets: https://github.com/gitcoinco/web/issues/6003
Demo: https://youtu.be/GQ-jEc4K31o
> Add "shift-enter" function to townsquare - New lines can now be made

- app/assets/v2/js/activity.js
- app/retail/templates/shared/activity.html
> Fix Townsquare regex

- app/dashboard/router.py
Fixes the kudos serializer for activity objects
n/a
not yet
> Fix kudos serializer

- docs/RUNNING_LOCALLY_DOCKER.md
> Properly format special instructions for WSL devs

- app/assets/v2/js/pages/join_tribe.js
- app/retail/templates/shared/activity.html
- app/retail/views.py
This PR adds a join tribe button to tribe activity entries in townsquare
n/a
Tested locally
> add ability to join tribe in townsquare activity feed

- app/assets/v2/js/activity.js
Disable the comment button when posting to avoid duplicate comments.
closes https://github.com/gitcoinco/web/issues/6085
> fix: disable comment button on post
