app/retail/templates/shared/activity.html
=> [Small Fix] Wording "Got A distribution of"

app/app/urls.py, app/marketing/mails.py, app/marketing/views.py, app/retail/emails.py, app/retail/templates/emails/new_bounty.html, app/retail/templates/emails/quest_small.html, app/retail/templates/emails/shared_quest_actions.html
This PR adds a section to the daily email to add a trending quests section
n/a
Tested locally
=> Trending quests in daily email

app/retail/templates/shared/activity.html
#6111
Add the quest link to the kudos image.
=> add: meta_quest link on kudos 

requirements/base.txt
updates markdown package to fix the wiki
=> updates markdown package

app/assets/v2/css/submit_bounty.css, app/assets/v2/js/pages/bounty_details2.js, app/assets/v2/js/pages/bulk_payout.js, app/assets/v2/js/pages/cancel_bounty/ETH.js, app/assets/v2/js/pages/create_bounty/token.js, app/assets/v2/js/pages/faucet_form.js, app/assets/v2/js/pages/fulfill_bounty/ETH.js, app/assets/v2/js/pages/increase_bounty.js, app/assets/v2/js/pages/new_bounty.js, app/assets/v2/js/pages/process_bounty.js, app/assets/v2/js/pages/refund_request.js, app/assets/v2/js/shared.js, app/dashboard/templates/bounty/details2.html, app/dashboard/templates/bounty/fund.html, app/dashboard/views.py, app/grants/templates/grants/new.html, app/retail/templates/pricing/subscribe.html
- shows wallet connect checks only when ERC20/ETH is selected
- prompts funder address when ETC is selected
- removed ability to add funder address of payout popup
=> fix web3connect in bounty create flow

app/assets/v2/js/activity.js
Add Comment Count to Show More Link in Town Square #6210
=> Add Comment Count to Show More Link in Town Square

app/assets/v2/js/activity.js, app/dashboard/tests/test_users_list.py
=> do not merge - seeing whats up with travis

app/app/settings.py, app/app/urls.py, requirements/test.txt
Cherry-picking commit from https://github.com/gitcoinco/web/pull/6200
=> adds django debug toolbar

docs/RUNNING_LOCALLY_DOCKER.md
Updates with one troubleshooting tip for problems with high CPU usage on mac while installing with docker and links to issues on this topic from docker's for mac repo.
https://github.com/gitcoinco/web/issues/6310
This is a documentation change.
=> troubleshooting docker and mac high cpu usage

app/assets/v2/js/landing_page.js
- [Can't find variable: moveBackground](https://sentry.io/organizations/gitcoin/issues/1567040592
)
=> bug: sentry fixes

app/dashboard/management/commands/sync_pending_fulfillments.py, scripts/crontab
- Set it to run every 5 minutes
- rename cron to `sync_pending_fulfillments.py`
=> chore: add sync_pending_fulfillments to cron

app/assets/v2/js/grants/fund.js
=> fix eslint

app/assets/v2/js/activity.js
Fixes show more comments count
=> fix show more count

app/app/urls.py, app/assets/v2/css/base.css, app/assets/v2/js/activity.js, app/assets/v2/js/pages/join_tribe.js, app/assets/v2/js/user_card.js, app/dashboard/views.py, app/retail/templates/shared/activity.html, app/townsquare/templates/townsquare/index.html
Add popover card to townsquare with profile information and graph to quickly understand the user use of the platform. 
Close #6293
https://share.vidyard.com/watch/XzirKkLDTXqhYoezZBjYAz?
=> Users popover card

app/app/utils.py, app/marketing/management/commands/assemble_leaderboards.py
refactors the GEOIP object not to thrash the disk IOPS
previously the 60 MB object was being loaded from disk everytime we tried to lookup the location of each of our 40k transactions that have happeend on the site. which is of course intensely wasteful.
Engineering convos this morning
on my local:
```
loaded geoIP singleton from DISK
loaded geoIP singleton from CACHE
loaded geoIP singleton from CACHE
loaded geoIP singleton from CACHE
loaded geoIP singleton from CACHE
```
=> refactors the GEOIP object not to thrash the disk IOPS

pydocmd.yml
=> temp fix pydoc google analytics

app/assets/v2/js/vue-components.js, app/dashboard/templates/profiles/tribes-vue.html
=> Add suggested profiles component

app/retail/templates/emails/bounty_roundup.html
Fixes codefund button text color in weekly roundup
n/a
tested locally
=> fix codefund button color

app/retail/emails.py
Follow up PR to #6438 
Makes the kudos images center aligned.
#6208, #6438
=> Make kudos center aligned. Follow-up to #6438 

app/assets/v2/css/quests.css
fix #6517 
Still testing to avoid 
special thanks to @rahulkrishna-web for pointing out the visual
=> Change color selected answer on Quests coupling background visually

app/assets/v2/css/activity_stream.css, app/assets/v2/css/base.css, app/assets/v2/css/colors.css, app/assets/v2/css/forms/input.css, app/assets/v2/css/gitcoin.css, app/assets/v2/css/notifications.css, app/assets/v2/css/theme_switcher.css, app/assets/v2/css/town_square.css, app/assets/v2/js/activity.js, app/dashboard/templates/profiles/status_box.html, app/dashboard/templates/shared/menu.html, app/dashboard/templates/shared/nav_auth.html, app/dashboard/templates/shared/theme_switcher.html, app/retail/templates/shared/activity-vue.html, app/retail/templates/shared/activity.html, app/townsquare/templates/townsquare/shared/shareactivity.html
- Fix styles to fit the design.
- move button under dropdown
- style all missing elements
- fix colors for readability 
https://share.vidyard.com/watch/mBRd33knCWnFNqiqZpdjiR?
=> fixes for darkmode

app/assets/v2/css/profile.css, app/dashboard/templates/profiles/tribes-vue.html
=> Add org townsquare responsive fixes

app/marketing/mails.py
fixes trending quests not appearing in new bounty email
n/a
tested locally
=> Fix trending quests

app/grants/clr.py, app/grants/templates/grants/card/clr_match.html, app/grants/templates/grants/card/front.html, app/grants/templates/grants/detail/info.html, app/grants/views.py
This PR sets up grants Round 5.5 for 6 specific grants
n/a
tested locally
```
from grants.models import Grant
blank_clr = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]
round_5_grants = Grant.objects.filter(id__in=[656, 493, 494, 502, 504, 662]).all()
for g in round_5_grants:
g.clr_prediction_curve = blank_clr
g.positive_round_contributor_count = 0
g.negative_round_contributor_count = 0
g.amount_received_in_round = 0
g.save()
```
=> Grants 5.5

app/dashboard/templates/dashboard/index-vue.html
- When a hackathon is not yet started, change the CTA from quests to townsquare
=> Hackathon Flow Update

app/assets/v2/js/pages/tokens_settings.js, app/assets/v2/js/tokens.js
hardcode mainnet tokens on /settings/tokens page 
we get a support request about this like twice a week.  rather than keep on trying to explain it, i think we should just show the mainnet tokens in all cases.
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1588720173226000
tested locally
=> hardcodes tokens to mainnet on tokens page

app/dashboard/views.py
Move the response for the tribes request further up the chain
=> Tribes Request performance boost

app/assets/v2/js/pages/bounty_details.js
makes sure that start works and submit works are only shown once on bounty detail page
inspired by this bounty
=> uniqueness on bounty page

app/dashboard/templates/dashboard/index-vue.html, app/dashboard/templates/dashboard/users.html, app/dashboard/templates/profiles/tribes-vue.html
#6610 
**Hacking 45% percent....**
=> Pop Over Across Site

app/dashboard/tests/test_dashboard_models.py
=> fix travis

app/townsquare/utils.py
Change the can_pin helper to prevent pinning on the wild card searches.
=> Don't allow pinning on wildcard searches

app/dashboard/views.py
Migrate to use the get_tags helper from townsquare/views
=> Fix to render tribes townsquare filters unselected.

app/retail/views.py
This PR remove the incorrect entry for Gitcoinbot's Linkedin in our about section - the account was never registered so a security researcher registered it and informed us in a vulnerability report.
n/a
Tested locally
=> remove incorrect linkedin for gitcoinbot in about

app/dashboard/templates/bounty/fulfill.html
As a hackathon participant, I want to ensure I don't forget to include a link to my project with my submission so my work gets considered.
https://github.com/gitcoinco/web/issues/6683
=> Link project is required

app/dashboard/router.py
fixes an issue with view counts code
tested locally
=> fix typo in sitewide viewcounts

app/dashboard/helpers.py
fixes the view count issue that aditya found in regression testing
https://gitcoincore.slack.com/archives/CDML7FS7M/p1590682070002500?thread_ts=1590596639004900&cid=CDML7FS7M
tested locally
=> fixes the view count issue

app/retail/emails.py
=> revert breaking premailer fix (#6743)

app/app/urls.py, app/dashboard/views.py, app/faucet/templates/bulk_DM.html, app/retail/templates/admin/index.html
a simple admin tool to send bulk DMs on gitcoin chat. useful for getting the word out in a personalized, but secretly automated, way.
https://gitcoincore.slack.com/archives/CSE21LF9P/p1590121390180800
=> admin bulk DM tool

docs/API.md
Adds documentation for grants api endpoint: https://gitcoin.co/api/v0.1/grants
Refers #4943
=> Documentation for  /grants api endpoint

app/assets/onepager/js/request.js, app/dashboard/models.py, app/dashboard/templates/request_payment.html, app/dashboard/tip_views.py
requests money form UX fixes
- prefill preferred payout addr
- prevent ppl from requesting from self
- force users to leave comment
- easier to view request send from form
convos in slack with connor
tested locally
=> requests money form UX fixes

app/dashboard/templates/dashboard/index-vue.html, app/dashboard/templates/dashboard/sidebar_search_hackathon.html
closes https://github.com/gitcoinco/web/issues/6651
=> chore: make hackathon page responsive

app/retail/templates/tribes/landing.html
=> bug: fix tribe follower count

app/assets/v2/js/cart.js, app/grants/models.py, app/grants/serializers.py, app/grants/templates/grants/bulk_add_to_cart.html, app/grants/templates/grants/card/front.html, app/grants/templates/grants/cart-vue.html, app/grants/templates/grants/detail/funding.html, docs/GRANTS.md
Changes:
- Fix safari stretch CSS bug (https://github.com/ScopeLift/gitcoin-web/issues/38)
- GRANTS.md updates (https://github.com/ScopeLift/gitcoin-web/issues/42)
- Auto-update % contribution to gitcoin (https://github.com/ScopeLift/gitcoin-web/issues/72)
- Implement helpers from https://github.com/gitcoinco/web/pull/6696
- Fix to ensure no negative values at checkout. (This got removed somehow) (https://github.com/ScopeLift/gitcoin-web/issues/67)
- Fix syntax (https://github.com/gitcoinco/web/commit/e76f9b430023f64e700cbeee88328ea7e5a58a01#comments)
- Cart page now defaults to mainnet if no provider is found
- Checkout brings up web3modal if no provider is found on checkout
=> Various updates

app/grants/templates/grants/cart-vue.html
https://www.loom.com/share/7c99fb9831ba49e297cb2a5103b80fd4
https://github.com/ScopeLift/gitcoin-web/issues/76
https://github.com/ScopeLift/gitcoin-web/issues/79
=> Fix display verfication 

scripts/crontab
This PR disabled clr calculation for round 5.5, thus finalizing the round
n/a
n/a
=> End round 5 5

app/assets/v2/js/pages/create_bounty/ETH.js, app/assets/v2/js/pages/new_bounty.js, app/assets/v2/js/wallet.js
Check token allowance based on bounty value
don't pop transactions until allowance is enough.
Fix big numbers (BigInt)  as values 1000+  were failing
=> check allowance

app/grants/models.py
fix missing import
https://sentry.io/organizations/gitcoin/issues/1727365924/?project=1398424&referrer=slack
=> bug: sentry alert

app/dashboard/views.py
=> fixed: Showing Bounties Funded on org activity_tabs

app/assets/v2/css/submit_bounty.css
closes #6884 Remove Border Red
=> fixed:  Reserved box 

app/assets/v2/js/pages/bounty_details2.js, app/dashboard/admin.py, app/dashboard/management/commands/sync_pending_fulfillments.py, app/dashboard/sync/zil.py
This PR fixes some final issues with the ZIL implementation
n/a
tested locally
=> zil fixes: handle 0x0 txn data

app/assets/v2/css/grants/cart.css, app/assets/v2/js/cart.js, app/grants/templates/grants/cart-vue.html
https://www.loom.com/share/4687808141994bb28282a6d2e5770b71
=> Add sugested comments

app/retail/templates/shared/grant_thanks_modal.html
=> fixed: remove margin-top on tweetModal for fixed bug on edge browser

app/grants/clr.py
=> chore: account for unverified profiles

app/grants/clr.py
=> Revert "chore: account for unverified profiles"

app/grants/clr.py
=> sms verified calculation

app/marketing/mails.py, app/retail/templates/emails/new_bounty.html
=> show no daily action

app/dashboard/tests/test_tokens.py
fixes broken test with tokens
n/a
tested locally
=> fix token test

app/assets/v2/js/pages/kudos_send.js
fixes issues with bignum conversion for kudos send
n/a
tested locally
=> fix bignum/bigint conversion for kudos send

app/retail/templates/about.html
About page
Quotation on the profile handle
=> Quotation on Profile handle

docs/README.md
=> Unavailable network link

app/grants/templates/grants/card/front.html, app/kudos/templates/kudos_details.html, app/retail/templates/leaderboard.html
=> User Card Grants/Podium/Kudos

app/assets/v2/css/quests.css, app/quests/templates/quests/index.html
This PR will add a "Info" button on description row so it shows heavy long description text on hover
=> Info on Description row

app/assets/v2/css/gitcoin.css, app/assets/v2/css/town_square.css
simple fixed z-index position
Nav-badge
=> fixed sticky-top because new hacker town square post card

app/retail/templates/tribes/landing.html
Change url for getting started CTA
https://gitcoincore.slack.com/archives/CMU93BVJQ/p1595273962000300
=> Change url for getting started CTA

app/dashboard/templates/dashboard/sponsors.html
- Sponsor Dashboard Responsive
- Show Accordion only if prize has submissions
- Replace Unpaid link with Pay Button 
- Update background of card to white + give the UI more space to breathe 
https://share.vidyard.com/watch/GiZK5RkYrQ99pvZW5GQ93Q?
=> dashboard tweaks + fixes

app/dashboard/admin.py, app/dashboard/utils.py, app/dashboard/views.py, app/townsquare/views.py
=> chore: show hackathons 28 days before they start

app/marketing/management/commands/bounty_feedback_email.py
https://sentry.io/organizations/gitcoin/issues/1683203358/?project=1398424&referrer=slack
=> bug: fulfiller_email -> profile.email

app/marketing/webhookviews.py
https://sentry.io/organizations/gitcoin/issues/1716270029/?project=1398424&referrer=slack
=> bug: account for IPV6 in sendgrid

app/retail/templates/cookielaw/banner.html
Fix a minor typo in the gitcoin GDPR banner.
=> Fix typo in banner

app/kudos/tasks.py
https://sentry.io/organizations/gitcoin/issues/1506566643/?project=1398424&referrer=slack
=> add timeout exception handling

app/assets/v2/css/vision.css, app/retail/templates/vision.html
Fix for the timeline vision timeline
Fixes #7237
=> Timeline Vision Data Issue fix

app/kudos/tasks.py
https://sentry.io/organizations/gitcoin/issues/1506566713/?project=1398424&referrer=slack
=> sentry: gracefully exit on max timeout

app/dashboard/templates/bounty/details2.html, app/dashboard/templates/bounty/new_bounty.html, app/dashboard/templates/dashboard/hackathon/projects.html, app/dashboard/templates/project/detail/info.html, app/dashboard/views.py, app/retail/templates/shared/activity.html
fix urls to point to single project pages
fix logo if doesn't exist default to org prize (as in the other areas)
fix new bounty rate hours estimate.
=> fix projects activity, logo, and urls

app/grants/views.py, app/perftools/management/commands/create_page_cache.py
update stats view code to prevent erroring out during Grant Stats creation
=> bug: fix create_cache

app/retail/templates/vision.html
=> Typo "market" vision

app/retail/templates/emails/bounty_roundup.html
https://www.loom.com/share/e208b414da1a4209bd1b502cc7d85b34
=> fix margins on roundup

app/assets/v2/js/cart.js, app/grants/templates/grants/cart-vue.html
Changes:
- Add gas limit estimates for approval transactions
- Fix for Argent 
- Fix for BN not loading
- Add spacing above buttons for better appearance on mobile
=> Additional cart improvements

app/assets/v2/js/grants/detail.js, app/grants/templates/grants/detail/index.html, app/grants/templates/grants/detail/info.html, app/grants/views.py
#7380
#7385
#7389
#7390 
#7392 
#7399
#7396
=> Always show edit and add instruction to verifiy account

app/dashboard/brightid_utils.py
=> Use SSL URLS for BrightID Integration

app/dashboard/brightid_utils.py
=> Fix sponsorship operations URL for BrightID

app/grants/models.py
This PR updates the tx validator to provide more details about what went wrong when a zkSync transaction for a contribution was not found
=> Improve validator comments

app/grants/templates/grants/governance_detail.html
Hello w0rld! First gitcoin commit - Adding sybil attack and grant weight to governance details page.
=> hello gitcoin world! first commit - Add sybil & grant weight

app/marketing/tests/management/commands/test_new_bounties_email.py, app/marketing/tests/management/commands/test_roundup.py
=> fix import

app/grants/templates/grants/faq.html, app/grants/templates/grants/quickstart.html
* We no longer support subscriptions
* Anyone can use grants
=> fix(faq): update info on grants

app/assets/v2/js/jobs.js, app/dashboard/templates/profiles/tab_resume.html
Fix issue with profile editing via resume tab.
Here's a [video recording](https://drive.google.com/file/d/1uFBoQ4RNpedQeodKuWipHvych4HrIKcO/view?usp=sharing)
=> fix(profile): fix profile edit in resume tab

app/dashboard/templates/dashboard/index-vue.html, app/dashboard/views.py
https://www.loom.com/share/285ba5e08f2b427a8792e5c7b2787be7
=> Hide events when no calendar id is associated

app/assets/v2/js/onboard.js
change datalayer to trigger the right event on save for GTM
=> change datalayer on save

app/marketing/mails.py, app/retail/emails.py
Follow-up to #7146 
Replaces usage of **`sponsors`** with **`sponsor_profiles`** as per the comment: https://github.com/gitcoinco/web/pull/7146#discussion_r497714006
Fixes #7146, #7140
=> Use sponsor_profiles instead of sponsors

app/dashboard/templates/profiles/header_details.html
Add bio and interests to profiles if not present use the github bio (old)
All interests selected
=> add new fields to profile

app/assets/onepager/js/confetti.js
Renaming the function name as its name conflicts with another variable name in onboard.js
Fixes #7598
=> Fix error when sending tip

app/dashboard/models.py, app/townsquare/views.py
=> Revert "(townsquare) fix/show only mainnet bounty activities in prod"

app/grants/templates/grants/cart-vue.html
Bump zksync.js from 0.6.4 to 0.7.2
=> Bump zksyncjs version

app/dashboard/templates/bounty/new_bounty.html, app/dashboard/templates/dashboard/hackathon/new_bounty.html
=> open up polkadot to public

app/assets/v2/js/grants/detail.js, app/grants/templates/grants/detail/info.html
=> Revert "Fix grant view/edit page"

app/assets/v2/js/cart.js, app/assets/v2/js/grants/funding.js
- Ethereum standard checkout works successfully
- zkSync checkout needs to be tested
- Donation summaries in Ethereum tab are correct
=> ZCash-Ethereum cart fixes

app/dashboard/templates/shared/newsletter.html
This PR updates the mailchimp list ids and urls hardcoded into the templates
n/a
n/a
=> switchover mailchimp form links in stable

app/grants/views.py
This PR fixes the issue reported where Matic grants were not saving correctly
https://github.com/gitcoinco/web/issues/7759
Tested locally
=> fix matic grants not saving

app/assets/v2/js/cart.js, app/grants/templates/grants/cart-vue.html, app/grants/templates/grants/detail/funding.html
Fixes "Apply to All" functionality for Ethereum carts. This fix assumes that all grants accept all tokens of that chain
=> Fix apply to all functionality

app/grants/management/commands/sync_pending_contributions.py, app/grants/sync/helpers.py, app/grants/sync/zcash.py, app/grants/views.py, scripts/debug/run_perftools.py
- email gets sent to user on clicking payout (doesn't wait for confirmation)
- entry in transaction tab is marked as pending state
=> showing txn in pending state

app/retail/templates/emails/grants/successful_contribution.html, app/retail/templates/emails/grants/successful_contribution.txt
This PR removes Etherscan specific language from succcessful grant contribution emails
n/a
untested
=> Explorer agnostic language

app/assets/v2/js/cart.js, app/assets/v2/js/onboard.js, app/assets/v2/js/pages/townsquare.js, app/grants/sync/zcash.py, app/grants/templates/grants/cart-vue.html, app/grants/templates/grants/transaction.html, app/grants/views.py, scripts/debug/output_weekly_mailing_list.py
=> Zcash txid support

app/grants/urls.py, app/grants/views.py, app/marketing/mails.py, app/retail/emails.py, app/retail/templates/emails/grants/grant_cancellation.html, app/retail/templates/emails/grants/grant_cancellation.txt
- have a new POST endpoint for cancel grant
- update email text
Fixes: https://github.com/gitcoinco/web/issues/7907
=> add new endpoint for grant cancellation

app/app/fixtures/grants.json, app/assets/v2/js/cart-ethereum-zksync.js
Changes:
- Adds missing `grant_type` field to default Rinkeby grants
- Updates zkSync gas estimate per transfer based on actual expected costs
=> Add missing grant_type field + gas estimate update

app/assets/v2/css/grants/collection.css, app/assets/v2/js/grants/components.js, app/grants/templates/grants/components/collection.html
Redo collections card UI as per design from @PixelantDesign on the landing page
closes https://github.com/gitcoinco/web/issues/7750
https://www.loom.com/share/2f178784eb6843fe870930a39138ec63
=> ui: redo collection UI #7750

app/retail/templates/emails/grants/new_grant.html
adds a new button that links to "Maximize your grant" blog post.
Fixes: https://github.com/gitcoinco/web/issues/7753
=> add "maximize your grant" blog link to new grant email

app/dashboard/templates/profiles/trust-vue.html, app/dashboard/views.py
Fix Idena verified badge not showing.
https://github.com/gitcoinco/web/pull/7646#issuecomment-734251649.
=> Fixing idena verified badge

app/grants/views.py
https://www.loom.com/share/477c618208e94688ab05c3b9189e85cb
=> Fix display of some collections

app/assets/v2/js/grants/_detail-component.js, app/assets/v2/js/grants/components.js, app/dashboard/views.py, app/grants/templates/grants/components/card.html, app/grants/templates/grants/detail/template-grant-details.html
- Fix checkIsCurator, now is space and '@' aware
- Fix removeCollection due to some browser doesn't construct the object properly
- Make optional the '@' in twitter handles
- Extract the username from twitter urls
- Validate twitter accounts using twitter urls and handles, also manage the '@' scenario
https://www.loom.com/share/2f6cabf8424b4a2b8e4fae3e841a4804
https://github.com/gitcoinco/web/issues/7947
=> Fixes grants 8

app/grants/tasks.py, app/grants/views.py
Fixes for backend twitter validation
* validate twitter handle in grant edit flow
* include '@' if it wasn't included in frontend
=> fix(grants): backend twitter validation

app/assets/v2/js/grants/_new.js
This PR allows twitter handles starting with @ or just starting with the alphanumeric handle characters to be used and not stopped by frontend validation if missing the @ symbol
GR8 fix
tested locally
=> fix twitter username validation in frontend

app/grants/views.py
This PR fixes the edit grants functionality which was broken because of a logic issue with how the address field was validated.
gr8 fix
Tested locally
=> GR8 regression - cant edit grants fix

app/grants/models.py, app/grants/utils.py
Run to populate collection thumnails
`docker-compose exec -e DJANGO_SETTINGS_MODULE="app.settings" web python3 app/manage.py build_collection_thumbnails`
https://gitcoincore.slack.com/archives/C01FQV4FX4J/p1606872074058300?thread_ts=1606868002.055200&cid=C01FQV4FX4J
=> request image from remote hosts

app/grants/utils.py
https://gitcoincore.slack.com/archives/C01FQV4FX4J/p1606886189063400?thread_ts=1606868002.055200&cid=C01FQV4FX4J
=> Replace request of static files with internal files

app/grants/templates/grants/bulk_add_to_cart.html
fix blank share cart page
https://github.com/gitcoinco/web/issues/7947#issuecomment-737368908
=> fix blank share cart page

app/grants/sync/helpers.py, app/grants/tasks.py, app/grants/utils.py, app/marketing/mails.py, app/retail/emails.py, app/retail/templates/emails/grants/thank_you_for_supporting.html
=> Revert bulk stable

app/assets/v2/js/cart-ethereum-zksync.js
Adds zksync component listener for wallet changes. This way we can make sure the zksync checkout manager and gas estimates are always correct based on the user's wallet section.
=> zkSync state and gas estimates now respond to wallet changes

app/assets/v2/js/grants/_detail.js, app/grants/templates/grants/detail/_index.html, app/grants/urls.py, app/grants/views.py
move transaction tab to rest json
=> tx to json

app/grants/models.py
Ensure amount_per_period_minus_gas_price is not 0 if contribution is made Gitcoin Grant
=> ensure amount_per_period_minus_gas_price is not 0 

app/assets/v2/js/cart-ethereum-zksync.js, app/assets/v2/js/cart.js, app/assets/v2/js/grants/_detail-component.js, app/assets/v2/js/grants/_detail.js, app/grants/views.py
Properly encode twitter verification text.
Grant titles with special characters e.g. [Pictosis: The Open Web for Digital Goods & Creative Economies](https://gitcoin.co/grants/1663/pictosis-the-open-web-for-digital-goods-creative-) and [@futurebank](https://gitcoin.co/grants/@futurebank) break from the point of the special character.
here's an example of a broken tweet: https://twitter.com/pictosis/status/1334510395411804163?s=20
#8026 #8027 #8020 #8012 
https://www.loom.com/share/b1758278d2ef4ad0aec0d9630f9e4c08
Co-authored-by: @octavioamu
=> fix(grants): properly encode twitter verif text

app/assets/v2/js/grants/_detail-component.js, app/assets/v2/js/grants/_new.js
=> chore: show error message to not allow ENS name

app/assets/v2/js/cart.js
Closes https://github.com/gitcoinco/web/issues/8112
=> Update gas limit estimate for BADGER

app/taskapp/celery.py
This PR adds configuration for celery tasks to allow the datadog agent to profile and deliver metrics on tasks.
n/a
tested locally by doing a standard ETH grants checkout
=> add datadog tracing for celery tasks

.travis.yml, docs/README.md
This PR removes codecov, which we aren't using/paying attention to much, as well as its crowding the PR reviews with automated warnings now making reviewing difficult.
n/a
n/a
=> remove codecov

app/grants/models.py, app/grants/templates/grants/cart-vue.html
=> if grant has no ROUND NUM -> show message not in active CLR

app/assets/v2/js/cart-ethereum-zksync.js, app/grants/templates/grants/detail/template-grant-details.html
Previously when `web3` was undefined, `this.user.address = (await web3.eth.getAccounts())[0];` would throw an error which showed int he console. We now explicitly handle this case.
@thelostone-mc Before merging, please do a few refreshes to make sure the error doesn't show up, and try some checkouts as well since we modified the checkout logic!
=> Handle web3/zksync errors

app/retail/views.py
Add Solexplorer to the about page. CC @owocki
=> Add myself to the about page

app/grants/management/commands/analytics_clr.py
removed phantom variables that were unused
none
tested with a matic CLR pull
=> Fix analytics_clr script

app/townsquare/clr.py, requirements/base.txt
The pandas doens't have a version and is currently breaking stuff. A deeper look indicates that pandas is not being used. Hence why we are removing the import and unused import.
=> Remove pandas

app/retail/emails.py
Even though chat has been removed from gitcoin, the configuration still exists in email settings. This PR removes it from settings.
fixes #8170
=> Remove chat emails from settings

app/dashboard/templates/bounty/new_bounty.html, app/dashboard/templates/dashboard/hackathon/new_bounty.html
Remove duplicate chains - BTC, PayPal, Harmony
=> remove duplicate chains in bounty/new

app/assets/v2/js/pages/new_bounty.js, app/dashboard/templates/bounty/new_bounty.html
- updated getParams method of Vue.mixin in new_bounty.js to populate form.issueURL if url has 
param with name "url" or "source"
- Also trigger vm.getIssueDetails if url is found in params in getParams method itself
- Update new_bounty.html template to render issueURL from correct context variable
https://user-images.githubusercontent.com/3512277/104272155-911e4200-54c2-11eb-9f65-148e2fb51131.mp4
Fixes: https://github.com/gitcoinco/web/issues/7364
No new functionality added
=> Resolve gitcoin.co/new?url=X no longer works

app/marketing/views.py
When the email is updated in GitHub, the account on gitcoin still holds the old email address.
closes #8167
https://www.loom.com/share/62a3b153541e4d458a0b64abaf1767e0
=> Update Email Address from Github

app/assets/v2/js/pages/new_bounty.js
https://share.vidyard.com/watch/ykWqMHR9wELvbBW7W2skDz?
fixes: https://github.com/gitcoinco/web/issues/8261
=> chore: prevent PR link being submitted in bounty creation

app/grants/views.py
Implements the suggestion in https://github.com/gitcoinco/web/pull/8274#discussion_r565474249 to change print statements to log statements in the `ingest_contributions` view
cc @owocki @thelostone-mc
=> Change  print statements to log statements

app/assets/v2/css/bounty.css, app/dashboard/templates/bounty/details.html, app/dashboard/templates/bounty/details2.html
If I input the expression with a line break and then submit it, it gathers all the content to the same line. It is expected that the content showing should break the line same as users input it
closes https://github.com/gitcoinco/web/issues/8270
Before
After
=> Add line break

app/dashboard/models.py
makes blocknative API only use mainnet txns
blocknative discord
tested locally
=> makes blocknative API only use mainnet txns

app/assets/v2/js/grants/_detail-component.js, app/retail/templates/settings/email.html
Sync email pref with mautic when user submit changes.
- create fields on mautic contact
=> add sync email pref from settings

app/grants/tasks.py
Tests are failing on grants/tasks.py - @tarunbhm added an extra import then removed it before the branch was merged. 
We no longer need to split the import across multiple lines.
Refers: https://github.com/gitcoinco/web/pull/8258
Tested locally 
Before:
After:
=> Fixes regression in grants/tasks.py

app/assets/v2/css/onboarding_v2.css, app/assets/v2/js/grants/index.js
Fixes stylelint and eslint errors
- stylelint:fix and reorders (no-descending-specificity) _(./app/assets/v2/css/onboarding_v2.css)_
- eslint:fix and drops unreachable code _(./app/assets/v2/js/grants/index.js)_
- drops left over console.log _(./app/assets/v2/js/grants/index.js)_
fixes: #8047
=> Fixes linting errors (stylelint & eslint)

app/grants/admin.py
- Adds polkadot_payout_address & kusama_payout_address to admin fields
Refers: #8269
=> Adds polkadot_payout_address & kusama_payout_address to grants/admin.py fields

app/assets/v2/js/grants/index.js, app/grants/views.py
- views.py - sends js readable values when missing background/banner image
- index.js - rescopes toggleStyle to the top of the document so that its immediately available 
fixes: #8047
views.py issue
index.js issue
=> Fixes bugs in grants page (frontend & backend)

app/app/templates/shared/sentry.html, app/dashboard/templates/ftux/avatar.html, app/grants/templates/grants/faq.html, app/grants/templates/grants/index.html, app/inbox/templates/inbox.html, app/ptokens/templates/shared/ptokens_buy_faq.html, app/ptokens/templates/shared/ptokens_faq.html, app/ptokens/templates/shared/ptokens_make_faq.html, app/retail/templates/email_unsubscribed.html, app/retail/templates/emails/recap/weekly_founder_recap.html, app/retail/templates/shared/footer_scripts.html, app/retail/templates/shared/footer_scripts_lite.html, app/retail/templates/shared/head.html
=> remove crossorigin

app/retail/templates/admin/change_form.html
`arketing/roundupemail` >>> `marketing/roundupemail`
from recent merge conflict resolution i guess?
=> fix: typo arketing/roundupemail

app/assets/v2/js/mautic.js, app/grants/urls.py, app/grants/views.py, app/kudos/models.py, app/kudos/templates/kudos_details.html, app/kudos/views.py, app/marketing/management/commands/post_data.py, app/marketing/views.py, app/retail/templates/results.html, docs/API.md, scripts/crontab
allows the pull of grant social info for https://github.com/gitcoinco/web/issues/8039
fixes https://github.com/gitcoinco/web/issues/8039
tested locally, checkout this data https://gist.github.com/owocki/b3f948def707ccee9a21a5b5dc11945c
=> fixes https://github.com/gitcoinco/web/issues/8039

scripts/deploy.bash
sets datetime of server to prevent https://gitcoincore.slack.com/archives/CAXQ7PT60/p1610986391011200
happened today on the celery server
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1610986391011200
tested locallly
=> sets datetime of server on deploy to prevent https://gitcoincore.slack.com/archives/CAXQ7PT60/p1610986391011200

app/assets/v2/js/lib/binance/utils.js
=> hotfix: rm unused binancechain listeners

app/retail/templates/shared/activity.html
contribution amounts ain't showing
=> hotfix - don't normalize metadata values

app/assets/v2/scss/onboarding_v2.scss, app/dashboard/templates/dashboard/hackathon/onboarding_v2.html
- Allows the modal to be scrollable again
- Adds a close button so that the user can exit early (I'm not sure if this was deliberately left out before?)
Fixes: #8440
https://www.loom.com/share/8c075e5931ed4faf8513c3f77ce0a150
=> Fixes scroll and adds a close button to onboarding modal

app/assets/v2/js/cart.js, app/grants/templates/grants/cart-vue.html, app/grants/templates/grants/cart/eth.html
Replaces #8375
- Some styling needs to be updated, since it seems some styles are no longer correct after changes made to `gpg/new-components` after this branch was started
- Mobile view is not yet implmented
However, my understanding of our new workflow is that it's ok to merge this PR into `grants-9`, and the above two bullets can be fixed in a separate PR
=> Start cart page refactor

app/grants/admin.py, app/grants/tasks.py, app/grants/templates/grants/detail/funding.html, app/grants/templates/grants/detail/template-grant-details.html, app/grants/views.py, app/retail/templates/admin/change_form.html, app/retail/templates/emails/grants/new_grant.html
This PR ensures only approved grants can show in /grants or can be eligible for clr
workflow checklist 👇 
upon grant creation,
when grant approved
closes #8410
https://www.loom.com/share/f59a31e4b7fb4e2ab837fa48eca825bd
=> require explicit approval for new grants

app/assets/v2/js/grants/index.js, app/grants/templates/grants/index.html, app/grants/views.py
- bulk add doesn't work as expected when no type is selected on dedicated CLR page
- This PR populates clr_pk on the clr page -> which is passed as a query param to the bulk add param
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1614276119230100
https://share.vidyard.com/watch/yTBSJ4xB2bQ9ejjzKSLvDQ?
=> bug: ensure bulk add works on CLR page

app/app/urls.py, app/grants/admin.py, app/marketing/mails.py, app/retail/emails.py, app/retail/templates/emails/grants/new_grant_approved.html, app/retail/templates/emails/grants/new_grant_approved.txt
Send an email to grant owner when grant is approved
=> feat: new grant approved email

app/grants/templates/grants/cart/extension/rsk.html
change https://explorer.rsk.one/#/tx/ to https://explorer.rsk.co/tx/
=> fix rsk explorer link

app/retail/templates/emails/grants/new_grant.html
=> revised verbiage

app/app/static_storage.py, app/app/urls.py, app/assets/v2/js/grants/grant-thanks-modal.js, app/grants/admin.py, app/grants/models.py, app/grants/urls.py, app/grants/utils.py, app/grants/views.py, app/retail/templates/admin/change_form.html, app/retail/templates/shared/grant_thanks_modal.html
fixes the pixelation of the collection images, and also allows generation of them without creating a collection (esp upon checkout)
https://github.com/gitcoinco/web/issues/8483
pixelation reported by @ceresstation ; the cart images being wrong reported by me
tested locally
=> fixes the pixelation of the collection images, and also allows generation of them without creating a collection (esp upon checkout)

app/grants/templates/grants/detail/template-grant-details.html
=> show total amount

app/grants/tasks.py
…to compress issues
prevent contributions from not saving if the email can't be sent due to compress issues
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1615413871053600
tested locallly
=> prevent contributions not saving if compress issue 

app/grants/management/commands/grant_related.py, app/grants/tasks.py, app/retail/views.py, app/search/views.py, app/townsquare/tasks.py, scripts/debug/fix_grants_stats.py
=> rate limit tokens api

app/grants/management/commands/grant_related.py, app/grants/tasks.py, app/retail/views.py, app/search/views.py, app/townsquare/tasks.py, scripts/debug/fix_grants_stats.py
=> Revert "rate limit tokens api"

app/grants/templates/grants/shared/active_clr_round.html
The wallet modal is loading behind the QF cards - this will push the QF cards back
https://github.com/gitcoinco/web/issues/8483#issuecomment-797584790
Tested locally
=> Fixes z-indexing on active QF cards

app/grants/templates/grants/cart-vue.html
Reorders v-if blocks so that we don't show empty before fetching
Fixes: https://github.com/gitcoinco/web/issues/8597#issuecomment-799900646
Tested locally
=> Switches order of empty/loading blocks on the cart so that we don't flash "empty"

app/assets/v2/scss/gc-variables.scss, app/assets/v2/scss/top-nav.scss
This PR will fix the missing nav-toggle icons on the mobile nav-bar
Fixes: #8603
Tested locally (with production .env's)
=> Fixes mobile nav-toggle icons

app/assets/v2/js/grants/funding.js, app/assets/v2/scss/grants/grant.scss, app/assets/v2/scss/grants/side-cart.scss, app/grants/templates/grants/components/card.html, app/grants/templates/grants/detail/side-cart.html, app/grants/templates/grants/index.html
This PR will tidy up the Grants/Explorer side-cart and both (grid/list) views so that the side-cart will be positioned correctly without squashing any content (at all break-points).
Refers: https://github.com/gitcoinco/web/issues/8483#issuecomment-792042177
Fixes: https://gitcoincore.slack.com/archives/CCL5Q0G5S/p1615520200022900
https://www.loom.com/share/d7e4e752af9748828654fe65133b7e13
=> Removes fly-out behaviour on side-cart and tidies up card/list-view

app/grants/models.py, app/grants/templates/grants/detail/_index.html, app/townsquare/models.py
gitcoinbot leaves a comment on the feed when a txn clears or is pending
helps prevent CS questions about why an activity feed item txn is not actually in a wallet
tested locally, heres what it looks like
=> gitcoinbot leaves a comment on the feed when a txn clears or is pending

app/retail/templates/emails/funded_featured_bounty.html, app/retail/templates/emails/grants/new_supporter.html, app/retail/templates/emails/kudos_mint.html, app/retail/templates/emails/kudos_mkt.html, app/retail/templates/emails/new_bounty.html, app/retail/templates/emails/new_bounty_acceptance.html, app/retail/templates/emails/new_kudos.html, app/retail/templates/emails/new_tip.html, app/retail/templates/emails/request_funds.html, app/retail/templates/emails/template.html
remove flexbox usage in emails; it breaks on some email clients
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1616098463014500
=> fix(emails): remove flexbox usages

app/assets/v2/js/search.js, app/assets/v2/scss/search.scss, app/dashboard/templates/shared/search.html
fixes the issue where the search bar sends a HTTP request every GET Request by adding a go button and requiring an enter button press to search
tested locally
PRing against stable bc this is causing slight site load delays
=> fixes the issue where the search bar sends a HTTP request every GET Request

app/retail/templates/emails/grants/successful_contribution.html, app/retail/templates/emails/grants/thank_you_for_supporting.html, app/retail/templates/emails/template.html
* maintain F pattern in `thank_you_for_supporting` and `successful_contribution` emails
* adjust footer
=> email alignment fixes

app/assets/v2/js/pages/bounty_details2.js, app/dashboard/templates/bounty/details2.html
=> ensure bounty time left shows expired when bounty has expired

app/retail/templates/home/index2020.html
- update numbers
- remove customers section
closes https://github.com/gitcoinco/web/issues/8695
=> landing page updates

app/assets/onepager/js/receive.js, app/assets/onepager/js/request.js, app/assets/onepager/js/send.js, app/assets/v2/js/activity.js, app/assets/v2/js/avatar.js, app/assets/v2/js/avatar3d.js, app/assets/v2/js/base.js, app/assets/v2/js/board.js, app/assets/v2/js/capture-rating.js, app/assets/v2/js/cart-ethereum-zksync.js, app/assets/v2/js/cart.js, app/assets/v2/js/hackathon-projects.js, app/assets/v2/js/jobs.js, app/assets/v2/js/pages/bounty_detail/xinfin_extension.js, app/assets/v2/js/pages/bounty_details2.js, app/assets/v2/js/pages/bounty_request_form.js, app/assets/v2/js/pages/bulk_payout.js, app/assets/v2/js/pages/cancel_bounty/token.js, app/assets/v2/js/pages/change_bounty.js, app/assets/v2/js/pages/fulfill_bounty/index.js, app/assets/v2/js/pages/fulfill_bounty/token.js, app/assets/v2/js/pages/kudos_send.js, app/assets/v2/js/pages/process_bounty.js, app/assets/v2/js/pages/profile_tokens.js, app/grants/templates/grants/detail/index.html, app/kudos/templates/transaction/receive_bulk.html, app/retail/templates/settings/account.html
https://gitcoincore.slack.com/archives/G01LRE6F39A/p1617025362000900
=> alert -> error to danger

app/dashboard/templates/quickstart.html
=> fix https://github.com/gitcoinco/web/issues/8718

app/marketing/mails.py
- Issue: https://sentry.io/organizations/gitcoin/issues/2337064359/?project=1398424&query=is%3Aunresolved
- report: 51k since deployed 
- flow affected: daily email digest which is triggered by cronjob
=> bug: bounty not defined 

app/retail/templates/emails/new_bounty.html
https://gitcoincore.slack.com/archives/C01H9H320CV/p1618518689143200
https://share.getcloudapp.com/8LubbN7r
=> digest: quest section

app/dashboard/templates/bounty/invoice.html, app/grants/templates/grants/invoice.html
https://gitcoincore.slack.com/archives/C01H9H320CV/p1618423960138500
=> update gitcoin address in bounty + grant invoice

app/dashboard/utils.py
replace xdai block explorer url from `AnyBlock` to `BlockScout` for clearly transaction info review
=> feat: replace xdai block explorer url

docs/performance.md
a  performance doc WIP in order to facilitate todays perf testing session
=>  performance doc WIP

app/dashboard/views.py, app/quests/views.py
=> bug: remove ;

app/grants/management/commands/estimate_clr.py
- Issue: https://sentry.io/share/issue/a9f6f0a8fef040489899661635e45e7e/
- report: 14k since deployed
- flow affected: slim clr estimate  which is triggered by cronjob
=> bug: invalid literal for int() with base 10: 'found'

app/assets/v2/js/cart.js
- Issue: https://sentry.io/share/issue/dbe1c8cf5e2a404ab7b65bf36675e1c4/
- Count: 1.4k
- Flow : Grants Cart
=> bug: Cannot read property 'length' of null

app/retail/views.py
- Issue: https://sentry.io/share/issue/2d4511dfe66e44f781d47082ae997d17/
- Reports: 1.6k
- Flow: Activity
=> bug: invalid literal for int() with base 10: '832170?utm_source=gitcoin'

app/dashboard/views.py
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1618947857133900
=> enable staff to close bounty

app/grants/views.py
https://sentry.io/organizations/gitcoin/issues/1912260359/?project=1398424&query=is%3Aunresolved
Reports: 1k
=> fix: invalid literal for int() with base 10: 14'

app/assets/v2/js/cart.js, app/assets/v2/js/grants/_new.js, app/assets/v2/js/grants/cart/binance_extension.js, app/assets/v2/js/grants/cart/harmony_extension.js, app/assets/v2/js/grants/cart/polkadot_extension.js, app/assets/v2/js/grants/cart/rsk_extension.js, app/assets/v2/js/grants/new_match.js
add: 
grants-creator
grants-pledger
grants-contributor
following the docs https://www.notion.so/gitcoin/bc293fb2beb84bfa8e1182b2efcee176?v=90f8891ac00e44959a52a38e5049e1df
=> Add triggers for grants

app/taskapp/celery.py
This is to resolve 
https://sentry.io/organizations/gitcoin/issues/1892482690/?project=1398424&query=is%3Aunresolved
Check thread for more details:
https://gitcoincore.slack.com/archives/CAXFMVDGD/p1618487081058100
=> remove datatrace usage in celery

app/assets/v2/js/pages/bounty_details2.js, app/dashboard/templates/bounty/details2.html
Reverts gitcoinco/web#8684
Based on discussion
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1618542602129600?thread_ts=1618252015.102200&cid=CAXQ7PT60
=> Revert "show submission only to needed folks"

app/dashboard/templates/onepager/base.html, app/dashboard/templates/shared/onepager_auth.html, app/grants/templates/grants/landingpage.html, app/kudos/templates/transaction/base.html, app/kudos/templates/transaction/kudos_auth.html, app/retail/templates/home/index2021.html, app/retail/templates/jtbd/earn.html, app/retail/templates/shared/footer_scripts.html, requirements/base.txt
This PR:
- upgrades wiki from 0.5 -> 0.7.3
- prevents navbar.js from being served on onepagers (tip/kudos etc)
- enables wallet connection for the landingpage and earn jtbd page
Fixes: https://sentry.io/organizations/gitcoin/issues/2358621600/?project=1398424&query=is%3Aunresolved
Tested locally
=> Fixes navbar regressions

app/dashboard/templates/dashboard/hackathon/hackathons.html, app/dashboard/views.py
list hackathon event numbers on tabs for easier nav
just user testing
tested locally
=> list hackathon event numbers on page

app/dashboard/management/commands/cleanup_goog_fb_ids.py, app/dashboard/router.py
Issue: https://sentry.io/share/issue/4bfc5e8954f440e0b2c05ed3c1995dde/
report: 4.8k
flow affected: bounty slim api
=> bug: bounty slim - invalid literal for int() with base 10

app/grants/router.py, app/grants/serializers.py
makes the /api/v0.1/grants endpoint responsive again
adds field that roy stoof needs for grandois (grants L2)
"Grandiose - A gitcoin grant discovery tool" email
tested locally
=> makes the /api/v0.1/grants endpoint responsive again

app/dashboard/router.py
https://sentry.io/organizations/gitcoin/issues/2358791705/
5.8k
=> fix: https://sentry.io/organizations/gitcoin/issues/2358791705/

app/dashboard/router.py
https://sentry.io/organizations/gitcoin/issues/2358701375/
10.8k
=> fix Invalid order_by arguments

app/dashboard/router.py
report: 3k
https://sentry.io/share/issue/d48f9c1d569844eab58773cae4533c6e/
locally http://localhost:8000/actions/api/v0.1/bounties/slim/
=> fix https://sentry.io/share/issue/d48f9c1d569844eab58773cae4533c6e/

app/dashboard/views.py
move mautic backend to his own def so can be used by the system without user intervention. 
usage:
```
from dashboard.views import mautic_proxy_backend
mybody = b'{"reason":3}'
mautic_proxy_backend('POST', f'contacts/{profile.mautic_id}/dnc/email/add', mybody)
```
=> create mautic backend

docs/README.md, docs/RUNNING_LOCALLY_DOCKER.md
I was working through the guide to run the local environment with docker and noticed a few markdown errors and a spelling mistake. I also made some organisational changes to fit the flow better.
If these changes are ok, I'd like to go a bit further in the _RUNNING_LOCALLY_DOCKER.md_ file:
Happy to do the above in this PR but wanted to make sure these were changes that the team is interested in.
N/A
Documentation only. I have read it for mistakes.
=> docs: organisation and spelling

app/dashboard/templates/legal/terms.html
=> updating terms

app/dashboard/management/commands/cleanup_earnings.py, app/grants/models.py
This PR:
- Will save the correct network  to the earnings entry (pulled from the subscription) for future rinkeby contributions
- Adds a management command to fix up the ~2590 entries which will ref the incorrect network
Fixes: #8895
Tested locally
=> Fixes network recorded in the earnings table for contributions made on rinkeby

app/marketing/mails.py
updates fund request to come from person who sent it not founders@gitcoin.co
my common sense, its a pain in the butt to deal with this without something like this 
tested locally
=> updates fund request to come from person who sent it not founders@gitcoin.co

app/quadraticlands/templates/quadraticlands/index.html
=> Update copy text

app/tdi/views.py
=> Updating error messages.

app/app/settings.py, app/assets/v2/js/quadraticlands/mission/receive/claim.js, app/assets/v2/js/wallet.js, app/dashboard/tests/__init__.py, requirements/base.txt, requirements/test.txt
This PR upgrades pytest to latest version:
- Latest version of ddtrace (0.49.0) requires attrs>=19.2.0
- upgrading pytest allows us to upgrade attrs
Refers: failing build
Tested locally and with travis
=> Upgrades pytest to latest version

CODEOWNERS
This PR adds Zack as a reviewer
=> Adds Zack to codeowners so that he's auto added as a reviewer

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/custom.md, .github/ISSUE_TEMPLATE/discussion.md, .github/ISSUE_TEMPLATE/feature_request.md, app/dashboard/notifications.py, app/dashboard/templates/dashboard/hackathon/onboard.html, app/dashboard/templates/shared/menu.html, app/retail/templates/emails/funder_payout_reminder.html, app/retail/templates/emails/template.html, app/retail/templates/jtbd/connect.html, app/retail/templates/jtbd/fund.html, docs/CONTRIBUTING.md, docs/GRANTS.md
This PR replaces any remaining links to the old discord invite with `https://discord.gg/gitcoin`
Refers: #8842
Tested locally
=> Replaces discord links with vanity url

app/app/sitemaps.py, app/app/urls.py, app/grants/templates/grants/detail/template-grant-details.html, app/grants/templates/grants/shared/landing_navbar.html, app/grants/templates/grants/shared/sidebar_search.html, app/retail/templates/shared/footer.html, app/retail/views.py
This PR purges all links to the wiki, but leaves the wiki installation in place so that we can pull information from the articles
Fixes: https://gitcoincore.slack.com/archives/C01UD76STQE/p1621719385050000
Tested locally
=> Purges wiki

app/assets/v2/js/abi.js
This PR drops the rinkeby addresses from abi.js
Fixes: (displaying GOPH on QL)
Tested locally
=> Drops rinkeby addresses

app/app/context.py
This PR fixes the bounties api endpoint
fixes: https://sentry.io/organizations/gitcoin/issues/2416728742/?project=1398424&referrer=slack
Tested locally
=> Fixes the bounties api endpoint

app/retail/templates/shared/footer.html
This PR places the new code of conduct in the footer
refers: #8931
Tested locally
=> Replaces code of conduct url

app/quadraticlands/helpers.py
=> remove rate limit

app/quadraticlands/scripts/ingest_faq.py, app/quadraticlands/templates/quadraticlands/stewards.html
=> Fix tallyurl

app/assets/v2/js/quadraticlands/mission/receive/claim.js, app/quadraticlands/templates/quadraticlands/mission/receive/claim.html
- added a view in claim.html that tell users they have 0 tokens + give them the option to complete the mission by forward to outro.
- added a hidden div that forward claimable token amount via data-atribute to js world
- added a check in claim.js for token amount = 0 to update the claim view on load
#8948
tested local
=> zeroclaim-fix

app/dashboard/templatetags/bundle.py, app/grants/router.py, app/grants/serializers.py
This PR retries the report_real which takes a lot of resources and times out on heavy grants
Instead, Gitcoin will now offer 2 endpoints for public consumption 
**Note:** 
- The results are paginated and return upto 30  
- These endpoints are rate limited by IP to 5/s
- The API will return a valid response only for a max of 30 days 
- These endpoints aren't restricted to just eth address but instead provide info on all chains supported 
- A new metadata object has been added to the response which provides details like total count, current page, how many pages, next_page, etc
- The original API is being retired but the data structure stays the safe and the info which was provided by the older endpoint, continues to be provided in the 2 new endpoints 
---------
**Endpoint**: …
=> chore: rewrite report endpoint

app/assets/v2/js/quadraticlands/forceWallet.js
This PR improves the forceWallet.js behaviour to avoid errors in edge cases. (_EVENTS_: **8.4k**  -  _USERS_: **1.3k**)
Refers: 
- https://sentry.io/organizations/gitcoin/issues/2418267809/?project=1398424
- https://sentry.io/organizations/gitcoin/issues/2418296892/?project=1398424
Tested locally
=> Forces wallet connection using wallet.js methods

app/app/urls.py
This PR disables the whitepaper paths
Refers: https://gitcoincore.slack.com/archives/CAXQ7PT60/p1622201102078900
Tested locally
=> Disables whitepaper paths

app/assets/v2/js/pages/faucet_form.js, app/assets/v2/js/pages/results.js, app/dashboard/templatetags/bundle.py, app/dashboard/views.py, app/grants/views.py, app/kudos/models.py, app/marketing/management/commands/send_tax_report.py, app/marketing/views.py
- https://sentry.io/organizations/gitcoin/issues/1840912919/ (24 events + 12 users)
- https://sentry.io/organizations/gitcoin/issues/1923563889/?project=1398424&query=is%3Aunresolved (49 events)
- https://sentry.io/organizations/gitcoin/issues/2386687294/?project=1398424 ( 3 events + 3 users)
- https://sentry.io/organizations/gitcoin/issues/2285614428/? (59 events)
- https://sentry.io/organizations/gitcoin/issues/2395667584/?project=1398424 (1.2k events)
- https://sentry.io/organizations/gitcoin/issues/2271008604/? (22 events)
=> fix: sentry bugs

app/dashboard/management/commands/cleanup_earnings.py, app/dashboard/utils.py, app/dashboard/views.py, requirements/base.txt
This PR replaces web3 queries with queries to the graph enabling verification of POAP's on xDai.
Fixes: #8677 
xDai has been tested locally - I'm unable to test mainnet, but it should work in the same way (it just utilises a different end-point)
=> POAP verification: Replaces web3 with the graph for xdai and mainnet

app/quadraticlands/templates/quadraticlands/about.html, app/quadraticlands/templates/quadraticlands/workstream/index.html
Remove duplicate 'and'
None
None
=> Remove duplicate 'and'

app/assets/v2/js/ql-banner.js, app/assets/v2/scss/ql-banner.scss, app/retail/templates/shared/top_nav.html
This PR alters the banner to be fixed height and dismissible to match post 48hr design
Closes: #8816
Tested locally
=> Alters QL banner to post 48hr version

app/retail/templates/shared/footer.html
Change Footer Nav Header from Business to Organization
Change Business to Organization in Footer
=> Change Business to Organization in Footer

app/townsquare/views.py
This PR fixes a security vulnerability where by any user can delete activity from any other users profile
refers: email string
Written by @owocki, verified by @thelostone-mc & myself
=> Prevents activity from being deleted by users who don't own that activity

app/app/context.py, app/app/settings.py, app/retail/templates/shared/head.html
=> Removing Hotjar

app/quadraticlands/templates/quadraticlands/dashboard/governance.html
Updated "past" to "paste"
N/a
N/a - simply adds a character to a word
=> Corrected typo

app/avatar/models.py
Fixes issues: 
https://sentry.io/organizations/gitcoin/issues/2418444400/?project=1398424&query=is%3Aunresolved (308k)
https://sentry.io/organizations/gitcoin/issues/1970042494/?project=1398424&query=is%3Aunresolved (308k)
This was tested locally and also on cronbox
=> bug: fix avatar bug reported on sentry

app/assets/v2/js/pages/kudos_bulk_receive.js, app/avatar/models.py, app/dashboard/views.py
- https://sentry.io/organizations/gitcoin/issues/2383067156 (4.6k)
- https://sentry.io/organizations/gitcoin/issues/1727638796 (35k)
=> @thelostone-mc bug: sentry fixes (40k)

app/dashboard/models.py
This PR will make sure that we pull all bounties for an org regardless of casing
Fixes: #9030
Tested locally
=> Fixes case sensitivity issue on get_orgs_bounties

app/assets/v2/js/pages/kudos_bulk_receive.js, app/retail/views.py
- Fix JSONStore not found exception [LINK](https://sentry.io/organizations/gitcoin/issues/978663356/) - 10.2k records
- The send transactions "from" field must be defined! [LINK](https://sentry.io/organizations/gitcoin/issues/2383441101) (9k events + 2k users)
=> sentry: bug fixes (20k)

app/grants/views.py
~datetime.timedelta~ timezone.timedelta
fixes #9002
=> fix import + undefined variable

app/retail/templates/emails/bounty_startwork_expire_warning.html, app/retail/templates/emails/new_bounty.html
closes #8996 
https://www.loom.com/share/9e659ef176f1441a802e70f402be5a59
=> fix broken emails

app/dashboard/views.py, app/grants/templates/grants/shared/landing_qf_active.html, app/grants/views.py
- add "active" field on json data 
- add condition to disable the countdown display based on "active"
- set default dates to 14 days round
=> add round active boolean to turn off the counter

app/dashboard/views.py
This PR fixes missing profile data from the context in `app/dashboard/views.py` which causes the activity to never load
Fixes: #9074
Tested locally
=> Ensures activity is supplied in the profile view

app/avatar/models.py
fixes sentry bug for avatar handle
=> fix: https://sentry.io/organizations/gitcoin/issues/1970042494 (300k reports)

app/grants/views.py
This PR restores variables lost in c10f867f994160feb7d2af8c3b3a21da0994ddb8 - which will enable the admin to edit grants
(https://sentry.io/organizations/gitcoin/issues/2450750744/?referrer=slack)
Fixes: #9088
Tested locally
=> Restores variables lost in SHA: c10f867f994160feb7d2af8c3b3a21da0994ddb8

app/assets/v2/js/cart-ethereum-zksync.js, app/assets/v2/js/cart.js
removes the EthereumCartJSONStore as this is not being used right now and this could possibly be causing contributions to be missed 
https://github.com/gitcoinco/web/pull/8563/files
fixes https://github.com/gitcoinco/web/issues/8852
**ZKSYNC**
--------------
**BULK CHECKOUT**
=> remove manageEthereumCartJSONStore

app/assets/v2/js/activity.js, app/assets/v2/js/pages/profile-tribes.js, app/assets/v2/js/pages/profile-trust.js, app/dashboard/templates/profiles/tribes-vue.html, app/grants/sync/celo.py, app/grants/sync/zcash.py, app/grants/views.py, app/quests/templates/quests/index.html, app/retail/templates/jtbd/connect.html
Fix broken sidebar update on tribe manage
Fixes https://github.com/gitcoinco/web/issues/9095
=> bug: fix broken sidebar

app/marketing/views.py
This PR ensures mautic contacts are removed when the profile is deleted (following this [documentation](https://developer.mautic.org/#delete-contact))
Fixes: #8850
Untested (@octavioamu - can you help me test this on Monday please?)
=> Deletes mautic contact on profile deletion

app/grants/templates/grants/detail/template-grant-details.html
This PR fixes the grant-details template
=> bug: Tidies up grant-details template

app/assets/v2/js/pages/onboard.js, app/assets/v2/scss/onboard.scss, app/retail/templates/avatar_landing.html
This PR fixes the missing function and the visibility of the nav menu
Fixes: #9105
Tested locally
=> fix: Fixes the avatar save flow and restores the navbar visibility

app/grants/templates/grants/shared/landing_qf_active.html, app/grants/views.py
This PR ensures that the user is authenticated before setting the `trust_bonus` into context
fixes: #9110
Sentry error: https://sentry.io/organizations/gitcoin/issues/2457424680/?project=1398424&referrer=slack
Tested locally
=> Ensures the user is authenticated before setting trust_bonus

app/retail/templates/emails/grants/new_grant.html
=> hotfix: new grant email CTAs

app/dashboard/views.py
Ensure value exists before checking
=> fix https://sentry.io/organizations/gitcoin/issues/2457438215/

app/grants/clr.py
Ensure only mainnet contributions are considered while calculating CLR
=> clr.py takes only mainnet contributions

app/dashboard/views.py
fix slow profiles by shaving off 5s of load time to gitcoin.co/owocki
https://github.com/gitcoinco/web/issues/9119
tested locally
=> fix slow profiles by shaving off 5s of load time to gitcoin.co/owocki

app/dashboard/views.py
This PR fixes the clearing of `google_user_id` and `facebook_user_id` which have unique constraints (can't be set to `False`)
fixes: #9128
Tested locally
=> fix: Fixes disconnect fn for google/facebook

app/grants/management/commands/send_grants_contributions_emails.py, app/grants/tasks.py, app/retail/emails.py
localize round_start_date condition
7k+ events
https://sentry.io/share/issue/ae9b5744b7814d408f3afb3ad4b27803/
=> fix https://sentry.io/share/issue/ae9b5744b7814d408f3afb3ad4b27803/

app/marketing/views.py
This PR fixes a KeyError in the email settings ([sentry: ~150 encounters](https://sentry.io/organizations/gitcoin/issues/2444856600/?project=1398424&query=is%3Aunresolved]))
fixes: #9126
Tested locally
=> fix: Fixes KeyError in email settings

app/retail/utils.py
This PR will enable the results page update to complete 
(we've missed an update when adding `round_active` to `get_clr_rounds_metadata`)
fixes: #9137
Tested locally
=> fix: Ensures that were unpacking the correct number of values

app/grants/management/commands/build_collection_thumbnails.py, app/grants/tasks.py
This PR converts `build_collection_thumbnails` to use celery so that we can safely run it over the ~8000 collections we have on production
Fixes: https://github.com/gitcoinco/web/issues/9134
Confirmed that the task will run locally
=> Converts build_collection_thumbnails to a celery task

app/assets/v2/js/pages/profile-trust.js
This PR corrects the verbiage used on the Twitter verification modal (body + button should match)
Fixes: #9141
N/A
=> fix: Corrects verbiage used on the Twitter verification modal

app/assets/v2/js/navbar.js
This PR ensures that certain elements, required to build the nav, are present before binding any fns
Fixes: [Cannot read property 'classList' of null - EVENTS: 48k - USERS: 29k](https://sentry.io/organizations/gitcoin/issues/2444569900/?project=1398424&query=is%3Aunresolved)
Fixes: #9139
Tested locally (although I was unable to replicate the error)
=> fix: Ensures elements are present before activating the nav

app/assets/v2/js/navbar.js
- https://sentry.io/organizations/gitcoin/issues/2444569900/?project=1398424&query=is%3Aunresolved+Cannot+read+property+%27classList%27+of+null&sort=freq&statsPeriod=14d (52k + 30k)
- https://sentry.io/organizations/gitcoin/issues/2444578370/?project=1398424&query=is%3Aunresolved+Cannot+read+property+%27classList%27+of+null&sort=freq&statsPeriod=14d (8.9k + 6.3k)
- https://sentry.io/organizations/gitcoin/issues/2444571887/?project=1398424&query=is%3Aunresolved+Cannot+read+property+%27classList%27+of+null&sort=freq&statsPeriod=14d (7.3k + 5.4k)
- https://sentry.io/organizations/gitcoin/issues/2444625263/?project=1398424&query=is%3Aunresolved+Cannot+read+property+%27classList%27+of+null&sort=freq&statsPeriod=14d (2.4k + 1.1k)
- https://sentry.io/organizations/gitcoin/issues/2418985192/?proje …
=> bug: fix sentry reports (50k reports + 35k users affected)

app/dashboard/admin.py
This pr fix the logic for unshadow trying to delete unshadow prop but it is actually another model.
fix #9148
=> fix unshadowban function on admin

app/townsquare/templates/townsquare/shared/tag.html
Filters on townsquare are with / on the html making going back to the root. 
close #9150
=> Fix townsquare filters 

app/assets/v2/js/theme_switcher.js
comment out theme switcher making the cart link to fail
close #9152
=> Fix cart link 

app/assets/v2/js/cart.js
Set data to be reactive when someone change the donation amount.
close #9156 9156
=> Fix cart match

app/grants/templates/grants/detail/template-grant-details.html
This PR places an orange border around the team member which created the grant (visible only to staff)
Fixes: #9154
Tested locally:
=> Highlights the grants owner to staff users

app/assets/v2/js/pages/new_bounty.js
There some situation when the fees get calculated with more than 18 decimals making the Tx to fail.
Fix #8977
=> fix decimals fees on bounties

app/assets/v2/js/navbar.js
This PR solves the navbar.js issue --- the mobile submenu implementation has not been rolled out over the products menu, so the errors are coming from users hitting one of the product links and navigating away, the href works, but the errors get thrown before the browser navigates.
This will place the checks in the right place to make sure the sub-submenu elements are present before attempting to place the menu in the correct position.
Refers: #9144
Fixes: [Cannot read property 'classList' of null - Events: 1.1k ~ Users: 594](https://sentry.io/organizations/gitcoin/issues/2464485024/?project=1398424&query=is%3Aunresolved+assigned_to%3Ame&statsPeriod=14d)
Fixes: [computedRootStyles is not defined - Events: 742 ~ Users: 544](https://sentry.io/organizations/gitcoin/issues/2445050840/?project= …
=> fix: Ensures the submenu els are present before attempting to display them

app/app/urls.py
This PR enables metadata to be gathered for URLs placed in a status update
Fixes: GITC-56
Tested locally
=> GITC-56: Allows service/metadata to be accessible when its not at the start of the url

app/app/settings.py, app/app/urls.py, app/dashboard/models.py, app/retail/templates/admin/index.html, requirements/base.txt
This PR introduces admindocs so that designers/new engineers can quickly grok Gitcoins data models
Fixes: GITC-57
Tested locally
=> GITC-57: Introduces admindocs to create admin pages from our models

app/retail/templates/shared/activity-vue.html, app/retail/templates/shared/activity.html
=> GITC-68 bug: fix kudos broken link

js-sdk/yarn.lock, yarn.lock
Fixes the issue reportef by security 
This just upgrade the yarn file. Will check if the packages need to updated as well
=> chore: upgrade yarn lock files

app/dashboard/templates/bounty/new_bounty.html
make SIA chain public for bounties
=> sia - straight outta staff flag

app/grants/views.py
ingestion breaks due to broken import
https://gitcoin.co/grants/add-missing-contributions.
More details: https://gitcoincore.slack.com/archives/CAXQ7PT60/p1624473122265600
=> fix: datetime.datetime bug

app/app/db.py
We need to make changes to the read replicas configuration, to do so safely, we should divert all traffic to master until the reconfiguration is complete
refers: GITC-74
N/A
=> GITC-74: Switches the backend servers to use master temporarily

app/app/db.py, app/app/settings.py
This PR reinstates the read replica and adds an additional replica
refers: GITC-74
Tested connection to replica2 on gitcoin3
=> GITC-74: Reinstates read replicas and adds an additional slave

app/marketing/utils.py
https://sentry.io/organizations/gitcoin/issues/2365052007
Locally tested
Fixes: GTC-85
=> GITC-85: invalid literal for int() with base 16

app/grants/views.py
https://sentry.io/organizations/gitcoin/issues/2273213109/?project=1398424&referrer=slack
=> GTC-83: 'NoneType' object has no attribute 'grant_contributor'

app/assets/v2/js/navbar.js, app/assets/v2/js/wallet.js
ensures getDataChains(id, 'chainId')[0] exists before accessing the property 
https://sentry.io/organizations/gitcoin/issues/1966089066/?project=1398424
GITC-86
=> GITC-86: undefined is not an object in wallet.js

app/grants/utils.py
This PR fixes the `save_grant_to_notion` payload to account for the change in db structure since we first implemented it (`URL` has been dropped)
Fixes: GITC-114
Tested locally
=> GITC-114: Fixes structure of the save_grant_to_notion payload

app/grants/serializers.py, app/grants/tasks.py, app/grants/views.py
- tweaked endpoint to provide txn hash 
Has been tested locally 
Fixes: GITC-109
https://github.com/gitcoinco/web/issues/9222
=> GITC-109: add txnhash to report endpoint

app/dashboard/templates/shared/nav_auth.html
This PR corrects the url used for the kudos section of the me-menu
Fixes: GITC-101
Tested locally
=> GITC-101: Fixes the sent/received kudos links in the me menu

app/grants/tasks.py
https://sentry.io/share/issue/8799c803bb41405086b9d2ae3faab138/
=> GITC-117: AttributeError: 'NoneType' object has no attribute 'sybil_score'

app/app/settings.py, app/app/templates/shared/sentry.html, app/retail/templates/error.html, requirements/base.txt
Update sentry to the latest versions on python and Js sdk, also remove raven old version adding all the variables to use more sentry powers. 
**IMPORTANT**
if 'RAVEN_JS_VERSION' is set on prod server env then it need to be changed to 6.8.0
https://gitcoin.atlassian.net/browse/GITC-105
not possible to do a send test but they provide a "debug" flag to check the config, all seems to be good.
=> GITC-105: Sentry update

app/grants/clr.py
This PR will ignore any contributions that are missing an associated profile from the CLR calc 
(*note: this is a situation we shouldn't be in and is a symptom of a different issue - namely: _"users are able to make contributions without having their profile associated with the subscription"_)
Fixes: GITC-124
=> GITC-124: Ensures each profile_for_clr exists before including the contribution in the calc

app/assets/v2/js/grants/ingest-missing-contributions.js, app/grants/admin.py, app/grants/views.py
Based on discussion here
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1625073981307100
This PR
- Adds better validation to ensure admin don't post random data
- Tweaks admin view to handle contributions with missing profilr (due to invalid data entry)
- Improves error messaging on the contribution ingestion page
GITC-125
=>  chore: make improvs to missing contiribution ingestions

app/assets/v2/js/pages/change_bounty.js, app/assets/v2/js/shared.js, app/assets/v2/js/tokens.js, app/dashboard/templates/bounty/change.html, app/dashboard/views.py
This PR forces `change_bounty` to use the same network on which it was created in order to gather token details and fixes the global Token->USD conversion to work against any given input field(s).
Fixes: GITC-113
Tested locally
=> GITC-113: Forces change_bounty to use the same network on which it was created to gather token details

app/dashboard/sync/eth.py
https://sentry.io/organizations/gitcoin/issues/1855066298/
GITC-42:
=> GITC-42: make hackathon page responsive

app/assets/v2/js/grants/cart/algorand_extension.js, app/assets/v2/js/pages/bounty_detail/algorand_extension.js
This PR fixes the following report:
> Reported issue from Algorand payouts not working. Asking for more info but this is what they said. Could it be similar to the Harmony ONE’s payout issue?
Michiel | Algorand Foundation, [Jul 2, 2021 at 5:42:56 AM]:
Hi guys, we are trying to make payments using Algorand’s ALGO token but we’re getting an error Asset ALGO is not present in RVZYBH7NDCDDBUHIWOPT7EQHDPOLZPNKSRCCFEFZUDLY432CNOQ72YAMRM
You can see the ALGO balance here: https://algoexplorer.io/address/RVZYBH7NDCDDBUHIWOPT7EQHDPOLZPNKSRCCFEFZUDLY432CNOQ72YAMRM
GITC-156
=> GITC-156: fix for algo asset check

app/dashboard/sync/zil.py, app/grants/router.py, app/grants/serializers.py, app/grants/sync/zil.py, app/grants/utils.py
-  include only mainnet contributions
- remove clr_round from txn
- add grant created date
- handle invalid page number param
- closes https://github.com/gitcoinco/web/issues/9256 ( GITC-159) 
- closes https://github.com/gitcoinco/web/issues/9254 (GITC-160)
- closes https://github.com/gitcoinco/web/issues/9255 (GITC-164)
- closes https://github.com/gitcoinco/web/issues/9253
has been tested locally
=> tweak: grant endpoint

app/retail/templates/emails/new_bounty.html
remove extra slash on the upcoming hackathons links
Fix https://gitcoin.atlassian.net/browse/GITC-168
https://sentry.io/organizations/gitcoin/issues/2488315064/?project=1398424&query=is%3Aunresolved&statsPeriod=14d
=> remove extra slash

app/assets/v2/js/pages/change_bounty.js
Fixing eslint bug
Ran eslint locally to confirm there are no other errors.
=> Adding semicolon to fix eslint

app/grants/serializers.py
Adds token_address to grant endpoint
- GITC-191 
- https://github.com/gitcoinco/web/issues/9266
Locally tested
=> add token_address to grant endpoint

app/dashboard/sync/zil.py, app/grants/sync/zil.py, app/grants/utils.py, app/perftools/management/commands/create_page_cache.py
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1625154841326300
=> tweak page_cache_command

app/dashboard/models.py
Grants landing page is broken due to incorrect variable being used
Works fine locally after this change
=> bug: fix broken trust score

app/dashboard/templates/shared/cart_nav.html
This PR will ensure that nothing overrides the default href behaviour allowing the checkout button to always navigate to grants/cart.
Fixes: GITC-199
Tested locally
=> GITC-199: Fixes the cart button to ensure navigation to grants/cart

app/dashboard/templates/profiles/trust-vue.html, app/dashboard/views.py, app/grants/templates/grants/shared/landing_qf_active.html
hide dates on banner if clr is not active (flag)
https://gitcoin.atlassian.net/browse/GITC-169
=> GITC-169 add flag to show/hide date on trust banner

app/app/utils.py, app/assets/v2/js/quadraticlands/app.js, app/assets/v2/js/quadraticlands/cookielaw.js, app/assets/v2/js/shared.js, app/git/utils.py, app/revenue/management/commands/kudos_revenue.py
- [bug: Unhandled 'blockNumber!](https://sentry.io/organizations/gitcoin/issues/2463372099/)
- [cookielawbutton: Cannot read property 'addEventListener' of null ](https://sentry.io/organizations/gitcoin/issues/2495515932/)
- bug: log needed github errors to sentry [Issue 1](https://sentry.io/organizations/gitcoin/issues/2514137549/), [Issue 2](https://sentry.io/organizations/gitcoin/issues/2514159090/), [Issue 3](https://sentry.io/organizations/gitcoin/issues/2514158049/), [Issue 4](https://sentry.io/organizations/gitcoin/issues/2516316692/)
- [noproviderIcon - Cannot read property 'addEventListener' of null](https://sentry.io/organizations/gitcoin/issues/2510421744/)
- ['NoneType' object has no attribute 'get_repos'](https://sentry.io/organizations/gitcoin/issues/2515434724/?project=13984 …
=> GITC-216  bug: sentry fixes

app/grants/management/commands/estimate_clr.py
This is to ensure debugging is easier while running payouts as opposed to having to wait for task to complete
=> allow running CLR as sync fo debugging

.travis.yml
Fixing outdated config settings in travis.yml. 
No code changes, Travis is building as expected now without warning or issues in the config.
=> GITC-241: Updating outdated configs in travis.yml

app/grants/utils.py
This PR will restore the connection between gitcoin and notion.
Fixes: GITC-255
Tested locally and on GC3
=> GITC-255: Fixes the gitcoin->notion integration due to table changes

app/assets/v2/js/pages/kudos_details.js
This PR replaces deprecated `TweenMax.killAll()` with `gsap.globalTimeline.clear()`
Fixes: GITC-263
Tested locally
=> GITC-263: Fixes use of deprecated .killAll method

app/retail/emails.py
=> More email clean ups

app/git/utils.py
Fixes sentry: https://sentry.io/share/issue/06ddf02856d147b4ae5e7047ce757ac4/
3.2k events
GITC-283
=> GITC-283: AssertionError while posting github issue comment

app/retail/templates/mission.html
set max-width to 100 on videos in mission
GITC-180
=> chore: set max-width to 100 on videos in mission

app/app/urls.py, app/perftools/management/commands/create_page_cache.py
- order upcoming by starting date
- clean up URLs
https://gitcoin.atlassian.net/browse/GITC-301
=> chore: order upcoming by starting date

app/perftools/management/commands/create_jtbd_cache.py
This PR will fix the earn page on staging and local envs
Fixes: GITC-321
Tested locally
=> GITC-321: Sets featured grant to 'grant_id = 1'

app/dashboard/templates/shared/menu.html
Updates the nav to point to GitcoinDAO.com instead of the old (unupdated QuadraticLands Site)
N/A
Tested locally
=> Updates the nav to point to GitcoinDAO.com instead of the old (unupdated QuadraticLands Site)

app/assets/v2/js/cart.js, app/grants/templates/grants/cart-vue.html
ensure cart can be cleared on loading screen as well
GITC-294
=> GITC-294: show clear cart on loading screen

.travis.yml
This PR should fix the doc deploy section of our travis build
Fixes: GITC-368
/
=> GITC-368: Adds skip_cleanup in .travis.yml to retain build artefacts

app/app/db.py
This PR will route all read operations to one of the read-replicas.
=> Updates db.py to always read from replicas

app/grants/clr3.py, app/grants/management/commands/analytics_clr3.py, app/grants/tasks.py
This PR refactors clr3.py to further reduce time complexity
Refers: GITC-245
Tested locally
=> Refactor clr3

app/assets/v2/js/cart-ethereum-polygon.js, app/grants/templates/grants/cart/eth.html
=> put polygon behind staff flag

app/assets/v2/js/grants/_detail.js, app/grants/templates/grants/detail/_index.html
This PR will fix the stats tab
Fixes: GITC-247
Tested locally
=> GITC-247: Fixes the stats tab for team_members

app/dashboard/views.py
This PR enqueues `update_trust_bonus` whenever the `trust_bonus` value changes (used by new `clr.py` calc)
Tested locally
=> Updates trust_bonus in as_dict on any change in state

requirements/base.txt
This PR updates the version of `ipdb` which hasn't been updated in a few years as it was breaking local deployments with Docker.
Tested locally
=> Updating the version of ipdb to fix docker deployment issue

app/assets/v2/js/grants/index.js
Retry fetching grants when fails
clean logs
=> retry fetching grants on fail

app/assets/v2/js/grants/components.js, app/assets/v2/js/grants/index.js, app/assets/v2/scss/gitcoin.scss, app/assets/v2/scss/lib/bootstrap/_variables.scss, app/grants/templates/grants/explorer.html
This PR adds scrolling and sorting to the explorer filters
Fixes: GITC-386
Tested locally
=> GITC-386: Adds scrolling and sorting to the explorer filters

app/kudos/models.py
Fixed typo in comment.
Orignal -> Original
=> chore: fix typo in kudos/models.py

app/dashboard/utils.py
this has been a long issue affecting the system to show the right avatars in this case was filecoin for long time with their avatar picture blocked because there was an scammer blocked with filecoin as part of the profile handle.
=> Fix is_blocked

app/grants/management/commands/payout_round_noncustodial.py
This changes the payout script by splitting the `setPayout` into 2 steps
- step 1: where the chunks can be created and uploaded onto contract
- step 2:  where the emails and contributions can be created 
step 2 would be done as the final step once payouts have been enabled
https://www.notion.so/gitcoin/Grants-Payout-non-custodial-payout-b0b3242b9db24072b5e251f1808866bd
https://gitcoin.atlassian.net/browse/GITC-264
https://rinkeby.etherscan.io/address/0x2FBcB3eCf744f38194147Addd81094c101Df4a45
=> GITC-264 chore: add new step in payout

app/assets/v2/js/cart.js
This PR requires that user's metamask is on ethereum network for standard checkout
fixes https://github.com/gitcoinco/web/issues/9468
https://www.loom.com/share/36d78eda1a3048c186b641047ac4c86f
=> Enforce ethereum chain for standard checkout

scripts/crontab2
switches cron to run every 2 hours instead
=> switch clr to run every 2 hours

app/app/settings.py, requirements/base.txt, scripts/crontab2, scripts/crontab4
an attempt at fixing login AuthStateMissing/AuthMissingParameter issue
https://sentry.io/share/issue/4ad74f86a20b4ad4b0d27fc8c5072cfa/
https://sentry.io/share/issue/e00c1e168d174dd3a46e604f5e724437/
50k + 10.9k events
=> GITC-431: fix login issue

app/grants/clr.py
This PR will revert to the old data sourcing mechanism from the original `clr.py` script.
#Performance
Tested locally
=> Adds old data sourcing to new clr script

app/app/settings.py
set `SOCIAL_AUTH_FIELDS_STORED_IN_SESSION = ['state']`
=> auth fix attempts

app/dashboard/templates/profiles/activity_stats.html
=> Fixing Grammar

app/assets/v2/js/cart-ethereum-polygon.js, app/assets/v2/js/cart.js
=> polygon feedback fixes

app/perftools/management/commands/create_jtbd_cache.py
Fixes bug that was preventing the /earn page from loading correctly on testing environment.
Testing on... testing
=> Fix reference for testing environment

app/dashboard/templates/bounty/new_bounty.html
reference -> https://gitcoincore.slack.com/archives/C01H9H320CV/p1632849602325600
=> allow nervos/tezos/casper for regular bounties

app/assets/v2/js/grants/cart/binance_extension.js, app/assets/v2/js/grants/cart/harmony_extension.js, app/assets/v2/js/grants/cart/polkadot_extension.js, app/assets/v2/js/grants/cart/rsk_extension.js
=> fix checkout error typos

app/grants/templatetags/grants_extra.py, app/perftools/management/commands/create_jtbd_cache.py, scripts/crontab
fix bounty query and ensure jtbd runs every day once
=> GITC-448: fix bounty query and ensure jtbd runs every day once

app/dashboard/templates/dashboard/index-vue.html
=> bug: fix guide button

requirements/base.txt
Bump up version 
This has been locally tested.
=> bump up social-auth version

app/kudos/admin.py
Fixed typo in comment.
avaialble -> available
=> Fix typo in kudos/admin.py

app/grants/templates/grants/explorer.html, app/grants/templates/grants/shared/top-filters.html
Fixes several alignment issues for mobile/tablet on the grants explorer
Fixes: GITC-474
Tested locally
=> GITC-474: Fixes alignment issues for grants explorer

app/dashboard/templates/shared/nav_auth.html
=> Revert "Changed log out link"

app/dashboard/tasks.py, app/kudos/management/commands/pull_tx_status.py
This PR refactors the `pull_tx_status` command to enqueue each `tx` as a new celery task.
Contributes to fixing: GITC-513
Tested locally
=> GITC-513: refactor pull_tx_status to work as a celery task

app/grants/templates/grants/detail/template-grant-details.html
=> unhide polygon in grants detail page

app/dashboard/models.py, app/dashboard/router.py, app/dashboard/views.py, app/retail/templates/shared/result.html
fixes issues with https://github.com/gitcoinco/web/commit/f4d9e8b09b1919a598450f53cf59f583e385b55e
makes the /explorer page view load much faster.
https://gitcoincore.slack.com/archives/CDXGQRZB3/p1635798553129600
tested locally
=> bounty performance fixes

app/grants/views.py
Set end claim date to 1st Feb 2022
=> update end claim date

app/dashboard/views.py, app/grants/tests/views/test_get_grants.py
Ensure the contributor API has been updated to account for contest bounties
=> GITC-534: fix contributor dashboard

app/retail/templates/admin/index.html
This PR purges a missing reverse lookup entry (remnant of  #9503)
Refers: GITC-347
Tested locally
=> GITC-347: purges _administrator/viz viz_index reverse lookup

app/assets/v2/js/grants/index.js, app/grants/templates/grants/explorer.html, app/grants/templates/grants/shared/top-filters.html
Fix a bug that was causing the load screen to show when the user was scrolling
=> GITC-505 - Fix loading icon on scroll

CODEOWNERS
Updating codeowners to include @nutrina as reviewer
=> fix: updates codeowners

app/grants/views.py
Have added image file validation for logo when creating brand.
GITC-607
Tested locally as described in ticket
=> GITC-607: Added image validation for logo when creating grant

app/dashboard/models.py
This PR will fix the bounties api for when the response includes a profile which has been deleted 
(https://sentry.io/organizations/gitcoin/issues/2761533717/?environment=production&project=1398424&query=is%3Aunresolved)
Fixes: GITC-627
Tested locally
=> GITC-627: Ensures name prop exists in bounties api

app/grants/tests/models/test_match_pledge.py
This PR will clear the seconds used in `test_match_pledge_has_end_date` to fix failures when theres skew between the two inputs.
Failing tests
Tested locally
=> fix: intermittently failing match_pledge test

app/assets/v2/scss/base.scss
This PR adds styling changes to the announcement banner in preparation for GR12 announcements
Tested locally. Automated testing not required for this change.
=> GITC-568: bridging to dgrants from cgrants placeholder

app/grants/views.py
The previous fix was apparently incomplete. Logo can be None, this must be verified.
This is the aparent reason why test runs fail.
GITC-607
Testing according to instruction in Jira ticket
=> GITC-607: image bypass

app/assets/v2/js/cart-ethereum-polygon.js, app/assets/v2/js/cart-ethereum-zksync.js, app/assets/v2/js/cart.js, app/grants/templates/grants/cart/eth.html
an alternative and neater solution for https://github.com/gitcoinco/web/pull/9724
=> watch selected token for token unsupported error

app/quadraticlands/views.py
Have implemented sanitisation of data to prevent XSS
GITC-590
Tested locally with the payload from the Jira ticket
=> Gitc 590 stop xss in quatraticlands

app/grants/templates/grants/landing/active_clr_round.html, app/grants/templates/grants/landing/round_by_type.html
This PR will dedupe the Gitcoin Building Gitcoin mini banner.
Fixes: GITC-632
Tested locally
=> GITC-632: dedupe Gitcoin Building Gitcoin mini banner

app/grants/templates/grants/landing/active_clr_round.html, app/grants/views.py
This PR ensures that ecosystem mini-banners are correctly displayed
Fixes: https://github.com/gitcoinco/web/pull/9725#issuecomment-982131752
Tested locally
=> fix: ensure ecosystem mini-banners are displayed correctly

app/quadraticlands/migrations/0009_game_gamefeed_gameplayer.py, app/retail/emails.py, app/retail/templates/emails/grants/thank_you_for_supporting.html
updates grant checkout email to be a professional cart checkout email
common sense,  when we refactored the checkout to be bulk checkout  in GR7,  we never did this.
tested locally at http://localhost:8000/_administration/email/thank_you_for_supporting
old email
new email
=> common sense update to grant checkout email.

app/grants/models/contribution.py
Adds missing polygon URL helper link
=> add polygon link

app/retail/emails.py, app/retail/templates/emails/grants/new_contributions.html
adds txn history in 12h grant email
self, saves the user a click to see who their contributions were from.
tested locally
here is a screenshot
=> txn history in 12h grant email

app/grants/templates/grants/landing/active_clr_round.html
Opening dgrants page in new tab
GITC-632
=> GITC-632: Opening dgrants page in a new tab

app/grants/management/commands/grant_collections_shuffle.py
This PR will increase the amount of random and decrease the effects of meta/age so that Collections are correctly shuffled
Fixes: GITC-512
Tested on gitcoin4 (cc. @owocki - results are shuffling now 🙌)
=> GITC-512: increase the amount of random and decrease the effects of meta/age

app/grants/templates/grants/detail/template-grant-details.html
This PR will hide the `grant_management` area from non-team-members/staff
fixes: empty `grant_management` container
Tested locally
=> fix: hide `grant_management` area from non-team-members/staff

app/grants/templates/grants/_new.html, app/grants/templates/grants/quickstart.html, app/grants/views.py
This PR address @frankchen07 snagging list on: https://github.com/gitcoinco/web/pull/9706#issuecomment-982178469
Tested locally
=> fix: addresses Franks feedback on #9706

app/grants/templates/grants/shared/top-filters.html
=> increase font size of grants count

app/assets/v2/js/cart-ethereum-polygon.js, app/assets/v2/js/cart-ethereum-zksync.js, app/assets/v2/js/cart.js
fixes https://github.com/gitcoinco/web/issues/9790#issuecomment-983960087
=> fix unsupported tokens alert in cart

app/assets/v2/js/cart-ethereum-polygon.js, app/grants/views.py
Based on discussion over at https://discord.com/channels/562828676480237578/915941427987509278/915941430420176896
https://polygonscan.com/address/0xb99080b9407436eBb2b8Fe56D45fFA47E9bb8877
=> inc gas price + limit

app/economy/tx.py, app/grants/tests/views/test_grants_landing_view.py
=> polygon logs

app/economy/tx.py
=> fix tx validator for polygon

app/grants/models/contribution.py
If a transaction is presenting itself to have been made in one token, but was actually made in a different token, then we should mark it as a failed tx.
Refs: grant contribution miscalculation thread in l2
Untested - can we verify the code before testing this against a single contribution on the cron box?
=> fix: zksync - token id mismatch should result in a failed transaction

app/assets/v2/js/cart.js, app/assets/v2/js/grants/_detail.js, app/grants/templates/grants/cart/eth.html, app/grants/templates/grants/detail/template-grant-details.html
Displaying tooltips for caped grants
GITC-650
Have tested locally, according to the acceptance criteria
=> GITC-650: inform users cap reached

app/app/sitemaps.py, app/dashboard/models.py, app/dashboard/views.py, app/retail/views.py
refactors ActivityIndex DB calls by allowing to ORM to handle the join as opposed to prepping a flatlist
=> refactor query

app/assets/v2/js/pages/bounty_detail/casper_extension.js
update casper extension to match breaking changes in 2.7.x
improved error handling
refers #9773 
[View transaction in explorer](https://casperstats.io/tx/2e1653cee3e6628fd8163cc9e2bb08a386fd6f1503289ca63b742c63b2498f91)
=> GITC-635: code changes to casper extension

app/assets/v2/js/cart.js
This PR will prevent any checkout if it includes grants which use a contract as a payout address
Refers: L2 thread: Polygon-EOA
Tested locally
=> fix: ensures no contribs can be sent to a contract on polygon

app/grants/templates/grants/landing/index.html
Adds additional spacing around new description and makes the background purple.
GITC-602
=> GITC-602 Fix styels

app/assets/v2/js/cart-ethereum-polygon.js
Updates the messaging to 
`Contributions cannot be sent to the following Grants (with a multisig payout address) on Polygon:`
=> chore: update alert messaging

app/dashboard/notifications.py, app/marketing/mails.py, app/marketing/management/commands/new_bounties_email.py, app/marketing/management/commands/unsubscribe_daily_emails.py, app/marketing/models.py, app/marketing/tasks.py, app/marketing/tests/test_marketing_utils.py, app/marketing/utils.py, app/retail/emails.py, app/retail/templates/emails/grants/thank_you_for_supporting.html, scripts/debug/output_weekly_mailing_list.py
This PR renames the function and cleans up the logic on how supression works.
Right now we have a lot of not conditions which makes the code tricky to playout.
This PR aims at making it straightforward 
https://discord.com/channels/562828676480237578/916088536292294697/917744247053119539
locally tested
=> chore: rename email supression logic checks

app/grants/templates/grants/explorer.html
Fix loading screen for collections. It now shows the GC loading image
GITC-638
=> GITC-638 Fix loading image on collections explorer

app/assets/v2/js/cart.js
Fixing display of total when token chosen by user is not DAI
=> Fixing display of total when token chosen by user is not DAI

app/grants/models/subscription.py
Fixing calculation of match_amount in Subscription. Small indentation error.
=> Fixing calculation of match_amount in Subscription

app/marketing/tests/test_marketing_utils.py
This PR corrects the negation on one of the travis tests (`test_allowed_to_send_email`)
Refs: Engineering thread on discord
Tested locally
=> fix: ensures all pytests pass

app/grants/templates/grants/landing/active_clr_round.html, app/grants/templates/grants/landing/index.html
=> GITC-602 - Additional styles requested from design

app/marketing/utils.py, app/marketing/views.py
https://discord.com/channels/562828676480237578/917822517564043274/917926254982881361
=> ensure emails are removed from subscription on deletion

app/grants/admin.py
Adds is idle prop on admin for easier debugging 
https://discord.com/channels/562828676480237578/920783887150489652/921012875189964831
=> chore: add is idle prop in admin

app/app/db.py, app/app/settings.py
This PR will allow us to spread the load over more DB replicas
Refs: l2 thread
We need to define more replica instances in the prod .envs
=> fix: adds more replica instances to the app

app/assets/v2/js/cart-ethereum-polygon.js, app/assets/v2/js/grants/ingest-missing-contributions.js, app/assets/v2/js/wallet.js, app/grants/templates/grants/ingest-contributions.html, app/grants/templates/grants/landing/index.html, app/grants/views.py
Enables polygon txn missing to be ingested 
https://share.vidyard.com/watch/k7yzpAQpXDbQn4eYuzpVeL?
=> polygon manual ingestion

app/grants/views.py
Minor improvements for error handling.
Related to #9837
See related PR
=> Have improved the error handling.

cypress/integration/bounties/test_bounty_creation.js
=> fix https://app.travis-ci.com/github/gitcoinco/web/builds/243462513

app/app/settings.py
…e username in case it changes.
GITC-682
GITC-682
See AC in ticket GITC-682
=> GITC-682: github username change

app/assets/v2/js/grants/_detail-component.js, app/assets/v2/scss/gc-utilities.scss, app/assets/v2/scss/grants/new.scss, app/grants/templates/grants/detail/_index.html, app/grants/templates/grants/detail/template-grant-details.html
Adds tooltip to tags, block selector and address when editing grant.
GITC-655 
See AC in GITC-655
=> GITC-655: tooltip grant payout address

scripts/crontab
run shuffle + rank less frequently
=> run shuffle + rank less frequently

scripts/crontab, scripts/crontab_gitcoin2
move kudos cron to it's own cron file
=> move kudos to it's own crontab

app/grants/clr.py, scripts/crontab, scripts/crontab_gitcoin2
This PR will ensure that invalidations are only saved if `save_to_db` is `True` and also ensures that we're correctly excluding `grants` which **will** be saved in the run. 
Fixes: CLR calcs
Tested locally
=> fix: ensure we only invalidate results which are no longer included in the round

app/grants/tasks.py, app/grants/utils.py
1. Refactored the `bsci_script` method for correctly importing the squelches from the BSci pipeline
2. Added a `ToggleUser` class and `FlaggingScriptOutput` type for describing the `bsci_script` output
3. Refactored `process_bsci_sybil_csv` so that toggling the sybil users happen outside the `bsci_script`
=> Update BSci script

app/grants/tasks.py, app/grants/utils.py
=> Revert "Update BSci script"

app/retail/templates/results.html
comment out feedback on results page as the data is spammy 
Discussion with @nfrgosselin 
locally tested
=> comment out feedback on results

app/app/settings.py
adjusts cache timeouts to avoid (or at least delay) thundering herd problem
https://gitcoincore.slack.com/archives/CDXGQRZB3/p1635529068086000
tested locally
=> adjusts cache timeouts to avoid thundering herd

app/quadraticlands/templates/quadraticlands/about.html
Removed copy/markup from about page
GITC-683
Just a small change to static html markup
=> GITC-683 remove copy from about page

cypress/integration/grants/test_grant_creation.js
Small update to address this [comment](https://github.com/gitcoinco/web/pull/9927#pullrequestreview-845419985) relating to updating the cypress test to account for short twitter handle
=> Allow specialshort twitter handles grant creation test

app/assets/v2/scss/grants/collection.scss, app/grants/tests/models/test_grant.py
This PR adds unit tests for the Grant model attributes
=> Test Grant model

app/grants/tests/factories/grant_hall_of_fame_factory.py, app/grants/tests/models/test_grant_hall_of_fame.py
Adds test coverage for GrantHallOfFame model
=> Test GrantHallOfFame

app/assets/v2/js/grants/matching_funds.js
this pr fixes multiple "+X more" in clr column
=> GITC-720: fix broken clr column in matching funds page

app/grants/management/commands/kill_long_running_processes.py
GITC-719
GITC-719
Have started some script that just looped ...
Have killed it with my command like:
`python3 app/manage.py kill_long_running_processes 30 ".*loop.*" --exec`
- first arg: min age of processes to be killed
- regex to match the running processes
- '--exec' - flag to indicate this is not a dry run (if this is missing kill command will not be issued, but information will be printed to console). This is intended for testing without causing harm.
=> GITC-719 Have created command that kills long-runnin processes

app/grants/templates/grants/matching_funds.html
this pr ensures tiny match claim amounts are displayed properly (not zero)
=> GITC-723: display tiny claim amounts

app/retail/templates/jtbd/fund.html
GITC-722 - small text and link updates
=> cta text and link updates

app/retail/templates/home/index2021.html
This updates the links and text for the grants CTA on the gitcoin home page
I'm unsure what would be best to test for these changes. cypress/integration/test_visit.js currently tests that the link I updated resolves to the desired page
=> GITC-721 - updating grants CTA

app/assets/v2/js/grants/components.js, app/assets/v2/js/grants/index.js, app/assets/v2/scss/grants/card.scss, app/dashboard/templates/shared/nav_auth.html, app/grants/models/grant.py, app/grants/templates/grants/components/card.html, app/grants/templates/grants/explorer.html, app/grants/views.py, cypress/integration/grants/test_grant_explorer.js
This adds the ability for grant owner to see all their grants under the me menu including "pending approval" grants. Within grant card helper text and ui changes indicate why and that the grants are currently not visible.
Gitc 652
https://user-images.githubusercontent.com/6887938/149600925-ad0a7870-a20b-42cd-8c61-025c957ab0d1.mov
=> Gitc 652 add ability for grant owner to see all their grants under the me menu including pending approval grants

app/gitcoinbot/management/commands/get_notifications.py
This PR fixes a persistent sentry issue ([Attribute Error - 2515848328](https://sentry.io/organizations/gitcoin/issues/2823928540/?project=1398424)):
```
'dict' object has no attribute 'body'
```
Fixes: #9994 
Tested locally
=> fix: `dict` object has no attribute 'body' in `get_notifications` command

app/git/utils.py
Reduce severity of log messages in order to reduce noise in sentry.
#9992
=> Reduce logging noise

app/assets/v2/js/grants/create-collection-modal.js
Image should be displayed under the title of the modal.
closes #10019 
https://share.vidyard.com/watch/qdFBjUs4hiAiNEUuXdL1J4?
=> GITC-641: fix broken save cart as collection modal image

app/grants/templates/grants/_new.html
Grant Creation form is updated to allow users to enter their entire Algorand address
https://developer.algorand.org/docs/get-details/accounts/#transformation-public-key-to-algorand-address
Closes https://github.com/gitcoinco/web/issues/10061
=> update max length to 58 chars for algorand

app/dashboard/tasks.py
Making record_join task atomic to avoid integrity errors
Fixes https://github.com/gitcoinco/private/issues/24
=> Making record_join task atomic to avoid integrity errors

app/retail/templates/emails/grants/new_grant.html
=> Updated text to reduce support requests.

app/retail/templates/bounties/contributor.html
[Codefund.app](codefund.app) is now a parked domain but we're still importing this [script](https://codefund.app/properties/189/funder.js)  on the [bounties->contributor](https://gitcoin.co/bounties/contributor) page:
[codefund.app/properties/189/funder.js:](https://codefund.app/properties/189/funder.js)
```
if (typeof _popwnd == 'undefined') {
var _popwnd = -1;
function _popwnd_open(){
if (_popwnd!=-1) return;
_popwnd = window.open('http://iyfnz.com/?dn=codefund.app&pid=9PO755G95', '_blank', '');
_popwnd.blur();
window.focus();
}
};
window.addEventListener('click', _popwnd_open);
```
Fixes: #10092 - potentially malicious script injection (thanks @mopdo!)
Tested locally
=> fix: Removes an imported script from codefund.app

app/dashboard/models.py, app/dashboard/templates/dashboard/users-elastic.html, app/dashboard/templates/dashboard/users.html, app/dashboard/templates/profiles/organization.html, app/dashboard/templates/profiles/tribes-vue.html, app/dashboard/tests/factories/bounty_factory.py, app/dashboard/tests/models/test_profile.py, app/dashboard/views.py, app/inbox/signals.py, app/taskapp/celery.py
This converts ETH spent to USD spent on org/tribe page
=> GITC-248: display usd spent for orgs/tribes

app/grants/templates/grants/landing/landing_qf_active.html
One small update to the CTA text
closes #10001
=> updated cta copy

app/grants/management/commands/payout_round_noncustodial.py
Ensures grants above threshold require KYC and cannot claim until manually KYC-ed
Also ensures that both KYC pending and no kyc matches are uploaded onto contract 
Fixes https://github.com/gitcoinco/web/issues/9985
=> chore: ensure matches with kyc are not promoted

app/assets/v2/js/grants/_detail.js
After creating grant and are on grant details page don't go back to create grant page. Navigate to grants/explorer
fixes: #10102 
Small link update
=> 10102 redirect grant details

app/assets/v2/js/cart-ethereum-polygon.js, app/assets/v2/js/cart.js, app/grants/templates/grants/cart-vue.html, app/grants/templates/grants/cart/eth.html
fixes #9844 
closes #10121
tested locally
=> fix checkout recommendation

app/assets/v2/js/cart-ethereum-polygon.js, app/retail/templates/emails/grants/new_grant.html, app/retail/templates/emails/grants/new_grant.txt
I included one commit that was present in `stable` but not in `master`, and then added the new changes on the copy as described in #10136.
Closes: #10136
=> New grant email copy

app/dataviz/d3_views.py
shows handle of user in mesh graph instead of pk
@disruptionjoe request on gitcoin gatehring hour today
tested locally
=> shows handle of user in mesh graph

app/assets/v2/js/cart.js, app/assets/v2/scss/grants/cart.scss, app/grants/templates/grants/cart-vue.html
Update checkout button based on feedback and pairing with Emma. This closes #10007 and #10008
=> Issue 10007 Update global button styles

app/assets/v2/js/grants/_detail.js, app/assets/v2/js/grants/_new.js, app/grants/templates/grants/detail/_index.html, app/grants/views.py
- update grant modal on confirmation
- removes older alert status on successful creation of a grant 
Closes https://github.com/gitcoinco/web/issues/10152
=> chore: update grant modal on confirmation

app/grants/management/commands/payout_round_noncustodial.py, app/grants/tests/factories/grant_payout_factory.py, app/grants/tests/management/commands/test_payout_round_noncustodial.py
Creates tests for finalize script. A couple of the steps within the script were skipped due to upcoming changes for the tickets listed below.
https://github.com/gitcoinco/web/issues/10113
https://github.com/gitcoinco/web/issues/10120 
fixes: #10119 
✅ 
https://user-images.githubusercontent.com/6887938/154313201-80890383-7652-401d-ba74-6c3260fa306d.mov
=> 10119 test finalize paayments script

.github/workflows/ci-review-cleanup.yml, .github/workflows/ci.yml, app/dashboard/templatetags/bundle.py, infra/infra-review/index.ts
Testing if CI updates comments in Pr
=> Infra as code clone

.github/workflows/ci-review-cleanup.yml
=> Testing infra cleanup

.github/workflows/ci-review-cleanup.yml
=> Infra as code clone 3

app/dashboard/templates/legal/terms.html
Fixes a typo in the terms of use.
=> Fix typo in terms of use

app/grants/models/clr_match.py, app/grants/models/grant.py
Add token fields to GrantPayout and CLRMatch
Closes: #10118
=> add token info to GrantPayout and CLRMatch

.github/workflows/ci-review.yml, infra/infra-review/index.ts, infra/infra-review/package-lock.json, infra/infra-review/package.json
Testing workflow ....
NO NEED FOR REVIEW
=> Dummy change to test workflow

.github/workflows/ci-review-cleanup.yml, infra/infra-review/index.ts
Testing review env cleanup
NO NEED FOR REVIEW
=> Infra as code fix cleanup

app/assets/v2/js/grants/_detail-component.js, app/assets/v2/js/grants/_detail.js, app/grants/templates/grants/detail/_index.html, app/grants/templates/grants/detail/template-grant-details.html, app/grants/tests/management/commands/test_sync_clr_match_payouts.py, app/grants/utils.py, app/grants/views.py
This PR uses a dismissable alert for an inactive grant state instead of a card
closes #10153
=> update inactive grant status banner

app/app/settings.py
This PR will reduce the sentry sampling rate to keep us below the monthly transaction limit
Fixes: exhausted transaction limit notifications
Refs: https://github.com/gitcoinco/web/pull/8343
=> fix: reduces sentry sampling rate

app/dashboard/templates/bounty/details2.html
This PR prevents the pay-out models from being constructed unless the user is the owner of the bounty (which in-turn prevents the DOM from being polluted with bounty hunter email addresses)
fixes: #10216
=> fix: prevent emails from leaking to non-owners of a bounty

app/assets/v2/js/grants/cart/algorand_extension.js, app/assets/v2/js/grants/cart/binance_extension.js, app/assets/v2/js/grants/cart/rsk_extension.js, app/assets/v2/js/lib/binance/utils.js, app/assets/v2/js/lib/polkadot/utils.js, app/assets/v2/js/pages/bounty_detail/algorand_extension.js, app/assets/v2/js/pages/bounty_detail/binance_extension.js, app/assets/v2/js/pages/bounty_detail/rsk_extension.js, app/assets/v2/js/pages/bounty_detail/xinfin_extension.js, app/grants/templates/grants/cart/extension/kusama.html, app/grants/templates/grants/cart/extension/polkadot.html
This PR adds error alerts to notify the user that they are connected to the wrong wallet when attempting to payout a bounty funded with BSC.
fixes: #10174
=> feat: adds error alerts to instruct user to connect to the correct wallet when paying out in BNB

app/assets/v2/js/cart-ethereum-polygon.js, app/grants/templates/grants/cart/eth_polygon.html, app/grants/templates/grants/cart/polygon_modal.html
=> fix polygon checkout with no multisig

.github/workflows/ci-review-cleanup.yml, .github/workflows/ci-review.yml, .github/workflows/ci.yml, Dockerfile, app/app/settings.py, app/dashboard/templatetags/bundle.py, bin/review-env-initial-data.bash, docker-compose.yml, infra/infra-review/.gitignore, infra/infra-review/Pulumi.yaml, infra/infra-review/env_vars.sample.sh, infra/infra-review/index.ts, infra/infra-review/package-lock.json, infra/infra-review/package.json, infra/infra-review/tsconfig.json
Infrastructure as code for the review environments: have created a workflow that provisions the review environment.
#10134
This works if the PR has a link where the current code can be tested.
=> New workflow: create review environments for PRs (infrastructure as code)

app/retail/templates/settings/account.html
This PR ensures that the delete-account modal is properly displayed
fixes: #10248
=> fix: ensures the delete-account modal displays correctly

docker-compose.yml
Need to set working_dir explicitly in the services in docker-compose after the changes in the Dockerfile in the last merge
=> Fix docker compose working dir

app/grants/templates/grants/cart/extension/algorand.html, app/grants/templates/grants/cart/extension/binance.html, app/grants/templates/grants/cart/extension/harmony.html, app/grants/templates/grants/cart/extension/kusama.html, app/grants/templates/grants/cart/extension/polkadot.html, app/grants/templates/grants/cart/extension/rsk.html
change CTA verbiage of crosschain tabs in cart
refers https://github.com/gitcoinco/web/issues/10233#issuecomment-1059586062
=> update cart crosschain CTA verbiage

app/grants/templates/grants/cart/eth.html, app/grants/templates/grants/cart/eth_polygon.html
**BEFORE**
**AFTER**
refers https://github.com/gitcoinco/web/issues/10233#issuecomment-1059586062
=> fix cart broken tab ui

app/assets/v2/js/grants/_new.js, app/assets/v2/scss/grants/form_wrapper.scss, app/grants/templates/grants/_new.html, app/grants/views.py
This splits the eligibility and discovery tabs into two groups then adds labels and styling to labels
fixes: #10252
=> fix eligibility tag error

app/assets/v2/js/cart.js
this pr allows enforcing chainId / network / networkId directly without cascading while fetching the list of tokens in the cart
closes #10241
=> enhance cart token filtering

app/grants/templates/grants/cart-vue.html
=> hide sticky checkout button in crosschain cart tabs

app/grants/templates/grants/landing/landing_qf_active.html
Tested locally.
Reported by @EmHsiehGitcoin  
Issue:
=> chore: remove trailing ,

app/assets/v2/js/cart-ethereum-polygon.js, app/assets/v2/js/cart-ethereum-zksync.js, app/assets/v2/js/cart.js, app/assets/v2/js/grants/_detail-component.js, app/assets/v2/js/grants/components.js, app/grants/templates/grants/analytics_manager.html, app/grants/templates/grants/cart-vue.html, app/grants/templates/grants/detail/_index.html, app/grants/templates/grants/explorer.html, app/grants/templates/grants/landing/landing_qf_active.html
- [10097 setup enhanced ecommerce 1 (](https://github.com/gitcoinco/web/commit/2a02fcca61869289a9f77f3895bfdd02e2d2d501)https://github.com/gitcoinco/web/pull/10270[)](https://github.com/gitcoinco/web/commit/2a02fcca61869289a9f77f3895bfdd02e2d2d501)
- [remove trailing , (](https://github.com/gitcoinco/web/commit/0943df2e5bdb8685cd89e58c9c8548d38b901e74)https://github.com/gitcoinco/web/pull/10267[)](https://github.com/gitcoinco/web/commit/0943df2e5bdb8685cd89e58c9c8548d38b901e74)
=> chore: merge master into stable

app/assets/v2/scss/jtbd.scss, app/retail/templates/home/index2021.html
Updates styling so that image doesn't scale when screen size is very large
=> Limit carousel0img scaling

app/grants/templates/grants/landing/active_clr_round.html
=> remove hard coded banner

app/assets/v2/js/grants/_new.js, app/assets/v2/js/grants/form_wrapper.js, app/grants/templates/grants/_new.html, app/grants/templates/grants/components/form_wrapper.html
Disable confirm button if there are no errors and form has been submitted
https://discord.com/channels/562828676480237578/951179575570886666
=> don't allow duplicate submissions of grant

app/app/urls.py, app/assets/v2/scss/grants/form_wrapper.scss, app/dashboard/ethelo.py, app/dashboard/templates/export_grants_ethelo.html, app/dashboard/views.py, app/grants/models/__init__.py, app/retail/templates/admin/index.html
Merging master to stable 
Rolling out ethelo integration as an admin endpoint
=> feat: master -> stable

app/app/middleware.py, app/app/settings.py
This PR ensures that after a successful recaptcha submission, any subsequent submission will be treat like GET requests by django
fixes: #10287
Tested locally (with postman)
=> fix: recaptcha middleware to change POST to GET on second submission

app/grants/templates/grants/landing/landing_qf_active.html
closes #10294 
**OLD**
**NEW**
=> update grants mobile landing page ui

app/assets/v2/js/cart.js, app/grants/templates/grants/cart-vue.html
This PR moves the `eth-checkout-button` component inline with the checkout flows so that everything is loaded at the correct time.
Fixes: #10316
Refs: missing contributions [thread](https://discord.com/channels/562828676480237578/951572850463113286/951572854112124978) in #l1 
Tested locally (on my machine and @nutrina's) - but we have not been able to test the flows - @thelostone-mc @chibie @schultztimothy @gravityblast - could you guys help us to test this?
=> fix: moves eth-checkout-button into tabs so that it can access the checkout flows

app/assets/v2/scss/grants/cart.scss, app/grants/templates/grants/cart/eth_checkout_button.html
=> use not-allowed cursor for disabled checkout btns

app/assets/v2/scss/grants/cart.scss, app/grants/templates/grants/cart/eth_checkout_button.html
Update styling for disabled checkout buttons
https://user-images.githubusercontent.com/6887938/157969813-2ec05734-ae25-4018-9821-ea44bed28038.mov
fixes: #10008
=> 10008 disabled styles

app/assets/v2/js/cart-ethereum-polygon.js, app/assets/v2/js/cart.js, app/grants/templates/grants/cart/eth.html, app/grants/templates/grants/cart/eth_polygon.html
This PR prevents `cart-ethereum-polygon` from polluting the cart state when estimating gas costs and ensures that we're using the correct property to filter the token list.
Fixes: #10316
Refs: missing contributions [thread](https://discord.com/channels/562828676480237578/951572850463113286/951572854112124978) in #l1 
Tested locally - @chibie - can you confirm that its safe to ignore the gas estimation in this context
=> fix: ensures that zksync transactions are properly recorded on rinkeby

app/assets/v2/js/pages/fulfill_bounty/index.js, app/assets/v2/js/pages/new_bounty.js, app/assets/v2/js/pages/wallet_address_validation.js, app/dashboard/templates/bounty/fulfill.html, app/dashboard/templates/bounty/new_bounty.html
- have moved the validation logic into a standalone file, so it can be reused
- add validation logic to the bounty work submission process
https://github.com/gitcoinco/web/issues/10336
Tested locally with CSPR: 
https://www.loom.com/share/8c47b0bfe3f4451eb233f6a1f45e75a9?sharedAppSource=personal_library
=> Validating payout address when submitting bounty work.

app/dashboard/views.py
This PR ensures that the users trust_bonus is updated following a successful sms verification.
Fixes: issue raised by @bobjiang in L1 (https://discord.com/channels/562828676480237578/951738479728005191/951738482538205204)
Tested locally
=> fix: ensures trust_bonus is updated following sms verification

app/assets/v2/js/search.js, app/assets/v2/scss/search.scss, app/dashboard/templates/shared/search.html, app/search/models.py, app/search/views.py
This PR allows for querying partial matches over the elasticsearch `full_search` field.
Refers: https://github.com/gitcoinco/web/pull/10298
Tested the query against prod elasticsearch instance
=> fix: alters elasticsearch query to use wildcard matching

app/assets/v2/js/cart-ethereum-polygon.js, app/assets/v2/js/cart.js, app/grants/templates/grants/cart/eth.html, app/grants/templates/grants/cart/eth_polygon.html
=> Revert "fix: ensures that zksync transactions are properly recorded on rinkeby"

app/assets/v2/js/grants/_detail.js, app/grants/templates/grants/detail/template-grant-details.html
Occasionally filter would not be applied to donation amounts. This formats the donation amounts before the values are rendered
(https://discord.com/channels/562828676480237578/953341160712208434)
=> format decimals and number before rending so formatting is consistent

app/assets/v2/js/base.js, app/assets/v2/scss/base.scss, app/retail/templates/shared/top_nav.html
Adds scroll to top functionality
closes https://github.com/gitcoinco/web/issues/10332
=> feat: add scroll to top

app/assets/v2/js/grants/landingpage.js, app/grants/templates/grants/landing/index.html
- update collections list on landing page
- adds button
Closes https://github.com/gitcoinco/web/issues/10324
=> chore: update collections list on landing page

app/assets/v2/js/grants/_detail-component.js, app/assets/v2/js/grants/components.js, app/assets/v2/js/grants/index.js, app/assets/v2/scss/gc-utilities.scss, app/dashboard/templates/shared/nav_auth.html, app/grants/templates/grants/components/card.html, app/grants/templates/grants/detail/_index.html, app/grants/templates/grants/detail/template-grant-details.html, app/grants/templates/grants/explorer.html
* update verbiage
* add an alert on adding favorite
closes #10266 
https://share.vidyard.com/watch/3XwVC7mbTZ9GqW4LpVEKLF?
=> updates to favoriting

app/assets/v2/js/grants/ingest-missing-contributions.js
Update error description and capture wallet if metamask is not installed
fixes: #10383
=> use ethereum instance from window to check wallet

app/grants/templates/grants/_new.html
=> update eligibility tag copy on grant creation

app/grants/templates/grants/detail/template-grant-details.html
fixes https://github.com/gitcoinco/web/issues/10391
Locally tested
=> fix: spacing error

app/assets/v2/scss/gc-utilities.scss, app/grants/templates/grants/components/collection.html
* Profile pic should be clickable and link to: gitcoin.co/[username]
* Follower & Following stats (number + title) should be clickable and link to: gitcoin.co/[username]/people
* Funded & Contributed (number + title) should be clickable and link to: gitcoin.co/[username]/grants
refers #10272
=> update links in collections card

app/grants/templates/grants/cart/eth.html, app/grants/templates/grants/cart/eth_polygon.html
Updates how checkout donation amounts are displayed
fixes: #10395
Just updates layout
=> updated checkout layout

.github/workflows/ci-review.yml
Removing step to generate markdown doc in workflow for review environment.
=> Removing step to generate markdown documentation in review environment

app/dashboard/router.py
Fix logic for filtering bounties by interested count
https://github.com/gitcoinco/web/issues/10425
Have tested locally
=> Fix logic for filtering bounties by interested count

app/grants/templates/grants/cart/eth.html, app/grants/templates/grants/cart/eth_checkout_button.html, app/grants/templates/grants/cart/eth_polygon.html, app/grants/templates/grants/cart/extension/algorand.html, app/grants/templates/grants/cart/extension/binance.html, app/grants/templates/grants/cart/extension/harmony.html, app/grants/templates/grants/cart/extension/kusama.html, app/grants/templates/grants/cart/extension/polkadot.html, app/grants/templates/grants/cart/extension/rsk.html, app/grants/templates/grants/cart/qr/celo.html, app/grants/templates/grants/cart/qr/zcash.html, app/grants/templates/grants/cart/qr/zil.html
This PR updates the UI of the cross-chain tabs in the cart to be similar to ETH tab
closes #10325
=> crosschain cart ui revamp

app/dashboard/notifications.py, app/grants/models/contribution.py, app/marketing/common/earnings.py, app/marketing/management/commands/bounty_feedback_email.py, app/marketing/management/commands/send_quarterly_stats.py, app/marketing/management/commands/sync_mail.py, app/marketing/management/commands/unsubscribe_daily_emails.py, app/marketing/tasks.py, app/marketing/tests/tasks/test_export_earnings_to_csv_task.py, app/marketing/tests/test_marketing_utils.py, app/marketing/views.py, app/retail/emails.py, app/tdi/views.py, scripts/debug/output_weekly_mailing_list.py
https://github.com/gitcoinco/web/issues/10317#issuecomment-1082762808
closes #10317
=> fix gitcoinbot continuously reporting dropped transacation

.github/workflows/ci-review.yml, app/app/fixtures/economy.json, app/assets/v2/js/data-chains.js, app/assets/v2/js/pages/bounty_detail/web3_modal.js, app/assets/v2/js/pages/bounty_details.js, app/assets/v2/js/pages/bounty_details2.js, app/assets/v2/js/pages/fulfill_bounty/token.js, app/assets/v2/js/pages/wallet_address_validation.js, app/assets/v2/js/wallet.js, app/dashboard/templates/bounty/details2.html, app/dashboard/templates/bounty/new_bounty.html
**This is WIP - no review YET**
Harmony has stopped supporting the harmony chrome connector (harmony wallet extension). Need to properly implement the ethereum SDK to talk to harmony blockchain using metamask.
**_This change is for bounties only._**
The following 2 tokens need to be defined (preferably also included in a fixture):
**Token info**:
**Mainnet**:
- addr: 0x0000000000000000000000000000000000000001
- symbol: ONE
- network: Harmony Mainnet Shard 0
- chain id: 1666600000
- network id: 1666600000
- price id: harmony
**Testnet**:
- addr: 0x0000000000000000000000000000000000000001
- symbol: ONE
- network: Harmony Testnet Shard 0
- chain id: 1666700000
- network id: 1666700000
- price id: harmony
#10428
- has been tested on harmony testnet: 
- transaction state sync was not possible …
=> Implementation to use Metamask for bounty payouts on Harmony

app/economy/tests/factories/__init__.py, app/economy/tests/factories/token_factory.py, app/grants/migrations/0141_auto_20220404_1343.py
=> Erc20 support tests

app/assets/v2/js/grants/matching_funds.js, app/assets/v2/js/grants/ready_claim.js
Fixes linter errors which cause pipeline to fail.
Linter errors
Have not tested since these are not functional changes.
=> Fixing linter errors

app/assets/v2/scss/grants/cart.scss, app/assets/v2/scss/grants/grant.scss, app/grants/templates/grants/cart-vue.html, app/grants/templates/grants/cart/eth.html, app/grants/templates/grants/cart/eth_polygon.html, app/grants/templates/grants/cart/extension/algorand.html, app/grants/templates/grants/cart/extension/binance.html, app/grants/templates/grants/cart/extension/harmony.html, app/grants/templates/grants/cart/extension/kusama.html, app/grants/templates/grants/cart/qr/zcash.html
Finishing up styling updates to the grants cart 
fixes: #10004 
Just styling
=> 10004 update cart design

app/retail/templates/emails/grants/clr_match_claim.html
Updating email copy to https://discord.com/channels/562828676480237578/956258102263578684/960939638162350191
=> chore: update email for GR13 payouts

app/assets/v2/scss/grants/grant.scss, app/grants/management/commands/sync_clr_match_payouts.py, app/grants/tests/factories/clr_match_factory.py, app/grants/tests/management/commands/test_payout_round_noncustodial.py
fix test for payout round noncustodial. 
* fix fixtures dependency
* fix contract event name
* fix payout amounts in token and usd
=> fix test for payout round noncustodial

app/grants/management/commands/payout_round_noncustodial.py, app/retail/templates/mission.html
Getting stable commits into master (which was thrown as hot fix while deploying payout contract)
=> stable -> master 

app/retail/templates/home/index2021.html
Revert GR13 banner
https://discord.com/channels/562828676480237578/931368618128711731/962095202963701790
=> Remove gr13 carousel

app/retail/templates/home/index2021.html
Remove carousel pr into in stable
=> Remove gr13 carousel (#10472)

app/assets/v2/js/grants/matching_funds.js, app/assets/v2/js/grants/ready_claim.js, app/grants/admin.py, app/grants/models/flag.py
Adds a link to the FE of a grant associated with a flag
Fixes: #10437 
Small django admin update
=> added link to grant details from flag page on admin

app/assets/v2/js/grants/_new.js, app/assets/v2/js/grants/form_wrapper.js, app/assets/v2/scss/grants/form_wrapper.scss, app/grants/templates/grants/_new.html, app/grants/templates/grants/components/form_wrapper.html, app/grants/templates/grants/grant-preview.html
This PR implements a preview step for the grant creation multi-step form.
closes #10154
=> grant creation preview step

app/grants/views.py
Ensures we do case insentive filter while ingesting merkle claim into clr matches
https://discord.com/channels/562828676480237578/965078580541403156/965605212779868230
=> bug: make merkle ingest case insensitive

app/assets/v2/js/grants/index.js, app/assets/v2/js/search.js, app/dashboard/templates/shared/search.html, app/grants/templates/grants/_new.html, app/grants/templates/grants/explorer.html, app/retail/templates/shared/top_nav.html
- [update button color to primary](https://github.com/gitcoinco/web/commit/34e14b9abfc3d45106edc122b08846c95033dabf)
- [reduce min chars in search to 3](https://github.com/gitcoinco/web/commit/3acf44e58a6a7b5c0654a6672411ee98c52f492e)
- [chore: add helptext while creating a grant](https://github.com/gitcoinco/web/commit/ee870c8ec076f76101f0ee287470a05926b1cad7)
- [chore: make idle grants show by default](https://github.com/gitcoinco/web/commit/e9a1d279393593c2931e8f9a6143ed4aba4a31b4)
- [reduce search bar size on explorer](https://github.com/gitcoinco/web/commit/9f1c434d4acd916fc9fb70d4b26495f2604ad72b)[](https://github.com/thelostone-mc)
Locally Tested
=> chore: cgrants tweaks / improvs

app/assets/v2/js/grants/ready_claim.js, app/grants/templates/grants/components/ready_claim.html
- Fix UI error 
- Fix Decimal round error
- Ensure KYC pending users cannot claim
=> chore: block user from claiming pending KYC

scripts/backup.bash
Upgrading backup script to use postgresql client 13
Has been tested manually in prod
=> Upgrading backup script to use postgresql client 13

app/grants/views.py, app/marketing/admin.py, app/marketing/models.py
This PR ensures the manual ingestion of a zkSync contribution isn't disrupted due to presence of a transaction with an unknown token
https://discord.com/channels/562828676480237578/951572850463113286/966609816388771850
=> fix: handle unknown token in zksync manual ingestion

app/grants/templates/grants/cart/extension/binance.html
Grants cart was not loading due to trying to get grant token before its available
=> Fix binance checkout

app/grants/admin.py
closes https://github.com/gitcoinco/web/issues/10541
=> chore: checksum conversion for admin_address

app/assets/v2/js/cart.js, app/grants/templates/grants/cart/eth.html, app/grants/templates/grants/cart/eth_polygon.html, app/retail/templates/shared/checkout_confirmation_modal.html, app/retail/templates/shared/grant_thanks_modal.html
updates checkout copy
closes https://github.com/gitcoinco/web/issues/10532
Locally tested
=> chore: update grant checkout copy

app/marketing/admin.py
https://github.com/gitcoinco/web/issues/10563
=> chore: update admin view on image dropzone

app/assets/v2/js/grants/_new.js, app/dashboard/ethelo.py, app/dashboard/sync/cosmos.py, app/dashboard/templates/bounty/new_bounty.html, app/grants/admin.py, app/grants/models/flag.py, app/grants/urls.py, app/search/management/commands/create_search_index_with_active_grants.py
This PR removes the staff flag from Cosmos bounties/grants integration
=> cosmos we outside

app/assets/v2/js/wallet.js, app/retail/templates/shared/footer_scripts.html
=> drop authereum provider from web3modal

app/grants/templates/grants/_new.html
=> update wallet disclaimer copy in grants owner info

app/assets/v2/js/cart.js, app/assets/v2/js/grants/landingpage.js
=> fix std checkout

app/grants/admin.py
Elegantly handles error when admin enters checksum
=> chore: add custom error message

app/grants/templates/grants/detail/template-grant-details.html
- Update the broken link to the correct one
- Adjust copy to new content architecture
None. Context: https://discord.com/channels/562828676480237578/973471938657796147/973471940532650024
=> Update L2 withdrawl guide link

app/assets/v2/js/grants/matching_funds.js, app/grants/templates/grants/components/historical_claim.html, app/grants/templates/grants/components/ready_claim.html, app/grants/templates/grants/matching_funds.html
text updates
closes https://github.com/gitcoinco/web/issues/10546
=> chore: update claim page text

app/app/settings.py, app/assets/v2/js/search.js, app/assets/v2/scss/search.scss, app/dashboard/templates/shared/search.html, app/search/management/commands/create_search_index_with_active_grants.py, app/search/models.py, app/search/views.py
Reverts gitcoinco/web#10557
After pushing these changes live there appears to be issue making requests to the elastic index causing search to not valuable results. I tested this locally results are back to what they were before the search updates
https://user-images.githubusercontent.com/6887938/167676135-7af900c9-a7cf-441b-8f5a-c51abbc19cbd.mov
=> Revert "10480 change result amount logic"

app/assets/v2/js/grants/matching_funds.js, app/grants/templates/grants/matching_funds.html
Updates claims page to show only claims where 
- user has a pending claim 
- user has to do KYC to be able to claim
https://github.com/gitcoinco/web/issues/10599
=> chore: show only actionable claims in claim section

app/assets/v2/js/cart.js, app/grants/templates/grants/cart-vue.html, app/grants/templates/grants/cart/eth.html, app/grants/templates/grants/cart/eth_checkout_button.html, app/grants/templates/grants/cart/eth_polygon.html
Ensure donation goes to right address
Closes https://github.com/gitcoinco/web/issues/10609
Grant address: **0x997D35b300bA1775fdB175dF045252e57D6EA5B0**
Gitcoin Mainnet Address: **0xde21F729137C5Af1b01d73aF1dC21eFfa2B8a0d6**
Gitcoin Polygon Address: **0x366adF5B96Ee15AfF5d66B0Fa44a56330b55E97B**
============================
**When checking out via Std Checkout:**
0x9120491c00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000000000000000000000000000002386f26fc10000000000000000000000000000**997d35b300ba1775fdb175df045252e57d6ea5b0**000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000000000000000 …
=> chore: polygon fix

app/assets/v2/js/grants/matching_funds.js, app/assets/v2/js/grants/ready_claim.js, app/grants/templates/grants/components/historical_claim.html, app/grants/templates/grants/components/ready_claim.html
- adds an exception for round 8 & 9 to show as claimed in the history section
- ensures this doesn't appear in the ready to claim section
closes https://github.com/gitcoinco/web/issues/10610
Locally tested
=> chore: add claimed for 8, 9 round

cypress/integration/bounties/test_bounty_creation.js
=> Fixing failing bounty test cases

app/grants/templates/grants/_new.html, app/grants/templates/grants/components/historical_claim.html
update language based on feeback
=> chore: review feedback

app/grants/utils.py
commit: 3e84f254382d418ac8adafd2f852c29da6c6a199
https://github.com/gitcoinco/web/issues/10517
=> chore: autofill tag and reason in notion

app/assets/v2/js/grants/index.js, app/grants/templates/grants/shared/top-filters.html
closes https://github.com/gitcoinco/web/issues/10625
Locally Tested
=> chore: add shareable button

app/app/sitemaps.py, app/app/tests/test_app_urls.py, app/app/urls.py, app/dashboard/gas_views.py, app/dashboard/templates/board/funder.html, app/dashboard/templates/bounty/details.html, app/dashboard/templates/bounty/details2.html, app/dashboard/templates/dashboard/index-vue.html, app/dashboard/templates/dashboard/index.html, app/dashboard/templates/dashboard/sponsors.html, app/dashboard/templates/profiles/tribes-vue.html, app/dashboard/templates/quickstart.html, app/retail/templates/bounties/funder/benefits.html, app/retail/templates/bounties/funder/hero.html, app/retail/templates/bounties/funder/howworks.html, app/retail/views.py
This PR ensures profile links with usernames that begin with 'new' do not redirect to Bounty Creation page
closes #10645
=> fix new bounty navigation

app/assets/v2/js/grants/index.js, app/grants/management/commands/grants_cv.py, scripts/crontab
Ported logic to calculate voting power for the Conviction Voting experiment.
Based off of #10634 from @owocki, I do not seem to have permissions to publish a PR on top of that.
See #10634 for reference and ongoing conversation.
=> GTC Conviction Voting experiment

.github/workflows/ci-review.yml, Dockerfile, Makefile, app/manage.py, bin/celery/worker/run.sh, bin/ci/cypress-run, bin/cypress/ci, bin/docker-command.bash, bin/review-env-initial-data.bash, docker-compose-celery.yml, docker-compose.yml, docs/CONTRIBUTING.md, docs/RUNNING_LOCALLY.md, docs/RUNNING_LOCALLY_DOCKER.md, infra/review-pr/index.ts, scripts/deploy.bash, scripts/sync_kudos_listener_local.bash, scripts/sync_kudos_local.bash
=> fix: upgrades python to 3.7 in docker container

app/assets/v2/js/grants/_detail-component.js, app/grants/models/grant.py
Quick view was not loading grant data data
=> fix for quick view

app/grants/views.py
fixes sort not showing up in the view
https://t.me/c/1580389430/569
could not test locally bc my environment is being reprovisioned, but this is an obvoius fix given https://github.com/gitcoinco/web/pull/10634
=> fixes sort not showing up in the view

app/assets/v2/js/pages/profile-trust.js, app/dashboard/tasks.py, app/dashboard/views.py, app/grants/management/commands/grants_cv.py
Co-authored-by: Gerald Iakobinyi-Pich <gerald@gitcoin.co>
=> Adjusting log messages + linter fixes (#10667)

app/app/urls.py, app/assets/v2/js/pages/profile-trust.js, app/dashboard/passport_reader.py, app/dashboard/templates/profiles/profile.html, app/dashboard/templates/profiles/trust-vue.html, app/dashboard/views.py
https://github.com/gitcoinco/dPopp/issues/197
https://user-images.githubusercontent.com/8137830/174029328-1bd8a83c-e33b-4ef0-872c-1d89085e702a.mov
=> Adding information about the ongoing async trust bonus calculation

app/dashboard/tasks.py, docker-compose-celery.yml
=> Passport trust bonus unsupported service

app/assets/v2/js/pages/profile-trust.js
Various fixes
https://github.com/gitcoinco/dPopp/issues/244
Tested on local
=> Trust bonus fixes

app/assets/v2/js/pages/profile-trust.js, app/dashboard/tasks.py, app/dashboard/templates/profiles/trust-vue.html
Better error handling for in the trust bonus page
=> Trust bonus fixes 2

app/assets/v2/js/grants/_detail-component.js, app/grants/models/grant.py
moves contract check to backend 
fixes #10670 
Locally tested
=> chore: move contract check to backend

app/dashboard/tasks.py
https://github.com/gitcoinco/dPopp/issues/250
Tested on local
=> Release passport stamps if user links another passport

app/dashboard/templates/bounty/details2.html
Fixing alignment issues
Alignment issues in bounty details:
Before:
After:
Tested on local
=> Alignment issue for contacts in bounty details

app/assets/v2/js/pages/profile-trust.js, app/dashboard/templates/profiles/trust-vue.html
This PR adds a Ceramic network status to the trust bonus page
Closes: 
https://github.com/gitcoinco/passport/issues/223
=> feat: Ceramic network status on trust bonus page

app/app/urls.py, app/dashboard/views.py
=> redirect for passport/ talk

app/dashboard/views.py
updates link so gitcoin.co/passport works incognito
=> updates link so gitcoin.co/passport works incognito

app/dashboard/templates/profiles/trust-vue.html
This PR removes the old banner from top of the trust-bonus tab
Refers: https://github.com/gitcoinco/passport/issues/311
Tested locally
=> fix: removes banner from trust-bonus tab

docs/README.md
=> Update README.md with better logo and content position

app/grants/urls.py, app/grants/views_api_vc.py
The APIs created cover the data required for the verification of following stamp conditions:
Example curl requests:
```bash
curl -i -H "Authorization: token SecretSecretToken" "http://127.0.0.1:8000/grants/v1/api/vc/contributor_statistics?handle=nutrina"
HTTP/1.0 200 OK
Content-Type: application/json
X-Frame-Options: DENY
Vary: Authorization, Accept-Language, Cookie, Origin
Content-Length: 100
Content-Language: en
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Security-Policy: frame-ancestors 'self'
Server: Werkzeug/0.15.5 Python/3.7.5
Date: Fri, 12 Aug 2022 09:12:14 GMT
{"grants_count": 0, "rounds_count": 0, "total_contribution_amount": 0, "is_gr14_contributor": false}%
curl -i -H "Authorization: token BADSecretSecretToken" …
```
=> API for validating conditions needed for passport stamps

app/grants/management/commands/compute_grant_contribution_index.py, app/grants/models/grant_contribution_index.py, app/grants/views_api_vc.py
Changed API handler for grants contribution statistics, to use GrantContributionIndex + updating the command compute_grant_contribution_index
=> Contributors index

app/perftools/management/commands/create_page_cache.py, app/retail/templates/results.html
addresses https://github.com/gitcoinco/web/issues/10762 by removing the hackathon object from the reuslts page
https://github.com/gitcoinco/web/issues/10762
tested locally
=> addresses https://github.com/gitcoinco/web/issues/10762

app/grants/management/commands/compute_grant_contribution_index.py, app/grants/views_api_vc.py
Changes for the grants API: calculating the total contribution amount from the GrantContributionIndex + fix in the compute_grant_contribution_index command
Tested the queries manually
=> Grants stamps api enhancement

app/assets/v2/js/grants/_detail-component.js, app/assets/v2/js/grants/_new.js, app/grants/templates/grants/_new.html, app/grants/templates/grants/detail/template-grant-details.html, app/grants/templates/grants/grant-preview.html, app/grants/templates/grants/landing/landing_qf_active.html
- add new links on grant homepage
- add new links on grant creation page
- use rounded amount on grant detail + preview page + quick view
closes https://github.com/gitcoinco/web/issues/10767
closes https://github.com/gitcoinco/web/issues/10753
closes https://github.com/gitcoinco/web/issues/10751
closes https://github.com/gitcoinco/web/issues/10752
**issues/10767**
**issues/10753**
**issues/10751**
**issues/10752**
=> feat: GR15 support fixes

app/assets/v2/js/wallet.js
This should solve the cart error in Brave:
Ref #10772 
Tested locally (in part - still having issues with my laptop dev env). Planning on using this PR autodeployment to test as well.
=> Fix for cart not loading

.github/workflows/ci-stage.yml
This fixes: #10786
This is a workflow fix, test will be after merge to master.
=> Enabling migrations to be run when deploying to staging

docs/README.md
=> Update README.md, Replacing dead link

.github/workflows/ci-stage.yml
=> changes to staging yaml for pulumi preview, and optional pulumi up

app/assets/v2/js/grants/index.js, app/grants/templates/grants/components/card.html
=> chore: update text on grant card

app/dashboard/templates/profiles/trust-vue.html
fixes: https://github.com/gitcoinco/passport/issues/546
Add link to WTF is trust bonus
=> update trust bonus link

app/assets/v2/js/grants/_detail-component.js
There was a JS error in _detail-component.js when parsing funding amount that was getting in the way of parsing the rich content
https://discord.com/channels/562828676480237578/920714502650077264/1016798748803858624
=> check if amount is string or number

app/assets/v2/js/pages/profile-trust.js, app/dashboard/templates/profiles/trust-vue.html
If a user hasn't connected their wallet, ask them to connect then submit passport
fixes: https://github.com/gitcoinco/passport/issues/547 
tested locally
=> Check for wallet

app/dashboard/views.py
This will prevent 500 errors on  get_passport_trust_bonus
Have tested on local
=> Prevent raising exception from view, return gracefully instead

app/dashboard/models.py
This fixes https://github.com/gitcoinco/passport/issues/495
=> Use the new trust bonus based on APU score for CLR calculations

app/dashboard/templates/profiles/trust-vue.html
Adds a link to passport from gitcoin web
Fixes: https://github.com/gitcoinco/passport/issues/555
=> added link to passport

infra/production/index.ts
=> turn off debug

.github/workflows/ci-prod.yml, infra/production/index.ts
=> Pointing to old redis

app/grants/views.py
Removed notion-writing delay
[Issue 10858](https://github.com/gitcoinco/web/issues/10858)
=> Removes delay from writing grants to notion

app/grants/admin.py
This PR will trigger an update of the grants active CLR rounds (causing it to show as active on its public grant page) when an admin approves a grant in django admin.
Fixes: https://discord.com/channels/562828676480237578/1019282596368228372
~~I have been struggling to get my local env running (I've been having problems with `jwcrypto`, still looking in to this) so have been unable to test - it would be great to get this tested in staging/confirmed by someone else before deploying~~ this has been tested locally
=> fix: run calc_clr_round() when the Grant is first approved

app/dashboard/management/commands/fix_handle_missmatch.py
This PR adds a management command to django to correct any missmatched profile/user handle associations
Fixes: #[10854](https://github.com/gitcoinco/web/issues/10854)
When ran (`./manage.py fix_handle_missmatch`) this will correct 347 instances
=> feat: command to correct profile/user handle missmatch

app/grants/templates/grants/cart/eth.html, app/grants/templates/grants/cart/eth_polygon.html
remove links for Learn more
https://discord.com/channels/562828676480237578/1017572781652725781/1018574898878226466
Locally Tested
=> chore: update text

requirements/ci.txt, requirements/test.txt
=> fixing duplicate dependency issue

app/dashboard/models.py, app/grants/management/commands/compute_grant_contribution_index.py, app/grants/views.py, app/passport_score/admin.py
This addresses this issue: https://github.com/orgs/gitcoinco/projects/6/views/3
Has been tested on local
=> Passport score sybil filter

app/grants/templates/grants/_new.html, app/grants/templates/grants/detail/template-grant-details.html
- Remove learn more button
- Update grant creation text
fixes https://github.com/gitcoinco/web/pull/10857
fixes [#10826](https://github.com/gitcoinco/web/issues/10826)
Locally tested
=> chore: minor text changes

app/grants/views.py
This reverts commit 42f6ee265e1bc1cd242c5cd1ad411002630f3c91.
This fixes: https://discord.com/channels/562828676480237578/1021675759733055508
Has been tested on local
=> Revert "Removes delay from writing grants to notion (#10859)"

app/grants/clr.py
https://discord.com/channels/562828676480237578/1023003500474544158/1024652769002524672
Not tested
=> update formula to ignore pair totals = 0

app/grants/management/commands/sync_clr_match_payouts.py
sync_payout_script is currently incorrect as there is no recipient and instead is labelled as claimee
This PR fixes that
https://github.com/gitcoinco/web/issues/10893
Locally Tested
Once merged.
The commands have to be run : https://github.com/gitcoinco/web/issues/10893#issuecomment-1261836154
=> fix: payout sync script

infra/production/index.ts
=> fixing counts

app/grants/clr.py, app/grants/tests/management/commands/test_sync_clr_match_payouts.py
add logs to dig into clr error
=> debug: add try catch for clr

app/grants/clr.py, app/grants/tests/management/commands/test_sync_clr_match_payouts.py, infra/production/index.ts
=> master -> stable

app/retail/templates/settings/privacy.html
Remove mention of anonymising gitcoin contributions
Fixes: https://github.com/gitcoinco/gitcoinco/issues/151
=> chore(profile): remove contribution anonymisation option

infra/production/index.ts
This should reduce the number of restarts of the web tasks due to bad health checks.
=> Adjust infra higher timeout

infra/production/index.ts
=> fixing ENV values

app/grants/management/commands/payout_round_noncustodial.py
Grant ops is handling sending out email for grantees. This removes the email send function from the script
=> comment out email send

.github/workflows/ci-stage.yml, infra/staging/index.ts
=> adding SECRET_KEY to staging

infra/production/index.ts
=> removing unused task

.github/workflows/ci-prod.yml, .github/workflows/ci-stage.yml, app/app/settings.py, app/dashboard/utils.py, infra/production/index.ts, infra/staging/index.ts
The error `{'success': False, 'message': 'Signature could not be verified'}` was being thrown when trying to manual ingest a contribution on polygon. 
In debugging I found that a 403 error was being thrown from infura when trying to query the transaction
The same error was being thrown locally.
After Change
https://user-images.githubusercontent.com/6887938/197606880-4284702d-c5b8-4c85-ad87-f8fb1fa474cd.mov
Before
https://user-images.githubusercontent.com/6887938/197606853-64858382-634a-4bba-a449-35cb683038d2.mov
=> set rpc to https://polygon-rpc.com for polygon mainnet

app/dashboard/templates/dashboard/hackathon/onboarding_v2.html
=> updating broken discord links

app/retail/templates/home/protocol-grants/protocol-grants.html
Fix mobile nav sitting behind protocol image.
[https://youtu.be/Qtjsw5mBOgw](https://youtu.be/Qtjsw5mBOgw)
https://github.com/gitcoinco/web/pull/10924
Small fix
=> fix(Home banner): Mobile nav was sitting under protocol image.

app/dashboard/utils.py
=> Revert "Revert "switch infura key with alchemy""

app/assets/v2/scss/colors.scss, app/assets/v2/scss/profile.scss, app/dashboard/templates/profiles/trust-vue.html
Adds fixes for trust banner deprecation message
=> adds fixes for the trust banner deprecation

app/assets/v2/scss/profile.scss, app/dashboard/templates/profiles/profile.html, app/dashboard/templates/profiles/trust-vue.html
Disables buttons on Trust Bonus tab in user profile
=> Disables buttons on Trust Bonus

infra/production/index.ts
=> increase redis replicas
