README.md

Adjust some paths according to actual source tree. Remove `sync_db` command,
deprecated from Django 1.9. Add comand to create Django cache table in Postgres

Fix instruction for running locally

---

app/app/settings.py

HTTP Strict Transport Security (HSTS) is an opt-in security enhancement that is specified by a web application through the use of a special response header. Once a supported browser receives this header that browser will prevent any communications from being sent over HTTP to the specified domain and will instead send all communications over HTTPS. It also prevents HTTPS click through prompts on browsers.
[OWASP HSTS](https://www.owasp.org/index.php/HTTP_Strict_Transport_Security_Cheat_Sheet)
[OWASP HSTS test](https://www.owasp.org/index.php/Test_HTTP_Strict_Transport_Security_(OTG-CONFIG-007))
[Django HSTS](https://docs.djangoproject.com/en/1.11/ref/middleware/#http-strict-transport-security)
[Django HSTS settings](https://docs.djangoproject.com/en/1.11/ref/settings/#secure-hsts-include-s …

HTTP Strict Transport Security

---

app/assets/yge/youvegoteth/send.js
app/assets/yge/youvegoteth/shared.js
app/dashboard/helpers.py
app/dashboard/templates/yge/send2.html

The goal of this PR is to fulfill #53 by implementing approx USD display following tip ETH amount.
I'm not a big frontend person, so bare with the PR.  I'll submit revisions where necessary, but it calculates as requested.

Update tip page to auto calculate USD

---

app/dashboard/models.py
app/marketing/models.py
app/tdi/models.py

The goal of this PR is to properly display:
- `Matches`
- `Access codes`
- `Bounties`
- `Whitepaper access`
while navigating the django admin.

Fix display of plurals for some models in admin

---

app/economy/management/commands/get_prices.py

The goal of this PR is to resolve #94 by updating the `get_prices` api to use the new etherdelta websocket-based API documented at:  https://github.com/etherdelta/etherdelta.github.io/blob/master/docs/API.md

Update get_prices to use new etherdelta WS API

---

app/marketing/mails.py

This change to ensure that the tip amount  displayed in the mail is consistent with tip
I'm assuming the smallest tip which can be assigned to anyone is `0.001`
**File(s) modified**
- mails.py
**Module(s) changed**
- template
**Fixes**: https://github.com/gitcoinco/web/issues/103
**Checklist**

fix: rounded tip amount to 3 decimal places in mail

---

app/assets/v2/css/timeline.css

Images in the landing page timeline section were overflowing their containers. Not anymore.

css: resize images to fit within the timeline container

---

app/assets/yge/css/main.css

**Problem:**
On this tip, the background image overflows (as the position keeps changing ) cause the screen to be scroll-able as the screen bg changes position, bad user experience.
**Fix:** A single line of css
@owocki Might need an extra pair of eyes to look into this , to make sure nothing else is broken.

css: fixed overflow scroll on tip recieve page

---

app/assets/v2/css/timeline.css

Some blocks still shift and it shifts when content fits, see:
https://drive.google.com/open?id=1Oaj7HIMb9gt4PPbd6x0w06njsiicXf2v
css: fix roadmap items shift by reducing padding on div :hover
Fixes: #100

fix roadmap items shift #100

---

requirements-test.txt

The goal of this PR is to resolve the false failing on Travis due to a dependency conflict with the `ethereum` package.
Travis/testing
Fixes #123

Resolve false fail on Travis

---

app/assets/v2/js/pages/bounty_details.js

PR is being submitted for #81.
We are currently generating some buttons on the gitcoin UI
by first querying information about the bounty and then deciding
what buttons to add on the UI based on that info.
However, we are only generating these buttons based on the
status of the bounty on the blockchain, and we do not take into account
whether the user is supposed to see those buttons. (For example, it makes
little sense for a person who just created a bounty to then claim their
own bounty.)
To prevent users from seeing buttons that they are not meant to see,
we will use the 'bounty_owner_address' to decide whether somebody
is a "Bounty Owner". If a user is currently logged into Metamask
and have the same address as the 'bounty_owner_address',
then they are likely the Bounty Owner. We then …

Remove misleading buttons on gitcoin UI

---

app/assets/v2/css/base.css
app/assets/v2/css/buttons.css
app/assets/v2/css/carousel.css
app/dashboard/templates/shared/search_bar.html
app/retail/templates/about.html
app/retail/templates/email_settings.html
app/retail/templates/getgitcoin.html
app/retail/templates/help.html
app/retail/templates/index.html
app/retail/templates/shared/hero.html
app/retail/templates/shared/mailchimp.html
app/retail/templates/slack.html
app/retail/templates/whitepaper_accesscode.html
app/retail/templates/whitepaper_new.html

Fixes: https://github.com/gitcoinco/web/issues/126
- I removed the `raise` class from all buttons to fix glitches. In all buttons that used to contain that class, interactivity is now indicated by a contrast change.
- **Hero buttons:**
Old:
New:
- **Carousel buttons.**
Old:
New:
- **Email submit form.**
Old:
New:

Glitches fixes and overall better buttons look and feel

---

app/dashboard/management/commands/cleanup_db_space.py
requirements.txt

The goal of this PR is to resolve #142 by pinning `cytoolz` to `0.8.2` and resolving an isort error in cleanup_db_space.py file.
Travis CI
Fixes #142

Resolve Travis failures on dependency conflict

---

app/assets/v2/js/tokens.js
app/assets/yge/youvegoteth/tokens.js
app/dashboard/tokens.py

add http://arcade.city  token base ARCD
https://etherscan.io/token/0xb581e3a7db80fbaa821ab39342e9cbfd2ce33c23
https://blog.arcade.city/the-arcade-token-arcd-sale-and-community-giveaway-begins-now-8eca8a503de1
- dashboard
- crypto

add http://arcade.city  token base ARCD

---

requirements.txt

The goal of this PR is to resolve the failing travis builds that are a result of the python ethereum version change (since we aren't pinning that module until something like #146 is merged).
Travis CI
Fixes #163

Pin cytoolz to 0.9.0 to fulfill ethereum new reqs

---

app/assets/v2/css/carousel.css
app/assets/v2/js/pages/carousel.js
app/retail/templates/shared/testimonials.html

Set display as none when slide goes out of focus. Ensures that user
get redirected to the active slides author profile  upon click.
- ui
__Currently:__ 
(head out to the testimonial section and click on the authors name, it redirects to issacs GitHub profile as even though the slide is hidden, it still exists in the background )
__hint: look at the bottom left corner__
__After this commit:__

carousel: fixed css 

---

app/marketing/models.py
app/tdi/views.py

Gitcoin Core currently generates hashes from low-entropy, predictable
data. While they may appear random to outside observers, looking at the
source code quickly shows these as being predictable.
The construct used in both places appears to be a RIPEMD-160 hash
salted with the RIPEMD-160 hash for empty string and then the Django
timezone. An adversary with knowledge of the rough time in which a
secret was generated may use this knowledge to predict the hash used for
the whitepaper access code or the `priv` property.
This pull request removes the `hashlib` from use and generates
hexadecimal secrets from the OS `urandom` facility. These strings are
then truncated to match the same length as previously to avoid any
compatibility issues.
While the construct with `codecs` may appear strange, …

Generate high-entropy secrets and codes

---

app/dashboard/templates/profile_details.html

The [profile](https://gitcoin.co/profile/thelostone-mc) page of the user where the link to their github repo is available is invalid!
**Current link:** https://github.com/thelostone-mc/repos
**Actual link:** https://github.com/thelostone-mc?tab=repositories
- html

html: fixed github repo link

---

app/assets/yge/css/main.css
app/assets/yge/sass/base/_typography.scss
app/dashboard/templates/yge/base.html
app/dashboard/templates/yge/send1.html

Similar to #116 and discussed in #151 this PR removes the global (on body) `text-transform: uppercase` style from the /tip (yge) application. 
As discussed in #151 properties like the bounty status should also be normalized (capitalized in the UI) 
These properties are stored in the DB and we need to decide where to put that presentation logic. 
ui
* #151 - "typography cleanup after PR #116"

Remove all-caps default in /tip (yge)

---

app/app/urls.py
app/assets/v2/css/base.css
app/assets/v2/js/pages/claim_bounty.js
app/assets/v2/js/pages/clawback_expired_bounty.js
app/assets/v2/js/pages/new_bounty.js
app/assets/v2/js/pages/process_bounty.js
app/assets/v2/js/shared.js
app/dashboard/templates/claim_bounty.html
app/dashboard/templates/clawback_expired_bounty.html
app/dashboard/templates/process_bounty.html
app/dashboard/templates/shared/metamask_estimate.html
app/dashboard/templates/submit_bounty.html
app/dashboard/views.py
app/gas/management/commands/sync_gas_prices.py
app/gas/utils.py
app/retail/templates/gas.html
scripts/debug/process_bounty.js

https://twitter.com/owocki/status/948304738306605056
* do the 'new bounty' form.  (i've already done the claiming, clawback, and process page)
* do the 'tips' form.
* do an estimate of how much ETH / USD it will cost on the page.
* allow user to update gas price and see an estimate of confirmation times and price on the page.
* see a warning when network conditions are clogged.

metamask gas price preview

---

app/assets/v2/js/tokens.js
app/assets/yge/youvegoteth/tokens.js
app/dashboard/tokens.py

Add RDN Token support for gitcoin
RDN Token: https://etherscan.io/token/0x255aa6df07540cb5d3d297f0d0d4d84cb52bc8e6
Raiden Info: https://raiden.network/ 
* dashboard
* crypto
Refs: #155

Add RDN Token support

---

app/assets/v2/js/pages/bounty_details.js
app/assets/v2/js/pages/dashboard.js

When the Issue Explorer is visited there are XHR requests to an endpoint related to bounties information. Due a missing trailing slash in the XHR's the API server returns with a 301 redirect and duplicate XHR's (now with the trailing slash) are sent out. This fix adds the trailing slashes into the JS files where the requests are sent out, so as to prevent the 301 and reduce loading time and bandwidth, if only by a small amount.

Changed bounties URL in JS to prevent 301 redirect

---

.pre-commit-config.yaml
app/dashboard/models.py
docs/CONTRIBUTING.md

The goal of this PR is to introduce [pre-commit](https://pre-commit.com/#install) for handling pre-commit checks (isort, eslint, etc).
Currently, this initial implementation enabled the `isort` pre-commit hook, which will verify that all python file imports are properly sorted.
Steps to install/test from within the `web` repository directory:
- `brew install pre-commit`
- `pre-commit install`
- Modify any .py file to include unsorted imports
- Attempt to stage the changes

Add initial pre-commit configuration

---

README.md
app/app/local_settings.py.dist

doc: changed port to 8000 in github integration ( same port as what the server is running )
- doc
- settings
Refs: https://github.com/gitcoinco/web/pull/271

doc: changed port to 8000

---

app/marketing/management/commands/ingest_slack_users.py
app/marketing/utils.py
app/retail/views.py

The goal of this PR is to modify Slack invitation handling.  Previously, we were calling `invite_to_slack` twice for users attempting to join slack via the `/slack` endpoint (calling the method: `invite_to_slack` in both the view and the `get_or_save_email_subscriber` method).
Refs: #276

Modify slack email invitation handling

---

app/app/settings.py
app/dashboard/templates/shared/github_username.html
app/dashboard/views.py
app/github/tests/test_utils.py
app/github/utils.py

The goal of this PR is to resolve an issue with `Tip` notifications not going out to the intended recipient email address.
Additional adjustments include fixing the github auth template to display the login link if they are not authenticated with github and adjusted the github scope to request read-only permissions.
Fixes #321

Adjust email handling for tip flow

---

app/assets/v2/css/base.css
app/assets/v2/css/gitcoin.css
app/dashboard/templates/shared/nav_internal.html
app/retail/templates/help.html
app/retail/templates/shared/nav.html
app/retail/templates/slack.html

replaced img with font-awesome -> page loads a tad bit faster
If this is alright, will do it in batches so as to use icons rather than images + refactor along the way
- replaced slack image with slack font-awesome
- re-indented nav
- noticed that nav bars have different size on different pages, so evened it out
- html

html: replaced slack image with font-awesome icon

---

app/dashboard/embed.py

Fixes: https://github.com/gitcoinco/web/issues/355
Now scales avatar photos by using [ImageOps.fit](http://pillow.readthedocs.io/en/4.0.x/reference/ImageOps.html#PIL.ImageOps.fit) instead of [Image.thumbnail](http://pillow.readthedocs.io/en/4.0.x/reference/Image.html#PIL.Image.Image.thumbnail) because Image.thumbnail will modify the image only if is larger than the given size. 
*Before*:
*After*:
As this is my first PR contributing to this repo, please let me know if I missed anything or if I need to include more data here. I read the CONTRIBUTING.md guide but I'm nervous I missed something 😬 
dashboard/embed
Fixes #355

Use ImageOps.fit instead of Image.thumbnail 

---

app/assets/v2/js/pages/fulfill_bounty.js

Just changes the call to `Math` to be `Math.pow` for the gwei to ether gas calculation so the submitting process doesn't throw. Looking at commit history, seems like a bad merge occurred somewhere. Pretty straightforward unless I'm missing something here 😁 
frontend
Fixes https://github.com/gitcoinco/web/issues/357

Changes Math to Math.pow for gwei->ether gas calculation

---

app/assets/v2/css/help.css
app/assets/v2/js/base.js
app/retail/templates/help.html

- optimized for mobile
- gave breathing space for FAQ and added basic animation (not visible in the gif )
- changed fonts to OpenSans
- refactored skeleton
- css
- https://github.com/gitcoinco/web/pull/333 // The slack image in the footer is replaced with an icon here
- https://github.com/gitcoinco/web/pull/323 // Required font used here

css: prettified /help page

---

Dockerfile
docker-compose.yml

When a user clones the `gitcoinco/web` repository on Windows without `--config core.autocrlf=input`, provisioning scripts are formatted incorrectly for execution in the deb container.
The goal of this PR is to resolve that issue by converting the `docker-command.bash` during the image build process with `dos2unix`.
Tested building and running the docker-compose stack on both macos high sierra (10.13.2) and Windows 10.
Refs: #363

Update Docker image to support Windows

---

app/dashboard/migrations/0039_useraction.py

The goal of this PR is to resolve the migration conflict introduced at: https://github.com/gitcoinco/web/pull/327/files#diff-b4f8f4003f31ce33f37b646c42e12eb5
Refs: #327

Fix migration conflict

---

app/dashboard/views.py

Fixes the currently failing build messages:
```
――――――――――――――――――――――――――――――――― isort-check ――――――――――――――――――――――――――――――――――
ERROR: /home/travis/build/gitcoinco/web/app/dashboard/views.py Imports are incorrectly sorted.
Subscription, Tip,
)
from dashboard.notifications import maybe_market_tip_to_email, maybe_market_tip_to_github, maybe_market_tip_to_slack
+from dashboard.utils import get_bounty, getBountyID, has_tx_mined
from dashboard.utils import process_bounty as web3_process_bounty
-from dashboard.utils import get_bounty, getBountyID, has_tx_mined
from gas.utils import conf_time_spread, eth_usd_conv_rate, recommend_min_gas_price_to_confirm_in_time
from github.utils import get_auth_url, get_github_emails, get_github_primary_email, is_github_token_valid
from marketing.models import …
```

Fix isort-check build failure

---

app/dashboard/views.py
requirements/base.txt

Update web3 and eth-utils to fix issue 488

---

app/assets/v2/css/forms/select.css

Due to custom icons on select2 selects we used an image for the dropdown arrow. This image needs to have `pointer-events` removed.
UI
Pull down and test
#514

Fix unselectable icons on select2 selects

---

app/assets/v2/css/dashboard.css

noticed that a few devices have width 380px which causes the github comment section to break
Fixed that up ! It's not needed but meh why not

css : fixed display for devices below 380px

---

app/assets/v2/css/base.css
app/assets/v2/css/forms/input.css
app/assets/v2/css/search_bar.css
app/dashboard/templates/dashboard.html
app/dashboard/templates/shared/search_bar.html

Added the sort feature in the search tab on the explorer page
- css
- https://github.com/gitcoinco/web/issues/570

explorer: added sort feature

---

app/assets/v2/css/base.css
app/dashboard/templates/shared/status_tooltip.html

- Updated the tooltip on the explorer page. 
- Made it generic enough to be reused.
- Added the styling to `base.css`
- ui

explorer: updated tooltip

---

app/marketing/management/commands/assemble_leaderboards.py
app/marketing/management/commands/expiration_start_work.py
app/marketing/management/commands/send_subscription_mails.py
app/marketing/tests/management/commands/test_assemble_leaderboards.py
app/marketing/tests/management/commands/test_expiration.py
app/marketing/tests/management/commands/test_expiration_start_work.py
app/marketing/tests/management/commands/test_expiration_tip.py
app/marketing/tests/management/commands/test_remarket_tweet.py
app/marketing/tests/management/commands/test_roundup.py
app/marketing/tests/management/commands/test_send_subscription_mails.py
app/marketing/tests/management/commands/test_sync_keywords.py
app/marketing/tests/test_marketing_utils.py
app/marketing/webhookviews.py

Adding tests to increase code coverage from 28% to 33%. Testing marketing module.
marketing
This PR is increasing test coverage. Only one little refactor was made.
[#408](https://github.com/gitcoinco/web/issues/408)

Writing coverage for marketing model, increasing coverage to 33%

---

app/dashboard/utils.py

fix for 
http://bits.owocki.com/0m450K2E0S3t/Screen%20Shot%202018-03-13%20at%206.01.19%20PM.png
https://github.com/JoinColony/colonyNetwork/issues/174#issuecomment-372719525
notifications
tested it

fix for empty github notification

---

.eslintrc
.pre-commit-config.yaml
.travis.yml

The goal of this PR is to enable `eslint` to run via `pre-commit` and on Travis, to ensure JS styling on already styled files.
pre-commit, travis, git
- Tested the pre-commit with both failing and passing cases
- Tested Travis on `mbeacom/web`

Enable ESLint in pre-commit and on Travis CI

---

app/faucet/views.py

doesnt allow a user to spoof their github username
also, fixes that `e.messages` does not exist.
```
ipdb> e.messages[0]
*** AttributeError: 'Exception' object has no attribute 'messages'
```

no faucet spoofing

---

app/assets/v2/js/shared.js
app/dashboard/views.py

Fixes https://github.com/gitcoinco/web/issues/478 - People shouldn't be able to start work on more than 3 issues at a time
interest
tested it
https://github.com/gitcoinco/web/issues/478

People shouldn't be able to start work on more than 3 issues at a time

---

app/assets/v2/js/pages/bounty_details.js
app/dashboard/helpers.py
app/dashboard/templates/bounty_details.html
app/dashboard/views.py

Records `UserAction` events for Tip, Start/Stop Work, and Bounty related events
Analytics
This is a continuation of https://github.com/gitcoinco/web/pull/513 but without all the weird sync_profile changes

Records UserAction events for Tip, Start/Stop Work, and Bounty related things

---

app/app/urls.py
app/assets/v2/js/pages/bounty_details.js
app/assets/v2/js/pages/increase_bounty.js
app/assets/v2/js/pages/new_bounty.js
app/assets/v2/js/shared.js
app/dashboard/helpers.py
app/dashboard/notifications.py
app/dashboard/templates/increase_bounty.html
app/dashboard/tests/test_notifications.py
app/dashboard/views.py

Gives the funder the ability to increase the payout.
Changes:
- add new route for increase_bounty view
- add increase_bounty view and js
- DRY up duplicate code in new_bounty.js and increase_bounty.js
- implement bounty increase notification through git, slack and twitter
- ui
Testing in progress
Fixes #617

Integrate StandardBounties increasePayout()

---

app/dashboard/notifications.py
app/dashboard/views.py
app/marketing/management/commands/remarket_tweet.py

Tweets about changes to bounties to https://twitter.com/gitcoinfeed
This allows the app to market to twitter again, after Vivek and I disabled it in January.  By taking our twitter presence and merging it into two different boths (getgitcoin - the main one) and (gitcoinfeed - just a firehose), we are able to balance the needs of our audience.
must be merged with https://gitlab.com/Owocki/gitcoin_server/merge_requests/6

twitter.com/gitcoinfeed

---

app/dashboard/views.py

Today we started seeing some issues wherein we would take some action (submit work, kill bounty, etc), and the system would not be able to pull updated data from infura, even after the tx had been confirmed.
on the presumption that this is some sort of state inconsistency issue upstream to us (likely at our web3 provider)... i am building some resilience into the `sync/web3` endpoint by allowing it to retry up to 3 times if it does not receive the changes from the upstream provider.

workaround for web3 sync issues

---

app/assets/v2/css/bounty.css
app/assets/v2/js/pages/bounty_details.js
app/dashboard/templates/bounty_details.html

- vertical aligned activity section
- Changed Kill Bounty -> Cancelled Bounty
- Changed Order of Cancel Bounty  & Add contribution
- https://github.com/gitcoinco/web/pull/691

bounty: review feedback added

---

app/retail/templates/shared/head.html

Forgot to remove this ! Sorry 😅 
@mbeacom white still looks better :P

html: removed extra css link from header.html

---

app/assets/v2/css/bounty.css
app/assets/v2/js/pages/bounty_details.js
app/assets/v2/js/shared.js

- Fixed wonky contributor info
- Added comma separated info  
Added comma separated info  
- css 
- js
@PixelantDesign

bounty: css fix for wonky contributor info

---

app/dashboard/templates/shared/sidebar_search.html

explorer: added missing css stylesheet to enable checkbox css
- html
- https://github.com/gitcoinco/web/issues/744

explorer: added missing css stylesheet

---

app/assets/v2/css/toolbox.css
app/dashboard/templates/toolbox.html

- Updated the sidebar on the tooltip to make it look a tad bit classier
- Replaced OpenSans with Multi on toolbox
- css
@owocki thought ? :P

css: sidebar fixup

---

docs/README.md

Contributing Link in README.md doesn't work : On clicking the link provided in first bullet point (link for guidelines) under heading On Github, it takes the user to 404 Not found page.
Fixes: #755

Fixed Contributing Link in README.md

---

app/assets/v2/css/bounty.css

^Removing the extra letter spacing for the description section
After fix
- css

bounty: css letter spacing fix for h1..h6

---

app/retail/templates/emails/template.html

Emails should contain actual year in copyright section.
emails
printed html to console :wink: 
Fixes #765

current year in copyright email section

---

app/assets/v2/css/base.css
app/assets/v2/css/forms/form.css
app/dashboard/templates/shared/bounty_nav.html
app/dashboard/templates/submit_bounty.html

Updates to responsive styles for new issue form.
UI for new issue form
Tested these changes in a responsive emulator. Also checked codebase for any scoping issues and found none.
Fixes: #679

#679 - new issue responsive updates

---

app/dashboard/templates/kill_bounty.html
app/dashboard/templates/process_bounty.html

- html
- https://github.com/gitcoinco/web/issues/780
- https://github.com/gitcoinco/web/issues/786

bounty: process + kill bounty width fix

---

app/assets/v2/js/pages/dashboard.js
app/dashboard/templates/shared/sidebar_search.html

If user is not logged in, my projects filters are disabled.
frontend
tested manually
Refs: #769

disable my projects filters if user not logged in

---

app/assets/v2/js/pages/dashboard.js

Fix for https://github.com/gitcoinco/web/issues/783 
- js
- https://github.com/gitcoinco/web/issues/783

explorer: updated label for issues with status done

---

app/assets/v2/css/bounty.css
app/assets/v2/js/pages/bounty_details.js
app/assets/v2/js/shared.js
app/dashboard/templates/bounty_details.html

- changed the order of action buttons
- start work turns white on starting work
- added svg background to comment
- fixed margin between action buttons
The change in order of buttons and color was implemented as discussed offline with @PixelantDesign

bounty : minor changes

---

app/assets/v2/css/bounty.css
app/assets/v2/js/pages/bounty_details.js
app/dashboard/templates/bounty_details.html

bounty: fixed avatar url + tooltip style

---

app/app/settings.py

@mbeacom i noticed this when dockerizing my setup: i think that the TODOs in the settings file shoudl be falsy, so that `settings.GITHUB_CLIENT_ID` (and others) are falsy... and we don't try to send out a bunch of github/twitter/slack notifications because of lines of code like [this](https://github.com/gitcoinco/web/blob/kevin/todo/app/dashboard/notifications.py#L66) everywhere.

todos should be falsy

---

app/assets/v2/css/bounty.css

Fixed up the actions buttons to ensure it's rendered right on mobile 
- css
-  https://github.com/gitcoinco/web/issues/759

bounty: mobile alignment fix

---

app/assets/v2/css/base.css
app/assets/v2/css/gitcoin.css
app/assets/v2/js/pages/dashboard.js
app/dashboard/templates/bounty_details.html

---
---
- html
- css
- js
- https://github.com/gitcoinco/web/issues/808
- https://github.com/gitcoinco/web/issues/816

bug fix : bounty + landing + dashboard

---

app/assets/v2/css/bounty.css
app/assets/v2/js/pages/bounty_details.js
app/dashboard/templates/bounty_details.html

- Added progress bar for expiring time
- Refactored a bit
- css
- js

bounty: added progress bar

---

app/assets/v2/css/base.css
app/dashboard/templates/profile_details.html

Separated profile and username to 2 lines. 
Fixes: https://github.com/gitcoinco/web/issues/792

Fixes: https://github.com/gitcoinco/web/issues/792

---

app/dashboard/models.py
app/dashboard/utils.py

Fixes: https://github.com/gitcoinco/web/issues/855

update can_submit_after_expiration_date 

---

bin/docker-command.bash
docker-compose.yml
docs/RUNNING_LOCALLY_DOCKER.md

This PR fixes a problem where if I 
`docker-compose up -d` then `docker-compose stop web; docker-compose run --service-ports web` 
as described [in the docs](https://github.com/gitcoinco/web/blob/master/docs/RUNNING_LOCALLY_DOCKER.md#ipdb)
i can no longer `exec` on the docker intance
```docker-compose exec web /bin/bash```
returns
```ERROR: No container found for web_1```
this is what `docker-compose ps` returns
```
Name                   Command                State             Ports
----------------------------------------------------------------------------------
web_db_1        docker-entrypoint.sh postgres    Up         0.0.0.0:5432->5432/tcp
web_node_1      bin/docker-node.sh               Exit 1
web_pgweb_1     /usr/bin/pgweb --bind=0.0. ...   Up         0.0.0.0:8081->8081/tcp …
```

docker shell fixes

---

Makefile
docker-compose.yml
docs/RUNNING_LOCALLY_DOCKER.md

The goal of this PR is to introduce entrypoints for `ipdb` and the django shell via `make` commands.
The method used in this PR allows us to inspect the ipdb shell and the django shells without an additional container in our compose stack.
Tested with multiple `web` repo directories to ensure the parent directory name (first part of compose image name) is properly detected.
Ref #861 - This PR aims to handle the same case as this PR.

Add ipdb and django shell access to docker setup

---

app/assets/v2/css/base.css
app/dashboard/templates/shared/nav_auth.html
app/retail/templates/shared/nav.html

refreshes the nav of the site
* landing/about/etc pages now show login option instead of the 'get gitcoin' button
* login button shows github logo instead of blockie [screenshot -- left is logged out, right is logged in](http://bits.owocki.com/221E2M2B0y09)
why
* increases conversion rate by showing one clear action instead of the insane get gitcoin modal
* unifies nav across the site
ui
tested in a bunch of resolutions
self

new nav for auth/login for site

---

app/assets/v2/js/pages/wallet_estimate.js
app/dashboard/templates/fulfill_bounty.html
app/dashboard/templates/increase_bounty.html
app/dashboard/templates/kill_bounty.html
app/dashboard/templates/process_bounty.html
app/dashboard/templates/shared/wallet_estimate.html
app/dashboard/templates/submit_bounty.html

Identify and handle trust wallet both in name and imaginery.
frontend
locally
Refs: #680

identify trust wallet

---

app/dashboard/notifications.py
app/marketing/management/commands/expiration_start_work.py

Github comments from gitcoinbot when a user is removed from the issue.
[example issue](https://github.com/gitcoinco/web/issues/540)
This gives context to anyone looking back at the thread to try and figure out what is going on with the issue that the github bot has kicked them off of the issue.
In addition, this PR will enable notifications to slack so that we can deal with it internally
bot
tested
self

Github comments when user is warned/removed (in addition to the emails that are sent when this happens)

---

app/dashboard/templates/shared/nav_auth.html

The goal of this PR is to introduce a navbar option for staff members that links to the django admin for easy access.  Additionally, this PR modifies the font awesome icon used for `Manage Settings` from `email` to `cog` to align with the changes from `Manage Email Settings` to `Manage Settings`
navbar, ui
Tested locally as a user with and without `user.is_staff == True`

Add admin link to navbar for staff and switch settings icon

---

app/assets/v2/css/base.css
app/assets/v2/css/search_bar.css
app/dashboard/templates/dashboard.html
app/dashboard/templates/shared/nav_auth.html

- Used font-awesome icon instead of img
- Fixed up the media-query for tablet view on the explorer (followed the guidelines as in given in bootstrap )
@PixelantDesign Can we keep the filter visible only for tablets (in landscape) & above ? 
As a user -> it's not fun scrolling on smaller devices just to get past the filters ( or we could make it into as an accordion which expands on click )
- removed blue notification at the bottom 
- html
- css

nav + explorer fixes

---

app/retail/templates/shared/nav.html

Navbar responsive issues 
* spaceship img hidden on < md screens
* removed spaceship img right margin so login doesnt exceed window
frontend
locally
Fixes #903

navbar responsive issues

---

app/dashboard/models.py
app/dashboard/tests/test_dashboard_models.py

This PR makes the expiration status less inclusive.
Before, if a bounty was past its expiration date and had no fulfillments it would be marked as expired
Now, after this change, the bounty will only be status expired if its past its expiration date if
* it was one of the bounties that existed before https://github.com/Bounties-Network/StandardBounties/issues/25
* and it's past its expiration date
otherwise, it will revert to one of the following statuses: open, started, submitted, done.
db
tested it
https://gitcoincommunity.slack.com/archives/G9ZRKFS68/p1524066432000794

make expiration status less inclusive

---

app/assets/v2/css/about.css
app/retail/templates/about.html
app/retail/views.py

- Cleaned up the team section in `/about`
- Added missing `div`
- Pending removal of stale CSS code once I can get the mgmt commands working to populate the leaderboard
- Updated job opening section
- html
- css

about: core team design revamp

---

app/assets/v2/js/pages/bounty_details.js

As of now, time left section is displayed canceled bounties which seems irrelevant.
Example: https://gitcoin.co/issue/thelostone-mc/web/411
- js

bounty: hide timeline on cancelled bounties

---

app/dashboard/notifications.py
app/marketing/management/commands/expiration_start_work.py

adds the following copy to gitcoin bot warnings about removal for non-action on an issue:

verboseness of gitcoinbot reminders

---

app/dashboard/models.py
app/marketing/mails.py
app/marketing/tests/test_mails.py

The goal of this PR is to resolve `Profile` queries resulting in `None` and attempting to use `Profile` class methods by replacing the query for `Profile` to `User` for `setup_lang()` and falling back if the found user doesn't have a profile for whatever reason.
i18n, notifications
Tested locally
Fix #979 
Ref #810

Modify setup_lang to use User

---

app/assets/v2/js/pages/new_bounty.js
app/dashboard/helpers.py

Today, Greg from MakerDAO was having trouble submitting his DAO bounties to the platform.  
Specificially, what was happeneing was that on the new bounty page.
1. He called `approval()` to give the contract approval to send the coins.
2. He immediately then called `issueAndActivateBounty()` to issue the bounty.
3. becuase the tx from 1 had not been confirmed by the network yet, metamask presumed that his second transaction would error out.  it also presents an insanely high bgas price to the end user
4. this is made worse by an issue in metamask where a user can't successfully override the gas price in the tx confirmation window
This PR solves that by waiting for the tx from 1 to mine before attempting 2.
1. In the future, we could batch up the transactions using web3js batch ( which i …

hotfix: wait for approval to issue bounty

---

app/assets/v2/js/pages/dashboard.js

@thelostone-mc - please take a look, I found passing the event to the now renamed `toggleAny` function made it easier to reason about and achieve the expected behaviour.
Fix toggle any filter - could not previously click "Any" 
- [x ] linter status: 100% pass
- [ x] changes don't break existing behavior
- [ x] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)
```   
for multiselect checkbox groups:
if all selected --> others deselected
if other selected --> any deselected
if none selected --> any selected
```
UI
Confirmed XHR request matches to existing app for:
1. Initial load
1. Select another option
1. Deselect all options within group (any)
1. Select other option from any
1. Select from techstack 
Note that I …

fix toggle any filter

---

app/assets/v2/css/bounty.css
app/dashboard/templates/addinterest.html
app/dashboard/templates/bounty_details.html

- css
@PixelantDesign @SaptakS thoughts ?

css: prettified start work dialog box to match style +  stop work button

---

app/marketing/views.py
app/retail/templates/settings/slack.html

Add test button to test slack integration
ui
manually tested
Fixes #1004

test button to test slack integration

---

app/assets/v2/js/pages/dashboard.js

- `/api/v0.1/bounties/?&` -> `/api/v0.1/bounties/?`
- `.net, pop, &` -> `.net,pop&`
uri : `/api/v0.1/bounties/?&network=mainnet,any&tech_stack=&raw_data=c, pop, &coinbase=unknown&order_by=-web3_created`
uri : `/api/v0.1/bounties/?network=mainnet&tech_stack=&&raw_data=.net,pop&coinbase=unknown&order_by=-web3_created`
- js 
@mbeacom I see `tech_stack` being added to the uri but the value always seems to be empty
and the backend doesn't filter via that keyword
All the tech_stack selected options end up in `raw_data`

dashboard: fix filter uri

---

app/dashboard/notifications.py

has warned about inactivity -> has _been_ warned about inactivity

Fix grammatical issue

---

docs/README.md

'Running locally' link in the Table of contents was broken as we didn't have a corresponding section with the href `running-locally`
This PR adds in a new heading, thereby creating a ref for the 'Running locally' link.
Also changed the level of the sub-headings and the text (With Docker, Without docker).
Removed 'Running locally' before those headings as it seemed a bit redundant after the inclusion of the link.

Fix broken running locally link

---

app/assets/v2/css/bounty.css

The activity time ("34 minutes ago") is squished to the 'Stop work' button (refer to the below screenshot).
This PR adds a bit of left margin to the activity time.
After:

Add left margin for activity time

---

app/assets/v2/js/pages/dashboard.js

- ensure that 'any' is deselected if any option is available via local
storage
- reindented + reused code
- js
- https://github.com/gitcoinco/web/issues/1064

dashboard: side_bar filters refactor

---

app/dashboard/helpers.py
app/dashboard/models.py
app/dashboard/notifications.py
app/dashboard/utils.py
app/dashboard/views.py
app/marketing/management/commands/expiration_start_work.py
app/marketing/tests/management/commands/test_expiration_start_work.py

* expiration script escalates to @vs77bb if a user is MIA, but does not do removal itself
* changes the 'did user abanadon work and can't start another task' functionality to be only IFF the user has been removed from another task by a staff member.
start/  stop work 
self/ vivek idea on slack

escalation not removal

---

app/dashboard/helpers.py
app/dashboard/tokens.py

https://gitcoin.co/funding/details?url=https://github.com/aragon
fix for the denomination not showing up here

ant token name did not show up

---

app/assets/v2/css/base.css
app/dashboard/templates/bounty_details.html

Styles 'Refresh Quote' button in the funding page. Also adds a margin to the quote author element.

Style refresh quote button

---

app/assets/v2/css/bounty.css

- Activity times`margin-left` was being overridden , so adding important
- css

css: added important for overridden prop

---

app/economy/fixtures/initial.json
app/economy/models.py
bin/docker-command.bash
docs/ENVIRONMENT_VARIABLES.md

The goal of this PR is to introduce `ConversionRate` initial fixture data for local development.  Additionally, this PR disabled `get_prices` from running during provisioning, but allows users to pass `FORCE_GET_PRICES` via env var to force loading fresh conversionrates on container restart.
docker, backend
Tested locally

Add CR fixtures and disable get_prices by default

---

app/assets/v2/css/bounty.css
app/assets/v2/js/pages/bounty_details.js
app/dashboard/templates/addinterest.html

- image is restricted in height & width 
- on click -> opens dialog with original image size
- css
- js
- #1105
@PixelantDesign was this what you had in mind ? ^_^

css: set limit for image in issue description

---

app/assets/v2/js/pages/bounty_details.js

per https://gitcoincommunity.slack.com/files/UAPHNE3JT/FAT1U80LD/screen_shot_2018-05-19_at_22.06.35.png
at least i think this might be a fix.. not totally sure

fix for 'accept submission' not showing up

---

app/dashboard/templates/fulfill_bounty.html
app/dashboard/templates/increase_bounty.html
app/dashboard/templates/kill_bounty.html
app/dashboard/templates/process_bounty.html
app/dashboard/templates/submit_bounty.html
app/dashboard/templates/yge/send2.html

The goal of this PR is to modify the `issueURL` placeholder text to be more representative of the appropriate URL to be used when opening a `Bounty` or `Tip`.
ux, funding forms
Viewed locally
Fixes: #1194

Modify issueURL placeholder text to reflect GH issues

---

app/assets/v2/css/base.css
app/assets/v2/css/bounty.css
app/assets/v2/css/dashboard.css
app/assets/v2/css/search_bar.css
app/assets/v2/css/tag.css
app/assets/v2/js/pages/bounty_details.js
app/assets/v2/js/pages/dashboard.js
app/dashboard/templates/dashboard.html

This PR fixes a few things which is broken on the dashboard on mobile & tablet  
- hid exp_level when it's unknown
- Updated media breakpoints css
- refactored code
- css

dashboard : minor fixes

---

app/assets/v2/js/pages/fulfill_bounty.js
app/assets/v2/js/pages/increase_bounty.js
app/assets/v2/js/pages/kill_bounty.js
app/assets/v2/js/pages/new_bounty.js
app/assets/v2/js/pages/process_bounty.js
app/assets/v2/js/tokens.js

Removes the ability to remember terms and blockchain tos in the funder forms
1. Fund an issue.
2. Increase the bounty (this is mainly where the localstorage got set)
3. Fund another issue and the checkbox won't be checked.
4. You can also check the localStorage to check that there is no `acceptTOS` or `accept_blockchain_tos`
Fixes #1238 
Refs #1234

GDPR: Remove remembering terms and blockchain tos from the funder forms

---

app/assets/v2/css/base.css
app/assets/v2/css/buttons.css
app/assets/v2/js/base.js
app/dashboard/templates/shared/nav_auth.html

- displays modal via localStorage check + github login
- removed weird yellow hover on cross icon on modal
- update the background color on opened modal
@vs77bb @owocki @PixelantDesign 
On clicking **View Our Updated Terms** -> it takes you to `https://gitcoin.co/legal/policy `. 
I'm guessing this isn't, could get the right url ? 
@PixelantDesign could you give me the rgb color code of the blue background ? This is what I got , when I used a color picker -> It's weird :P 
Or I can default it to the black background ^_^ 
- css
- js
- #1239

GDPR: show updated policy via modal

---

app/retail/templates/settings/ens.html
app/retail/templates/settings/privacy.html
app/retail/templates/settings/settings.html

- fonts now use Muli
- removed + refactored + reindented html
- optimized view for mobile
- css + html
- https://github.com/gitcoinco/web/issues/1261
@SaptakS should I change them to `rem` ? :P

settings: updated styling  + linting

---

app/assets/v2/_variables.scss
app/assets/v2/css/base.css
app/assets/v2/css/carousel.css
app/assets/v2/css/external_bounties/bounties.css
app/assets/v2/css/external_bounties/bounty.css
app/assets/v2/css/gitcoin.css
app/assets/v2/css/ios.css
app/assets/yge/css/main.css

Looks like we've been using the wrong font name (cause it to default to sans-serif)  in a few places around the site 
This PR just fixes those up
Pointed out :  https://github.com/gitcoinco/web/pull/1260#issuecomment-392054296
- css

css: fixed font name

---

app/app/settings.py
app/app/urls.py
app/retail/templates/admin/index.html
requirements/base.txt

adds the ability to impersonate users as an admin.
important for GDPR account deletion, and debugging purposes
https://bitbucket.org/petersanchez/django-impersonate

admin / impersonate users

---

docker-compose.yml

it was loading from local.env instead of `.env`, and therefore the following info was set
```
GITHUB_API_USER=None
GITHUB_API_TOKEN=None
GITHUB_CLIENT_ID=xxxx
GITHUB_CLIENT_SECRET=xxx
GITHUB_APP_NAME=MyGitcoinApp
```

docker-compose was wrong

---

app/assets/yge/youvegoteth/receive.js

- Makes the button text in tip receive success page visible.
- Also uppercases 'to' to standardize the way we render button texts.
UI
Tested it
Fixes #1313

Fix primary button style in receive tip success page

---

app/assets/v2/js/toolbox.js

toolbox: avoid $.get when url is undefined

---

app/app/settings.py

The goal of this PR is to reduce the initial permissions we request for users.
auth

Decrease the scope of GH perms requested on login

---

app/dashboard/management/commands/sync_geth.py
docs/RUNNING_LOCALLY.md
docs/RUNNING_LOCALLY_DOCKER.md
scripts/crontab

The goal of this PR is to adjust the `sync_geth` command and related documentation to start at `402` when syncing with rinkeby.  This avoids running through 400 bounties that don't have `payload` data.
sync_geth
Locally.
Fix #1334

Adjust sync_geth settings and docs for local

---

app/assets/v2/js/pages/bounty_details.js

Trims the whitespaces in the action plan before validation forcing the user to enter a string as the issue plan.
UX
Fixes #1336

Trim issue action plan before validation

---

app/dashboard/templates/shared/yge_auth.html
app/retail/templates/shared/head.html

Not sure what is being missed here, so shifting to FA CDN until resolved

temp: using font-awesome CDN

---

app/assets/v2/css/forms/input.css

Removes invalid css definition. The margin top of .5rem isn't required so the whole definition has been removed.
UI
I did.

Remove invalid css

---

app/assets/v2/js/pages/dashboard.js
app/assets/v2/js/shared.js
app/dashboard/templates/bounty_details.html

Fixes weird rendering of font awesome icons, a regression introduced in https://github.com/gitcoinco/web/pull/1333
The issue is `fa` prefix has been deprecated in Font Awesome 5. The new default is `fas`.
UI
Fixes #1353

Fix font awesome icon classes

---

app/dashboard/templates/submit_bounty.html

The goal of this PR is to fix the display of the price estimation text on the new bounty form to span a whole row.
UI
I did, _manually_
Fixes #1361

Let price estimation text span a whole row

---

app/dashboard/templates/bounty_details.html
app/dashboard/templates/ens/base.html
app/dashboard/templates/shared/current_balance.html
app/dashboard/templates/shared/search_bar.html
app/dashboard/templates/shared/yge_auth.html
app/dashboard/templates/yge/base.html
app/dataviz/templates/cohort.html
app/dataviz/templates/dataviz/circles.html
app/dataviz/templates/dataviz/draggable.html
app/dataviz/templates/dataviz/graph.html
app/dataviz/templates/dataviz/heatmap.html
app/dataviz/templates/dataviz/index.html
app/dataviz/templates/dataviz/spiral.html
app/dataviz/templates/dataviz/steamgraph.html
app/dataviz/templates/dataviz/sunburst.html
app/dataviz/templates/funnel.html
app/dataviz/templates/stats.html
app/external_bounties/templates/external_bounties_show.html
app/faucet/templates/process_faucet_request.html
app/retail/templates/admin/index.html
app/retail/templates/leaderboard.html
app/retail/templates/process_accesscode_request.html
app/retail/templates/resend_tip.html
app/retail/templates/shared/head.html

The goal of this PR is to resolve the static handling issue with `link` entries for FA css.
frontend, static, css
Local

Fix FontAwesome static refs

---

app/dashboard/templates/shared/project_type_tooltip.html

In the above screenshot, the project type 'Co-operative' has the number 2 when it should be 3. I assume this was a result of copy+paste in haste. Feel free to comment and close the PR if it indeed is intentional.
UI

Fix project type number

---

app/assets/v2/css/bounty.css

In the below screenshot from desktop view, the 'Project Type' subheading and the value 'Traditional' look unassociated when they are in fact related. The PR attempts to fix it by making sure the info items always go together. In the mobile view, the items are rendered one in a row.
UI
/cc @PixelantDesign

Enhancement bounty info view on the bounty details page

---

app/dashboard/templates/shared/hours_worked.html

Currently, we're not validating the hours worked input field. So, a user cannot enter negative numbers though it doesn't make sense. This PR adds a minimum value of `0.25` to the input field.
**Note**: This is a really minor thing as an average gitcoiner wouldn't enter negative numbers but it was bugging me so I decided to submit a patch.
I did, _manually_

Add min value for hours worked input field on submit work form

---

app/dashboard/templates/bounty_details.html
app/dashboard/templates/ens/base.html
app/dashboard/templates/ens/ens_pending.html
app/dashboard/templates/ftux/metamask.html
app/ethos/templates/redeem_ethos.html
app/faucet/templates/process_faucet_request.html
app/retail/templates/about.html
app/retail/templates/community.html
app/retail/templates/help.html
app/retail/templates/index.html
app/retail/templates/results.html
app/retail/templates/settings/ens.html
app/retail/templates/shared/bottom_notification.html

[According to most UX studies](http://uxmovement.com/navigation/why-external-links-should-open-in-new-tabs/), external links should open in a new tab. Some of the links weren't following this. So modified them.
Also, wherever we use `target=_blank` we should also add `rel="noopener noreferrer"` because of the [most underetimated vulnerability](https://dev.to/ben/the-targetblank-vulnerability-by-example). Fixed few of those too.
Links

External links should open in new tab with noreferrer and noopener

---

app/dashboard/models.py
docs/THIRD_PARTY_SETUP.md

The goal of this PR is to attempt to further mitigate unintentional Github comments/notifications while running notification generating activities on `local` by limiting all GH notifications to only repositories owned by the `GITHUB_API_USER`.
notifications (non-prod)
Local

Github notification safeguard for local

---

app/assets/v2/css/base.css
app/assets/v2/css/bounty.css
app/assets/v2/css/landing_page.css
app/dashboard/templates/shared/nav_auth.html
app/dashboard/templates/shared/newsletter.html
app/retail/templates/index.html
app/retail/templates/shared/nav.html
app/retail/views.py

- updated navbar
- swap fund & login button
- custom newsletter
- landing page

landing page: final changes

---

app/app/settings.py
scripts/deploy.bash
scripts/rollbar.bash

The goal of this PR is to disable the `mail_admins` log handler for all environments except `prod` and add granular control to other steps (crontab, etc) in the `deploy.bash` script.
Additionally, this allows us to disable the crontab update step (for staging) to avoid the mushrooming `sync_geth.log`.
deploy
Local and stage

Update django logger and deploy script handling

---

app/assets/v2/css/onboard.css
app/dashboard/templates/ftux/onboard.html

- css
@SaptakS Should we move the css into it's own file for every step  ?
I'm in two minds cause it's just a few lines as of now

updated font-size for ftux large devices

---

app/dashboard/notifications.py
ops/lambdas/welcomebot/app.py

The goal of this PR is to link names mentioned in suspension slack messages to @vs77bb and slack handles in the welcomebot message.
*EDIT: Updated this PR to use user IDs since username linking was deprecated.  Additionally, added @SaptakS, @thelostone-mc, Scott, and Ben*
https://api.slack.com/changelog/2017-09-the-one-about-usernames
welcomebot, notifications

Add name linking to vivek's slack notification and welcomebot

---

app/dashboard/templates/shared/yge_auth.html

Changes login link hover color on ENS and YGE (You've got eth) pages to white.
UI
Fixes #1484

Change login link hover color to white

---

.travis.yml
Makefile
app/faucet/views.py
docs/RUNNING_LOCALLY_DOCKER.md
requirements/test.txt

@owocki @leonprou this should fix the travis error in pytest.
@mbeacom review.
Fixes #1492 
Refs #1491

Fix pytest version

---

app/assets/v2/js/pages/dashboard.js

Fixes `New Error: Error: Syntax error, unrecognized expression: input[name="tech_stack"][value=c++] `
For more details, check [Rollbar](https://rollbar.com/gitcoin/gitcoin/items/1351/)

Fix jquery selector

---

app/assets/v2/css/base.css
app/assets/v2/js/shared.js

it seems to me that the alert messages `.alert .message` should not be `display:flex`
see this gif with a before and after for why:

no flex on alert messages

---

app/retail/templates/emails/template.html

There was additional `letter-spacing` applied to text in Gitcoin emails. For headings this is fine, however it causes larger bodies of text to be more difficult to read.
This PR removes the extra spacing for non-heading elements. The most recent Gitcoin Weekly would now appear as follows:
Marketing emails (`app/retail/templates/emails`)
No changes in logic, therefore should be without issue
Fixes: #1480

Remove unnecessary letter spacing in emails

---

app/app/urls.py
app/retail/templates/shared/nav.html
app/retail/views.py

The goal of this PR is to consolidate the `how it works` urls to use one entry and pass the type to the view.
Tested locally

Update how it works to use one url

---

app/assets/v2/css/landing_page.css
app/retail/templates/index.html
app/retail/templates/landing/pilot.html

The goal of this PR is to resolve display issues introduced in `how it works` (some CSS elements were transitioned from `_` to `-` naming convention (oddly enough, not all of them though 🤔) resulting in poor rendering on the landing page.

Fix broken CSS from how it works

---

app/assets/v2/js/pages/onboard.js
app/dashboard/templates/shared/nav_auth.html
app/dashboard/views.py

- Take to profile page after saving
When using the standalone avatar builder outside of the onboarding flows, the save avatar button takes to the profile page.
Refs: #1523

Save Avatar takes you to Profile Page

---

app/assets/v2/js/amounts.js
app/assets/v2/js/shared.js

fix : eslint errors

---

app/assets/v2/css/gitcoin.css
app/retail/templates/shared/nav.html

Fixes: https://github.com/gitcoinco/web/issues/1557

nav: fix on mobile

---

app/retail/templates/shared/nav.html

The goal of this PR is to no longer display "How it works" on about, mission, slack, and results pages following further request/clarification.
Locally

Update where to display how it works again

---

app/dashboard/templates/ftux/avatar.html

adds the following link on the avatar builder page:
which allows users to request more avatar items on a github thread

avatar schwag request form

---

requirements/base.txt

The goal of this PR is to upgrade Django to `2.0.7` to resolve the bugs outlined in:
https://docs.djangoproject.com/en/2.0/releases/2.0.7/
Specifically:
`Fixed migrations crash with namespace packages on Python 3.7` 
Locally

Upgrade Django to 2.0.7

---

app/faucet/views.py
app/retail/utils.py

those code produces the following output:
```
pulled alumni in 0.0 seconds (total: 0.0 sec)
pulled count_* in 0.01 seconds (total: 0.01 sec)
pulled orgs in 0.0 seconds (total: 0.01 sec)
pulled Stats1 in 0.15 seconds (total: 0.17 sec)
pulled Stats2 in 0.17 seconds (total: 0.34 sec)
pulled bounty_history in 0.08 seconds (total: 0.42 sec)
pulled completion_rate in 0.01 seconds (total: 0.43 sec)
pulled universe_total_usd in 0.01 seconds (total: 0.44 sec)
pulled bounty_average_turnaround in 0.61 seconds (total: 1.05 sec)
pulled bounty_median_pickup_time in 0.59 seconds (total: 1.64 sec)
pulled final in 0.0 seconds (total: 1.64 sec)
```
and introduces caching of that information

/results page is slow, this PR perf profile helps diagnose that and makes it faster

---

app/assets/v2/js/tokens.js
app/assets/yge/youvegoteth/send.js
app/assets/yge/youvegoteth/tokens.js
app/dashboard/tokens.py

adds OZR token

---

app/retail/templates/contributor_landing.html

The reference to `landing_page.js` is unnecessary on the contributor landing page. This PR removes the reference.
Fixes #1603

Remove unnecessary script

---

app/assets/v2/js/shared.js

The tooltip persists when you switch from the wrong network to the right network.
This PR fixes that

bug: set title attribute to null when switching to right network

---

app/retail/templates/contributor_landing.html

Make color from green to blue for "Get Started" button. cc: @PixelantDesign

Changes color of getting started from green to gc blue

---

app/dashboard/management/commands/sync_listener.py
scripts/crontab

It listens for new blocks that contain transactions to standard bounties(fulfillBounty), and processes those bounties instantly.
Example:
./manage.py sync_listener mainnet
Fixes #1605

Implement management command 'sync_listener'

---

app/dashboard/notifications.py

Updates slack notification to display the bounty title first and then the value.

Display bounty title before value

---

app/dashboard/helpers.py
app/dashboard/management/commands/create_activity_records.py

..so that work_done and work_submitted activities[n].{profile} = {fulfiller_profile}
and not bounty_owner_profile.
Note: we need to purge all activities from all already recorded bounties
Fixes #1659

WIP: Fix record_bounty_activity..

---

app/assets/v2/js/pages/bounty_details.js
app/dashboard/helpers.py
app/dashboard/management/commands/create_activity_records.py
app/dashboard/models.py

fix for https://github.com/gitcoinco/web/issues/1661
1. clears ALL activity if `force_refresh`, not just for current_bounty
2. fixes the attribution of worker_approved, work_applied, etc to be for the funder, not the bounty hunter.
TODOS:
1. why are we making two requests
http://localhost:8000/actions/api/v0.1/bounties/?github_url=https://github.com/XLNT/gnarly/issues/11&network=mainnet&standard_bounties_id=677&not_current=1
and
http://localhost:8000/actions/api/v0.1/bounties/?github_url=https://github.com/XLNT/gnarly/issues/11&network=mainnet&standard_bounties_id=677
??
i think we should only care about activites related to teh current bounty and we should migrate the actions to the current_bounty=1 when we create a new current_bounty

fix for https://github.com/gitcoinco/web/issues/1661

---

app/assets/v2/css/base.css

@PixelantDesign  As discussed -> hiding the pill on mobile

hide network pill on mobile + reorder media query code

---

app/retail/templates/contributor_landing.html

Contributor landing page: change text color of 'Get started' to white.

---

app/assets/v2/css/newsletter.css
app/dashboard/templates/shared/newsletter.html
app/retail/templates/contributor_landing.html
app/retail/views.py

Improves the newsletter section in contributor landing page

Improve the css for newsletter

---

app/retail/templates/landing/contributor/hero.html

Changes the button color on the hero banner of contributor landing page to blue from green

Makes get started button blue as suggested by Alisa

---

app/dashboard/templates/toolbox.html

Allow upto 4 cards in a row to make the page more balanced. Else everything seems a little too much on the left
Before:
After:

Allow upto 4 cards in a row to utilise more space

---

app/dashboard/embed.py
docs/README.md

The goal of this PR is to implement `maxAge` GET param for the embedded image view.
embeded
Locally

Allow maxAge GET param for embed image responses

---

app/dashboard/templates/shared/onepager_auth.html

Note: The gitcoin logo(s) are already clickable.
Fixes #1739

Make the user profile in onepager link to /profile/

---

.gitignore
Dockerfile
app/assets/v2/js/pages/shared_bounty_mutation_estimate_gas.js
app/dashboard/gas_views.py
app/dashboard/templates/shared/gas_nav.html
app/dashboard/templates/shared/onepager_auth.html
app/gas/management/commands/output_gas_viz.py
app/retail/templates/gas.html
scripts/crontab

[see the output here](http://bits.owocki.com/0q2q452E2C0Z/out.mp4)
could be cool to put on the gas station, not sure how its gonna perform marketing-wise tho

3d dataviz of gas prices vs confirmation time

---

app/dashboard/templates/shared/gas_nav.html
app/retail/templates/gas.html
app/retail/templates/gas_history.html
package-lock.json

This pull request allows the gas navigation bars to adjust according to screen width allowing for mobile compatibility and window resizing. Furthermore, gas navigation links have added padding/length so as to make clicking them a lot easier. The SVG graph for gas history resizes to a readable and non-bleedable width length on initial window startup. 
**NOTE: for some reason, after cloning the repo and running it, only the gas history graph with no data showed (only axes and titles). The gas graph was not available to see or for me to test. Therefore, the graphs I tested resize properly, but unfortunately, while I do make data refresh calls for the graphing lines, I haven't tested the graphs with data.**
`app/dashboard/templates/shared/gas_nav.html`
`app/retail/templates/gas_history.html` …

Mobile responsive Gas Navigation and Resizing SVG gas graphs

---

app/dashboard/models.py

self.amount is always 'natural value', thus we should not divide by 10**18.
Fixes #1592

Fix Dai Value Bug Gitcoin Bot #1592

---

app/app/settings.py
app/app/utils.py
app/avatar/models.py
app/avatar/utils.py
app/avatar/views.py
app/dashboard/embed.py
app/dashboard/helpers.py
app/dashboard/ios.py
app/dashboard/models.py
app/dashboard/notifications.py
app/dashboard/tests/test_dashboard_helpers.py
app/dashboard/tip_views.py
app/dashboard/views.py
app/external_bounties/management/commands/sync_known_github_repos.py
app/external_bounties/models.py
app/git/apps.py
app/git/tests/test_utils.py
app/git/utils.py
app/gitcoinbot/actions.py
app/gitcoinbot/management/commands/get_notifications.py
app/marketing/management/commands/expiration_start_work.py
app/marketing/management/commands/pull_github.py
app/marketing/management/commands/sync_github.py
app/marketing/stats.py
requirements/base.txt

The goal of this PR is to introduce `pygithub` and refactor the `dashboard.helpers.issue_details` view.
- Removes BS4 for finding keywords
- Slims up the response from `get_issue_details`
- Drops the requests to GH significantly
- Fixes bug in `get_issue_details` where `/pull` urls wouldn't return results, but rather an error.
- Removes some dead imports
dashboard helpers, issue details
Locally
Ref #1772

Refactor GH issue details endpoint

---

app/assets/v2/js/pages/onboard.js

Currently the browser back button doesn't work on the contributor onboard page. This PR allows users to click the back button and return to wherever they came from.
Fixes: https://github.com/gitcoinco/web/issues/1685
Whenever a user is sent to https://gitcoin.co/onboard/contributor/, they are instantly redirected to https://gitcoin.co/onboard/contributor/github which causes the issue reported in #1685. This PR simply doesn't add this initial redirect to the browser history.
ui
I manually tested this.
https://github.com/gitcoinco/web/issues/1685

Make back button work on contributor onboard

---

app/dashboard/notifications.py

The goal of this PR is to add a GC issue details URL to the `start work` gitcoinbot notification comment as requested in: #1794
bot, notifications
Locally
Fix #1794

Add gitcoin bounty details url to start work github bot copy

---

app/dashboard/templates/profiles/hidden.html
app/dashboard/templates/profiles/organization.html
app/dashboard/templates/profiles/profile.html
app/dashboard/views.py

- Indent + Restructure
- All profile templates resides within `profile/`  & have been broken down into smaller templates
to make code more maintainable
This is not being pushed to the orgs branch as I wanna avoid dealing with conflicts due to this restructuring. All further changes will be made in the `mark-orgs` branch 
- https://github.com/gitcoinco/web/issues/1798

restructuted profiles

---

app/retail/utils.py

Fixes division by zero error in `get_completion_rate` method by returning 0 if there are no bounties with a given keyword.
Fixes #1650

Fix division by zero error

---

app/retail/templates/shared/nav.html

this PR shows how it works on landing page / external nav.
im not sure why it was hidden, but this information architecture makes more sense to me.  if i'm new to the site (eg on the landing page), i might be curious how it works

shows how it works on landing page / external nav

---

app/dashboard/models.py

The goal of this PR is to remove the duplicate `Tip` properties that are being redefined.
- `amount_in_wei`
- `amount_in_whole_units`
tips
Locally

Remove duplicate Tip properties

---

app/dashboard/models.py
app/retail/emails.py
app/retail/templates/emails/quarterly_stats.html

WIP: Stats email v2

---

app/assets/v2/js/pages/wallet_estimate.js
app/assets/v2/js/shared.js

Also, we should display the gas rate message in the right location
if a banner is shown.
Fixes #1792

Do not display an 'wrong network' alert banner if metamask is locked.

---

app/dashboard/templates/bulk_payout_bounty.html

Change to the blue button in the bulk payout page.
cc: @owocki @PixelantDesign 
Bulk Payout, UI

Change color of payout submit button

---

app/dashboard/models.py
app/retail/templates/activity.html
app/retail/templates/contributor_landing.html
app/retail/templates/landing/contributor/activity.html
app/retail/templates/shared/activity.html
app/retail/views.py

puts an activity feed on the contributor landing page.  ideally this increases conversion rate bc it shows how active the platform is 
works responsive
ui
tested it 
https://github.com/gitcoinco/web/issues/1733

activity feed on landing page to increase conversion rate 

---

app/assets/v2/js/shared.js

...instead of showing nothing.
Related #1678

Display an error banner on network error on start-/stop work..

---

app/assets/v2/css/submit_bounty.css
app/dashboard/templates/submit_bounty.html

Visually improves the readonly fields
- Greys out the readonly fields
- Adds helper titles
ui
Refs: https://github.com/gitcoinco/web/pull/1779#issuecomment-407878923

Visually improves the readonly fields

---

app/assets/v2/css/base.css
app/assets/v2/css/search_bar.css

css: display filter tags + sort on mobile

---

app/assets/v2/css/base.css
app/dashboard/templates/submit_bounty.html

- trans support 
- a bit of css refactor 
- Cause we serve the dark lord @mbeacom

css: minor refactor

---

app/app/urls.py
app/marketing/mails.py
app/marketing/management/commands/funder_stale_email.py
app/retail/emails.py
scripts/crontab

sends an email to funders who have been inactive for 30 days, asking if they have any feedback
email 
tested it
https://github.com/gitcoinco/web/issues/1872
https://github.com/gitcoinco/web/issues/1879

sends an email to funders who have been inactive for 30 days, asking if they have any feedback

---

app/dashboard/templates/bulk_payout_bounty.html
app/dashboard/templates/fulfill_bounty.html
app/dashboard/templates/increase_bounty.html
app/dashboard/templates/kill_bounty.html
app/dashboard/templates/onepager/send2.html
app/dashboard/templates/process_bounty.html
app/dashboard/templates/submit_bounty.html
docs/README.md

as a user, i want documentation about chain of custody, so that i know my funds are secure. 
all links go to the documentation about chain of custody
tested it, just a ui change
https://gitcoincore.slack.com/archives/CAXFMVDGD/p1533176973000114?thread_ts=1533051885.000109&cid=CAXFMVDGD

as a user, i want documentation about chain of custody, so that i know my funds are secure

---

app/assets/v2/css/landing_page.css
app/assets/v2/js/landing_page.js
app/retail/templates/landing/funder.html
app/retail/templates/landing/funder/howworks.html

Switching tree section with 1,2,3 section on landing page.
frontend
Locally
Fixes #1861

Switching tree section on landing page

---

app/assets/v2/css/landing_page.css
app/retail/templates/about.html
app/retail/templates/landing/funder.html
app/retail/templates/shared/what_is_gitcoin.html

puts the 'what is it' video on about, and adds the funder video the existing lander
screenshot => http://bits.owocki.com/0A2x1y3Z2W2b/Screen%20Shot%202018-08-02%20at%201.56.38%20PM.png
ui
tested
https://github.com/gitcoinco/web/issues/1836

lander video switcharooooooooooooO

---

app/dashboard/notifications.py
app/dashboard/tip_views.py

- Removes duplicate github url
- Removes the colon at the end if the tip doesn't have a github url associated
- Replaces the event name `"new_tip"` to `"New tip"`. I didn't bother to create a dictionary as the function is only called with the new tip event and I can't imagine us broadcasting other tip events at this point.

Improve tip slack notification

---

app/assets/v2/js/shared.js

Show Just 1 Alert Banner for ERC20 Token

---

app/dashboard/helpers.py
app/dashboard/utils.py

This is a workaround for IPFS hashes of fulfillments not existing on IPFS.
```
ERROR:dashboard.utils:Could not get QmbaKB87MVLhEvqvQcMSYrgg2R136MxCEVDi2e6kdrXNj5 from ipfs
ERROR:dashboard.utils:Could not get QmNk6bdJypXJ2h4JovvMHiDtAbMrX4zq6YzfAUtkctzMwi from ipfs
```
@mbeacom i'm not sure the root cause of these hashes not existing. I hope there's not a broader issue with the pinning of the IPFS hashes on our node!

workaround for ipfs hashes not existing

---

app/assets/v2/js/pages/dashboard.js

The second PR is purely to make testing this PR easier.
Needs to be removed before merge
Ensure pending request gets abandoned before firing another request to prevent results from two diff APIs pop-ing up
https://github.com/gitcoinco/web/issues/1938

explorer:  ensure results from latest api call are served to the user

---

app/app/utils.py
app/dashboard/views.py

The goal of this PR is to clean the provided standard bounties ID and ensure it's a digit before attempting to filter the QS by the provided value.
bounty details
Locally
Fixes #1972

Strip characters from stdbounties_id and check isdigit

---

app/dashboard/views.py

Ensures trailing slashes for profiles don't lead up to a 404

hack: trailing slash for profile

---

app/retail/templates/shared/analytics.html

The goal of this PR is to eliminate the fetching/usage of the `FullStory` JS library since we're actively using Hotjar.
analytics, fullstory
Locally

Remove FullStory

---

app/dashboard/templates/bounty/details.html

This is to ensure that the accept / reject options appear on the screen when the funder is logged in on his permission-ed bounty
To test : 
- Create Permissioned bounty as X  -> Start work as another user Y
Y should not see any options on the work applied section 
X should see 2 buttons Approve & Reject on the work applied section 
Tested it out locally but needs one more round of testing on stage 
https://github.com/gitcoinco/web/issues/1947

bounty: enable accept / reject worker for owner

---

app/assets/v2/js/pages/dashboard.js

Initialize localStorage['keywords'] if empty, instead of appending.
Fixes #2011

pages/dashboard: Fix issue explorer keyword bug

---

app/dashboard/templates/dashboard/index.html
app/retail/templates/shared/footer.html
app/retail/templates/shared/result.html

code clean up

---

app/assets/v2/js/pages/bounty_details.js

This serves as a convenient hint.

Add (Issue is closed) to the 'View on Github' button if is_issue_closed.

---

app/app/settings.py
requirements/base.txt

The goal of this PR is to introduce the elastic apm integration for python/django.
apm, performance, logging
Locally
Ref #1873 #1208 #1207

Add base elastic apm integration

---

app/dashboard/models.py
app/marketing/management/commands/bounty_feedback_email.py
app/marketing/management/commands/expiration.py
app/marketing/management/commands/funder_stale_email.py
app/marketing/management/commands/new_bounties_email.py
app/marketing/management/commands/sync_github.py
app/marketing/utils.py
app/retail/emails.py

migrates from current_bounty=True to .current() because the latter is more exhaustive

migrates from current_bounty=True to .current() because the latter is more exhaustive

---

app/app/urls.py
app/assets/v2/js/pages/bounty_details.js
app/assets/v2/js/pages/change_bounty.js
app/assets/v2/js/pages/new_bounty.js
app/dashboard/helpers.py
app/dashboard/notifications.py
app/dashboard/templates/bounty/change.html
app/dashboard/templates/bounty/new.html
app/dashboard/templates/shared/issue_deadline.html
app/dashboard/templates/shared/issue_details.html
app/dashboard/views.py
app/marketing/mails.py
app/retail/emails.py
app/retail/templates/emails/bounty_changed.html
app/retail/templates/emails/bounty_changed.txt

bounty details ('experience_level', 'project_length', 'bounty_type',
'permission_type', 'project_type')
can be changed if the bounty is still on 'the happy path' by the funder
or staff.
Fixes #1928

Change Bounty Details

---

app/assets/v2/css/landing_page.css
app/retail/templates/landing/funder/howworks.html

Adding 6 icons to tree section
frontend, home page
locally 
Fixes #1861

Adding icons to tree section

---

app/assets/v2/css/landing_page.css

Fixes: #2141
@pmaojo thanks for the report :)
I've put out the fix! Feel free to review and give feedback if needed

css: fix missing background color

---

app/dashboard/notifications.py

Title -> Issue
/cc @PixelantDesign

Update title to issue in slack notifications

---

app/app/middleware.py
app/app/settings.py

The goal of this PR is to drop the `Accept-Language` header in the standard request context `META` allowing us to use the standard Django `LocaleMiddleware`, but disable the autodetection/header based aspect.
I'm open to adjusting this middleware to mimic `LocaleMiddleware` and not drop the header, but this seemed like the fastest/simplest path to success without rewriting core django functionality into a custom middleware.
system wide, middleware, translations, i18n
Locally

Add middleware to disable autodetect lang by header

---

app/dashboard/admin.py
app/dashboard/tip_views.py

- stores user agent
- makes searchable by ip and metadata

small tip tweaks

---

app/assets/v2/css/bounty.css
app/assets/v2/css/forms/button.css
app/assets/v2/js/pages/bounty_details.js
app/dashboard/templates/bounty/kill.html
app/dashboard/templates/shared/no_issue_error.html

PR does three things
- bounty details page -> updates cancel button color to red
- update banner & cancel button color to red
- prettifies admin control
Fixes: #2145

bounty: changes cancel button to red

---

app/dashboard/router.py

Fixes: https://github.com/gitcoinco/web/issues/1387
This PR fixes the issue that was displaying personal information (Name and Email) even when deselecting the option  while creating a bounty.
UI
Before:
After:
#1387

Hide Personal Information on Unselected Option

---

app/dashboard/notifications.py

Update work start Gitcoin bot text 
-  gitcoin bot
Ended up printing the msg output which gives follwing msg
Pasting that here results in the outcome as
1. [thelostone-mc](http://localhost:8000/profile/thelostone-mc) has applied to start work _(Funders only: [approve worker](http://localhost:8000/issue/gitcoinco/web/2005/1151?mutate_worker_action=approve&worker=thelostone-mc) | [reject worker](http://localhost:8000/issue/gitcoinco/web/2005/1151?mutate_worker_action=reject&worker=thelostone-mc))_.
Fixes: https://github.com/gitcoinco/web/issues/1535

bot : remove dibs text from message

---

app/dashboard/templates/bounty/details.html
app/dashboard/templates/shared/issue_details.html
app/dashboard/templates/shared/sidebar_search.html
app/retail/templates/emails/bounty.html

Replace text 'Project Length' with 'Time Commitment'
Replace on funder form, issue details, and left rail filters on issue explorer.
Let's see if it fits here:
If not maybe we can go down a font size or two on all of the headers.
/cc @PixelantDesign

Replace project length with time commitment

---

app/dashboard/notifications.py

A contributor is expected to provide plan of action before starting work on an permissioned issue.
Occasionaly they use ordered list and when we render this in bot message (which itself is a ordered list), it ends up looking like [this](https://github.com/gitcoinco/web/issues/2200#issuecomment-420528664)
This PR changes the latter to unordered-list
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done
<hr>
__Workers have applied to start work__.
These users each claimed they can complete the work by 5 months, 3 weeks from now.
Please review their action plans below:
**1) [thelostone-mc](http://localhost:8000/profile/thelostone-mc) has applied to start work _(Funders only: [approve worker](http://localhost:8000/issue/mbeacom/test-repo/5/461?mutate_worker_action=approve&worker=thelostone …

bot: updated markdown

---

app/assets/cookielaw/css/cookielaw.css
app/retail/templates/cookielaw/banner.html

Users can click the 'i agree' button on iOS safari and the cookie banner is displayed  in a small portion at the bottom of the screen 
Web
Should now look like this in an iPhone 5 which is the smallest screen for  iOS i could test for.
Also all tests are passing so it won't break anything
Fixes #2103

Adjust cookie banner for iOS/Safari 

---

app/assets/v2/css/profile.css
app/retail/templates/landing/contributor/hero.html

Refs: https://github.com/gitcoinco/Marketing/issues/1#issuecomment-422039620

html: updated text on banner contributor page

---

app/retail/emails.py
app/retail/templates/emails/template.html

The goal of this PR is to resolve a bug with `premailer` not honoring django static paths in email templates.
emails, templates
Locally

Adjust premailer to use base_url

---

app/app/urls.py
app/assets/v2/js/pages/increase_funding_limit_request_form.js
app/dashboard/tip_views.py
app/marketing/mails.py
app/retail/forms.py
app/retail/templates/increase_funding_limit_request_form.html
app/retail/views.py

Increase Funding Limit Request Form

---

app/assets/v2/js/pages/bulk_payout.js

- Captured prevention of advanced payout form submission when recipient github username is empty
Fixes: https://github.com/gitcoinco/web/issues/2010
This PR aims to fix the bug where advance payout form submission was completing despite having empty recipient address (which is a required field)
Advanced Payout form UI
Tested this change locally
Screenshots:
Before:
After:
Fixes: #2010

WOC: Prevent advanced payout form submission when recipient address is empty

---

app/app/settings.py
app/app/urls.py
app/dashboard/apps.py
app/git/management/commands/check_gh_ratelimit.py
app/git/utils.py
app/healthcheck/apps.py
app/healthcheck/healthchecks.py
app/healthcheck/views.py
app/retail/views.py
pydocmd.yml
requirements/base.txt
scripts/crontab

The goal of this PR is to move existing healthcheck specific functions and classes to the `healthcheck` app and introduce new checks, crontab job, and management command for Github API ratelimit logging.  Additionally, this PR introduces a new health check that *always* checks the Infura IPFS API for connectivity since some specific calls rely on this.
healthchecks, ipfs, github
Locally

Add GH ratelimit healthcheck, job, cmd and additional Infura specific healthcheck

---

app/retail/templates/emails/bounty_changed.html
app/retail/templates/emails/bounty_startwork_expire_warning.html
app/retail/templates/emails/bounty_startwork_expire_warning.txt
app/retail/templates/emails/bounty_uninterested.html
app/retail/templates/emails/faucet_request_rejected.html
app/retail/templates/emails/faucet_request_rejected.txt
app/retail/templates/emails/gdpr_reconsent.html
app/retail/templates/emails/gdpr_reconsent.txt
app/retail/templates/emails/new_bounty.html
app/retail/templates/emails/new_bounty_acceptance.html
app/retail/templates/emails/new_bounty_expire_warning.html
app/retail/templates/emails/new_bounty_rejection.html
app/retail/templates/emails/new_match.html
app/retail/templates/emails/render_bounty_startwork_expired.html
app/retail/templates/emails/render_bounty_startwork_expired.txt
app/retail/templates/emails/start_work_rejected.html
app/retail/templates/emails/start_work_rejected.txt
app/retail/templates/emails/template.html

The goal of this PR is to standardize most of our email templates (at least those living in `app/retail/templates/emails/`) to use `{% url '' %}` vs hardcoded paths.  This will mitigate the chances of errors like:  `https://gitcon.co/` occurring in the future and allow us to update URL paths without updating numerous files referencing the paths.  Additionally, this PR aims to migrate these templates to 2-space indentation and standard django template formatting for template variables and functions:  `{{ var|somefilter }}` and `{% endif %}`
emails, templates
Locally
Fix #2329

Fix #2329 - Adjust email template URL references and fix bad ref

---

app/assets/v2/css/ios.css

gitcoin.co/ios title is now impossible to read due to the green text
Fix (changed the text color to white):

fix ios text

---

app/assets/v2/js/avatar_builder.js

Fixes parsing colour from path in avatar builder. The issue was that on `localhost` splitting with `'.'` was working correctly, but in production environment `path` includes actual domain with dots and splitting returns incorrect portion. Fixed this by taking portion not from beginning, but from end (where there's no domain name).
Does not affect core subsystems.
Fixes: https://github.com/gitcoinco/web/issues/2150.

fixed avatar builder color handling

---

app/assets/v2/css/card.css

On gitcoin.co/tools, the card description is covered by the 'Try It' button if the title is two lines.
Fixed:

Fix overflowing text on toolbox cards

---

.travis.yml
Dockerfile
app/avatar/utils.py
requirements/base.txt

The goal of this PR is to migrate from `Wand`/`libmagickwand` to `pyvips`/`libvips`.
Additionally, this conversion method works with **complex** SVG layers. cc @jasonrhaas 
- **Faster**
- **More performant**
- **Less resources to perform conversion**
- **Less storage usage for dependencies**
avatar, images
Locally

Migrate image converter to pyvips

---

app/assets/onepager/js/send.js
app/assets/v2/js/user-search.js
app/dashboard/templates/onepager/send2.html

@octavioamu I removed the default function call which happens within `user-search.js` and whichever page needs -> needs to individually invoke the function. 
If you want only the name invoke function as `userSearch('element-identifier', false);`
If you want the set payout address also -> `userSearch('element-identifier', true);`
Fixes: https://github.com/gitcoinco/web/issues/2362

tip : autocomplete shows payout address

---

app/retail/emails.py

The goal of this PR is to update the weekly roundup email copy and bounty references for the week of 12 October 2018.
Locally

Update weekly roundup for 12OCT2018

---

app/grants/templates/grants/new.html

Adds metamask check banners in the grant creation form page
ref: #2443

Adds metamask check in grant form

---

docs/STYLEGUIDE.md

Fixes the broken link to typography.css in the Styleguide
doc
Tested by clicking link :-)
Fixes #2460

Fixes: https://github.com/gitcoinco/web/issues/2460

---

app/assets/v2/js/pages/bounty_details.js
app/dashboard/templates/bounty/details.html

This PR aims to resolve issue #2273 that involved hiding funder details if they chose to be anonymous. It does so by using a simple check to see if the `result.bounty_owner_name == 'Anonymous'`, and, if so - it simply hides the elements that need to be hidden. 
This was completed 100% by @GatteJyoti, although they went MIA post review so I've restructured the code according to review and PR'd. 
UI subsystem is the only one that has been changed. 
I assume that this has been tested beforehand, but I've also run it on a local machine to confirm that it works. 
PR fixes issue #2273.

Hide Anonymous - Refactoring GatteJyoti's commit and pushing.

---

app/grants/templates/grants/detail.html
app/grants/views.py

The goal of this PR is to eliminate the `Milestone.objects.get(...)` query from the `grant_details` view by `prefetch_related('milestones')` and eliminate `can_edit_milestones` for `is_admin`.
grants, milestones
Locally

Eliminate additional Milestone query and remove can_edit_milestones

---

app/retail/emails.py

roundup email 2018/10/19

---

app/assets/v2/js/pages/tabs.js
app/dashboard/management/commands/cleanup_dupe_profiles.py
scripts/crontab

cleanup dupe profiles, which fixes https://github.com/gitcoinco/web/issues/2478
profiles
tested it, it fixes http://localhost:8000/profile/owocki
https://github.com/gitcoinco/web/issues/2478

cleanup dupe profiles

---

app/assets/v2/css/howitworks.css

Fixes landing page mobile view issue
Fixes: #2489 
Before:
After:

Fixes: https://github.com/gitcoinco/web/issues/2489

---

app/assets/v2/js/grants/fund_grant.js

grants/fund : populate token in dropdown

---

scripts/deploy.bash

Ensure deploy.bash crontab, static, invalidation, and migrations only run on one instance.
deployments, internal
Locally
Fix #2607

Adjust deploy bash to only run provisioning on jobs_node

---

app/assets/v2/js/pages/kudos-search.js

Fix sentry error log

---

app/dashboard/models.py
app/dashboard/views.py

The goal of this PR is to resolve the exception encountered in:  #2655 when attempting to query for a profile that doesn't exist in `lazy_load_kudos`
Local
Fix #2655

Adjust lazy_load_kudos to catch nonexistent profile

---

app/dashboard/models.py
app/dashboard/views.py
app/kudos/templates/shared/kudos_card_hover_content.html
app/kudos/templates/shared/kudos_card_profile.html

refactors kudos data profile so the view/data/query is comprehensible

refactors kudos data profile so the view/data/query is comprehensible

---

app/assets/v2/js/pages/kudos_receive.js
app/assets/v2/js/pages/kudos_send.js
app/retail/templates/results.html

gas limit fix.  this is a fix for 
https://github.com/gitcoinco/web/issues/2586
it needs to be tested before deployment.  i can't do that currently bc i have bad internet..

fix for tx's running out of gas

---

app/kudos/management/commands/mint_all_kudos.py

The goal of this PR is to eliminate the retry attempts when minting a kudos fails in `mint_all_kudos`
kudos
Locally
Fix #2654

Remove range retry attempt from mint_all_kudos

---

app/dashboard/views.py
app/kudos/views.py

- fix save address on receive
- fix ajax kudos fetch from profile
- ~fix show same id card (keeps duplicating comments)~ fixed in #2662 
The kudos profile filter need refactor to handle the relation since token_id is null in kudos transfer

Profile fixes

---

app/dashboard/management/commands/cleanup_stray_activities.py
scripts/crontab

cleans up stray activities
tesxted on my local
https://gitcoincommunity.slack.com/archives/C7A4F4UHK/p1541448206270900?thread_ts=1541427130.245200&cid=C7A4F4UHK

cleanup stray activities

---

app/app/utils.py
app/dashboard/management/commands/cleanup_dupe_profiles.py
app/dashboard/views.py

duplicate profiles, but now also handles:
- profiles with case sesnsitivity issues
- profiles with @ signs in front of them
tested:
[kennethashley](http://bits.owocki.com/45b26455da6b/Screen%20Shot%202018-11-05%20at%201.30.10%20PM.png)
[market protocol](http://bits.owocki.com/9d3c571abb95/Screen%20Shot%202018-11-05%20at%201.30.59%20PM.png)
[pelsasser](http://bits.owocki.com/06b5bfe5cf91/Screen%20Shot%202018-11-05%20at%201.31.20%20PM.png)
self

dupe profile cleanup part 2

---

app/assets/v2/js/pages/bounty_details.js
app/assets/v2/js/pages/new_bounty.js
app/dashboard/helpers.py
app/dashboard/router.py
app/dashboard/templates/bounty/details.html
app/dashboard/templates/shared/issue_details.html

Allow funder to turn off auto approvals at bounty creation
Tested manually
Fixes #1807

allow funder to turn off auto approvals at bounty creation

---

app/assets/v2/js/avatar_builder.js
app/marketing/tests/management/commands/test_assemble_leaderboards.py

Fix travis tests

---

app/avatar/models.py

previous_* was being set every time, when really it should only updated if the field its dervied from is updated
per https://gitcoincore.slack.com/archives/CBZEHJCN7/p1541628897002900

fixes the logic for avatar save checks

---

app/assets/v2/css/bounty.css
app/assets/v2/js/pages/bounty_details.js
app/dashboard/templates/bounty/details.html

- removed funder name from details page
- ensures email label + field is shown only if available
- cleans up extra code
Fixes: https://github.com/gitcoinco/web/issues/2579

details : remove full name 

---

app/assets/v2/js/pages/bounty_details.js
app/assets/v2/js/shared.js

This fixes the estimate expiration when user choose "Never"
In bounty detail:
In explorer:
Fixes: #2538

Fix never expires

---

app/assets/v2/css/kudos/styles.css
app/assets/v2/css/kudos/styles.scss
app/assets/v2/js/pages/kudos_details.js
app/kudos/templates/kudos_details.html
app/kudos/templates/share.html

@octavioamu could you help out with these  
- Adding custom message + image for share facebook URL. (not sure how to configure the URL)
- Do i use scss / css ? I've left in within the `share.html` file for now as I'm not sure which we way to go
https://github.com/gitcoinco/web/issues/2666 and #2617

kudos : add share button

---

app/app/log_filters.py
app/app/settings.py

The goal of this PR is to update the logging output sent to CloudWatch to include the hostname of the delivery node.
Logging

Add hostfilter for CW logging

---

app/dashboard/models.py

enforce casing / formatting rules for profiles

---

app/app/pipeline.py
app/dashboard/models.py
app/dashboard/views.py

dont let users submit work unless they've started work
fulfill work
tested it locally
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1542113751027400

dont let users submit work unless they've started work

---

app/app/context.py
app/app/settings.py

The goal of this PR is to resolve a bug encountered while attempting to communicate with the local IPFS docker instance from IPFS JS by defaulting to `localhost` for IPFS JS if `IPFS_HOST == 'ipfs'`.
ipfs, context, settings
Locally
Fix #2335

Fix #2335 - If IPFS_HOST is ipfs pass localhost to IPFSJS

---

app/bounty_requests/templates/bounty_request_form.html
app/dashboard/templates/bounty/change.html
app/dashboard/templates/bounty/increase.html
app/dashboard/templates/bounty/new.html
app/dashboard/templates/ftux/onboard.html
app/dashboard/templates/grants_index.html
app/dashboard/templates/profiles/profile.html
app/dashboard/templates/quickstart.html
app/dashboard/templates/toolbox.html
app/external_bounties/templates/external_bounties.html
app/external_bounties/templates/external_bounties_new.html
app/external_bounties/templates/external_bounties_show.html
app/retail/templates/increase_funding_limit_request_form.html
app/retail/templates/leaderboard.html
app/retail/templates/settings/tokens.html

`shared.js` is included in footer_scripts.html.
This also fixes errors like this:
`shared.js:1 Uncaught SyntaxError: Identifier 'activity_names' has
already been declared`

Fix redundant `shared.js` includes.

---

app/dashboard/notifications.py

Also adjust the message accordingly if the bounty is done with no
fulfillments.
Fixes #2125

github work_done notification: Add non-crowdfund tips to the msg.

---

requirements/base.txt

I get random errors on my local docker setup if I use
the site and constant errors for things like POST and
api calls.
For example:
```
web_1    | redis.exceptions.DataError: Invalid input of type: 'CacheKey'. Convert to a byte, string or number first.
```
Details of this issue are here:
https://github.com/niwinz/django-redis/issues/342
The latest djang-redis release fixes the issues.

Pin django-redis==4.10.0

---

app/assets/v2/js/metamask-approval.js
app/assets/v2/js/shared.js

Sometimes, the window's `load` handler get executed in another order
which breaks variable lookup.
Fix that by explicit declaring `is_metamask_approved` and `is_metamask_unlocked`.
Fixes #2813

Fix rare `is_metamask_approved is not defined` race condition.

---

app/retail/templates/shared/cards_pic.html

Change the og:url to be the page one and not gitcoin main page to avoid facebook scraping redirect and wrong image

Fix kudos facebook share url

---

app/retail/templates/shared/grants_nav.html

Currently opening an grants url gives an error because it is unable to reverse resolve the 'new_grants' url which has been removed but was still being used in nav of grants. Fixed it.

Fix new grants reverse name in the grants_nav.html

---

app/assets/v2/css/grants/grant.css
app/grants/templates/grants/index.html
app/grants/views.py

Refactoring landing page based on @willsputra design. 
Refs: https://github.com/gitcoinco/web/issues/2025#issuecomment-439112816

Refactor landing page for grants

---

app/assets/v2/js/grants/shared.js

In the web3 version we are using on grantz
```
const listen_web3_1_changes = () => {
web3.eth.getCoinbase().then(function(result) {
if (result) {
...
web3.eth.net.getNetworkType(function(err, network) { // returns null
currentNetwork(network); 
});
} ...
});
}
```
` web3.eth.net.getNetworkType` needs to be replaced with `getnNetworkId` as per the [doc](https://web3js.readthedocs.io/en/1.0/web3-eth-net.html#example)
This PR fixes that and ensures you can get the current logged in network via `document.network`

updated the grant error page

---

app/retail/templates/emails/grants/new_grant.html
app/retail/templates/emails/grants/successful_contribution.html
app/retail/templates/emails/grants/thank_you_for_supporting.html

@captnseagraves it was an extra spacing issue 😂  
They were converted to `%20` when rendered in the email. derpderp
https://github.com/gitcoinco/web/issues/3057

grant/email: fix default image in email

---

app/assets/v2/js/pages/bounty_details.js

UI: Chnaged the crowdfunding tooltip to say USD instead of the tokenName.
Quick change, doesn't break the linting or anything.
Fixes: #3062

Replace tokenName with USD in crowdfunding tooltip

---

app/assets/v2/css/base.css
app/assets/v2/css/grants/fund.css
app/assets/v2/js/grants/cancel_subscription.js
app/assets/v2/js/grants/fund.js
app/assets/v2/js/grants/new.js
app/assets/v2/js/pages/shared_bounty_mutation_estimate_gas.js
app/assets/v2/js/pages/wallet_estimate.js
app/dashboard/templates/bounty/new.html
app/dashboard/templates/shared/wallet_estimate.html
app/grants/templates/grants/cancel.html
app/grants/templates/grants/fund.html
app/grants/templates/grants/new.html
app/grants/views.py
app/retail/templates/emails/grants/support_cancellation.html
app/retail/templates/emails/grants/support_cancellation.txt

This PR adds dynamic gas pricing to
- grants/new
- grants/fund
- grant/fund/cancel
Refs: https://github.com/gitcoinco/web/issues/3067
Questions ( @owocki / @captnseagraves  ):
- where else does this need be added ? 
(If yes for subscription -> we have 2 contract deployment, so we use the same gas price for both ?)
- should we be converting `gas` in [grantz](https://github.com/thelostone-mc/web/blob/gas_setting/app/assets/v2/js/grants/new.js#L82) to hex like in [bounties](https://github.com/gitcoinco/web/blob/master/app/assets/v2/js/pages/new_bounty.js#L424-L426)

grant/new: add gas-setting

---

app/assets/v2/css/dashboard.css

without wrap tags are exceeding screen in certain situations making profile page not fully responsive
before:
after:
ui
- [] Ran `make test` and everything passed!

tags exceeding profile page

---

app/kudos/views.py

sets num kudos limit higher, so you can see 100 ppl who own those kudos instead of just 20
https://gitcoin.co/kudos/430/resilience
inspired by this kudos, which has 100 sends.
i hope this PR opens a discussion about performance and how many http requests were making... i'm open to disucssion about how to reduce server load here and still show the images

sets num kudos limit higher

---

app/dashboard/management/commands/cleanup_dupe_profiles.py

The goal of this PR is to remove a redundant import (while resolving the associated sentry error) and fix whitespace around an operator.
management commands, profile
Fix #3186

Remove redundant/secondary import of Profile and fix operator space in cleanup_dupe

---

app/retail/templates/shared/top_nav.html

The tophat currently shows the CodeFund URL as `.io` but should be `.app`

Updated URL for CodeFund to use .app

---

app/avatar/utils.py

**Description**
This fixes the unavailability of the darth_inspired mask information in the utils.py file.
**Checklist**
**Affected core subsystem(s)**
Avatar
**Refers/Fixes**
#3255

Inconsistency Fix - Darth_Inspired Util edit

---

app/dashboard/tip_views.py
app/inbox/__init__.py
app/inbox/admin.py
app/inbox/apps.py
app/inbox/models.py
app/inbox/signals.py

Inbox backend changes

---

requirements/base.txt

Fix security vulnerability by upgrading to 2.1.6
No breaking changes ! Locally app boots up while after rebuilding the app
https://docs.djangoproject.com/en/2.1/releases/2.1.6/

fix: updated django 2.1.5 -> 2.1.6

---

app/assets/v2/css/base.css

Fixes missing background on the zero balance error that makes the text unreadable
Fixes issue noticed by Scott Moore
Small CSS change

fix missing background for zero balance error

---

app/retail/templates/emails/funded_featured_bounty.html

This PR fixes the conversion issue that is found in #3999 
N/A
Fixes: #3999 
Small Change Done.

Fix for conversion rate on bounty email is wrong

---

app/app/settings.py
docs/ENVIRONMENT_VARIABLES.md
docs/THIRD_PARTY_SETUP.md
requirements/base.txt

This PR upgrades the Sentry SDK to the latest version, which has a simpler setup. 
logging, error reporting
Fixes: https://github.com/gitcoinco/web/issues/3887 https://github.com/gitcoinco/web/issues/3809
Tested locally with hosted sentry environment

Restore previous default logging behavior, cleanup logging setup, upgrade Sentry SDK

---

app/assets/v2/css/bounty.css
app/assets/v2/js/pages/bounty_details.js
app/dashboard/router.py
app/dashboard/templates/bounty/details.html

Show kudos in bounty activity

---

app/dashboard/views.py

Related to https://sentry.io/organizations/gitcoin/issues/938282538/?project=1398424

Require login for invite code URL

---

app/assets/v2/js/grants/newMatchingPartner.js
app/grants/views.py

#3913 Correct validation in JS

---

requirements/base.txt

This is because we have matplotlob twice in our requirements. https://github.com/gitcoinco/web/blob/master/requirements/base.txt#L12

removed duplicate matplotlib

---

app/retail/emails.py

The bounty acceptance email in admin was throwing error because there was no default value for rating_count provided in the function.

Fixes the bounty acceptance email in admin

---

app/assets/v2/js/pages/bounty_details.js

- refactored code 
- the text pops up only when the following conditions are all met
a) bounty is expired
b) logged in user is bounty owner (with the right metamask address )
c) issue has not been done / cancelled
closes https://github.com/gitcoinco/web/issues/4110

 feat: notify funder to extend expiration date before taking action

---

app/app/urls.py
app/assets/v2/css/leaderboard.css
app/retail/templates/home/index.html
app/retail/views.py

- redirects `/funder/` -> `/bounties/funder`
- redirects `/contributor/<tech-stack>` -> `/bounties/contributor/<tech-stack>`

/funder + /contributor redirects

---

app/assets/v2/js/shared.js

Fix bug where ETH tips always returned insufficient funds

dont check for sufficient funds on tips with ETH

---

app/retail/emails.py

newsletter 4/18

---

app/assets/v2/css/dashboard.css
app/assets/v2/css/sidebar_search.css
app/assets/v2/js/pages/dashboard.js
app/dashboard/templates/dashboard/index.html
app/dashboard/templates/dashboard/sidebar_search.html
app/dashboard/templates/dashboard/sidebar_search_hackathon.html

- enables filters on mobile with minimize + maximize option  for both explorer + hackathon
- fix results not found img margin
- code refactor
Fixes: https://github.com/gitcoinco/web/issues/4199

show filter on explorer/hackathon on mobile 

---

app/assets/v2/js/grants/shared.js

This PR checks to see if the coinbase check returns undefined, which isn't unexpected behavior (the encapsulating function is waiting for the web3 client to be ready) but is causing our alert system to go crazy lately.
No issue
Tested creating a grant and funding it with a recurring donation manually.

check for undefined web3 coinbase

---

app/assets/v2/js/pages/bounty_details.js

Moving changes over from https://github.com/gitcoinco/web/pull/4211 which was raised against stable

refactor code

---

app/assets/v2/css/gitcoin.css
app/assets/v2/css/home.css
app/retail/templates/home/index.html
app/retail/templates/shared/footer.html

add links to footer

---

app/dashboard/views.py

add network to filters

---

app/assets/v2/css/forms/button.css
app/assets/v2/js/shared.js

Removed the addClass('disabled') for button and css for button:disabled selector.
Fixes #4315

Remove button class disabled and css for disabled button

---

app/retail/templates/emails/campaigns/email_campaign_day_2.html
app/retail/templates/emails/campaigns/email_campaign_day_2.txt

Update for permissionless bounties.
Refers: #4345 
Fixes: #4345

#4345: proposing change for permissionless bounties

---

app/retail/templates/products.html

- made designs responsive
- fixed image overflow

/product: fixed overflowing img

---

app/assets/v2/css/user_popover.css
app/assets/v2/js/user_popover.js

Fixes #4280 
Fixes bugs created while building #3915

Fix Issue 3699 popover quick glance bugs

---

docs/CONTRIBUTING.md
docs/README.md

Waffle.io has shut down. There are references. References to dead links are bad.
Fixes #4484 
Check Github README

#4484 - remove waffle.io references

---

app/assets/v2/js/pages/bounty_details.js
app/assets/v2/js/pages/bulk_payout.js

fix missing id and deleting session storage

---

app/marketing/mails.py

Share bounty/invite user to bounty emails currently put the user who invited's email address as the sender, which is basically spoofing as them. This is bad for many reasons, but mostly it lowers our email reputation.
https://github.com/gitcoinco/web/issues/4545
Untested

fix spoofing email sender on bounty invite

---

app/grants/templates/grants/activity.html
app/grants/views.py

add sorting for subscriptions, cancelled_subscriptions and contributors
Fixes: #4515
Works
Thanks!

#4515 - GRANTS - Adding sorting

---

app/assets/v2/js/pages/dashboard.js
app/assets/v2/js/shared.js
app/dashboard/models.py
app/dashboard/router.py
app/dashboard/templates/shared/bounty-popover.html

This PR takes the explorer lazy load time from
```
kevinowocki@local /Users/kevinowocki/Sites/gitcoin/web~ % time curl "http://localhost:8000/api/v0.1/bounties/?bounty_owner_github_username=owocki&network=mainnet&idx_status=open&order_by=-featuring_date&offset=10&limit=5" > /dev/null
curl  > /dev/null  0.01s user 0.01s system 0% cpu 1.747 total
```
```
kevinowocki@local /Users/kevinowocki/Sites/gitcoin/web~ % time curl "http://localhost:8000/api/v0.1/bounties/slim/?bounty_owner_github_username=owocki&network=mainnet&idx_status=open&order_by=-featuring_date&offset=10&limit=5" > /dev/null
curl  > /dev/null  0.01s user 0.01s system 4% cpu 0.459 total
```
by creating a new route at `http://localhost:8000/api/v0.1/bounties/slim/` that loads ONLY what is needed to load the /explorer results in …

api results speed down from 1.5s to 0.4s

---

app/assets/v2/js/pages/onboard.js
app/retail/templates/home/index.html
app/retail/views.py

uses localStorage to identify if user has gone through
funder onboarding process and accordingly update the
fund this issue link on the landing
fixes: https://github.com/gitcoinco/web/issues/4436
DEMO : [SEE HERE](https://embed.vidyard.com/share/asZB6DvwxjEyVX4CGnnRwY?)

Use localstorage to trigger funder onboarding

---

app/assets/v2/js/grants/fund.js
app/grants/management/commands/subminer.py

This PR properly sets the approval transaction hash for grant subscriptions. When this field is missing, the finalization of a subscription or one-time donation in our database fails and defaults to the first subscription made after the updated grants code was deployed. This subscription was mine since it has an empty value, and each donation made afterwards synced with my donation, hence the emails going out saying I contributed 1 DAI.
https://github.com/gitcoinco/web/issues/4577
Tested locally

Subscription email fix

---

app/assets/v2/js/base.js
app/assets/v2/js/grants/shared.js
app/assets/v2/js/pages/bounty_details.js
app/assets/v2/js/shared.js
app/grants/templates/grants/shared/shared_scripts.html

- [Cannot read property 'length' of undefined](https://sentry.io/organizations/gitcoin/issues/1038441468/)
- [Cannot read property 'now' of undefined](https://sentry.io/organizations/gitcoin/issues/1038910274/)
- [Cannot read property 'style' of null
](https://sentry.io/organizations/gitcoin/issues/1058239597/)
- ['Web3' is undefined](https://sentry.io/organizations/gitcoin/issues/915316423)
- [compiledSplitter0 is not defined](https://sentry.io/organizations/gitcoin/issues/1038512681) - on grants index page

sentry: fix undefined error

---

app/grants/templates/grants/fund.html

adds "maintainer" language describing optional gitcoin grant donation

fix wording for one-time contribution

---

requirements/base.txt

Github[ reported on our repo ](https://user-images.githubusercontent.com/5358146/58385863-c4be0700-8014-11e9-9d89-44f642f2a95f.png) stating current version of djangorestframework has vulnerabilities and deems an update to 3.9.1 
release notes are captured here :
https://www.django-rest-framework.org/community/release-notes/#391
- Rebuilt docker image with the updated django-restframework as shown [HERE](https://user-images.githubusercontent.com/5358146/60389432-718d1780-9ade-11e9-80c5-d45d103b189a.png)
_Note: grant fund recurring failed once but passed the second time when I tried it_ 
closes #4504

update djangorestframework to 3.9.1

---

scripts/crontab

This change to the cron schedule matches the sync_mail job timing to the timing in the script itself (syncing new users from the last 2 hours here: https://github.com/gitcoinco/web/blob/master/app/marketing/management/commands/sync_mail.py#L121)
This issue was discovered when we noted our mailchimp audience list contains about half the actual user count from our platform - since the cronjob syncs new users from the database every 6 hours, and script only looks at users from the last 2 hours, we were missing 2/3 new users. The remaining 1/6 likely came from Sumo
Will monitor production infrastructure metrics one deployed

sync mail every 2 hours to match script

---

app/marketing/tests/management/commands/test_assemble_leaderboards.py
app/marketing/tests/test_marketing_utils.py

Fixes tests failures in master
Fixes 2 issues - 1) the old grants test left EmailSubscriber objects in the database, breaking a later test. 2) The GeoIP database we use updated the entry for one of the IP addresses in our tests from Cuyahoga Falls to Tallmadge, another city 5 km away. Great. ;P
The tests now pass

 Fix tests failing in master

---

app/assets/v2/js/grants/fund.js

This PR fixes an issue where the metatx "gas price" for legacy grants was being calculated incorrectly.
Tested locally

fix legacy grants metatx gasprice

---

app/assets/v2/js/pages/profile.js
app/dashboard/templates/profiles/profile.html
app/dashboard/views.py

improves profile speed by moving the activity tab into lazy load
this is driven by an analysis on my local that shows that for profile/owocki , the activity tab is the slowest thing to load on the page (currently takes 5s to load, 2.2s is from activity tab)
https://github.com/gitcoinco/web/issues/4620
tested locally
BEFORE THIS CHANGE:
```
kevinowocki@local /Users/kevinowocki/Sites/gitcoin/web~ % time curl "http://localhost:8000/profile/owocki" > /dev/null
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  122k  100  122k    0     0   100k      0  0:00:01  0:00:01 --:--:--  100k
curl "http://localhost:8000/profile/owocki" > /dev/null  0.01s user 0.01s system 1% cpu 1.242 total
```
AFTER THIS CHANGE:
``` …
```

improves profile speed by moving the activity tab into lazy load

---

app/dashboard/models.py

more profile speed improvments (see comments inline for desc)
https://github.com/gitcoinco/web/issues/4620
tested locally

more profile speed improvments

---

app/assets/v2/js/pages/dashboard.js
app/dashboard/templates/dashboard/sidebar_search.html

This pr solves some issues related to bounty explorer:
- Set applicants = all by default 
- Fix bounties duplication
- Fix persist applicants election
- Fix apply parameter if applicants is in the url
- Fix on change filters collisions 
Fix #4795 
Tested diff scenarios:
reset filters, query by url, change filters, reload page, reload with params, tested hackathon explorer.

Fix explorer filter

---

app/assets/v2/css/profile.css
app/assets/v2/js/pages/profile-edit.js
app/dashboard/templates/profiles/profile.html
app/retail/templates/shared/top_nav.html

Fix logic to use django variable
fix styles to work in any screen
change styles to look better

Fix banner upload problems

---

app/retail/emails.py

@coderberry waiting on Solana bit.ly tracker link until merge
@gitcoinco/engineers pls wait until we patch the URL into the email!

newsletter 07-19-2019

---

app/assets/v2/js/abi.js
app/assets/v2/js/grants/cancel_subscription.js
app/assets/v2/js/grants/detail.js
app/assets/v2/js/grants/fund.js
app/assets/v2/js/grants/index.js
app/assets/v2/js/grants/new.js
app/assets/v2/js/pages/bounty_details.js
app/grants/templates/grants/detail/index.html

```
Scott Moore [Today at 2:31 AM]
:large_blue_circle: clicking on gitcoin grant recipient address leads to an invalid etherscan page as spaces aren’t trimmed https://gitcoin.co/grants/22/fuzz-geth-and-parity-for-evm-consensus-bugs-2
thelostone-mc  [2 hours ago]
Do you mean it should point to
https://etherscan.io/address/0x7056E70A5CA249Ba88e9550EB22CAEc4C985bb8E
as opposed to
https://etherscan.io/tx/0x7056E70A5CA249Ba88e9550EB22CAEc4C985bb8E
?
```
https://embed.vidyard.com/share/ApLoYYB5oznWx44NkTL8VQ?

bug: fix grant owner address etherscan link

---

app/app/context.py
app/dashboard/models.py
app/dashboard/templates/profiles/profile_activities.html
app/dashboard/templates/shared/profile_activities_misc.html
app/retail/templates/shared/activity.html

show 'joined Gitcoin' as an item on /activity, and on profiles
this lets us eyeball who is joining and what they're into just by looking at /activity -- also makes the network more active
self
tested locally

show 'joined Gitcoin' as an item on /activity

---

app/app/sitemaps.py
app/kudos/models.py

Fixed sitemap kudos url to be relative, since actually the urls are wrong.

Fix sitemap kudos url

---

app/assets/v2/css/home.css
app/assets/v2/css/newsletter.css
app/retail/templates/home/index.html
app/retail/views.py

Add the email capture functionality onto the landing page
cc @octavioamu would like you to double-check this
closes https://github.com/gitcoinco/web/issues/4846

feat: add email capture to landing

---

app/dashboard/views.py

Fixes issue with activities not loading due to a bug with the "Joined Gitcoin" activity changes

fix activities not loading

---

app/avatar/models.py
app/marketing/tests/management/commands/test_assemble_leaderboards.py

This PR fixes the failing tests in master
no issue
tested locally

fix failing tests in master

---

app/assets/v2/js/pages/bounty_details.js
app/assets/v2/js/pages/increase_bounty.js
app/assets/v2/js/shared.js

https://gitcoin.co/issue/ethereum/EIPs/2221/3296
this bounty (a) shows $4.91 USD as the USD amount when there is 1.189 ETH on the main bounty and 1.12 ETH on the crowdfund.  (b) not show the 1.12 ETH in crowdfund.
fix before / after:
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1564565072006400
tested locally

crowdfund contribs + USD estimates for them were completely jacked

---

app/dashboard/views.py

Adds a custom card_desc for grow ethereum hackathon
Longer term fix described here: https://github.com/gitcoinco/web/issues/4913
Untested

add card desc for grow eth hackathon

---

app/assets/v2/js/pages/bulk_payout.js

- Fixes advanced payout 
- Function is already declared in shared.js https://github.com/gitcoinco/web/blob/master/app/assets/v2/js/shared.js#L1350-L1352 causing advanced payout to fail

remove duplicate function

---

app/assets/v2/css/home.css
app/assets/v2/css/profile.css
app/dashboard/templates/onepager/base.html
app/dashboard/templates/profiles/profile.html
app/dashboard/templates/shared/labs_nav.html
app/dashboard/templates/shared/rate_bounties.html
app/grants/templates/grants/index.html
app/grants/templates/grants/nav.html
app/kudos/templates/kudos_about.html
app/kudos/templates/kudos_details.html
app/kudos/templates/kudos_marketplace.html
app/kudos/templates/shared/kudos_nav.html
app/retail/templates/about.html
app/retail/templates/base.html
app/retail/templates/home/index.html
app/retail/templates/home/nav.html
app/retail/templates/jobs.html
app/retail/templates/mission.html
app/retail/templates/not_a_token.html
app/retail/templates/shared/nav.html
app/retail/templates/vision.html

Remove cookielaw banner from templates pages and add is to navs included in all site
Check ALL pages of the site and fix banner styles and fixes. 
A lot

add cookielaw and fix styles

---

app/assets/v2/css/base.css
app/assets/v2/js/pages/bounty_details.js
app/assets/v2/js/shared.js
app/dashboard/templates/bounty/details.html
app/retail/templates/results.html

piggybacks on https://github.com/gitcoinco/web/pull/4930

fixes tooltips on bounty detail pages

---

app/dashboard/templates/shared/hackathon_sponsors.html

chore: show supported by only if sponsors are present

---

app/assets/v2/css/featured-bounties.css
app/assets/v2/js/pages/dashboard.js
app/dashboard/templates/dashboard/featured_bounties.html

Add clickable arrows to featured bounties carousel 
https://embed.vidyard.com/share/CuHhZDHuNnG4D75WWHtQLo

Add carousel arrows

---

app/assets/v2/js/pages/bounty_details.js
app/assets/v2/js/shared.js
app/dashboard/templates/bounty/details.html

fix condition to add workplan when bounty is permissionless 
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1565203752074200

fix workplan in permissionless

---

app/marketing/utils.py

cast first arg to string for sup email

---

app/assets/v2/css/gitcoin.css
app/dashboard/templates/board.html

- added padding to make footer look nicer
- fixed margin on the dashboard

chore: css fixes

---

app/dashboard/templates/dashboard/hackathons.html
app/dashboard/views.py

- Bigger cards
- Cards with same explorer background 
- No image card

Style hackathon list

---

app/dashboard/views.py

Set the last_remarket to current-time when it's None
@vince0656 
- locally tested

bug: remarket issue

---

app/assets/v2/js/grants/shared.js

When you are logged in as the grant owner as wrong address the alert shows up as usual.
When you logout -> we add a null check to ensure to show the alert only if the user is logged in
Demo: https://embed.vidyard.com/share/CY7m7HX19YngBqzs6wfd6W?
closes https://github.com/gitcoinco/web/issues/5026

bug: supress multiple alert when owner is logged out

---

app/marketing/views.py

This change adds response headers after disconnecting your account from Github to prevent accidental reconnection if the user presses the back button.
n/a
Tested locally

prevent back button github reconnect

---

app/assets/v2/js/users.js

http://localhost:8000/users?skills=html,PHP activates the filters and it works as expected
closes https://github.com/gitcoinco/web/issues/5014
https://embed.vidyard.com/share/7ksCTEBQJc6C3BEZGXF4mb?

feat: open users with skill filter

---

app/assets/v2/css/bounty.css
app/assets/v2/css/dashboard.css
app/assets/v2/js/pages/bounty_details.js
app/dashboard/router.py
app/dashboard/templates/bounty/details.html
app/dashboard/templates/dashboard/index.html
app/retail/templates/shared/nav.html
app/retail/templates/shared/result.html

**Add event data to bounty router**
add hachathon list link to navbar 
Add event tags to general explorer only
Add event tag to bounty detail
Tested locally in explorer and hackathon explorer

add hachathon list link and event tags

---

app/assets/v2/css/base.css
app/retail/templates/shared/top_nav.html

Changed the color to match the hackathon color and catch more attention

change color to yellow

---

app/assets/v2/js/pages/new_bounty.js
app/dashboard/templates/shared/reserved.html
app/marketing/mails.py

add group by skill and change subject

---

app/dashboard/models.py
app/dashboard/templates/shared/profile_kudos.html
app/dashboard/templates/shared/rate_bounties.html
app/dashboard/views.py
app/kudos/templates/shared/kudos_card.html
app/retail/templates/results.html

Fix long time bug on profiles when after rating a bounty and reloading the page the bounty didn't disappears.
- Disable cache on bounty feedbacks query
- Add verification if the feedback already exist fire an error on top of the screen.
- Remove comments and activity print on profile. 
Fix #5098
Tested locally with funder and contributor

Fix repeated rating cards on profile after rated and reload

---

app/assets/onepager/js/send.js
app/assets/v2/js/pages/new_bounty.js
app/bounty_requests/templates/bounty_request_form.html
app/dashboard/templates/onepager/send2.html
app/dashboard/templates/shared/github_username.html
app/dashboard/templates/shared/labs_nav.html
app/dashboard/templates/shared/nav_auth.html
app/dashboard/templates/shared/newsletter.html
app/dashboard/templates/shared/onepager_auth.html
app/faucet/templates/faucet_form.html
app/grants/templates/grants/index.html
app/kudos/templates/transaction/kudos_auth.html
app/kudos/templates/transaction/receive_bulk.html
app/kudos/templates/transaction/send.html
app/marketing/views.py
app/retail/templates/base.html
app/retail/templates/home/nav.html
app/retail/templates/increase_funding_limit_request_form.html
app/retail/templates/settings/email.html
app/retail/templates/settings/settings.html

Add and fix GTM events
together with gtm changes for tracking
Add data-gtm as auto tracking attr 
locally, intensive

add missing events and fixes for gtm

---

app/marketing/views.py

Addressing GWE-282-0
#5125
Unable to reproduce GWE-282-0 with this change.

Fix for GWE-282-0

---

app/assets/v2/js/pages/onboard.js
app/marketing/views.py

This PR fixes saving of skills/keywords during onboarding, as well as saving the emailsubscriber keyword settings to your user profile so they display in the user directory
https://github.com/gitcoinco/web/issues/4424
https://embed.vidyard.com/share/LAXMnXgpZ7RuFkLrkLJeN9?

save es keywords to profile and fix onboarding

---

app/assets/v2/js/user_popover.js
app/dashboard/models.py
app/dashboard/templates/bounty/details.html
app/dashboard/views.py

Adds success rate calculation based on already existing calculation found in quarterly stats function
exposes success rate for https://github.com/gitcoinco/web/issues/5036
Tested locally:

add simple success rate calculation

---

app/assets/v2/js/shared.js

We use a variety of techniques in our shared.js to determine whether the user has web3 access. One of the ways we do it is to attempt to access the coinbase of the connected ETH node - if the coinbase comes back as something other than undefined, then we assume we have a working blockchain connection. However, when calling this synchronous method in browsers that do not have metamask unlocked, we get an error trying to access the coinbase, and use this to show the user the "unlock metamask" alert. Each time this happens however, an alert is sent to sentry.
This PR catches the error.
Untested

catch infura/metamask errors before they alert sentry

---

app/retail/templates/shared/head.html

Currently all fonts are loaded from the CDN subdomain https://s.gitcoin.co, but the preloader gets the fonts from the main domain https://gitcoin.co. In order to benefit from the browser preloader, the domain should be adapted.
Sorry, no tests.

Preload fonts from the static domain

---

app/marketing/management/commands/no_applicants_email.py

Fixes syntax error in no applicants email alert

fix syntax error in no applicants email management command

---

docs/README.md
pydocmd.yml

Fix GitCoin Bot document link
https://github.com/gitcoinco/web/issues/5116
preview markdown

Fix GitCoin Bot document link

---

app/dashboard/templates/shared/nav_auth.html

Navbar with the updated list 
fixes https://github.com/gitcoinco/web/issues/5124

chore: update navbar

---

app/dashboard/templates/board/contributor.html
app/dashboard/templates/board/funder.html

typos fixes for dashboard
Fix #5138

Fix dashboard typos

---

app/dashboard/models.py

Fixes the success rate calculation

fix success rate math

---

app/dashboard/templates/ens/base.html
app/dashboard/templates/ens/ens_register.html

The [ENS subdomain onepager](https://gitcoin.co/ens/) is a little bit broken. I will try to fix the layout.
* Removing duplicate stylesheets (already loaded by [shared/head.html](https://github.com/gitcoinco/web/blob/a6d073c3c8a3be999269e1ae0b390b13ff2cb814/app/dashboard/templates/ens/base.html#L7))
* Removing favicon include (already loaded by [shared/head.html](https://github.com/gitcoinco/web/blob/a6d073c3c8a3be999269e1ae0b390b13ff2cb814/app/retail/templates/shared/head.html#L75))
* Fixing ENS page footer
A designer should make a visual test of the layout changes.

Fix ENS onepager layout

---

app/dashboard/templates/dashboard/hackathon_onboard.html

Fix hackathon onboarding typos
from:
to:

Fix hackathon onboarding typos

---

app/app/settings.py

This was first reporter as permissions not saving on the admin but actually affection any data sent by a form containing an array. Just the last one element of the array was getting into the backend so instead of `<QueryDict: {'skills[]': ['css', 'solidity'], 'bountyId': ['37']}>` the `request.POST` was getting `<QueryDict: {'skills[]': [ 'solidity'], 'bountyId': ['37']}>` Probably affecting lot of places on the application. 
For now this PR just disabled  django-bleach until we solved or probably remove it as that project is very new and just have 1 issue, not enough usage. 
Fix #5190
Fix #4893
And actually any array sent, like grants team people probably failing.

FIX requests with arrays on the site

---

app/marketing/mails.py

Looks like there are a couple of undefined variables which needed to be fixed!
- `render_no_applicant_reminder` takes only one argument  as shown [here](https://github.com/gitcoinco/web/blob/a88246ea9c96801bc2d482acf4bde9f03c4f6cbf/app/retail/emails.py#L324)
- `live` is not defined anywhere so it would not work

bug: no applicant email

---

app/assets/v2/css/buttons.css
app/dashboard/templates/dashboard/index.html

Change cta button

---

app/assets/v2/css/board.css
app/assets/v2/js/board.js
app/dashboard/templates/board/contributor.html
app/dashboard/templates/board/index.html
app/dashboard/views.py

Create matching bounties area based on skills.
Fix #5220
No skills:
No bounties with my skills 
With match

Create match bounties area

---

app/assets/v2/js/board.js
app/dashboard/templates/quickstart.html

- Show only open bounties 
- Fix quickstart activity styles

add open filter

---

app/assets/v2/css/kudos/styles.css

add loading for kudos 

---

app/assets/v2/js/pages/new_bounty.js

>  can’t fund an issue with exactly 15 ETH which is a small, random issue
- removes blue events to ensure while tabbing token amount / usd amount don't change
https://share.vidyard.com/watch/gFMn84vzHT6tHBrTfWC6ik?

chore: remove on blur event for amount update

---

app/assets/v2/css/grants/fund.css
app/assets/v2/css/tabs.css
app/grants/templates/grants/detail/tabs.html

keeping it uniform like in profile

chore: pretty up grant tabs

---

app/grants/clr.py

Pairs the contributor with itself and ensures grants get matching clr even if it has one contributor
If grant has only 1 contributor. 
Assume with `contributor_profile : 1` who contributed `5 DAI` :
- while generating pair we assume another pseudo contribution who makes `1 DAI` 
(I'm assuming this is the lowest possible contribution )
- pair generated would : `1` & `_1` with contributions `5 DAI` and `1 DAI`  
If a new profile contributes,
the pesudo contributor_profile's (`_1`) contibution (`1 DAI`) is ignored and algorithm works as usual
Fixes: https://github.com/gitcoinco/web/issues/5223
https://share.vidyard.com/watch/rTqnXvuiRuswAnbvK91GbR?

feat: account for single contribution for grant in clr

---

app/dashboard/templates/profiles/profile.html

Hiding the kudos badges on mobile at the point where overflowing occurs.
https://github.com/gitcoinco/web/issues/5292

Hides kudos badges on mobile #5292

---

app/economy/utils.py

fix broken tip test

---

app/assets/v2/css/base.css
app/assets/v2/css/submit_bounty.css
app/assets/v2/js/pages/increase_bounty.js
app/dashboard/templates/bounty/increase.html
app/dashboard/templates/shared/success_container.html
app/dashboard/views.py

- cleans up UI to match fund bounty
- add coupon code support 
- general CSS refactor
DEMO: https://share.vidyard.com/watch/NvBGnjdrmunuypf44fimGw?

increase_bounty: add coupon code

---

app/assets/v2/css/grants/card.css
app/grants/templates/grants/card/back.html

Ensure fund + view details button are always visible as opposed to be thrown to the bottom of the screen
**Problem in live**
After this change
https://share.vidyard.com/watch/2bzk24r5qYBqbbTYqbDijB?

bug: ensure fund + detail button are always visible

---

app/assets/v2/js/pages/new_bounty.js
app/assets/v2/js/pages/quests.index.js

track bounty fee purchases in the digital goods table
https://github.com/gitcoinco/web/issues/4121
tested locally

track bounty fee purchases in the digital goods table

---

app/dashboard/templates/profiles/tab_active.html

Refs: https://github.com/gitcoinco/web/pull/5310
Due to accidentally close previous PR after messing up the log.
This is same PR as #5310 
The avatar is now rounded and use all existing styling.
This PR is to fix Issue #5291

Fixes: https://github.com/gitcoinco/web/issues/5291

---

app/dashboard/helpers.py
app/dashboard/models.py
app/dashboard/views.py
app/marketing/management/commands/share_activity.py
app/retail/templates/shared/activity.html
scripts/crontab

refactors @gitcoinfeed twitter account sharing to match gitcoin.co/activity
the reason for doing this is to cover more of the activities that happen on the platform; and to do sharing as a background task instead of upon GET request.
self
tested locally
```
.  @stake-capital updated their avatar http://localhost:8000/profile/stake-capital
.  @iiitkalyanifosc updated their avatar http://localhost:8000/profile/iiitkalyanifosc
.  @arweave-sophie tipped @logitec1994 1.3000 ETH http://localhost:8000/issue/ArweaveTeam/Bounties/1/3184
.  @lolx21341 updated their avatar http://localhost:8000/profile/lolx21341
.  @lolx21341 joined Gitcoin  http://localhost:8000/profile/lolx21341
.  @alexgreen92 played Quest: Fight for Open Source Sustainability  http://localhost:8000/profile/alexgreen92
. …
```

refactors @gitcoinfeed twitter account sharing to match gitcoin.co/activity

---

app/app/utils.py
app/git/tests/test_utils.py
app/git/utils.py

Bugs this try to solve:
There is a bug with new users sync_profile not saving the email on profile obj
If someone change the username on gh data just get in sync the second time the user logins
Now users can change GH username and when login this will update username, and profile
Force to save user emails on profile 
TODO: fix sync_profile to save the data the first login
fix https://sentry.io/organizations/gitcoin/issues/1278683144/events/?project=1398424&referrer=slack
Tested with New user
Tested with a user changing GH username.

Fix username GH changes and email save new users

---

app/assets/v2/css/bounty.css
app/dashboard/templates/bounty/details.html

- refactor
- ensure UI doesn't break on responsive 
Before Fix 
After Fix 
Demo: https://share.vidyard.com/watch/GwwsEwiBAEZBh3bseiKRd8?

fix up bounty details summary

---

app/grants/views.py

another branch removed the typeform redirect for the old grant creation endpoint, which is just used for testing - this one removes it for the new endpoint

remove typeform for new style grants

---

app/marketing/views.py

limit visibiltiy of orgs to admin

---

app/dashboard/templates/onepager/base.html

The Send Tip button in the footer doesn't redirect to the correct url:
It should redirect to `/tip/send/2`

Fixed redirect for Send Tip link

---

app/retail/emails.py

newsletter 2019-11-01

---

app/dashboard/admin.py
app/dashboard/templates/dashboard/users.html
app/dashboard/views.py

Change rule of having at least 1 skill to have at least some filter
Add option to custom search by leaderboard and bounties complete amounts
Fix admin view for invites 
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1572424579194800

fix bulk invite and query

---

app/retail/views.py

This change correctly casts the query parameter for the page number to an int before adding 1 to it.
Fixes a recurring sentry error when viewing the activity feed
not tested

fix typecast for query param

---

app/assets/v2/css/base.css
app/assets/v2/css/bulk_payout_bounty.css
app/assets/v2/css/gitcoin.css
app/assets/v2/js/pages/bulk_payout.js
app/assets/v2/js/tooltip_hover.js
app/dashboard/templates/bulk_payout_bounty.html
app/retail/templates/shared/bulk_payout_form.html

- redesign + refactor
- responsive design
- add more information on how advanced payout works
Demo: https://share.vidyard.com/watch/sEstVPgihvwWciy49jH91B?
closes https://github.com/gitcoinco/web/issues/5321

feat: revamp advanced payout to make it cleaner

---

app/assets/v2/js/pages/dashboard.js

update scrub logic to show languages 
fixes https://github.com/gitcoinco/web/issues/5387

bug: update scrub logic

---

app/assets/v2/css/quests.css

Add portrait view support for android and iphone devices and fix overlapping options and submit button.
https://github.com/gitcoinco/web/issues/5418
*Android samsung galaxy s5*:
*Iphone 5*:

Update quest style to support portrait view

---

app/dashboard/notifications.py

Changed tips to Payouts where they come from bounties
closes https://github.com/gitcoinco/web/issues/2978

Notify bounties cancelled for advanced payout as work_done,  changed tips to payouts when they come from bounties

---

app/assets/v2/js/pages/kudos-search.js

When you add whitespace in search bar value, for example: "Limited edition", the query parameters will be "Limited+edition", so when results come back in the view, the search bar get its value from query parameters (queryParam.q), so it will also show up in the search bar as Limited+edition. The simplest solution is to replace the plus signs with whitespace:\
$('#kudos-search').val(queryParam.q.replace(/\+/g, " "));
I think it does look better.

Proposed fix for Kudos marketplace search bar

---

app/app/urls.py

makes the profile urls.py entry way more  restrictive
see octavio msg https://gitcoincore.slack.com/archives/CC24APWGN/p1572989388030500
and likely other profile handle URL things we haven't figured out already!
tested against http://localhost:8000/media/avatars/72f4f6d365732c50762730b1bc630379/octavioamu.png
http://localhost:8000/owocki
http://localhost:8000/owocki/resume

makes the profile urls.py entry way more  restrictive

---

app/assets/v2/css/base.css
app/assets/v2/css/bounty.css
app/assets/v2/css/forms/button.css
app/assets/v2/css/gitcoin.css
app/assets/v2/js/pages/bounty_details.js
app/dashboard/templates/bounty/details.html
app/dashboard/templates/bounty/fund.html

- move funder change address notification to above action buttons
- move extra options to dropdown
- update buttons to new style
- refactor code + remove dead code
Demo: https://share.vidyard.com/watch/Sr8M9Um3vyjt9GWfa1Zj2R?
Current
After
closes https://github.com/gitcoinco/web/issues/5347

ui: prettify work details section

---

pytest.ini
requirements/test.txt
setup.cfg

This PR specifies in the pytest configuration where the tests are located. While this does add some additional coupling in that devs will need to add their tests to this file when creating a new module, or adding tests to a nonstandard path, it speeds up running the tests massively.
`168.28s` vs `506.17s` on my local
This PR also pins a dependency that caused an issue with PyTest 4
n/a
Tested locally and with Docker

speed up tests massively by specifying location

---

app/assets/v2/css/quests.css

We recently found that our style sheets in our Quests code were a tiny bit unsorted for our Mobile UI/UX.
**Quest Start on Mobile UI looked Akward:**
**Character Class Unsorted and unresponsive**
Unable to click submit -metacartel quest mobile UI [5418](https://github.com/gitcoinco/web/issues/5418)
1. - Added Comments on new Style Rules for better Code Maintenance
2. - Added New Style Rule (@ media) for Better Mobile UI (500px)
3. - Character Class unsorted on stage2 on Mobile UI aligned accordingly to the right border
4. - Button Line-Height px unresponsive on iPhone (fixed)
5. - Quests Rules fixed for better alignment on the iPhone
**Character should look Now:** 
**Quest Rules Style for Mobile UI was extremely bigger. We made some fixes so it looks like**
**User was claiming that he …

Some new Fixes added for Quests on Mobile UI

---

app/assets/v2/js/pages/quests.new.js
app/quests/templates/quests/new.html

This PR fulfills issue #5379. The changes are the following on the page where a new quest is created.
Clean new answers when added:
Before:
After:
Clean new questions when added:
Before:
After:
Limit on the number of answers for each question:
#5379 - Main issue this addresses
It also builds upon these PRs: #5393 and #5409
No tests. I just changed javascript.

Quests improvements

---

app/assets/v2/js/pages/change_bounty.js
app/assets/v2/js/pages/new_bounty.js
app/dashboard/templates/bounty/change.html
app/dashboard/templates/bounty/fund.html
app/dashboard/templates/shared/bounty_categories.html
app/dashboard/templates/shared/bounty_details.html
app/dashboard/templates/shared/bounty_keywords.html
app/dashboard/views.py

- Not all bounty details updates were persisted
- bounty details can now be updated
- ensure documentation tag shows in bounty details
- DRY code btwn new bounty + change bounty
https://gitcoincore.slack.com/archives/CAXQ7PT60/p1573848437281400
https://share.vidyard.com/watch/vzJxysi2T4StLaE1Z34gfB?

bug: fix bounty details update

---

app/dashboard/models.py

As of now -> if you use advanced payout using wallet , 
the UI renders the status as DONE which is confusing despite the bounty being open.
- This happens on the explorer 
- Bounty Page (preventing users from performing contributor/funder actions which should be possible on the original bounty )
AFTER THIS CHANGE

ensure bounty is open when advanced payout is done using tips

---

app/grants/clr.py

Based on the changes made by @frankchen07 after discussing with vitalik
@frankchen07 I haven't commented out the one off contribution -> let me know if that is something you would still want to remove. Cause in that case if a grant has no contributors -> it'll appear in the UI that contributing any amount would have a matching 0 as pair could not be formed
ref: https://github.com/thelostone-mc/clr/commit/ef292e4088a907811eda2aff36a524bb0a409cfe
fixes: https://github.com/gitcoinco/web/issues/5425

chore: update clr formula

---

app/assets/v2/js/pages/bulk_payout.js
app/assets/v2/js/pages/fulfill_bounty.js
app/assets/v2/js/pages/kudos_send.js
app/assets/v2/js/pages/process_bounty.js
app/dashboard/templates/bounty/fulfill.html
app/retail/templates/shared/footer_scripts_lite.html

Add bounties creation, payment and submission (basic and advance) support to opera wallet. 
Fixes:
creating bounties 
basic payout (+ kudos)
advance payout
submit work 
fix projects modal issue.
Fix #5466
creating bounties 
basic payout
basic payout + kudos
advance payout
submit work 
fix projects modal issue.

Opera bounties

---

Dockerfile
requirements/base.txt

Better solution based on this chat with the maintainer https://github.com/alpinelinux/aports/commit/2f6bc1cb9b406078ebc8e9621231a50159680dd9#r36149376
fix #5549
failing probably related https://github.com/ethereum/populus/issues/369

alpile 3.8 > 3.10

---

app/dashboard/views.py

closes https://github.com/gitcoinco/web/issues/5528
https://share.vidyard.com/watch/hAuHoXdRuZjB3ALFFs6qNA?

feat: redirect to hackathon list for incorrect URL

---

app/assets/v2/css/search_bar.css
app/assets/v2/js/pages/dashboard.js
app/dashboard/templates/dashboard/index.html

Generates orgs specific shareable hackathon URL
Merge after https://github.com/gitcoinco/web/pull/5548
Refs https://github.com/gitcoinco/web/issues/5483
https://share.vidyard.com/watch/69pPwDP6A1DzWaFJkM2vCF?

chore: make org specific hackathon URI

---

app/assets/v2/css/bounty.css
app/assets/v2/js/pages/bounty_details.js
app/dashboard/templates/bounty/details.html

The bounty activity section in bounty details has been cryptic and there is dead code in the js-render logic written to generate the activity.
As a funder, this makes it difficult to figure out what's happened with a bounty over the course of time
This PR
- removes dead code
- makes UI responsive + prettifys
- makes the activity more readable so that folks know what exactly happens during the bounty lifecycle

feat: updated activity section in bounty detail

---

Dockerfile
bin/docker-command.bash
docker-compose.yml
scripts/sync_kudos_listener_local.bash
scripts/sync_kudos_local.bash

Change dockerfile to use ubuntu instead of alpine linux

working ubuntu boot

---

app/grants/views.py

Fixes casting of user pks when setting team members in grants
bug noticed in pre-deploy tests
tested locally

grants: fix team member pk casting

---

app/chat/templates/embed.html

CSS updates to provider a more responsive wrapper, originally was going to get the permission work added in but after reviewing and looking at @owocki's  comments around usage for templates etc, changing to permissions in this release would be too rushed so it was held back.
#5522 1.1 ticketing notes.

responsive fixes for chat

---

Makefile

This PR fixes the pytest Makefile commands not running on the new ubuntu-based container
n/a
Tested locally

fix pytest Makefile commands

---

app/grants/clr.py
app/grants/management/commands/estimate_clr.py
app/grants/models.py
scripts/crontab

- estimate_clr.py -> new arguments clr_type, network
- clr logic updated to query grants by network + grant_type + not hidden
- grant str updated to also print grant_type
- crontab updated to run both clr for media and tech grants
Gets in after #5637

clr: update estimate_clr command to query by grant type 

---

app/grants/clr.py
app/grants/management/commands/estimate_clr.py
scripts/crontab

Added three methods:
1. method that translates grant dictionary data into a list of lists
2. method that aggregates and calculates the by pair totals
3. method that continually tests thresholds until the proper total CLR amount is found, and calculates the result
I was going through the curve calculation part, and I believe it may break it. My concern is around line 224, but it may be that it's alright. Let's pair up and take look at that @thelostone-mc.

Faster CLR Calculation

---

docs/CONTRIBUTING.md
docs/README.md

There is a tiny issue on our lovely 'Logo' on the <code> contributing.md </code> and it's happening in all screen sizes.
While the logo on <code> contributing.md</code> it's looking pretty good on Github. It's not in the actual deployed document site https://docs.gitcoin.co/mk_contributors/
**It has an automatic width of 238 x 238. Which is causing the conflict.**
Since it looks like we want our logo there to be bigger in size. We have added specific width in the <code> contributing.md</code> so it makes the logo look as we want
Issue: #4943 
- All Browsers, And all sizes.

[Small Fix] Added Logo width on Contributing.md [Documentation]

---

pydocmd.yml

The PR removes the `Edit this page` button from the documentation pages which redundantly redirects to a 404 page.
#4943
No tests required.

Removes edit this page link from every page

---

app/dashboard/templates/bounty/details.html
app/retail/templates/shared/featured_bounty_cards.html
app/retail/templates/shared/result.html

Escape template variables evaluated* by jsrender, template variables evaluated by django are automatically [escaped](https://docs.djangoproject.com/en/1.7/topics/templates/#automatic-html-escaping).
Fixes #5656 
*use `>` [link](https://www.jsviews.com/#htmltag) in favour of `:` [link](https://www.jsviews.com/#assigntag)

Fix XSS: Escape temp vars

---

app/assets/v2/js/grants/detail.js

Expected Admin Grant Address <code> #grant_contract_owner_address </code> on the Error Message but I am seeing on the file it's appending the value as <code> #contract_owner_address </code>
Syntax:
<code> $('selector expression').text('content if applied'); </code>
Line fixing
#5647 
Brave Browser
This should not break any other components

Fix for Admin Address Pull on Grant

---

app/retail/emails.py
scripts/crontab

duplicate of https://github.com/gitcoinco/web/pull/5685/

chore: update email text for stale funder + schwag

---

app/grants/clr.py
app/grants/templates/grants/card/clr_estimate.html
app/grants/templates/grants/index.html
app/grants/views.py
app/retail/templates/shared/grant_thanks_modal.html
scripts/crontab

This PR updates stable to enable grants CLR mode for round 4 
Tested Locally

Clr round 4

---

Dockerfile

Fixes: https://github.com/gitcoinco/web/issues/5696
fixing a mistype in tar extraction for GeoLite
https://github.com/gitcoinco/web/issues/5696

fixing a mistype in tar extraction for GeoLite

---

app/assets/v2/js/grants/fund.js

This PR checks a users token balance to ensure they have enough tokens to cover their grant contribution, or at least the first in a series of recurring contributions
Tested locally

check token balance covers first contribution

---

app/grants/views.py

This PR includes all phantom funding selections in the grant details page
Tested locally

include all rounds in phantom funding calc

---

app/grants/clr.py

This PR sets an empty clr prediction curve for grants that have no contributions, so that sorting on the grants index page works as expected
Tested this fix in interactive shell on production

save empty curve if no contributions to fix sorting
